# Handling Imbalanced Dataset

Imbalance Dataset:

An unequal class distribution

In [18]:
# Importing necessary libraries
import numpy as np
import pandas as pd

Download the dataset using link,

(https://drive.google.com/file/d/1WkcjUn5tVJDUtkN6d2_gztiT1FmIIVDP/view?usp=sharing)

In [19]:
# Loading the dataset into pandas DataFrame
cred_card_df = pd.read_csv("/content/credit_data.csv")

In [20]:
cred_card_df.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0.0
1,0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0.0
2,1,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0.0
3,1,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0.0
4,2,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0.0

In [21]:
cred_card_df.shape

(19898, 31)

In [22]:
cred_card_df["Class"].value_counts()

Class
0.0    19812
1.0       85
Name: count, dtype: int64

Highly Imbalance Dataset

0 = Legit Transaction

1 = Fraudulent Transaction

# Undersampling, Technique To Handle Imbalance Data

Splitting The Legit & Fraud Transactions Data

In [23]:
legit = cred_card_df[cred_card_df.Class == 0]
fraud = cred_card_df[cred_card_df.Class == 1]

In [24]:
print(f"Legit Shape:{legit.shape}\nFraud Shape:{fraud.shape}")

Legit Shape:(19812, 31)
Fraud Shape:(85, 31)

Building A Sample Dataset Containing Similar Distribution Of Legit & Fraud Transactions

Number Of Fraudulent Transaction = 85

Taking Similar Amount From Legit Transactions

In [25]:
# Using 'sample' function
legit_sample = legit.sample(n=85)

In [26]:
legit_sample.shape

(85, 31)

# Concatenating Legit-sample & Fraud DataFrames

In [27]:
# 'axis = 0' means we want to concatenate row-wise, for column wise 'axis = 1'
upd_cred_card_df = pd.concat([legit_sample, fraud], axis = 0)

In [28]:
upd_cred_card_df.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
7855,10940,1.234986,0.071850,0.776162,0.024008,-0.606055,-0.641954,-0.351304,-0.139826,1.319004,...,-0.222306,-0.393708,0.083683,0.336825,0.085163,0.846303,-0.097696,-0.005043,6.79,0.0
13247,23306,-2.281012,2.166472,-2.391333,0.381712,1.980649,3.545425,-1.996486,-0.661805,-0.176846,...,-1.275282,0.130416,0.253525,0.787568,-0.118801,-0.386388,-0.401633,-0.143033,1.00,0.0
18888,29845,-1.022335,0.458807,1.292151,0.000692,0.596044,-0.841429,0.598571,-0.105633,-0.360994,...,-0.279389,-0.573055,0.461739,-0.125121,0.024510,0.110655,0.216109,0.051463,3.59,0.0
7083,9282,-0.722200,0.868301,2.126433,-1.212151,0.144630,-0.355836,0.534976,-0.030070,0.646243,...,-0.191794,-0.408831,-0.261604,0.013544,0.145208,0.777770,-0.083211,0.032607,10.96,0.0
551,411,0.238849,0.241702,0.369161,-2.124041,-0.172508,-0.838345,0.183133,-0.921449,0.517945,...,0.846544,0.047365,-0.162210,0.284053,0.773004,-0.034858,0.153185,0.207924,10.00,0.0

In [29]:
upd_cred_card_df.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
17480,28755,-30.552380,16.713389,-31.103685,6.534984,-22.105532,-4.977692,-20.371514,20.007208,-3.565738,...,1.816520,-2.288686,-1.460544,0.183179,2.208209,-0.208824,1.232636,0.356660,99.99,1.0
18466,29526,1.102804,2.829168,-3.932870,4.707691,2.937967,-1.800904,1.672734,-0.300240,-2.783011,...,-0.106994,-0.250050,-0.521627,-0.448950,1.291646,0.516327,0.009146,0.153318,0.68,1.0
18472,29531,-1.060676,2.608579,-2.971679,4.360089,3.738853,-2.728395,1.987616,-0.357345,-2.757535,...,-0.063168,-0.207385,-0.183261,-0.103679,0.896178,0.407387,-0.130918,0.192177,0.68,1.0
18773,29753,0.269614,3.549755,-5.810353,5.809370,1.538808,-2.269219,-0.824203,0.351070,-3.759059,...,0.371121,-0.322290,-0.549856,-0.520629,1.378210,0.564714,0.553255,0.402400,0.68,1.0
18809,29785,0.923764,0.344048,-2.880004,1.721680,-3.019565,-0.639736,-3.801325,1.299096,0.864065,...,0.899931,1.481271,0.725266,0.176960,-1.815638,-0.536517,0.489035,-0.049729,30.30,1.0

In [30]:
# Counting values
upd_cred_card_df["Class"].value_counts()

Class
0.0    85
1.0    85
Name: count, dtype: int64