# **Project 2 Altermagnets Ground States Predictions Using ALIGNN**

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
pwd

'/content'

In [ ]:
cd drive/MyDrive/Proj_2_Alt_Mags_Grnd_E/

/content/drive/MyDrive/Proj_2_Alt_Mags_Grnd_E

In [ ]:
pwd

'/content/drive/MyDrive/Proj_2_Alt_Mags_Grnd_E'

## Phase - 1 - Building the dataset

Our immediate target is:

$$ \boxed{ \text{large collection of }(G,S,E_{\rm magnetic}) } $$

where:

\(G\) = crystal structure
\(S\) = particular magnetic configuration
\(E_{\rm magnetic}\) = reliable DFT energy for that configuration.

We will also retain:

$$ \text{magnetic moments},\quad \text{composition},\quad \text{space group},\quad \text{magnetic atoms}, $$

and, where available,

$J_{ij}$, ground-state ordering, AM/AFM/FM/FiM labels.

### Step - 1.1 - Project setup - Frey dataset

In [ ]:
# !git clone https://github.com/kaueltzen/paper-exchange-heuristics-in-magnetic-materials.git
# %cd paper-exchange-heuristics-in-magnetic-materials
# !find . -maxdepth 3 -type f | head -100

!git clone https://github.com/ncfrey/magnetic-topological-materials.git
%cd magnetic-topological-materials
# Showing repository contents
!find data -maxdepth 3 -type f | head -100

fatal: destination path 'magnetic-topological-materials' already exists and is not an empty directory.
/content/drive/MyDrive/Proj_2_Alt_Mags_Grnd_E/magnetic-topological-materials
data/X_test.json
data/X_train.json
data/database_snapshot/README.md
data/database_snapshot/magnetic-orderings-database-snapshot.part1.json.gz
data/database_snapshot/magnetic-orderings-database-snapshot.part2.json.gz
data/mtm_X_test.json
data/mtm_X_train.json
data/mtm_y_test.json
data/mtm_y_train.json
data/y_test.json
data/y_train.json

In [ ]:
pwd

'/content/drive/MyDrive/Proj_2_Alt_Mags_Grnd_E/magnetic-topological-materials'

In [ ]:
import os

for root, dirs, files in os.walk("data"):
    level = root.replace("data", "").count(os.sep)

    if level > 3:
        continue

    indent = "    " * level

    print(f"{indent}{os.path.basename(root)}/")

    for f in files:
        print(f"{indent}    {f}")

data/
    X_test.json
    X_train.json
    mtm_X_test.json
    mtm_X_train.json
    mtm_y_test.json
    mtm_y_train.json
    y_test.json
    y_train.json
    database_snapshot/
        README.md
        magnetic-orderings-database-snapshot.part1.json.gz
        magnetic-orderings-database-snapshot.part2.json.gz

### Step - 1.2 - Inspecting repository structure

In [ ]:
import gzip
import json
from pathlib import Path

data_dir = Path("data/database_snapshot")

for fname in [
    "magnetic-orderings-database-snapshot.part1.json.gz",
    "magnetic-orderings-database-snapshot.part2.json.gz"
]:
    path = data_dir / fname

    print("\n" + "="*70)
    print(fname)
    print("="*70)

    with gzip.open(path, "rt", encoding="utf-8") as f:
        # Read only the beginning; don't load the huge database into RAM
        text = f.read(10000)

    print(text[:5000])

======================================================================
magnetic-orderings-database-snapshot.part1.json.gz
======================================================================
[{"formula": "La2 Fe2 O6", "formula_pretty": "LaFeO3", "parent_structure": {"@module": "pymatgen.core.structure", "@class": "Structure", "charge": null, "lattice": {"matrix": [[2.82369064, 1.63025836, 4.52781815], [-2.82369064, 1.63025836, 4.52781815], [-0.0, -3.26051767, 4.52781814]], "a": 5.579615430318018, "b": 5.579615430318018, "c": 5.57961580982914, "alpha": 60.805164933372346, "beta": 60.805164933372346, "gamma": 60.805163336311274, "volume": 125.05868583705937}, "sites": [{"species": [{"element": "La", "oxidation_state": null, "occu": 1.0}], "abc": [0.25001055, 0.25001055, 0.25001055], "xyz": [0.0, -2.3751002253824538e-07, 3.396006915444342], "label": "La", "properties": {"wyckoff": "n/a"}}, {"species": [{"element": "La", "oxidation_state": null, "occu": 1.0}], "abc": [0.75001055, 0.75001055, 0.75001055], "xyz": [0.0, -7.125100225380265e-07, 10.187734135444343], "label": "La", "properties": {"wyckoff": "n/a"}}, {"species": [{"element": "Fe", "oxidation_state": null, "occu": 1.0}], "abc": [0.50000468, 0.50000468, 0.50000468], "xyz": [0.0, -4.7500444599890557e-07, 6.791790790566779], "label": "Fe", "properties": {"wyckoff": "2b"}}, {"species": [{"element": "Fe", "oxidation_state": null, "occu": 1.0}], "abc": [4.68e-06, 4.68e-06, 4.68e-06], "xyz": [0.0, -4.446000001940035e-12, 6.35705667792e-05], "label": "Fe", "properties": {"wyckoff": "2b"}}, {"species": [{"element": "O", "oxidation_state": null, "occu": 1.0}], "abc": [0.32692944, 0.17307603, 0.75001329], "xyz": [0.4344344337490825, -1.6302934872666053, 5.659857621868362], "label": "O", "properties": {"wyckoff": "n/a"}}, {"species": [{"element": "O", "oxidation_state": null, "occu": 1.0}], "abc": [0.17307603, 0.75001329, 0.32692944], "xyz": [-1.6290923409292466, 0.4389148649935106, 5.6598576260992], "label": "O", "properties": {"wyckoff": "n/a"}}, {"species": [{"element": "O", "oxidation_state": null, "occu": 1.0}], "abc": [0.75001329, 0.32692944, 0.17307603], "xyz": [1.1946579071801642, 1.191377434755273, 5.6598576276377335], "label": "O", "properties": {"wyckoff": "n/a"}}, {"species": [{"element": "O", "oxidation_state": null, "occu": 1.0}], "abc": [0.82692944, 0.25001329, 0.67307603], "xyz": [1.629032732819836, -0.43888140024472744, 7.923766697637733], "label": "O", "properties": {"wyckoff": "n/a"}}, {"species": [{"element": "O", "oxidation_state": null, "occu": 1.0}], "abc": [0.25001329, 0.67307603, 0.82692944], "xyz": [-1.1945982990707538, -1.1913439700064896, 7.9237666960992], "label": "O", "properties": {"wyckoff": "n/a"}}, {"species": [{"element": "O", "oxidation_state": null, "occu": 1.0}], "abc": [0.67307603, 0.82692944, 0.25001329], "xyz": [-0.4344344337490822, 1.630223707733395, 7.923766701868361], "label": "O", "properties": {"wyckoff": "n/a"}}], "@version": "2020.10.20"}, "wf_meta": {"wf_uuid": "913524cf-a98b-4b21-bf0b-dfa9baed3137", "wf_name": "MagneticOrderingsWF", "wf_version": 2.0}, "task_id": 27, "structure": {"@module": "pymatgen.core.structure", "@class": "Structure", "charge": null, "lattice": {"matrix": [[2.823691, 1.630258, 4.527818], [-2.823691, 1.630258, 4.527818], [0.0, -3.260518, 4.527818]], "a": 5.5796153855950505, "b": 5.5796153855950505, "c": 5.579615889059748, "alpha": 60.80516655919878, "beta": 60.80516655919878, "gamma": 60.8051724475279, "volume": 125.05869696307667}, "sites": [{"species": [{"element": "La", "occu": 1}], "abc": [0.250011, 0.250011, 0.250011], "xyz": [0.0, -5.000220000273004e-07, 3.3960129179939997], "label": "La", "properties": {"magmom": 0.012}}, {"species": [{"element": "La", "occu": 1}], "abc": [0.750011, 0.750011, 0.750011], "xyz": [0.0, -1.5000219999450337e-06, 10.187739917994], "label": "La", "properties": {"magmom": 0.012}}, {"species": [{"element": "Fe", "occu": 1}], "abc": [0.500005, 0.500005, 0.500005], "xyz": [0.0, -1.0000099999185608e-06, 6.79179491727], "label": "Fe", "properties": {"magmom": 4.372}}, {"species": [{"element": "Fe", "occu": 1}], "abc": [5e-06, 5e-06, 5e-06], "xyz": [0.0, -1.0000000000699553e-11, 6.791727e-05], "label": "Fe", "properties": {"magmom": 4.372}}, {"species": [{"element": "O", "occu": 1}], "abc": [0.326929, 0.173076, 0.750013], "xyz": [0.4344333314230001, -1.630293735444, 5.659854000724], "label": "O", "properties": {"magmom": 0.175}}, {"species": [{"element": "O", "occu": 1}], "abc": [0.173076, 0.750013, 0.326929], "xyz": [-1.629091814467, 0.43891533774000013, 5.659854000724], "label": "O", "properties": {"magmom": 0.175}}, {"species": [{"element": "O", "occu": 1}], "abc": [0.750013, 0.326929, 0.173076], "xyz": [1.194658483044, 1.191375897668, 5.659854000724], "label": "O", "properties": {"magmom": 0.175}}, {"species": [{"element": "O", "occu": 1}], "abc": [0.826929, 0.250013, 0.673076], "xyz": [1.6290325169560003, -0.4388831023319999, 7.923763000724], "label": "O", "properties": {"magmom": 0.175}}, {"species": [{"element": "O", "occu": 1}], "abc": [0.250013, 0.673076, 0.826929], "xyz": [-1.1945991855330003, -1.19134366226, 7.923763000724], "label": "O", "pro

======================================================================
magnetic-orderings-database-snapshot.part2.json.gz
======================================================================
[{"formula": "Li4 Ni2 C4 O12", "formula_pretty": "Li2Ni(CO3)2", "parent_structure": {"@module": "pymatgen.core.structure", "@class": "Structure", "charge": null, "lattice": {"matrix": [[-2.1268972, 0.04462337, 4.69122633], [4.31847574, -0.00054603, 4.73771943], [0.09048318, 7.71530745, -0.03828814]], "a": 5.151047216227324, "b": 6.410555234339444, "c": 7.7159330113443225, "alpha": 89.76237821951175, "beta": 90.0400524692694, "gamma": 66.7389136673293, "volume": 234.07509297240838}, "sites": [{"species": [{"element": "Li", "oxidation_state": null, "occu": 1.0}], "abc": [0.33348111, 0.2607431, 0.92227992], "xyz": [0.5001835326222477, 7.130411815166052, 2.7644506322019105], "label": "Li", "properties": {"wyckoff": "n/a"}}, {"species": [{"element": "Li", "oxidation_state": null, "occu": 1.0}], "abc": [0.15067671, 0.25805859, 0.42466802], "xyz": [0.8323712007032982, 3.283027133331564, 1.9132079965878952], "label": "Li", "properties": {"wyckoff": "n/a"}}, {"species": [{"element": "Li", "oxidation_state": null, "occu": 1.0}], "abc": [0.80771414, 0.81164603, 0.56416083], "xyz": [1.8381958131857439, 4.388273998538874, 7.6129203384531134], "label": "Li", "properties": {"wyckoff": "n/a"}}, {"species": [{"element": "Li", "oxidation_state": null, "occu": 1.0}], "abc": [0.66161584, 0.74492994, 0.07723693], "xyz": [1.8167616393578452, 0.6250234357751712, 6.630101441290792], "label": "Li", "properties": {"wyckoff": "n/a"}}, {"species": [{"element": "Ni", "oxidation_state": null, "occu": 1.0}], "abc": [0.49904691, 0.50019995, 0.50148155], "xyz": [1.1440555190318895, 3.891080369486136, 4.691748230303351], "label": "Ni", "properties": {"wyckoff": "1a"}}, {"species": [{"element": "Ni", "oxidation_state": null, "occu": 1.0}], "abc": [0.99965425, 0.00275775, 0.00143402], "xyz": [-2.114122794131332, 0.055670340845038996, 4.702614878295962], "label": "Ni", "properties": {"wyckoff": "1a"}}, {"species": [{"element": "C", "oxidation_state": null, "occu": 1.0}], "abc": [0.71678017, 0.13361608, 0.26576132], "xyz": [-0.9234530072800274, 2.082342480464245, 3.985437998075566], "label": "C", "properties": {"wyckoff": "n/a"}}, {"species": [{"element": "C", "oxidation_state": null, "occu": 1.0}], "abc": [0.78284474, 0.36625319, 0.76407988], "xyz": [-0.01423839251169913, 5.929844375815344, 5.378451513735863], "label": "C", "properties": {"wyckoff": "n/a"}}, {"species": [{"element": "C", "oxidation_state": null, "occu": 1.0}], "abc": [0.21630136, 0.634087, 0.2356107], "xyz": [2.299557374987214, 1.8271148541038884, 4.009823839990121], "label": "C", "properties": {"wyckoff": "n/a"}}, {"species": [{"element": "C", "oxidation_state": null, "occu": 1.0}], "abc": [0.27932894, 0.86999263, 0.73634767], "xyz": [3.229565205036019, 5.69313822070671, 5.403982882489158], "label": "C", "properties": {"wyckoff": "n/a"}}, {"species": [{"element": "O", "oxidation_state": null, "occu": 1.0}], "abc": [0.97155907, 0.12414681, 0.25596458], "xyz": [-1.5071207892684504, 2.0181318829849224, 5.13617583656975], "label": "O", "properties": {"wyckoff": "n/a"}}, {"species": [{"element": "O", "oxidation_state": null, "occu": 1.0}], "abc": [0.6089201, 0.0891011, 0.12435096], "xyz": [-0.8990778466595533, 0.9865293031517559, 3.2739568517249915], "label": "O", "properties": {"wyckoff": "n/a"}}, {"species": [{"element": "O", "oxidation_state": null, "occu": 1.0}], "abc": [0.57681516, 0.17585982, 0.40914639], "xyz": [-0.4303593159580652, 3.1823336024763806, 3.523479498044651], "label": "O", "properties": {"wyckoff": "n/a"}}, {"species": [{"element": "O", "oxidation_state": null, "occu": 1.0}], "abc": [0.92588856, 0.31900562, 0.90599471], "xyz": [-0.5096744724583956, 7.031169816876548, 5.820223063175241], "label": "O", "properties": {"wyckoff": "n/a"}}, {"species": [{"element": "O", "oxidation_state": null, "occu": 1.0}], "abc": [0.88898913, 0.40842704, 0.62152652], "xyz": [-0.07076853164349281, 4.83471486758589, 6.0816648424737085], "label": "O", "properties": {"wyckoff": "n/a"}}, {"species": [{"element": "O", "oxidation_state": null, "occu": 1.0}], "abc": [0.52448421, 0.38188318, 0.75613369], "xyz": [0.6020466314271753, 5.856999624942202, 4.240778544916], "label": "O", "properties": {"wyckoff": "n/a"}}, {"species": [{"element": "O", "oxidation_state": null, "occu": 1.0}], "abc": [0.4726095, 0.62137339, 0.24563035], "xyz": [1.7004195031256717, 1.9158638093729807, 5.151606184067054], "label": "O", "properties": {"wyckoff": "n/a"}}, {"species": [{"element": "O", "oxidation_state": null, "occu": 1.0}], "abc": [0.10962553, 0.58692817, 0.37729781], "xyz": [2.3356119361179157, 2.915539984559656, 3.280533136428575], "label": "O", "properties": {"wyckoff": "n/a"}}, {"species": [{"element": "O", "oxidation_state": null, "occu": 1.0}], "abc": [0.42149851, 0.820711, 0.59486069], "xyz": [2.7015614292161625, 4.607893664407989, 5.842867249903282], "label": "O", "properties": {"wyckoff": "n/a"}}, {"species": [{"element": "O", "oxidation_state": null, "occu": 1.0}], "abc": [0.07210257, 0.684618

In [ ]:
print("="*70)
print("DATABASE SNAPSHOT README")
print("="*70)

print(Path("data/database_snapshot/README.md").read_text(encoding="utf-8"))

======================================================================
DATABASE SNAPSHOT README
======================================================================
# Magnetic Ordering Database Snapshot

The canonical repository for Materials Project calculations is on the [Materials Project website](https://materialsproject.org) and is accessible via a REST API. The easiest way to use the REST API is via the `MPRester` in [`pymatgen`](https://pymatgen.org).

For convenience and for the historical record, a static data dump is also provided here. This data dump is generated from the magnetic orderings workflow in [`atomate`](https://atomate.org) and is a copy of the generated `magnetic_orderings` collection. The file provided here is a snapshot of the database at this point in time. As the database is being expanded, future results will be made available at the Materials Project. This snapshot will not be updated.

The file format is JSON with crystal structures encoded via `pymatgen`. The easiest way to load this data is using the following code snippet, though note this will load the whole dataset in memory:

```
from monty.serialization import loadfn
data = loadfn("magnetic-orderings-database-snapshot.part1.json.gz")  # and the same for part 2
```

This snapshot is split into parts simply due to git's large file limit. If loading the data with a different JSON parser, the `Structure` objects can be reconstructed in Python using pymatgen and `Structure.from_dict()`. Data analysis is usually easier if the snapshot is first loaded into a database that can handle JSON documents, like MongoDB.

If using any of this data please cite:

N. C. Frey, M. K. Horton, J. M. Munro, S. M. Griffin, K. A. Persson, and V. B. Shenoy, https://arxiv.org/abs/2006.01075 1 (2020).

Horton, M. K., Montoya, J. H., Liu, M., & Persson, K. A. (2019). High-throughput prediction of the ground-state collinear magnetic order of inorganic materials using density functional theory. npj Computational Materials, 5(1), 2.

and the [canonical Materials Project citations](https://www.materialsproject.org/citing).

If there are any questions about the data, please email either Nathan Frey or Matt Horton, thank you!

In [ ]:
pwd

'/content/drive/MyDrive/Proj_2_Alt_Mags_Grnd_E/magnetic-topological-materials'

In [ ]:
import gzip
import json
from pprint import pprint

file_path = "/content/drive/MyDrive/Proj_2_Alt_Mags_Grnd_E/magnetic-topological-materials/data/database_snapshot/magnetic-orderings-database-snapshot.part1.json.gz"

with gzip.open(file_path, "rt", encoding="utf-8") as f:
    data = json.load(f)

print("Number of records:", len(data))

# Show ONLY the keys of the first complete record
print("\nTop-level fields:")
for key in data[0].keys():
    print(" -", key)

print("\nFirst record:")
pprint(data[0], depth=2)

Number of records: 23155

Top-level fields:
 - formula
 - formula_pretty
 - parent_structure
 - wf_meta
 - task_id
 - structure
 - magmoms
 - input
 - total_magnetization
 - total_magnetization_per_formula_unit
 - total_magnetization_per_unit_volume
 - ordering
 - ordering_changed
 - symmetry
 - symmetry_changed
 - energy_per_atom
 - stable
 - decomposes_to
 - energy_above_ground_state_per_atom
 - energy_diff_relax_static

First record:
{'decomposes_to': 46,
 'energy_above_ground_state_per_atom': 0.04013631100000037,
 'energy_diff_relax_static': 7.490000006882269e-07,
 'energy_per_atom': -7.599370667,
 'formula': 'La2 Fe2 O6',
 'formula_pretty': 'LaFeO3',
 'input': {'index': 5,
           'input_index': None,
           'ordering': 'FM',
           'origin': 'input',
           'structure': {...},
           'symmetry': 'R-3c'},
 'magmoms': {'bader': [...], 'vasp': [...]},
 'ordering': 'FM',
 'ordering_changed': False,
 'parent_structure': {'@class': 'Structure',
                      '@module': 'pymatgen.core.structure',
                      '@version': '2020.10.20',
                      'charge': None,
                      'lattice': {...},
                      'sites': [...]},
 'stable': False,
 'structure': {'@class': 'Structure',
               '@module': 'pymatgen.core.structure',
               '@version': '2020.10.20',
               'charge': None,
               'lattice': {...},
               'sites': [...]},
 'symmetry': 'R-3c',
 'symmetry_changed': False,
 'task_id': 27,
 'total_magnetization': 9.9999788,
 'total_magnetization_per_formula_unit': 19.9999576,
 'total_magnetization_per_unit_volume': 0.07996228205506149,
 'wf_meta': {'wf_name': 'MagneticOrderingsWF',
             'wf_uuid': '913524cf-a98b-4b21-bf0b-dfa9baed3137',
             'wf_version': 2.0}}

In [ ]:
# Inspect likely important fields more deeply
record = data[0]

print("\n" + "="*70)
print("FIELD TYPE / SUMMARY")
print("="*70)

for key, value in record.items():
    print(f"\n{key}:")
    print("  type =", type(value).__name__)

    if isinstance(value, dict):
        print("  subkeys =", list(value.keys()))

    elif isinstance(value, list):
        print("  length =", len(value))
        if len(value) > 0:
            print("  first item type =", type(value[0]).__name__)

======================================================================
FIELD TYPE / SUMMARY
======================================================================

formula:
  type = str

formula_pretty:
  type = str

parent_structure:
  type = dict
  subkeys = ['@module', '@class', 'charge', 'lattice', 'sites', '@version']

wf_meta:
  type = dict
  subkeys = ['wf_uuid', 'wf_name', 'wf_version']

task_id:
  type = int

structure:
  type = dict
  subkeys = ['@module', '@class', 'charge', 'lattice', 'sites', '@version']

magmoms:
  type = dict
  subkeys = ['vasp', 'bader']

input:
  type = dict
  subkeys = ['structure', 'ordering', 'symmetry', 'index', 'origin', 'input_index']

total_magnetization:
  type = float

total_magnetization_per_formula_unit:
  type = float

total_magnetization_per_unit_volume:
  type = float

ordering:
  type = str

ordering_changed:
  type = bool

symmetry:
  type = str

symmetry_changed:
  type = bool

energy_per_atom:
  type = float

stable:
  type = bool

decomposes_to:
  type = int

energy_above_ground_state_per_atom:
  type = float

energy_diff_relax_static:
  type = float

### Step - 1.3 - Auditing dataset

In [ ]:
import pandas as pd
from collections import Counter

rows = []

for r in data:
    rows.append({
        "task_id": r.get("task_id"),
        "formula": r.get("formula_pretty", r.get("formula")),
        "ordering": r.get("ordering"),
        "energy_per_atom": r.get("energy_per_atom"),
        "energy_above_ground": r.get("energy_above_ground_state_per_atom"),
        "total_magnetization": r.get("total_magnetization"),
        "symmetry": r.get("symmetry"),
        "stable": r.get("stable"),
        "ordering_changed": r.get("ordering_changed"),
        "symmetry_changed": r.get("symmetry_changed"),
    })

df = pd.DataFrame(rows)

print("="*70)
print("MAGNETIC ORDERING DATASET AUDIT")
print("="*70)

print("Total records:", len(df))
print("Unique task IDs:", df["task_id"].nunique())
print("Unique formulas:", df["formula"].nunique())

print("\nOrdering distribution:")
print(df["ordering"].value_counts(dropna=False))

print("\nMissing values:")
print(df.isna().sum())

print("\nRecords per task:")
print(df.groupby("task_id").size().describe())

print("\nTasks with multiple magnetic configurations:")
multi = df.groupby("task_id").size()
print("Count:", (multi > 1).sum())
print("Maximum configurations for one task:", multi.max())

======================================================================
MAGNETIC ORDERING DATASET AUDIT
======================================================================
Total records: 23155
Unique task IDs: 23155
Unique formulas: 1967

Ordering distribution:
ordering
FiM    10467
AFM     8719
FM      3885
NM        84
Name: count, dtype: int64

Missing values:
task_id                0
formula                0
ordering               0
energy_per_atom        0
energy_above_ground    0
total_magnetization    0
symmetry               0
stable                 0
ordering_changed       0
symmetry_changed       0
dtype: int64

Records per task:
count    23155.0
mean         1.0
std          0.0
min          1.0
25%          1.0
50%          1.0
75%          1.0
max          1.0
dtype: float64

Tasks with multiple magnetic configurations:
Count: 0
Maximum configurations for one task: 1

In [ ]:
# Show examples where the same material/task has multiple configurations

multi_tasks = (
    df.groupby("task_id")
      .filter(lambda x: len(x) > 1)
      .sort_values(["task_id", "energy_per_atom"])
)

print(multi_tasks.head(50).to_string(index=False))

Empty DataFrame
Columns: [task_id, formula, ordering, energy_per_atom, energy_above_ground, total_magnetization, symmetry, stable, ordering_changed, symmetry_changed]
Index: []

In [ ]:
# ============================================================
# PHASE 1B — GROUP BY PARENT STRUCTURE
# ============================================================

import json
import hashlib
import pandas as pd

def structure_signature(parent_structure):
    """
    Create a reproducible signature for the parent crystal.
    We ignore pymatgen metadata and retain the physical structure.
    """
    lattice = parent_structure["lattice"]["matrix"]

    sites = []
    for site in parent_structure["sites"]:
        element = site["species"][0]["element"]
        abc = site["abc"]
        sites.append({
            "element": element,
            "abc": [round(float(x), 6) for x in abc]
        })

    # Sort sites so ordering in the JSON does not matter
    sites = sorted(
        sites,
        key=lambda x: (x["element"], x["abc"][0], x["abc"][1], x["abc"][2])
    )

    obj = {
        "lattice": [
            [round(float(x), 6) for x in row]
            for row in lattice
        ],
        "sites": sites
    }

    text = json.dumps(obj, sort_keys=True)
    return hashlib.sha256(text.encode()).hexdigest()


# Build signatures
signatures = []

for r in data:
    signatures.append(structure_signature(r["parent_structure"]))

df["parent_structure_id"] = signatures

print("="*70)
print("PARENT STRUCTURE GROUPING")
print("="*70)

print("Total records:", len(df))
print("Unique parent structures:", df["parent_structure_id"].nunique())

counts = df.groupby("parent_structure_id").size()

print("\nRecords per parent structure:")
print(counts.describe())

print("\nParent structures with >1 magnetic ordering:",
      (counts > 1).sum())

print("Maximum orderings for one parent:",
      counts.max())

======================================================================
PARENT STRUCTURE GROUPING
======================================================================
Total records: 23155
Unique parent structures: 2588

Records per parent structure:
count    2588.000000
mean        8.947063
std         4.129885
min         1.000000
25%         6.000000
50%         9.000000
75%        12.000000
max        16.000000
dtype: float64

Parent structures with >1 magnetic ordering: 2532
Maximum orderings for one parent: 16

In [ ]:
# ============================================================
# SHOW ACTUAL MULTI-ORDERING MATERIALS
# ============================================================

multi = (
    df.groupby("parent_structure_id")
      .filter(lambda x: len(x) > 1)
      .sort_values(["parent_structure_id", "energy_per_atom"])
)

print(
    multi[
        [
            "parent_structure_id",
            "formula",
            "ordering",
            "energy_per_atom",
            "energy_above_ground",
            "total_magnetization",
            "symmetry"
        ]
    ].head(100).to_string(index=False)
)

                                             parent_structure_id     formula ordering  energy_per_atom  energy_above_ground  total_magnetization symmetry
001811216d9f019e2440ee897870fd552e7ba3915cc17c7391bfd225142f61f9       VGaO3       FM        -6.948634         0.000000e+00         8.010861e+00     Pnma
001811216d9f019e2440ee897870fd552e7ba3915cc17c7391bfd225142f61f9       VGaO3      AFM        -6.948318         3.157350e-04         4.670000e-05     Pnma
001811216d9f019e2440ee897870fd552e7ba3915cc17c7391bfd225142f61f9       VGaO3      AFM        -6.943229         5.404711e-03         3.140000e-05     Pnma
001811216d9f019e2440ee897870fd552e7ba3915cc17c7391bfd225142f61f9       VGaO3      FiM        -6.942791         5.843074e-03         8.112000e-04     Pnma
0027238c0d697ffb3a24191a8ef1c06470d145a1b8afc4d447dad714f32a7339      TiCoO3      AFM        -7.856785         0.000000e+00         1.050000e-05      R-3
0027238c0d697ffb3a24191a8ef1c06470d145a1b8afc4d447dad714f32a7339      TiCoO3       FM        -7.855887         8.978575e-04         5.999023e+00      R-3
0027238c0d697ffb3a24191a8ef1c06470d145a1b8afc4d447dad714f32a7339      TiCoO3      FiM        -7.850065         6.719966e-03         3.600000e-06      P-1
0027238c0d697ffb3a24191a8ef1c06470d145a1b8afc4d447dad714f32a7339      TiCoO3      FiM        -7.849434         7.350455e-03         6.300000e-06      P-1
0027238c0d697ffb3a24191a8ef1c06470d145a1b8afc4d447dad714f32a7339      TiCoO3      AFM        -7.843586         1.319921e-02         2.230000e-05      P-1
0027238c0d697ffb3a24191a8ef1c06470d145a1b8afc4d447dad714f32a7339      TiCoO3      FiM        -7.842616         1.416933e-02         6.930000e-05       P1
0027238c0d697ffb3a24191a8ef1c06470d145a1b8afc4d447dad714f32a7339      TiCoO3      FiM        -7.817326         3.945876e-02         2.948000e-04      P-1
0027238c0d697ffb3a24191a8ef1c06470d145a1b8afc4d447dad714f32a7339      TiCoO3      FiM        -7.816956         3.982891e-02         4.217000e-04      P-1
0080599ae6fef59caf03361636453651f921aabcea87763ed45b12d4bfe7e42b    Y2MnCoO6       FM        -7.991958         0.000000e+00         1.200003e+01   P2_1/c
0080599ae6fef59caf03361636453651f921aabcea87763ed45b12d4bfe7e42b    Y2MnCoO6      FiM        -7.989210         2.747801e-03         0.000000e+00      P-1
0080599ae6fef59caf03361636453651f921aabcea87763ed45b12d4bfe7e42b    Y2MnCoO6      FiM        -7.985770         6.187767e-03         6.000075e+00      P-1
0080599ae6fef59caf03361636453651f921aabcea87763ed45b12d4bfe7e42b    Y2MnCoO6      FiM        -7.985770         6.187767e-03         6.000075e+00      P-1
0080599ae6fef59caf03361636453651f921aabcea87763ed45b12d4bfe7e42b    Y2MnCoO6      FiM        -7.985411         6.546228e-03         5.999971e+00      P-1
0080599ae6fef59caf03361636453651f921aabcea87763ed45b12d4bfe7e42b    Y2MnCoO6      FiM        -7.985411         6.546228e-03         5.999971e+00      P-1
0080599ae6fef59caf03361636453651f921aabcea87763ed45b12d4bfe7e42b    Y2MnCoO6      FiM        -7.980623         1.133411e-02         3.367000e-04      P-1
0080599ae6fef59caf03361636453651f921aabcea87763ed45b12d4bfe7e42b    Y2MnCoO6      FiM        -7.979848         1.210992e-02         5.506800e-03   P2_1/c
00a3d9e3cff0a3357d0a7dad9bcdeb3570f739439169f9386df6a207a0e59faa   Cr(SbO3)2      FiM        -6.571381         0.000000e+00         4.946000e-04 P2_12_12
00a3d9e3cff0a3357d0a7dad9bcdeb3570f739439169f9386df6a207a0e59faa   Cr(SbO3)2      FiM        -6.571305         7.610611e-05         1.126030e-02     Pnnm
00a3d9e3cff0a3357d0a7dad9bcdeb3570f739439169f9386df6a207a0e59faa   Cr(SbO3)2      FiM        -6.542915         2.846569e-02         2.127285e+00     P2_1
00a3d9e3cff0a3357d0a7dad9bcdeb3570f739439169f9386df6a207a0e59faa   Cr(SbO3)2      FiM        -6.542435         2.894599e-02         2.314744e+00     Pnnm
00a3d9e3cff0a3357d0a7dad9bcdeb3570f739439169f9386df6a207a0e59faa   Cr(SbO3)2       FM        -6.424387         1.469935e-01         3.036212e+00     Pnnm
00b38beda8751fc85eb397ccc2f94eeefcd08916100cc0dbf7c98e6e7169cfdb      RbMnO2      FiM        -6.174876         0.000000e+00         2.590000e-05       P1
00b38beda8751fc85eb397ccc2f94eeefcd08916100cc0dbf7c98e6e7169cfdb      RbMnO2      FiM        -6.174721         1.557233e-04         4.000000e-07       P1
00b38beda8751fc85eb397ccc2f94eeefcd08916100cc0dbf7c98e6e7169cfdb      RbMnO2      FiM        -6.174549         3.275758e-04         3.800000e-06      P-1
00b38beda8751fc85eb397ccc2f94eeefcd08916100cc0dbf7c98e6e7169cfdb      RbMnO2      FiM        -6.174366         5.104625e-04         5.600000e-06      P-1
00b38beda8751fc85eb397ccc2f94eeefcd08916100cc0dbf7c98e6e7169cfdb      RbMnO2      FiM        -6.172271         2.605530e-03         1.270000e-05       P1
00b38beda8751fc85eb397ccc2f94eeefcd08916100cc0dbf7c98e6e7169cfdb      RbMnO2      FiM        -6.171785         3.091832e-03         3.800000e-06      P-1
00b38beda8751fc85eb397ccc2f94eeefcd08916100cc0dbf7c98e6e7169cfdb      RbMnO2       FM        -6.165254         9.622004e-03         2.399752e+01      P-1
010614385d406bfe532622ed6d61e4a50c25417beb6b1df7bf6e4057c371efdb Ti2Co(PO5)2      AFM        -7.870752         0.000000e+00         1.500000e-06   P2_1/c
010614385d406bfe532622ed6d61e4a50c25417beb6b1df7bf6e4057c371efdb Ti2Co(PO5)2      AFM        -7.870734         1.843667e-05         6.500000e-06   P2_1/c
010614385d406bfe532622ed6d61e4a50c25417beb6b1df7bf6e4057c371efdb Ti2Co(PO5)2      FiM        -7.870683         6.868150e-05         3.740000e-05      P-1
010614385d406bfe532622ed6d61e4a50c25417beb6b1df7bf6e4057c371efdb Ti2Co(PO5)2      FiM        -7.870643         1.093557e-04         3.700000e-06     P2_1
010614385d406bfe532622ed6d61e4a50c25417beb6b1df7bf6e4057c371efdb Ti2Co(PO5)2      AFM        -7.870594         1.578618e-04         3.400000e-06      P-1
010614385d406bfe532622ed6d61e4a50c25417beb6b1df7bf6e4057c371efdb Ti2Co(PO5)2      FiM        -7.870585         1.666347e-04         0.000000e+00      P-1
010614385d406bfe532622ed6d61e4a50c25417beb6b1df7bf6e4057c371efdb Ti2Co(PO5)2      FiM        -7.870499         2.532737e-04         0.000000e+00      P-1
010614385d406bfe532622ed6d61e4a50c25417beb6b1df7bf6e4057c371efdb Ti2Co(PO5)2      FiM        -7.870327         4.252403e-04         3.000000e-06      P-1
010614385d406bfe532622ed6d61e4a50c25417beb6b1df7bf6e4057c371efdb Ti2Co(PO5)2      FiM        -7.870174         5.784805e-04         3.634000e-04      P-1
0111b5e04a035fa0936b9d332f4332073465220282d193315de2f24d9dfd2ce5  Li3Co2RuO6      FiM        -5.999350         0.000000e+00         5.194520e+00     C2/c
0111b5e04a035fa0936b9d332f4332073465220282d193315de2f24d9dfd2ce5  Li3Co2RuO6       FM        -5.998037         1.313428e-03         9.005569e+00     C2/m
0111b5e04a035fa0936b9d332f4332073465220282d193315de2f24d9dfd2ce5  Li3Co2RuO6       FM        -5.996636         2.714079e-03         1.802023e+01      P-1
0111b5e04a035fa0936b9d332f4332073465220282d193315de2f24d9dfd2ce5  Li3Co2RuO6       FM        -5.996636         2.714079e-03         1.802023e+01      P-1
0111b5e04a035fa0936b9d332f4332073465220282d193315de2f24d9dfd2ce5  Li3Co2RuO6      FiM        -5.996424         2.925925e-03         5.902560e+00     P2/m
0111b5e04a035fa0936b9d332f4332073465220282d193315de2f24d9dfd2ce5  Li3Co2RuO6      FiM        -5.994796         4.554149e-03         2.001771e+00       P1
0111b5e04a035fa0936b9d332f4332073465220282d193315de2f24d9dfd2ce5  Li3Co2RuO6       FM        -5.989236         1.011459e-02         1.632444e+01      P-1
0111b5e04a035fa0936b9d332f4332073465220282d193315de2f24d9dfd2ce5  Li3Co2RuO6       FM        -5.989236         1.011459e-02         1.632444e+01      P-1
0111b5e04a035fa0936b9d332f4332073465220282d193315de2f24d9dfd2ce5  Li3Co2RuO6      FiM        -5.985189         1.416150e-02         8.800782e+00       C2
0111b5e04a035fa0936b9d332f4332073465220282d193315de2f24d9dfd2ce5  Li3Co2RuO6      FiM        -5.983975         1.537497e-02         2.865083e+00     C2/m
0111b5e04a035fa0936b9d332f4332073465220282d193315de2f24d9dfd2ce5  Li3Co2RuO6      FiM        -5.983342         1.600772e-02         3.019024e+00       C2
0111b5e04a035fa0936b9d332f4332073465220282d193315de2f24d9dfd2ce5  Li3Co2RuO6      FiM        -5.976320         2.303018e-02         7.024942e-01       P1
0111b5e04a035fa0936b9d332f4332073465220282d193315de2f24d9dfd2ce5  Li3Co2RuO6      FiM        -5.976022         2.332768e-02         1.366785e+00      P-1
0111b5e04a035fa0936b9d332f4332073465220282d193315de2f24d9dfd2ce5  Li3Co2RuO6      FiM        -5.967859         3.149123e-02         6.381301e+00       C2
0111b5e04a035fa0936b9d332f4332073465220282d193315de2f24d9dfd2ce5  Li3Co2RuO6       FM        -5.958338         4.101174e-02         6.001474e+00     C2/m
0144dccc723608c2bf82cb4eb508096a730930fced745806296a24c010a3bd64      CoPtO2      FiM        -6.046298         0.000000e+00         4.290067e+00      P-1
0144dccc723608c2bf82cb4eb508096a730930fced745806296a24c010a3bd64      CoPtO2      FiM        -6.021159         2.513961e-02         2.393660e-02      P-1
0144dccc723608c2bf82cb4eb508096a730930fced745806296a24c010a3bd64      CoPtO2      FiM        -6.011311         3.498691e-02         1.273710e-02      P-1
0144dccc723608c2bf82cb4eb508096a730930fced745806296a24c010a3bd64      CoPtO2      FiM        -6.008855         3.744339e-02         3.462000e-04     P2/c
0144dccc723608c2bf82cb4eb508096a730930fced745806296a24c010a3bd64      CoPtO2      FiM        -6.007090         3.920863e-02         1.241948e-01      P-1
0144dccc723608c2bf82cb4eb508096a730930fced745806296a24c010a3bd64      CoPtO2      FiM        -6.004566         4.173237e-02         9.164990e-02      P-1
0144dccc723608c2bf82cb4eb508096a730930fced745806296a24c010a3bd64      CoPtO2      FiM        -5.987249         5.904947e-02         1.466557e+00       C2
0144dccc723608c2bf82cb4eb508096a730930fced745806296a24c010a3bd64      CoPtO2      FiM        -5.983621         6.267751e-02         1.633865e+00       P1
0144dccc723608c2bf82cb4eb508096a730930fced745806296a24c010a3bd64      CoPtO2      FiM        -5.977637         6.866136e-02         2.491687e+00       Cm
0144dccc723608c2bf82cb4eb508096a730930fced745806296a24c010a3bd64      CoPtO2      FiM        -5.942385         1.039130e-01         2.076200e-03     C2/m
0144dccc723608c2bf82cb4eb508096a730930fced745806296a24c010a3bd64      CoPtO2      FiM        -5.925273         1.210252e-01         1.762700e-03      P-1
0144dccc723608c2bf82cb4eb508096a730930fced745806296a24c010a3bd64      CoPtO2      FiM        -5.922502         1.237962e-01         3.281459e+00     R-3m
0144dccc723608c2bf82cb4eb508096a730930fced745806296a24c010a3bd64      CoPtO2      FiM        -5.910636         1.356622e-01         1.405750e-02     C2/m
014d51014a70c99d5252a81104d96574d5ec5bdaefbb335694b9e77230f2dd65        FeOF      AFM        -6.085324         0.000000e+00         0.000000e+00     Pnma
014d51014a70c99d5252a81104d96574d5ec5bdaefbb335694b9e77230f2dd65        FeOF      AFM        -6.082388         2.936115e-03         3.100000e-06     Pnma
014d51014a70c99d5252a81104d96574d5ec5bdaefbb335694b9e77230f2dd65        FeOF      AFM        -6.028946         5.637805e-02         0.000000e+00     Pnma
014d51014a70c99d5252a81104d96574d5ec5bdaefbb335694b9e77230f2dd65        FeOF       FM        -6.024820         6.050389e-02         1.999958e+01     Pnma
014d51014a70c99d5252a81104d96574d5ec5bdaefbb335694b9e77230f2dd65        FeOF       FM        -6.024806         6.051785e-02         1.999957e+01     Pnma
016a233be97bda6ad643b4e900a83061fd0001b8c1e3f1f50728e6bca17fb5e6  Li3TiCr3O8      FiM        -7.297379         0.000000e+00         0.000000e+00       C2
016a233be97bda6ad643b4e900a83061fd0001b8c1e3f1f50728e6bca17fb5e6  Li3TiCr3O8      FiM        -7.297355         2.481667e-05         1.080000e-05       C2
016a233be97bda6ad643b4e900a83061fd0001b8c1e3f1f50728e6bca17fb5e6  Li3TiCr3O8      FiM        -7.296867         5.120520e-04         5.800000e-05      P-1
016a233be97bda6ad643b4e900a83061fd0001b8c1e3f1f50728e6bca17fb5e6  Li3TiCr3O8      FiM        -7.296525         8.544967e-04         1.334000e-04      P-1
016a233be97bda6ad643b4e900a83061fd0001b8c1e3f1f50728e6bca17fb5e6  Li3TiCr3O8      FiM        -7.295989         1.390390e-03         0.000000e+00     C2/m
016a233be97bda6ad643b4e900a83061fd0001b8c1e3f1f50728e6bca17fb5e6  Li3TiCr3O8      FiM        -7.295910         1.469488e-03         7.600000e-06       Cm
016a233be97bda6ad643b4e900a83061fd0001b8c1e3f1f50728e6bca17fb5e6  Li3TiCr3O8      FiM        -7.295553         1.826825e-03         1.200226e+01     P2/m
016a233be97bda6ad643b4e900a83061fd0001b8c1e3f1f50728e6bca17fb5e6  Li3TiCr3O8      FiM        -7.295527         1.852855e-03         1.200225e+01     P2/m
016a233be97bda6ad643b4e900a83061fd0001b8c1e3f1f50728e6bca17fb5e6  Li3TiCr3O8      FiM        -7.295457         1.922039e-03         1.200244e+01     C2/m
016a233be97bda6ad643b4e900a83061fd0001b8c1e3f1f50728e6bca17fb5e6  Li3TiCr3O8      FiM        -7.295457         1.922039e-03         1.200244e+01     C2/m
016a233be97bda6ad643b4e900a83061fd0001b8c1e3f1f50728e6bca17fb5e6  Li3TiCr3O8      FiM        -7.295302         2.077485e-03         1.200228e+01     C2/m
016a233be97bda6ad643b4e900a83061fd0001b8c1e3f1f50728e6bca17fb5e6  Li3TiCr3O8       FM        -7.295241         2.138535e-03         9.000100e+00       C2
01713c675f442938b6dd35b0623dcbaf761df09d1820a15f108b80d27f849f2d   Sr2NiRuO6       FM        -6.288685         0.000000e+00         7.992007e+00    Fm-3m
01713c675f442938b6dd35b0623dcbaf761df09d1820a15f108b80d27f849f2d   Sr2NiRuO6       FM        -6.288685         1.395000e-07         7.991957e+00    Fm-3m
01713c675f442938b6dd35b0623dcbaf761df09d1820a15f108b80d27f849f2d   Sr2NiRuO6       FM        -6.288455         2.297410e-04         4.001065e+00    Fm-3m
01713c675f442938b6dd35b0623dcbaf761df09d1820a15f108b80d27f849f2d   Sr2NiRuO6       FM        -6.288378         3.063740e-04         4.000925e+00    Fm-3m
01713c675f442938b6dd35b0623dcbaf761df09d1820a15f108b80d27f849f2d   Sr2NiRuO6       FM        -6.288372         3.126965e-04         7.998322e+00    Fm-3m
01713c675f442938b6dd35b0623dcbaf761df09d1820a15f108b80d27f849f2d   Sr2NiRuO6       FM        -6.288372         3.126965e-04         7.998322e+00    Fm-3m
01713c675f442938b6dd35b0623dcbaf761df09d1820a15f108b80d27f849f2d   Sr2NiRuO6      FiM        -6.285981         2.703726e-03         3.995496e+00    Fm-3m
01713c675f442938b6dd35b0623dcbaf761df09d1820a15f108b80d27f849f2d   Sr2NiRuO6      FiM        -6.285979         2.705277e-03         3.995742e+00    Fm-3m
01713c675f442938b6dd35b0623dcbaf761df09d1820a15f108b80d27f849f2d   Sr2NiRuO6      FiM        -6.285767         2.917664e-03         3.995703e+00    Fm-3m
01713c675f442938b6dd35b0623dcbaf761df09d1820a15f108b80d27f849f2d   Sr2NiRuO6      FiM        -6.284285         4.399889e-03         4.062341e+00    Fm-3m
01713c675f442938b6dd35b0623dcbaf761df09d1820a15f108b80d27f849f2d   Sr2NiRuO6      FiM        -6.284271         4.413336e-03         4.062171e+00    Fm-3m
01713c675f442938b6dd35b0623dcbaf761df09d1820a15f108b80d27f849f2d   Sr2NiRuO6      FiM        -6.284256         4.428958e-03         4.061819e+00    Fm-3m
01713c675f442938b6dd35b0623dcbaf761df09d1820a15f108b80d27f849f2d   Sr2NiRuO6      FiM        -6.282154         6.530596e-03         2.458720e-02    Fm-3m
01713c675f442938b6dd35b0623dcbaf761df09d1820a15f108b80d27f849f2d   Sr2NiRuO6      FiM        -6.278948         9.736904e-03         1.980800e-03    Fm-3m

### Step - 1.4 - Reconstructing magnetic configurations

In [ ]:
# ============================================================
# PHASE 1C — INSPECT SITE-RESOLVED MAGNETIC CONFIGURATIONS
# ============================================================

import numpy as np

# Pick the first parent structure having multiple records
parent_id = (
    df["parent_structure_id"]
    .value_counts()
    .loc[lambda x: x > 1]
    .index[0]
)

records = [
    r for r in data
    if structure_signature(r["parent_structure"]) == parent_id
]

print("=" * 80)
print("SELECTED PARENT STRUCTURE")
print("=" * 80)

print("Formula:", records[0]["formula_pretty"])
print("Number of configurations:", len(records))

for i, r in enumerate(records):

    vasp_magmoms = np.array(r["magmoms"]["vasp"], dtype=float)

    print(f"\nConfiguration {i+1}")
    print("-" * 50)
    print("task_id:", r["task_id"])
    print("ordering:", r["ordering"])
    print("energy/atom:", r["energy_per_atom"])
    print("energy above ground:", r["energy_above_ground_state_per_atom"])
    print("total magnetization:", r["total_magnetization"])
    print("symmetry:", r["symmetry"])

    print("VASP magmoms:")
    print(vasp_magmoms)

    print("Signs:")
    print(np.sign(vasp_magmoms))

================================================================================
SELECTED PARENT STRUCTURE
================================================================================
Formula: SrFe4(CuO4)3
Number of configurations: 16

Configuration 1
--------------------------------------------------
task_id: 88
ordering: FiM
energy/atom: -6.0089305675
energy above ground: 0.0013066755000004093
total magnetization: 0.0049506
symmetry: Im-3
VASP magmoms:
[ 0.    -4.202 -4.202  4.201  4.201 -0.    -0.    -0.     0.072  0.072
 -0.072 -0.072 -0.    -0.     0.     0.    -0.    -0.    -0.    -0.   ]
Signs:
[ 0. -1. -1.  1.  1.  0.  0.  0.  1.  1. -1. -1.  0.  0.  0.  0.  0.  0.
  0.  0.]

Configuration 2
--------------------------------------------------
task_id: 90
ordering: AFM
energy/atom: -6.008906605
energy above ground: 0.0013306380000006612
total magnetization: 0.000219
symmetry: Im-3
VASP magmoms:
[ 0.    -4.201 -4.201  4.201  4.201 -0.     0.    -0.    -0.071 -0.071
  0.072  0.072  0.     0.    -0.    -0.     0.     0.    -0.    -0.   ]
Signs:
[ 0. -1. -1.  1.  1.  0.  0.  0. -1. -1.  1.  1.  0.  0.  0.  0.  0.  0.
  0.  0.]

Configuration 3
--------------------------------------------------
task_id: 95
ordering: FM
energy/atom: -6.004682642000001
energy above ground: 0.005554601000000048
total magnetization: 38.0009486
symmetry: Im-3
VASP magmoms:
[-0.007 -0.007  4.255  4.254  4.252  4.252  4.252  4.252  4.255  4.254
  0.046  0.044  0.045  0.047  0.046  0.046  0.129  0.128  0.128  0.128
  0.129  0.128  0.128  0.128  0.128  0.127  0.128  0.127  0.128  0.127
  0.128  0.127  0.123  0.122  0.122  0.123  0.128  0.129  0.129  0.128]
Signs:
[-1. -1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
  1.  1.  1.  1.]

Configuration 4
--------------------------------------------------
task_id: 98
ordering: AFM
energy/atom: -6.0089636859999995
energy above ground: 0.001273557000001091
total magnetization: 0.0045799
symmetry: Im-3
VASP magmoms:
[ 0.000e+00 -4.202e+00 -4.202e+00  4.202e+00  4.202e+00  0.000e+00
  0.000e+00  0.000e+00 -7.200e-02 -7.200e-02  7.200e-02  7.200e-02
  0.000e+00  0.000e+00 -0.000e+00 -0.000e+00  1.000e-03  1.000e-03
  0.000e+00  0.000e+00]
Signs:
[ 0. -1. -1.  1.  1.  0.  0.  0. -1. -1.  1.  1.  0.  0.  0.  0.  1.  1.
  0.  0.]

Configuration 5
--------------------------------------------------
task_id: 99
ordering: FM
energy/atom: -6.004556646999999
energy above ground: 0.005680596000001259
total magnetization: 38.0013352
symmetry: Im-3
VASP magmoms:
[-0.007 -0.007  4.254  4.255  4.251  4.251  4.251  4.251  4.254  4.255
  0.047  0.046  0.047  0.047  0.044  0.046  0.128  0.128  0.127  0.129
  0.128  0.128  0.127  0.129  0.127  0.129  0.128  0.128  0.128  0.128
  0.127  0.129  0.123  0.123  0.123  0.123  0.128  0.129  0.129  0.129]
Signs:
[-1. -1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
  1.  1.  1.  1.]

Configuration 6
--------------------------------------------------
task_id: 100
ordering: FM
energy/atom: -6.004683291
energy above ground: 0.005553952000000528
total magnetization: 38.0011095
symmetry: Im-3
VASP magmoms:
[-0.007 -0.007  4.255  4.254  4.252  4.252  4.252  4.252  4.255  4.254
  0.046  0.046  0.045  0.047  0.046  0.043  0.129  0.127  0.128  0.128
  0.129  0.127  0.128  0.128  0.128  0.127  0.128  0.127  0.128  0.127
  0.128  0.127  0.123  0.122  0.122  0.123  0.128  0.129  0.129  0.128]
Signs:
[-1. -1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
  1.  1.  1.  1.]

Configuration 7
--------------------------------------------------
task_id: 104
ordering: FiM
energy/atom: -6.008932851
energy above ground: 0.0013043920000006537
total magnetization: 0.0011858
symmetry: Im-3
VASP magmoms:
[-0.    -4.202 -4.202  4.201  4.201 -0.    -0.    -0.     0.072  0.072
 -0.072 -0.072 -0.    -0.     0.     0.    -0.    -0.    -0.    -0.   ]
Signs:
[ 0. -1. -1.  1.  1.  0.  0.  0.  1.  1. -1. -1.  0.  0.  0.  0.  0.  0.
  0.  0.]

Configuration 8
--------------------------------------------------
task_id: 105
ordering: FM
energy/atom: -6.0035798135
energy above ground: 0.006657429500000589
total magnetization: 38.0385166
symmetry: Im-3
VASP magmoms:
[-0.007 -0.007  4.254  4.254  4.255  4.255  4.254  4.254  4.254  4.254
  0.043  0.041  0.041  0.044  0.044  0.043  0.127  0.127  0.127  0.127
  0.126  0.126  0.126  0.126  0.128  0.128  0.128  0.128  0.129  0.129
  0.129  0.129  0.128  0.128  0.128  0.128  0.128  0.128  0.128  0.128]
Signs:
[-1. -1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
  1.  1.  1.  1.]

Configuration 9
--------------------------------------------------
task_id: 106
ordering: FM
energy/atom: -6.003848803
energy above ground: 0.006388440000000273
total magnetization: 38.03927
symmetry: Im-3
VASP magmoms:
[-0.007 -0.007  4.255  4.255  4.255  4.255  4.256  4.256  4.255  4.255
  0.04   0.044  0.042  0.04   0.044  0.042  0.127  0.127  0.127  0.127
  0.128  0.128  0.128  0.128  0.127  0.127  0.127  0.127  0.125  0.125
  0.125  0.125  0.129  0.129  0.129  0.129  0.128  0.128  0.128  0.128]
Signs:
[-1. -1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
  1.  1.  1.  1.]

Configuration 10
--------------------------------------------------
task_id: 108
ordering: FiM
energy/atom: -6.010237243000001
energy above ground: 0.0
total magnetization: 8.9969589
symmetry: R-3
VASP magmoms:
[ 3.000e-03 -4.196e+00 -4.196e+00 -4.197e+00  4.237e+00 -1.400e-02
 -1.200e-02 -1.300e-02 -7.800e-02 -7.800e-02 -3.000e-03 -3.000e-03
 -8.000e-02 -8.000e-02 -3.000e-03 -3.000e-03 -7.800e-02 -7.800e-02
 -2.000e-03 -2.000e-03]
Signs:
[ 1. -1. -1. -1.  1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1.
 -1. -1.]

Configuration 11
--------------------------------------------------
task_id: 110
ordering: FM
energy/atom: -6.0053998669999995
energy above ground: 0.0048373760000011146
total magnetization: 18.9960963
symmetry: Im-3
VASP magmoms:
[-0.007  4.254  4.254  4.254  4.254  0.044  0.044  0.044  0.127  0.127
  0.127  0.127  0.127  0.127  0.127  0.127  0.127  0.127  0.127  0.127]
Signs:
[-1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
  1.  1.]

Configuration 12
--------------------------------------------------
task_id: 111
ordering: FM
energy/atom: -6.0038026355
energy above ground: 0.006434607500001022
total magnetization: 38.0286898
symmetry: Im-3
VASP magmoms:
[-0.007 -0.007  4.255  4.255  4.255  4.255  4.255  4.255  4.255  4.255
  0.045  0.042  0.041  0.044  0.042  0.041  0.127  0.127  0.127  0.127
  0.126  0.126  0.126  0.126  0.128  0.128  0.128  0.128  0.129  0.129
  0.129  0.129  0.127  0.127  0.127  0.127  0.128  0.128  0.128  0.128]
Signs:
[-1. -1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
  1.  1.  1.  1.]

Configuration 13
--------------------------------------------------
task_id: 114
ordering: FM
energy/atom: -6.0038026355
energy above ground: 0.006434607500001022
total magnetization: 38.0286898
symmetry: Im-3
VASP magmoms:
[-0.007 -0.007  4.255  4.255  4.255  4.255  4.255  4.255  4.255  4.255
  0.045  0.042  0.041  0.044  0.042  0.041  0.127  0.127  0.127  0.127
  0.126  0.126  0.126  0.126  0.128  0.128  0.128  0.128  0.129  0.129
  0.129  0.129  0.127  0.127  0.127  0.127  0.128  0.128  0.128  0.128]
Signs:
[-1. -1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
  1.  1.  1.  1.]

Configuration 14
--------------------------------------------------
task_id: 115
ordering: FM
energy/atom: -6.005173556
energy above ground: 0.005063687000000705
total magnetization: 18.9963368
symmetry: Im-3
VASP magmoms:
[-0.007  4.254  4.254  4.254  4.254  0.044  0.044  0.044  0.128  0.128
  0.128  0.128  0.128  0.128  0.128  0.128  0.128  0.128  0.128  0.128]
Signs:
[-1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
  1.  1.]

Configuration 15
--------------------------------------------------
task_id: 124
ordering: FiM
energy/atom: -6.0101728285
energy above ground: 6.441450000060911e-05
total magnetization: 18.0087789
symmetry: C2/m
VASP magmoms:
[-0.000e+00  5.000e-03 -4.216e+00 -4.216e+00 -4.161e+00 -4.161e+00
 -4.216e+00 -4.216e+00  4.265e+00  4.265e+00 -1.700e-02 -2.000e-03
 -2.000e-03 -6.000e-03 -6.000e-03  2.000e-03 -8.200e-02 -1.100e-02
 -1.100e-02 -8.200e-02 -8.200e-02 -1.100e-02 -1.100e-02 -8.200e-02
 -2.500e-02 -6.500e-02 -6.500e-02 -2.500e-02 -6.500e-02 -2.500e-02
 -2.500e-02 -6.500e-02  1.190e-01 -6.900e-02 -6.900e-02  1.190e-01
 -1.060e-01 -1.050e-01 -1.050e-01 -1.060e-01]
Signs:
[ 0.  1. -1. -1. -1. -1. -1. -1.  1.  1. -1. -1. -1. -1. -1.  1. -1. -1.
 -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1.  1. -1. -1.  1.
 -1. -1. -1. -1.]

Configuration 16
--------------------------------------------------
task_id: 125
ordering: FiM
energy/atom: -6.0102299845
energy above ground: 7.25850000105055e-06
total magnetization: 18.0133464
symmetry: C2/m
VASP magmoms:
[-5.000e-03  0.000e+00 -4.265e+00 -4.265e+00  4.216e+00  4.216e+00
  4.163e+00  4.163e+00  4.216e+00  4.216e+00  2.000e-03  2.000e-03
  6.000e-03  6.000e-03  1.700e-02 -2.000e-03  1.000e-02  8.300e-02
  8.300e-02  1.000e-02  1.000e-02  8.300e-02  8.300e-02  1.000e-02
  6.500e-02  2.500e-02  2.500e-02  6.500e-02  2.500e-02  6.500e-02
  6.500e-02  2.500e-02  6.900e-02 -1.190e-01 -1.190e-01  6.900e-02
  1.050e-01  1.050e-01  1.050e-01  1.050e-01]
Signs:
[-1.  0. -1. -1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1. -1.  1.  1.
  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1. -1. -1.  1.
  1.  1.  1.  1.]

In [ ]:
# ============================================================
# UNIQUE MAGNETIC CONFIGURATION PATTERNS
# ============================================================

configurations = []

for r in records:

    mags = np.array(r["magmoms"]["vasp"], dtype=float)

    # For the first version we use signs for collinear magnetism
    signs = np.sign(mags).astype(int)

    configurations.append({
        "task_id": r["task_id"],
        "ordering": r["ordering"],
        "energy_per_atom": r["energy_per_atom"],
        "energy_above_ground": r["energy_above_ground_state_per_atom"],
        "magmoms": mags,
        "spin_pattern": signs
    })


# Compare patterns
seen = {}

for c in configurations:
    key = tuple(c["spin_pattern"])

    if key not in seen:
        seen[key] = []

    seen[key].append(c)


print("=" * 80)
print("UNIQUE SPIN PATTERNS")
print("=" * 80)

print("Total records:", len(configurations))
print("Unique sign patterns:", len(seen))

for i, (pattern, items) in enumerate(seen.items(), start=1):

    print("\nPattern", i)
    print("Spin:", pattern)
    print("Number of occurrences:", len(items))

    for item in items:
        print(
            "   ",
            item["ordering"],
            "E=",
            item["energy_per_atom"],
            "ΔE=",
            item["energy_above_ground"]
        )

================================================================================
UNIQUE SPIN PATTERNS
================================================================================
Total records: 16
Unique sign patterns: 8

Pattern 1
Spin: (np.int64(0), np.int64(-1), np.int64(-1), np.int64(1), np.int64(1), np.int64(0), np.int64(0), np.int64(0), np.int64(1), np.int64(1), np.int64(-1), np.int64(-1), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0))
Number of occurrences: 2
    FiM E= -6.0089305675 ΔE= 0.0013066755000004093
    FiM E= -6.008932851 ΔE= 0.0013043920000006537

Pattern 2
Spin: (np.int64(0), np.int64(-1), np.int64(-1), np.int64(1), np.int64(1), np.int64(0), np.int64(0), np.int64(0), np.int64(-1), np.int64(-1), np.int64(1), np.int64(1), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0))
Number of occurrences: 1
    AFM E= -6.008906605 ΔE= 0.0013306380000006612

Pattern 3
Spin: (np.int64(-1), np.int64(-1), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1))
Number of occurrences: 7
    FM E= -6.004682642000001 ΔE= 0.005554601000000048
    FM E= -6.004556646999999 ΔE= 0.005680596000001259
    FM E= -6.004683291 ΔE= 0.005553952000000528
    FM E= -6.0035798135 ΔE= 0.006657429500000589
    FM E= -6.003848803 ΔE= 0.006388440000000273
    FM E= -6.0038026355 ΔE= 0.006434607500001022
    FM E= -6.0038026355 ΔE= 0.006434607500001022

Pattern 4
Spin: (np.int64(0), np.int64(-1), np.int64(-1), np.int64(1), np.int64(1), np.int64(0), np.int64(0), np.int64(0), np.int64(-1), np.int64(-1), np.int64(1), np.int64(1), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(1), np.int64(1), np.int64(0), np.int64(0))
Number of occurrences: 1
    AFM E= -6.0089636859999995 ΔE= 0.001273557000001091

Pattern 5
Spin: (np.int64(1), np.int64(-1), np.int64(-1), np.int64(-1), np.int64(1), np.int64(-1), np.int64(-1), np.int64(-1), np.int64(-1), np.int64(-1), np.int64(-1), np.int64(-1), np.int64(-1), np.int64(-1), np.int64(-1), np.int64(-1), np.int64(-1), np.int64(-1), np.int64(-1), np.int64(-1))
Number of occurrences: 1
    FiM E= -6.010237243000001 ΔE= 0.0

Pattern 6
Spin: (np.int64(-1), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1))
Number of occurrences: 2
    FM E= -6.0053998669999995 ΔE= 0.0048373760000011146
    FM E= -6.005173556 ΔE= 0.005063687000000705

Pattern 7
Spin: (np.int64(0), np.int64(1), np.int64(-1), np.int64(-1), np.int64(-1), np.int64(-1), np.int64(-1), np.int64(-1), np.int64(1), np.int64(1), np.int64(-1), np.int64(-1), np.int64(-1), np.int64(-1), np.int64(-1), np.int64(1), np.int64(-1), np.int64(-1), np.int64(-1), np.int64(-1), np.int64(-1), np.int64(-1), np.int64(-1), np.int64(-1), np.int64(-1), np.int64(-1), np.int64(-1), np.int64(-1), np.int64(-1), np.int64(-1), np.int64(-1), np.int64(-1), np.int64(1), np.int64(-1), np.int64(-1), np.int64(1), np.int64(-1), np.int64(-1), np.int64(-1), np.int64(-1))
Number of occurrences: 1
    FiM E= -6.0101728285 ΔE= 6.441450000060911e-05

Pattern 8
Spin: (np.int64(-1), np.int64(0), np.int64(-1), np.int64(-1), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(-1), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(-1), np.int64(-1), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1))
Number of occurrences: 1
    FiM E= -6.0102299845 ΔE= 7.25850000105055e-06

### Step - 1.5 - Inspecting initial magnetic configuration

In [ ]:
# ============================================================
# PHASE 1D — INSPECT INITIAL MAGNETIC CONFIGURATION
# ============================================================

# Inspect one representative record
r = data[0]

print("=" * 80)
print("BASIC RECORD")
print("=" * 80)

print("Formula:", r["formula_pretty"])
print("task_id:", r["task_id"])
print("ordering:", r["ordering"])
print("ordering_changed:", r["ordering_changed"])

print("\nInput keys:")
print(r["input"].keys())

print("\nInput structure keys:")
print(r["input"]["structure"].keys())

print("\nFirst input site:")
print(r["input"]["structure"]["sites"][0])

================================================================================
BASIC RECORD
================================================================================
Formula: LaFeO3
task_id: 27
ordering: FM
ordering_changed: False

Input keys:
dict_keys(['structure', 'ordering', 'symmetry', 'index', 'origin', 'input_index'])

Input structure keys:
dict_keys(['@module', '@class', 'charge', 'lattice', 'sites', '@version'])

First input site:
{'species': [{'element': 'La', 'occu': 1}], 'abc': [0.250011, 0.250011, 0.250011], 'xyz': [0.0, -5.000220000273004e-07, 3.3960129179939997], 'label': 'La', 'properties': {'magmom': 0.0}}

### Step - 1.6 - Finding initial magmom

In [ ]:
# ============================================================
# PHASE 1E — FIND WHERE INITIAL MAGMOM IS STORED
# ============================================================

sites = r["input"]["structure"]["sites"]

for i, site in enumerate(sites[:10]):

    print("\nSite", i)
    print("Species:")
    print(site["species"])

    print("Properties:")
    print(site.get("properties", {}))

Site 0
Species:
[{'element': 'La', 'occu': 1}]
Properties:
{'magmom': 0.0}

Site 1
Species:
[{'element': 'La', 'occu': 1}]
Properties:
{'magmom': 0.0}

Site 2
Species:
[{'element': 'Fe', 'occu': 1}]
Properties:
{'magmom': 4.373}

Site 3
Species:
[{'element': 'Fe', 'occu': 1}]
Properties:
{'magmom': 4.373}

Site 4
Species:
[{'element': 'O', 'occu': 1}]
Properties:
{'magmom': 0.177}

Site 5
Species:
[{'element': 'O', 'occu': 1}]
Properties:
{'magmom': 0.176}

Site 6
Species:
[{'element': 'O', 'occu': 1}]
Properties:
{'magmom': 0.172}

Site 7
Species:
[{'element': 'O', 'occu': 1}]
Properties:
{'magmom': 0.176}

Site 8
Species:
[{'element': 'O', 'occu': 1}]
Properties:
{'magmom': 0.172}

Site 9
Species:
[{'element': 'O', 'occu': 1}]
Properties:
{'magmom': 0.177}

### Step - 1.7 - Extracting initial magnetic configuration

In [ ]:
# ============================================================
# PHASE 1F — EXTRACT INITIAL MAGNETIC CONFIGURATIONS
# ============================================================

import numpy as np
import pandas as pd


def extract_initial_magmoms(record):
    """
    Extract the initial magnetic moments from:
        record["input"]["structure"]["sites"][i]["properties"]["magmom"]

    Returns:
        list of floats
    """
    sites = record["input"]["structure"]["sites"]

    magmoms = []

    for site in sites:
        props = site.get("properties", {})
        magmom = props.get("magmom", 0.0)

        if magmom is None:
            magmom = 0.0

        magmoms.append(float(magmom))

    return magmoms


# ------------------------------------------------------------
# Extract every record
# ------------------------------------------------------------

rows = []

for r in data:

    initial_magmoms = extract_initial_magmoms(r)

    rows.append({
        "task_id": r.get("task_id"),
        "formula": r.get("formula_pretty"),
        "parent_structure_id": structure_signature(
            r["parent_structure"]
        ),

        "ordering": r.get("ordering"),
        "ordering_changed": r.get("ordering_changed"),

        "energy_per_atom": r.get("energy_per_atom"),
        "energy_above_ground": (
            r.get("energy_above_ground_state_per_atom")
        ),

        "initial_magmoms": initial_magmoms,

        "n_sites": len(initial_magmoms),

        "total_initial_moment": sum(initial_magmoms),

    })


df_mag = pd.DataFrame(rows)

print("=" * 80)
print("INITIAL MAGNETIC CONFIGURATION EXTRACTION")
print("=" * 80)

print("Total records:", len(df_mag))

print("\nMissing initial magnetic configurations:",
      df_mag["initial_magmoms"].isna().sum())

print("\nNumber of sites:")
print(df_mag["n_sites"].describe())

print("\nOrdering-changed:")
print(df_mag["ordering_changed"].value_counts(dropna=False))

print("\nExample:")
print(df_mag.iloc[0][[
    "formula",
    "ordering",
    "ordering_changed",
    "initial_magmoms",
    "total_initial_moment"
]])

================================================================================
INITIAL MAGNETIC CONFIGURATION EXTRACTION
================================================================================
Total records: 23155

Missing initial magnetic configurations: 0

Number of sites:
count    23155.000000
mean        27.835198
std         13.249307
min          2.000000
25%         18.000000
50%         28.000000
75%         36.000000
max        120.000000
Name: n_sites, dtype: float64

Ordering-changed:
ordering_changed
False    18812
True      4343
Name: count, dtype: int64

Example:
formula                                                            LaFeO3
ordering                                                               FM
ordering_changed                                                    False
initial_magmoms         [0.0, 0.0, 4.373, 4.373, 0.177, 0.176, 0.172, ...
total_initial_moment                                                9.796
Name: 0, dtype: object

### Step - 1.8 - Inspecting the full magnetic-state statistics

In [ ]:
# ============================================================
# PHASE 1G — MAGNETIC CONFIGURATION STATISTICS
# ============================================================

print("=" * 80)
print("MAGNETIC CONFIGURATION STATISTICS")
print("=" * 80)

# Number of magnetic atoms/sites
df_mag["n_magnetic_sites"] = df_mag["initial_magmoms"].apply(
    lambda x: sum(abs(m) > 1e-6 for m in x)
)

print("\nMagnetic sites per record:")
print(df_mag["n_magnetic_sites"].describe())


# Number of positive and negative moments
df_mag["n_positive"] = df_mag["initial_magmoms"].apply(
    lambda x: sum(m > 1e-6 for m in x)
)

df_mag["n_negative"] = df_mag["initial_magmoms"].apply(
    lambda x: sum(m < -1e-6 for m in x)
)

df_mag["n_zero"] = df_mag["initial_magmoms"].apply(
    lambda x: sum(abs(m) <= 1e-6 for m in x)
)

print("\nPositive-spin sites:")
print(df_mag["n_positive"].describe())

print("\nNegative-spin sites:")
print(df_mag["n_negative"].describe())

print("\nZero/nonmagnetic sites:")
print(df_mag["n_zero"].describe())

================================================================================
MAGNETIC CONFIGURATION STATISTICS
================================================================================

Magnetic sites per record:
count    23155.000000
mean        26.354222
std         14.968420
min          1.000000
25%         16.000000
50%         28.000000
75%         36.000000
max        120.000000
Name: n_magnetic_sites, dtype: float64

Positive-spin sites:
count    23155.000000
mean        24.590542
std         14.548334
min          1.000000
25%         15.000000
50%         25.000000
75%         33.000000
max        118.000000
Name: n_positive, dtype: float64

Negative-spin sites:
count    23155.000000
mean         1.763680
std          1.012849
min          0.000000
25%          1.000000
50%          2.000000
75%          2.000000
max         14.000000
Name: n_negative, dtype: float64

Zero/nonmagnetic sites:
count    23155.000000
mean         1.480976
std          4.470863
min          0.000000
25%          0.000000
50%          0.000000
75%          0.000000
max         30.000000
Name: n_zero, dtype: float64

### Step - 1.9 - Comparing initial vs final magnetic states

In [ ]:
# ============================================================
# PHASE 1H — COMPARE INITIAL VS FINAL MAGNETIC STATES
# ============================================================

def extract_final_magmoms(record):
    """
    Extract final VASP magnetic moments.
    """

    magmoms = record.get("magmoms", {})

    vasp = magmoms.get("vasp")

    if vasp is None:
        return None

    return [float(x) for x in vasp]


comparison = []

for r in data:

    initial = extract_initial_magmoms(r)
    final = extract_final_magmoms(r)

    if final is None:
        continue

    changed = False

    if len(initial) != len(final):
        changed = True

    else:
        changed = not np.allclose(
            initial,
            final,
            atol=0.1
        )

    comparison.append({
        "task_id": r.get("task_id"),
        "formula": r.get("formula_pretty"),
        "ordering": r.get("ordering"),
        "ordering_changed_database": r.get("ordering_changed"),
        "initial_magmoms": initial,
        "final_magmoms": final,
        "initial_final_different": changed
    })


df_compare = pd.DataFrame(comparison)

print("=" * 80)
print("INITIAL VS FINAL MAGNETIC STATES")
print("=" * 80)

print(
    df_compare["initial_final_different"]
    .value_counts(dropna=False)
)

print("\nDatabase ordering_changed:")
print(
    df_compare["ordering_changed_database"]
    .value_counts(dropna=False)
)

================================================================================
INITIAL VS FINAL MAGNETIC STATES
================================================================================
initial_final_different
True     22908
False      247
Name: count, dtype: int64

Database ordering_changed:
ordering_changed_database
False    18812
True      4343
Name: count, dtype: int64

### Step - 1.10 - Assigning spin sign pattern

In [ ]:
def spin_sign_pattern(magmoms, threshold=0.1):

    pattern = []

    for m in magmoms:

        if m > threshold:
            pattern.append(+1)

        elif m < -threshold:
            pattern.append(-1)

        else:
            pattern.append(0)

    return tuple(pattern)

In [ ]:
df_mag["spin_pattern"] = df_mag["initial_magmoms"].apply(
    spin_sign_pattern
)

### Step - 1.11 - Auditing magnetic ordering changes

In [ ]:
# ============================================================
# PHASE 1I — AUDIT ACTUAL MAGNETIC ORDERING CHANGES
# ============================================================

print("=" * 80)
print("MAGNETIC ORDERING CHANGE AUDIT")
print("=" * 80)

print("Total records:", len(df_mag))

print("\nOrdering changed:")
print(df_mag["ordering_changed"].value_counts())

print("\nPercentage changed:")
print(
    df_mag["ordering_changed"].value_counts(normalize=True)
    .mul(100)
    .round(2)
)

# Show examples of records where ordering changed
changed = df_mag[df_mag["ordering_changed"] == True]

print("\nNumber with ordering_changed=True:", len(changed))

print("\nExamples:")
print(
    changed[
        [
            "task_id",
            "formula",
            "ordering",
            "energy_per_atom",
            "energy_above_ground"
        ]
    ]
    .head(30)
    .to_string(index=False)
)

================================================================================
MAGNETIC ORDERING CHANGE AUDIT
================================================================================
Total records: 23155

Ordering changed:
ordering_changed
False    18812
True      4343
Name: count, dtype: int64

Percentage changed:
ordering_changed
False    81.24
True     18.76
Name: proportion, dtype: float64

Number with ordering_changed=True: 4343

Examples:
 task_id      formula ordering  energy_per_atom  energy_above_ground
       4 LaFe4(CuO4)3      AFM        -6.342479             0.000016
       7 LaFe4(CuO4)3      AFM        -6.342490             0.000005
       8 LaFe4(CuO4)3      AFM        -6.342495             0.000000
       9 LaFe4(CuO4)3       FM        -6.319486             0.023009
      10 LaFe4(CuO4)3       FM        -6.319695             0.022800
      15 LaFe4(CuO4)3       FM        -6.319692             0.022803
      16 LaFe4(CuO4)3       FM        -6.319596             0.022899
      17 LaFe4(CuO4)3       FM        -6.319541             0.022954
      18 LaFe4(CuO4)3      FiM        -6.336319             0.006176
      25 LaFe4(CuO4)3       FM        -6.319597             0.022898
      26 LaFe4(CuO4)3       FM        -6.319597             0.022898
      32 LaFe4(CuO4)3      FiM        -6.331787             0.010707
      33 LaFe4(CuO4)3      FiM        -6.331835             0.010660
      34 LaFe4(CuO4)3       FM        -6.319422             0.023073
      37 LaFe4(CuO4)3       FM        -6.319388             0.023107
      88 SrFe4(CuO4)3      FiM        -6.008931             0.001307
      90 SrFe4(CuO4)3      AFM        -6.008907             0.001331
      95 SrFe4(CuO4)3       FM        -6.004683             0.005555
      98 SrFe4(CuO4)3      AFM        -6.008964             0.001274
      99 SrFe4(CuO4)3       FM        -6.004557             0.005681
     100 SrFe4(CuO4)3       FM        -6.004683             0.005554
     105 SrFe4(CuO4)3       FM        -6.003580             0.006657
     106 SrFe4(CuO4)3       FM        -6.003849             0.006388
     108 SrFe4(CuO4)3      FiM        -6.010237             0.000000
     110 SrFe4(CuO4)3       FM        -6.005400             0.004837
     111 SrFe4(CuO4)3       FM        -6.003803             0.006435
     114 SrFe4(CuO4)3       FM        -6.003803             0.006435
     115 SrFe4(CuO4)3       FM        -6.005174             0.005064
     124 SrFe4(CuO4)3      FiM        -6.010173             0.000064
     125 SrFe4(CuO4)3      FiM        -6.010230             0.000007

### Step - 1.12 - Ordering type

In [ ]:
# ============================================================
# PHASE 1J — ORDERING CHANGE BY ORDERING TYPE
# ============================================================

ordering_change_table = pd.crosstab(
    df_mag["ordering"],
    df_mag["ordering_changed"],
    margins=True
)

print(ordering_change_table)

ordering_changed  False  True    All
ordering
AFM                7898   821   8719
FM                 2049  1836   3885
FiM                8865  1602  10467
NM                    0    84     84
All               18812  4343  23155

Percentage of ordering changed

In [ ]:
# Percentage of each ordering that changed
ordering_change_percent = (
    pd.crosstab(
        df_mag["ordering"],
        df_mag["ordering_changed"],
        normalize="index"
    )
    .mul(100)
    .round(2)
)

print("\nPercentage within each ordering:")
print(ordering_change_percent)

Percentage within each ordering:
ordering_changed  False   True
ordering
AFM               90.58    9.42
FM                52.74   47.26
FiM               84.69   15.31
NM                 0.00  100.00

### Step - 1.13 - Configuration availability at parent level

In [ ]:
# ============================================================
# PHASE 1K — PARENT-LEVEL CONFIGURATION AVAILABILITY
# ============================================================

parent_stats = (
    df_mag
    .groupby("parent_structure_id")
    .agg(
        n_records=("task_id", "count"),
        n_unchanged=("ordering_changed", lambda x: (~x).sum()),
        n_changed=("ordering_changed", "sum"),
        min_energy=("energy_per_atom", "min"),
        max_energy=("energy_per_atom", "max")
    )
)

parent_stats["has_multiple_states"] = parent_stats["n_records"] > 1
parent_stats["has_multiple_unchanged_states"] = (
    parent_stats["n_unchanged"] > 1
)

print("=" * 80)
print("PARENT-LEVEL DATASET QUALITY")
print("=" * 80)

print("Total parent structures:", len(parent_stats))

print(
    "\nParents with >1 calculated state:",
    parent_stats["has_multiple_states"].sum()
)

print(
    "Parents with >1 unchanged magnetic state:",
    parent_stats["has_multiple_unchanged_states"].sum()
)

print("\nNumber of usable states per parent:")
print(parent_stats["n_unchanged"].describe())

================================================================================
PARENT-LEVEL DATASET QUALITY
================================================================================
Total parent structures: 2588

Parents with >1 calculated state: 2532
Parents with >1 unchanged magnetic state: 2199

Number of usable states per parent:
count    2588.000000
mean        7.268934
std         4.716666
min         0.000000
25%         4.000000
50%         7.000000
75%        11.000000
max        16.000000
Name: n_unchanged, dtype: float64

### Step - 1.14 - Determining the final magnetic configurations

Extracting the final signed moments and creating a final spin pattern.

In [ ]:
# ============================================================
# PHASE 1L — FINAL MAGNETIC CONFIGURATION
# ============================================================

def extract_final_magmoms(record):
    """
    Extract final VASP magnetic moments.
    """
    vasp = record.get("magmoms", {}).get("vasp")

    if vasp is None:
        return None

    return [float(x) for x in vasp]


def spin_sign_pattern(magmoms, threshold=0.1):
    """
    Convert magnetic moments into a simple collinear
    spin-sign representation.

    +1 = positive moment
    -1 = negative moment
     0 = approximately nonmagnetic
    """

    pattern = []

    for m in magmoms:

        if m > threshold:
            pattern.append(1)

        elif m < -threshold:
            pattern.append(-1)

        else:
            pattern.append(0)

    return tuple(pattern)


final_rows = []

for r in data:

    final_mags = extract_final_magmoms(r)

    if final_mags is None:
        continue

    final_rows.append({
        "task_id": r.get("task_id"),
        "formula": r.get("formula_pretty"),

        "parent_structure_id": structure_signature(
            r["parent_structure"]
        ),

        "ordering": r.get("ordering"),
        "ordering_changed": r.get("ordering_changed"),

        "energy_per_atom": r.get("energy_per_atom"),
        "energy_above_ground": (
            r.get("energy_above_ground_state_per_atom")
        ),

        "final_magmoms": final_mags,

        "final_spin_pattern": spin_sign_pattern(final_mags),

        "total_final_moment": sum(final_mags)
    })


df_final = pd.DataFrame(final_rows)

print("=" * 80)
print("FINAL MAGNETIC CONFIGURATION")
print("=" * 80)

print("Records:", len(df_final))

print("\nExample:")
print(
    df_final.iloc[0][[
        "formula",
        "ordering",
        "ordering_changed",
        "final_magmoms",
        "final_spin_pattern",
        "total_final_moment"
    ]]
)

================================================================================
FINAL MAGNETIC CONFIGURATION
================================================================================
Records: 23155

Example:
formula                                                          LaFeO3
ordering                                                             FM
ordering_changed                                                  False
final_magmoms         [0.012, 0.012, 4.372, 4.372, 0.175, 0.175, 0.1...
final_spin_pattern                       (0, 0, 1, 1, 1, 1, 1, 1, 1, 1)
total_final_moment                                                9.818
Name: 0, dtype: object

### Step - 1.15 - Distincting final spin patterns

In [ ]:
# ============================================================
# PHASE 1M — DISTINCT FINAL SPIN PATTERNS
# ============================================================

pattern_counts = (
    df_final
    .groupby("parent_structure_id")["final_spin_pattern"]
    .nunique()
)

print("=" * 80)
print("FINAL SPIN PATTERN DIVERSITY")
print("=" * 80)

print("Parent structures:", len(pattern_counts))

print("\nDistinct final patterns per parent:")
print(pattern_counts.describe())

print(
    "\nParents with >1 final spin pattern:",
    (pattern_counts > 1).sum()
)

print(
    "Parents with exactly 1 final spin pattern:",
    (pattern_counts == 1).sum()
)

================================================================================
FINAL SPIN PATTERN DIVERSITY
================================================================================
Parent structures: 2588

Distinct final patterns per parent:
count    2588.000000
mean        3.977589
std         2.421293
min         1.000000
25%         3.000000
50%         3.000000
75%         5.000000
max        16.000000
Name: final_spin_pattern, dtype: float64

Parents with >1 final spin pattern: 2500
Parents with exactly 1 final spin pattern: 88

Showing one parent with multiple final spin patterns

In [ ]:
candidate_parent = (
    pattern_counts[pattern_counts > 1]
    .sort_values(ascending=False)
    .index[0]
)

example = (
    df_final[
        df_final["parent_structure_id"] == candidate_parent
    ]
    .sort_values("energy_per_atom")
)

print(example[
    [
        "formula",
        "task_id",
        "ordering",
        "ordering_changed",
        "energy_per_atom",
        "energy_above_ground",
        "final_spin_pattern"
    ]
].to_string(index=False))

       formula  task_id ordering  ordering_changed  energy_per_atom  energy_above_ground                                                                                                     final_spin_pattern
Cu3NiH6(ClO3)2    15236      FiM              True        -4.693472             0.000000      (-1, 1, -1, -1, 1, 1, 1, -1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, -1, 0)
Cu3NiH6(ClO3)2    14917      FiM              True        -4.693269             0.000202        (-1, -1, 1, 1, 1, 1, 1, -1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0)
Cu3NiH6(ClO3)2    15022      FiM              True        -4.693141             0.000330        (1, 1, 1, 1, -1, -1, 1, -1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1)
Cu3NiH6(ClO3)2    15026      FiM              True        -4.693133             0.000338       (1, -1, 1, -1, 1, 1, -1, -1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0)
Cu3NiH6(ClO3)2    15630       FM              True        -4.692610             0.000862 (-1, 1, 1, -1, -1, -1, -1, -1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, -1, -1, 0, 0, 0, -1, 0)
Cu3NiH6(ClO3)2    24877      FiM              True        -4.691399             0.002073      (1, 1, 1, -1, -1, 1, -1, -1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, -1, 1)
Cu3NiH6(ClO3)2    15288       FM              True        -4.689165             0.004307    (1, -1, -1, 0, 1, -1, -1, -1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 0, 0, 0, 0, 0, -1, 0, 0, 0)
Cu3NiH6(ClO3)2    15517      FiM              True        -4.688644             0.004828        (1, 1, 1, 1, -1, 1, -1, -1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0)
Cu3NiH6(ClO3)2    15618      FiM              True        -4.687924             0.005547         (1, 1, 1, -1, 1, 1, 1, -1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0)
Cu3NiH6(ClO3)2    15669       FM              True        -4.687902             0.005570       (0, -1, 1, 1, 1, -1, -1, -1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0)
Cu3NiH6(ClO3)2    15354      FiM              True        -4.687439             0.006032        (-1, -1, 1, 0, 1, 0, 1, -1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0)
Cu3NiH6(ClO3)2    15214      FiM              True        -4.684331             0.009141         (0, 0, 1, 1, 1, -1, 1, -1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0)
Cu3NiH6(ClO3)2    14937       FM              True        -4.683697             0.009775                                                                (1, 1, 0, -1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0)
Cu3NiH6(ClO3)2    15321       FM              True        -4.682892             0.010579                                                                 (1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0)
Cu3NiH6(ClO3)2    14731       FM              True        -4.682401             0.011071                                                             (-1, -1, -1, -1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0)
Cu3NiH6(ClO3)2    14683       NM              True        -4.657061             0.036411                                                                (-1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0)

### Step - 1.16 - Checking whether repeated final states have consistent energies

In [ ]:
# ============================================================
# PHASE 1N — IDENTICAL FINAL SPIN PATTERN / ENERGY CHECK
# ============================================================

# Number of records represented by each exact final pattern
pattern_frequency = (
    df_final
    .groupby(
        ["parent_structure_id", "final_spin_pattern"],
        dropna=False
    )
    .agg(
        n_records=("task_id", "count"),
        n_orderings=("ordering", "nunique"),
        min_energy=("energy_per_atom", "min"),
        max_energy=("energy_per_atom", "max"),
        energy_std=("energy_per_atom", "std")
    )
    .reset_index()
)

pattern_frequency["energy_range"] = (
    pattern_frequency["max_energy"]
    - pattern_frequency["min_energy"]
)

print("=" * 80)
print("IDENTICAL FINAL PATTERN ANALYSIS")
print("=" * 80)

print("Unique (parent, final-spin-pattern) states:",
      len(pattern_frequency))

print("\nRecords per final state:")
print(pattern_frequency["n_records"].describe())

print("\nEnergy range within identical final patterns:")
print(pattern_frequency["energy_range"].describe())

================================================================================
IDENTICAL FINAL PATTERN ANALYSIS
================================================================================
Unique (parent, final-spin-pattern) states: 10294

Records per final state:
count    10294.000000
mean         2.249369
std          2.253421
min          1.000000
25%          1.000000
50%          1.000000
75%          2.000000
max         15.000000
Name: n_records, dtype: float64

Energy range within identical final patterns:
count    10294.000000
mean         0.002312
std          0.012632
min          0.000000
25%          0.000000
50%          0.000000
75%          0.000309
max          0.449135
Name: energy_range, dtype: float64

In [ ]:
# Showing states where the SAME final spin pattern
# appears with noticeably different energies

duplicates = pattern_frequency[
    pattern_frequency["n_records"] > 1
].sort_values(
    "energy_range",
    ascending=False
)

print("\nRepeated final states:", len(duplicates))

print(
    duplicates.head(30).to_string(index=False)
)

Repeated final states: 4045
                                             parent_structure_id                                                                                            final_spin_pattern  n_records  n_orderings  min_energy  max_energy  energy_std  energy_range
3e6c11ec22e37fb2d0d21312e785a64d92c1194ff3b93f70a9c593e163c50113                                                                                    (-1, -1, 1, 1, 0, 0, 0, 0)          4            2   -6.703051   -6.253916    0.222828      0.449135
2380272a95bf5671cf8f870a6258d8b06ff8091db2cfd0880c0fc2489b72f611                                      (1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0)          3            1   -6.277082   -5.981322    0.170758      0.295761
421c289513c003a489838ecb982544ec7e354facc1d50b3f72922d4a23833639 (0, 0, 0, 0, -1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0)          2            1   -6.778775   -6.493963    0.201392      0.284812
ab854b22b646735292844684875da7c512af3344db7828b8c0f0ca0ed0fdbd58                  (-1, -1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0)          2            2   -7.224353   -6.956288    0.189551      0.268065
dca98bbb8510b15fa8510580464ce0fc1a8d032d4b8ca30b4ea3c4846fe6667b                          (1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0)          2            1   -6.534251   -6.274419    0.183729      0.259832
5efca3e8a94abaa5983968db587d5bedab91207bdafab2e5ef89d334db7200f6                                                            (1, 1, -1, -1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0)          2            1   -6.993609   -6.762375    0.163507      0.231234
38bc2c2bfe87ec40c58c8580b095a24fa357b3900657c49d9ff7e397bcc52e98       (0, 0, 0, 0, 0, 0, -1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0)          3            1   -6.801523   -6.576613    0.114557      0.224910
2380272a95bf5671cf8f870a6258d8b06ff8091db2cfd0880c0fc2489b72f611                                                                         (1, 1, 0, 0, 0, -1, 0, 0, 0, 0, 0, 0)          2            2   -6.276662   -6.055206    0.156593      0.221456
bfe7a5a05a3f9306e11d192056279680b556ccde3154b007b764d3915dddede5                                                  (0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0)          2            1   -8.264112   -8.065866    0.140181      0.198246
d6045252775ce8695d4f0a60e74a19375969575bc21ab80139cff1fda1dd1e0b                                        (-1, -1, -1, -1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0)          7            1   -5.779400   -5.583251    0.067438      0.196149
c5ea0a244c1e2f8d1eb7570773ca2055055170bd1f9b4438a107f22b6e1c8de6            (0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, -1, -1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0)          4            1   -6.357396   -6.166001    0.110498      0.191395
49314fea5a7e046b3a99470e56f53f7414890510cd488ef5b817cb15c25221a7                                                            (0, 0, 0, 0, -1, -1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0)          4            2   -6.072932   -5.891199    0.077711      0.181734
a362ab88bffb42f043805b48bec10a6bca6736b7d6b9174c550c197db15d9206       (-1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0)          3            1   -6.148875   -5.971417    0.089320      0.177457
5576020dec810d227fa5efce2d677ee5fa86ec17be00cbe9556726b1c7347f7f                                                  (0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0)          2            1   -7.752545   -7.575658    0.125078      0.176887
39cf0a66f9f46cce57fe28822d313f74197424c7da2dc56fa596a5ee56853ba1                                                           (-1, -1, 1, 1, -1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0)          4            1   -6.288123   -6.136714    0.075598      0.151409
01b92fef5d2923f648762d7315de7e522ce1e42c52c0613889584099519522a2                          (0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0)          4            1   -6.665986   -6.526820    0.063759      0.139166
e2ee22883017828535691529a96615f211388056b83ea2ab35e68b781c851996                              (-1, -1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0)          3            1   -6.863569   -6.738127    0.071944      0.125442
e214029b1acd416b09274867403cbb43b1b765cbe28affda2d178b1dbd6f46b1                                                                 (0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0)          2            1   -7.913956   -7.789597    0.087935      0.124359
367adb7591eed27e1ca47d10c043d9a9e2779f3f3491e7665c282d298081ec12                                                                  (0, 0, -1, -1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0)          2            1   -7.392953   -7.270395    0.086661      0.122558
459417af8d63f5eeb7e4c22918c2c13906b0512994fe310e7b95e86e6ae34090                                                (-1, -1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0)          3            2   -7.454040   -7.339517    0.061317      0.114522
d3204c0b790d982777cc9e87faf972be87e7411ce40c293701762e8332e52da0                                                                    (1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0)          2            1   -6.916810   -6.806357    0.078102      0.110454
d0a950c940bfdb7b1811547d98b10c11f7124e1452748b94cb976b9f3d76bd34                                                                        (-1, -1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0)          2            2   -7.499569   -7.389892    0.077554      0.109677
e2ee22883017828535691529a96615f211388056b83ea2ab35e68b781c851996                             (-1, -1, -1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0)          5            2   -6.863897   -6.756635    0.047668      0.107263
163f34ebf718312ed36331de3effd418ae820a2d6d6f8ac3e514ac08a776ad3e                                                            (0, 0, 0, 0, -1, -1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0)          9            2   -6.652731   -6.546373    0.046262      0.106358
34aa688abb94c754d9742c265975d58d77a1ad4882c720c953311b8a3f5eb146                              (0, 0, -1, -1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0)          5            1   -7.532325   -7.428510    0.045650      0.103816
498eb82b7830a41a1109aa5e7388196cdceda8c042dcfa55c993a861835b09b4                                                            (0, 0, 0, 0, -1, -1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0)          5            2   -6.787881   -6.684198    0.041493      0.103683
6aee013e4ba1eaac7bac327df1eb133a3dd9b4edd2c78137c0ceaf5c4e21ae01                     (0, 0, -1, -1, -1, -1, -1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0)          4            1   -7.513166   -7.411230    0.050687      0.101936
3961a938657c3fe7699401926b0d4dfa017a4702319219363e6ac3bde169b540             (0, 0, 0, 0, -1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0)          7            1   -5.849359   -5.748880    0.038382      0.100479
eb78abfc6f5d595be1e1f80c3a6942fdce4aba410b24b2cad574a79dd5d8ff04                                (0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0)          2            1   -5.431339   -5.332094    0.070177      0.099245
24799023134039b5c0584c3efcef99779c7e9231d4e6dce2c79afc12ab81e1e4                                                             (0, 0, 0, 0, 1, 1, -1, 1, 0, 0, 0, 0, 0, 0, 0, 0)          2            1   -6.162906   -6.064442    0.069624      0.098464

### Step - 1.17 - Comparing final states with the database ground state

In [ ]:
# ============================================================
# PHASE 1O — INDEPENDENT PARENT-LEVEL DELTA E
# ============================================================

df_final["delta_E_parent"] = (
    df_final["energy_per_atom"]
    -
    df_final.groupby("parent_structure_id")["energy_per_atom"]
    .transform("min")
)

# Compare database value with our independently calculated value
df_final["delta_E_difference"] = (
    df_final["energy_above_ground"]
    -
    df_final["delta_E_parent"]
)

print("=" * 80)
print("ENERGY ABOVE GROUND-STATE CHECK")
print("=" * 80)

print(
    df_final["delta_E_difference"].describe()
)

print("\nMaximum absolute difference:")

print(
    df_final["delta_E_difference"]
    .abs()
    .max()
)

print("\nExamples:")
print(
    df_final[
        [
            "formula",
            "energy_per_atom",
            "energy_above_ground",
            "delta_E_parent",
            "delta_E_difference"
        ]
    ].head(20).to_string(index=False)
)

================================================================================
ENERGY ABOVE GROUND-STATE CHECK
================================================================================
count    23155.0
mean         0.0
std          0.0
min          0.0
25%          0.0
50%          0.0
75%          0.0
max          0.0
Name: delta_E_difference, dtype: float64

Maximum absolute difference:
0.0

Examples:
     formula  energy_per_atom  energy_above_ground  delta_E_parent  delta_E_difference
      LaFeO3        -7.599371             0.040136        0.040136                 0.0
      LaFeO3        -7.627412             0.012095        0.012095                 0.0
      LaFeO3        -7.599424             0.040083        0.040083                 0.0
      LaFeO3        -7.614271             0.025236        0.025236                 0.0
      LaFeO3        -7.621639             0.017868        0.017868                 0.0
      LaFeO3        -7.639507             0.000000        0.000000                 0.0
LaFe4(CuO4)3        -6.342479             0.000016        0.000016                 0.0
LaFe4(CuO4)3        -6.342490             0.000005        0.000005                 0.0
LaFe4(CuO4)3        -6.342495             0.000000        0.000000                 0.0
LaFe4(CuO4)3        -6.319486             0.023009        0.023009                 0.0
LaFe4(CuO4)3        -6.319695             0.022800        0.022800                 0.0
LaFe4(CuO4)3        -6.319692             0.022803        0.022803                 0.0
LaFe4(CuO4)3        -6.319596             0.022899        0.022899                 0.0
LaFe4(CuO4)3        -6.319541             0.022954        0.022954                 0.0
LaFe4(CuO4)3        -6.336319             0.006176        0.006176                 0.0
LaFe4(CuO4)3        -6.319597             0.022898        0.022898                 0.0
LaFe4(CuO4)3        -6.319597             0.022898        0.022898                 0.0
LaFe4(CuO4)3        -6.342436             0.000058        0.000058                 0.0
LaFe4(CuO4)3        -6.331787             0.010707        0.010707                 0.0
LaFe4(CuO4)3        -6.331835             0.010660        0.010660                 0.0

### Step - 1.18 - Investigating identical pattern & different energies

In [ ]:
# ============================================================
# PHASE 1P — INVESTIGATE IDENTICAL PATTERN / DIFFERENT ENERGY
# ============================================================

# Pick the repeated state with the largest energy range
worst = pattern_frequency.sort_values(
    "energy_range",
    ascending=False
).iloc[0]

parent_id = worst["parent_structure_id"]
pattern = worst["final_spin_pattern"]

print("=" * 80)
print("WORST IDENTICAL-PATTERN ENERGY DISCREPANCY")
print("=" * 80)

print("Parent ID:", parent_id)
print("Final spin pattern:", pattern)
print("Energy range:", worst["energy_range"])

# Get the corresponding original records
matching_records = []

for r in data:

    pid = structure_signature(r["parent_structure"])

    final_mags = extract_final_magmoms(r)

    if final_mags is None:
        continue

    final_pattern = spin_sign_pattern(final_mags)

    if pid == parent_id and final_pattern == pattern:
        matching_records.append(r)

print("\nNumber of matching records:", len(matching_records))


# Print detailed information
for r in matching_records:

    initial = extract_initial_magmoms(r)
    final = extract_final_magmoms(r)

    print("\n" + "-" * 80)

    print("task_id:", r.get("task_id"))
    print("formula:", r.get("formula_pretty"))
    print("ordering:", r.get("ordering"))
    print("ordering_changed:", r.get("ordering_changed"))

    print("energy/atom:",
          r.get("energy_per_atom"))

    print("energy above ground:",
          r.get("energy_above_ground_state_per_atom"))

    print("\nInitial moments:")
    print(initial)

    print("\nFinal moments:")
    print(final)

    print("\nFinal spin pattern:")
    print(spin_sign_pattern(final))

================================================================================
WORST IDENTICAL-PATTERN ENERGY DISCREPANCY
================================================================================
Parent ID: 3e6c11ec22e37fb2d0d21312e785a64d92c1194ff3b93f70a9c593e163c50113
Final spin pattern: (-1, -1, 1, 1, 0, 0, 0, 0)
Energy range: 0.4491346487500003

Number of matching records: 4

--------------------------------------------------------------------------------
task_id: 6849
formula: FeO
ordering: AFM
ordering_changed: False
energy/atom: -6.70036640875
energy above ground: 0.009364031250000515

Initial moments:
[-5.0, -5.0, 5.0, 5.0, 0.6, 0.6, 0.6, 0.6]

Final moments:
[-3.745, -3.745, 3.745, 3.745, 0.0, -0.021, 0.0, 0.021]

Final spin pattern:
(-1, -1, 1, 1, 0, 0, 0, 0)

--------------------------------------------------------------------------------
task_id: 6874
formula: FeO
ordering: AFM
ordering_changed: False
energy/atom: -6.69515576
energy above ground: 0.01457468000000084

Initial moments:
[-5.0, -5.0, 5.0, 5.0, 0.6, 0.6, 0.6, 0.6]

Final moments:
[-3.747, -3.747, 3.747, 3.747, -0.0, -0.057, -0.0, 0.057]

Final spin pattern:
(-1, -1, 1, 1, 0, 0, 0, 0)

--------------------------------------------------------------------------------
task_id: 7039
formula: FeO
ordering: FiM
ordering_changed: False
energy/atom: -6.2539162625
energy above ground: 0.45581417750000064

Initial moments:
[-5.0, -5.0, 5.0, 5.0, 0.6, 0.6, 0.6, 0.6]

Final moments:
[-3.81, -3.809, 3.8, 3.804, 0.0, 0.0, 0.0, 0.0]

Final spin pattern:
(-1, -1, 1, 1, 0, 0, 0, 0)

--------------------------------------------------------------------------------
task_id: 23170
formula: FeO
ordering: AFM
ordering_changed: False
energy/atom: -6.70305091125
energy above ground: 0.00667952875000033

Initial moments:
[-5.0, -5.0, 5.0, 5.0, 0.6, 0.6, 0.6, 0.6]

Final moments:
[-3.742, -3.742, 3.742, 3.742, 0.055, -0.055, -0.055, 0.055]

Final spin pattern:
(-1, -1, 1, 1, 0, 0, 0, 0)

### Step - 1.19 - Comparing final structures

In [ ]:
# ============================================================
# PHASE 1Q — COMPARE FINAL STRUCTURES
# ============================================================

def structure_summary(structure):
    """
    Extract basic structural information.
    """

    lattice = structure["lattice"]["matrix"]

    sites = []

    for site in structure["sites"]:

        element = site["species"][0]["element"]

        abc = site["abc"]

        sites.append(
            (
                element,
                round(float(abc[0]), 6),
                round(float(abc[1]), 6),
                round(float(abc[2]), 6)
            )
        )

    return {
        "lattice": np.array(lattice, dtype=float),
        "sites": sites
    }


for r in matching_records:

    final_structure = r.get("structure")

    if final_structure is None:
        print("\nNo final structure:", r["task_id"])
        continue

    s = structure_summary(final_structure)

    print("\n" + "-" * 80)
    print("task_id:", r["task_id"])
    print("energy:", r["energy_per_atom"])

    print("Lattice:")
    print(np.array(s["lattice"]))

    print("First 10 sites:")
    print(s["sites"][:10])

--------------------------------------------------------------------------------
task_id: 6849
energy: -6.70036640875
Lattice:
[[-2.267506e+00 -3.012000e-03 -2.265198e+00]
 [ 2.267347e+00  2.081452e+00 -4.527710e+00]
 [ 2.271063e+00 -4.189922e+00 -2.274208e+00]]
First 10 sites:
[('Fe', 0.500234, 0.999432, 0.500167), ('Fe', 0.749766, 0.500568, 0.249833), ('Fe', 0.249718, 0.500635, 0.749865), ('Fe', 0.000282, 0.999365, 0.000135), ('O', 0.87507, 0.249903, 0.625123), ('O', 0.125, 0.75, 0.375), ('O', 0.37493, 0.250097, 0.124877), ('O', 0.625, 0.75, 0.875)]

--------------------------------------------------------------------------------
task_id: 6874
energy: -6.69515576
Lattice:
[[-2.251074 -2.093744 -0.019752]
 [-2.27911   4.196012 -2.211918]
 [ 2.26791  -2.156067 -4.518775]]
First 10 sites:
[('Fe', 0.500867, 0.000513, 0.498423), ('Fe', 0.24913, 0.499485, 0.751579), ('Fe', 0.000349, 0.999754, 0.999523), ('Fe', 0.749654, 0.500247, 0.250477), ('O', 0.125618, 0.249693, 0.37504), ('O', 0.874999, 0.75, 0.625042), ('O', 0.624386, 0.25031, 0.874875), ('O', 0.375, 0.749998, 0.125042)]

--------------------------------------------------------------------------------
task_id: 7039
energy: -6.2539162625
Lattice:
[[-4.346597e+00  9.510000e-04  2.201000e-03]
 [-2.175237e+00  4.502571e+00  2.176079e+00]
 [ 2.202000e-03 -9.170000e-04 -4.348339e+00]]
First 10 sites:
[('Fe', 0.49999, 0.999957, 0.499948), ('Fe', 0.250018, 0.500022, 0.250042), ('Fe', 1.2e-05, 5.6e-05, 6.8e-05), ('Fe', 0.749977, 0.499969, 0.749945), ('O', 0.500029, 2.6e-05, 0.99999), ('O', 0.999993, 0.999968, 0.500025), ('O', 0.750006, 0.500036, 0.249976), ('O', 0.249975, 0.499967, 0.750006)]

--------------------------------------------------------------------------------
task_id: 23170
energy: -6.70305091125
Lattice:
[[-2.270212e+00  1.691000e-03 -2.271245e+00]
 [-1.577400e-02  4.177793e+00  1.224600e-02]
 [ 4.542253e+00 -3.074300e-02 -4.544824e+00]]
First 10 sites:
[('Fe', 0.000144, 0.000857, 0.497408), ('Fe', 0.499539, 0.498949, 0.752454), ('Fe', 0.000198, 0.998872, 0.996641), ('Fe', 0.500129, 0.501331, 0.253472), ('O', 0.498787, 0.001253, 0.249329), ('O', 0.00052, 0.501112, 0.501306), ('O', 0.501427, 0.998679, 0.748577), ('O', 0.999257, 0.498947, 0.000815)]

### Step - 1.20 - Comparing the INPUT structures

In [ ]:
# ============================================================
# PHASE 1R — COMPARE INPUT STRUCTURES
# ============================================================

print("=" * 80)
print("INPUT STRUCTURES FOR THE FOUR FeO RECORDS")
print("=" * 80)

for r in matching_records:

    inp = r["input"]["structure"]

    print("\n" + "-" * 80)
    print("task_id:", r["task_id"])
    print("energy:", r["energy_per_atom"])
    print("ordering:", r["ordering"])
    print("ordering_changed:", r["ordering_changed"])

    print("\nInput lattice:")
    print(np.array(inp["lattice"]["matrix"]))

    print("\nInput first 8 sites:")

    for i, site in enumerate(inp["sites"]):

        element = site["species"][0]["element"]
        abc = site["abc"]
        magmom = site.get("properties", {}).get("magmom")

        print(
            i,
            element,
            "abc=",
            [round(float(x), 6) for x in abc],
            "magmom=",
            magmom
        )

================================================================================
INPUT STRUCTURES FOR THE FOUR FeO RECORDS
================================================================================

--------------------------------------------------------------------------------
task_id: 6849
energy: -6.70036640875
ordering: AFM
ordering_changed: False

Input lattice:
[[-2.265716  0.       -2.265716]
 [ 2.265718  2.083392 -4.531432]
 [ 2.265717 -4.166785 -2.265716]]

Input first 8 sites:
0 Fe abc= [0.5, 0.0, 0.5] magmom= -5.0
1 Fe abc= [0.75, 0.5, 0.25] magmom= -5.0
2 Fe abc= [0.25, 0.5, 0.75] magmom= 5.0
3 Fe abc= [0.0, 0.0, 0.0] magmom= 5.0
4 O abc= [0.875, 0.25, 0.625] magmom= 0.6
5 O abc= [0.125, 0.75, 0.375] magmom= 0.6
6 O abc= [0.375, 0.25, 0.125] magmom= 0.6
7 O abc= [0.625, 0.75, 0.875] magmom= 0.6

--------------------------------------------------------------------------------
task_id: 6874
energy: -6.69515576
ordering: AFM
ordering_changed: False

Input lattice:
[[-2.265717 -2.083392  0.      ]
 [-2.265716  4.166785 -2.265716]
 [ 2.265718 -2.083392 -4.531432]]

Input first 8 sites:
0 Fe abc= [0.5, 0.0, 0.5] magmom= -5.0
1 Fe abc= [0.25, 0.5, 0.75] magmom= -5.0
2 Fe abc= [0.0, 0.0, 0.0] magmom= 5.0
3 Fe abc= [0.75, 0.5, 0.25] magmom= 5.0
4 O abc= [0.125, 0.25, 0.375] magmom= 0.6
5 O abc= [0.875, 0.75, 0.625] magmom= 0.6
6 O abc= [0.625, 0.25, 0.875] magmom= 0.6
7 O abc= [0.375, 0.75, 0.125] magmom= 0.6

--------------------------------------------------------------------------------
task_id: 7039
energy: -6.2539162625
ordering: FiM
ordering_changed: False

Input lattice:
[[-4.531433e+00  0.000000e+00  0.000000e+00]
 [-2.265717e+00  4.166785e+00  2.265716e+00]
 [ 1.000000e-06  0.000000e+00 -4.531432e+00]]

Input first 8 sites:
0 Fe abc= [0.5, 0.0, 0.5] magmom= -5.0
1 Fe abc= [0.25, 0.5, 0.25] magmom= -5.0
2 Fe abc= [0.0, 0.0, 0.0] magmom= 5.0
3 Fe abc= [0.75, 0.5, 0.75] magmom= 5.0
4 O abc= [0.5, 0.0, 0.0] magmom= 0.6
5 O abc= [0.0, 0.0, 0.5] magmom= 0.6
6 O abc= [0.75, 0.5, 0.25] magmom= 0.6
7 O abc= [0.25, 0.5, 0.75] magmom= 0.6

--------------------------------------------------------------------------------
task_id: 23170
energy: -6.70305091125
ordering: AFM
ordering_changed: False

Input lattice:
[[-2.265716  0.       -2.265716]
 [ 0.        4.166785  0.      ]
 [ 4.531434  0.       -4.531432]]

Input first 8 sites:
0 Fe abc= [0.0, 0.0, 0.5] magmom= -5.0
1 Fe abc= [0.5, 0.5, 0.75] magmom= -5.0
2 Fe abc= [0.0, 0.0, 0.0] magmom= 5.0
3 Fe abc= [0.5, 0.5, 0.25] magmom= 5.0
4 O abc= [0.5, 0.0, 0.25] magmom= 0.6
5 O abc= [0.0, 0.5, 0.5] magmom= 0.6
6 O abc= [0.5, 0.0, 0.75] magmom= 0.6
7 O abc= [0.0, 0.5, 0.0] magmom= 0.6

Calculating input volumes

In [ ]:
# ============================================================
# INPUT STRUCTURE VOLUME
# ============================================================

for r in matching_records:

    lattice = np.array(
        r["input"]["structure"]["lattice"]["matrix"],
        dtype=float
    )

    volume = abs(np.linalg.det(lattice))

    print(
        "task_id:",
        r["task_id"],
        "input volume:",
        volume
    )

task_id: 6849 input volume: 85.56026485466502
task_id: 6874 input volume: 85.56026916194521
task_id: 7039 input volume: 85.56026526775942
task_id: 23170 input volume: 85.56026526775942

### Step - 1.21 - Inspecting magnetic-ordering metadata

In [ ]:
# ============================================================
# PHASE 1S — INSPECT MAGNETIC-ORDERING METADATA
# ============================================================

for r in matching_records:

    print("\n" + "=" * 80)
    print("task_id:", r["task_id"])
    print("formula:", r["formula_pretty"])
    print("database ordering:", r["ordering"])
    print("ordering_changed:", r["ordering_changed"])

    print("\nInput metadata:")

    inp = r["input"]

    print("input ordering:", inp.get("ordering"))
    print("symmetry:", inp.get("symmetry"))
    print("index:", inp.get("index"))
    print("origin:", inp.get("origin"))
    print("input_index:", inp.get("input_index"))

================================================================================
task_id: 6849
formula: FeO
database ordering: AFM
ordering_changed: False

Input metadata:
input ordering: FiM
symmetry: I4/mmm
index: 6
origin: afm
input_index: 0

================================================================================
task_id: 6874
formula: FeO
database ordering: AFM
ordering_changed: False

Input metadata:
input ordering: FiM
symmetry: I4/mmm
index: 8
origin: afm
input_index: 0

================================================================================
task_id: 7039
formula: FeO
database ordering: FiM
ordering_changed: False

Input metadata:
input ordering: FiM
symmetry: I4/mmm
index: 1
origin: afm
input_index: 0

================================================================================
task_id: 23170
formula: FeO
database ordering: AFM
ordering_changed: False

Input metadata:
input ordering: FiM
symmetry: I4/mmm
index: 4
origin: afm
input_index: 0

### Step - 1.22 - Structure & spin sign

In [ ]:
# ============================================================
# PHASE 1T — STRUCTURE + SPIN SIGNATURE
# ============================================================

import json
import hashlib


def input_spin_structure_signature(record, threshold=0.1):

    structure = record["input"]["structure"]

    sites = []

    for site in structure["sites"]:

        element = site["species"][0]["element"]
        abc = site["abc"]

        m = float(
            site.get("properties", {})
                 .get("magmom", 0.0)
        )

        if m > threshold:
            spin = 1
        elif m < -threshold:
            spin = -1
        else:
            spin = 0

        sites.append({
            "element": element,
            "abc": [
                round(float(abc[0]), 6),
                round(float(abc[1]), 6),
                round(float(abc[2]), 6)
            ],
            "spin": spin
        })

    obj = {
        "lattice": [
            [
                round(float(x), 6)
                for x in row
            ]
            for row in structure["lattice"]["matrix"]
        ],
        "sites": sites
    }

    text = json.dumps(obj, sort_keys=True)

    return hashlib.sha256(
        text.encode()
    ).hexdigest()

In [ ]:
# Apply to entire dataset

df_mag["input_spin_signature"] = [
    input_spin_structure_signature(r)
    for r in data
]

print(
    "Unique input structure + spin states:",
    df_mag["input_spin_signature"].nunique()
)

print(
    "Total records:",
    len(df_mag)
)

print(
    "Exact duplicate calculations by this signature:",
    len(df_mag)
    - df_mag["input_spin_signature"].nunique()
)

Unique input structure + spin states: 22426
Total records: 23155
Exact duplicate calculations by this signature: 729

### Step - 1.23 - Investigating the 729 duplicate states

In [ ]:
# ============================================================
# PHASE 1U — DUPLICATE INITIAL STATES
# ============================================================

dup_stats = (
    df_mag
    .groupby("input_spin_signature")
    .agg(
        n_records=("task_id", "count"),
        n_parents=("parent_structure_id", "nunique"),
        min_energy=("energy_per_atom", "min"),
        max_energy=("energy_per_atom", "max"),
        energy_std=("energy_per_atom", "std"),
        n_orderings=("ordering", "nunique"),
        n_changed=("ordering_changed", "sum")
    )
    .reset_index()
)

duplicates = dup_stats[
    dup_stats["n_records"] > 1
].copy()

duplicates["energy_range"] = (
    duplicates["max_energy"]
    - duplicates["min_energy"]
)

print("=" * 80)
print("DUPLICATE INITIAL STRUCTURE + SPIN STATES")
print("=" * 80)

print("Number of duplicated signatures:",
      len(duplicates))

print("Total records belonging to duplicated signatures:",
      duplicates["n_records"].sum())

print("\nEnergy-range statistics:")
print(duplicates["energy_range"].describe())

print("\nLargest energy ranges:")
print(
    duplicates
    .sort_values("energy_range", ascending=False)
    .head(30)
    .to_string(index=False)
)

================================================================================
DUPLICATE INITIAL STRUCTURE + SPIN STATES
================================================================================
Number of duplicated signatures: 729
Total records belonging to duplicated signatures: 1458

Energy-range statistics:
count    7.290000e+02
mean     1.754314e-03
std      1.433812e-02
min      0.000000e+00
25%      0.000000e+00
50%      0.000000e+00
75%      3.900000e-08
max      3.270020e-01
Name: energy_range, dtype: float64

Largest energy ranges:
                                            input_spin_signature  n_records  n_parents  min_energy  max_energy  energy_std  n_orderings  n_changed  energy_range
f756a59b914b760818d72d939afe32192c2a28212ff3ed035d2603fcaeff6f30          2          1   -6.960675   -6.633673    0.231225            1          2      0.327002
daeb9168f7c6149348e31961dde542b478be664d03721591f29defec2609685b          2          1   -7.079710   -7.000734    0.055845            1          1      0.078977
afe634574704169943d6b372913251300a9548b0e0257e444a8895362b1194a3          2          1   -7.290320   -7.222324    0.048081            1          2      0.067996
edeaa8c8ce53ec563db8ab1c451fa78eeda3ed8c515d32384f8d89ecf347fe24          2          1   -6.038495   -5.971063    0.047682            1          2      0.067433
9d86aa9fbb82228973a5e85f9f435f6d57ff83612e3542be4b7337d12b49959c          2          1   -7.227553   -7.161406    0.046773            1          1      0.066147
8f7b0a49ccca8648bf944c3eb0182d51c86feca3687400b01f7257a6559c8451          2          1   -6.774862   -6.716363    0.041365            1          1      0.058499
6bd955435015e4909fd1a1ac30c2fc120852b25a7e8a0d9537977ec14bc787c1          2          1   -6.887130   -6.829221    0.040947            1          2      0.057908
d8369ceb682363e011774ddb1e0d697ed02fcf1c6f99d2229adf06fb8faa3ebe          2          1   -6.778442   -6.722407    0.039622            1          1      0.056035
3138b7cba480079523d84dbeb3df34d2468bed8a04baac826bf328f12df39f6c          2          1   -7.966322   -7.914219    0.036843            1          2      0.052103
3c8a95685456a1ba63a0ef789e68d9ce44330f15b3e2ff9834ccf04ea0cc0b9e          2          1   -6.773769   -6.727119    0.032986            1          1      0.046650
d8b33f96c7de1c83fbdced8c4d7c7fa79929b4b2318fa41c0f8fa0549d71823e          2          1   -5.936147   -5.891519    0.031557            1          2      0.044628
5726460a4e656119da7858ba0b31fb21b815b7a19162933b697c0b6f106c7af5          2          1   -6.073465   -6.028962    0.031469            2          2      0.044503
7ba87b4d6dc54cca4ec3453648bcc7e4c8b4dd3e0e9a6585a34071c640c6aab3          2          1   -6.375489   -6.335669    0.028157            1          2      0.039820
2ac239eb9c204b48e84ab34b9e21c5ac8573b57b197abdf3f6b5d8ef3883dfc0          2          1   -6.010721   -5.976757    0.024016            2          2      0.033964
8c387561e503318c07a5bcf35c258c6a4fa7d41d7fefbcb5a176a177fcb21a39          2          1   -6.005449   -5.980423    0.017697            1          2      0.025027
a0840b415297342adf5348ed06c3b736d25b4741b429221635478b8b287916b0          2          1   -6.083886   -6.059381    0.017328            1          2      0.024506
2affd85ea43cd65ca23afe3c86f7a0ae475262812b9ded634453814598cb12a0          2          1   -6.622284   -6.598060    0.017129            1          0      0.024224
261278e2f1267ac0dab216dd8b81fb2201ca1d49ea7ac011b77b5150987d3549          2          1   -7.078244   -7.057374    0.014758            1          2      0.020870
704cb6ce7027121f19fb171e6fa8cc51a1bc954d23df31d87f6f224b014d1835          2          1   -7.061972   -7.042603    0.013696            2          2      0.019369
e2868614350376cf953879566c6406ceda8dd8ef922b23ff5d3fe2fd3123c674          2          1   -6.694193   -6.675289    0.013367            1          2      0.018904
1586f3056bb17bcee392b31758d58bb9ca68542e3cec37ba8b2f7ff0848d88b7          2          1   -6.691448   -6.677666    0.009746            1          2      0.013783
b8db053a9a108a19c2af4d4b0956974ec5700fc6d8bd3ac4dbc129761b767e66          2          1   -7.105266   -7.094065    0.007920            1          2      0.011201
32d0a849e0573acc554c6840df5e96fb3c7fe4bfc50492ef8b0351356421116a          2          1   -7.091495   -7.080948    0.007458            2          2      0.010547
60e1c79de517b3122d77bd97f7187f91c08e9ce9da908105bb6dcfb2bbce1788          2          1   -6.898191   -6.889973    0.005811            1          2      0.008218
9f0ab73338aa5c62a6fffbe9f9e39015f978642fa55059d2cb81dd213506e946          2          1   -7.071189   -7.064386    0.004811            1          0      0.006804
f2c1a231c8b3c333cf9aeb0c13367870ad9d6df75fd32eb4ce5a1c56a726c2ca          2          1   -5.272771   -5.266434    0.004481            1          0      0.006337
e32ab1cbfb1b101e8a3afa5cd6e15df4220b926b73aa3e6031a0486ecf849e1b          2          1   -7.060413   -7.054909    0.003892            1          1      0.005505
21d44a229966a5b4fe83df1c2f69ff9f541b377b801e9501771bfe568086897b          2          1   -6.032733   -6.028662    0.002879            1          0      0.004072
c3668140cce7383a98e06ffbc980fce53b6951dd5eee62084b68d010566dea24          2          1   -7.035548   -7.031664    0.002747            1          2      0.003884
38f9a9335a9ea2acbe8f63fe26b1b8b840adac6c3bc9d2014235fd0b4757f967          2          1   -6.929984   -6.926194    0.002680            1          0      0.003790

In [ ]:
# ============================================================
# SHOW THE WORST DUPLICATE INITIAL STATE
# ============================================================

worst_signature = (
    duplicates
    .sort_values("energy_range", ascending=False)
    .iloc[0]["input_spin_signature"]
)

duplicate_records = []

for r in data:

    sig = input_spin_structure_signature(r)

    if sig == worst_signature:
        duplicate_records.append(r)


print("=" * 80)
print("WORST DUPLICATE INITIAL STATE")
print("=" * 80)

print("Number of records:", len(duplicate_records))

for r in duplicate_records:

    print("\n" + "-" * 80)

    print("task_id:", r["task_id"])
    print("formula:", r["formula_pretty"])
    print("ordering:", r["ordering"])
    print("ordering_changed:", r["ordering_changed"])

    print("energy:", r["energy_per_atom"])
    print(
        "energy above ground:",
        r["energy_above_ground_state_per_atom"]
    )

    print("input ordering:",
          r["input"].get("ordering"))

    print("index:",
          r["input"].get("index"))

    print("origin:",
          r["input"].get("origin"))

    print("input_index:",
          r["input"].get("input_index"))

================================================================================
WORST DUPLICATE INITIAL STATE
================================================================================
Number of records: 2

--------------------------------------------------------------------------------
task_id: 30837
formula: Li2V3CoO8
ordering: FiM
ordering_changed: True
energy: -6.6336730049999995
energy above ground: 0.47388140785714317
input ordering: FiM
index: 9
origin: afm_by_V
input_index: 0

--------------------------------------------------------------------------------
task_id: 31972
formula: Li2V3CoO8
ordering: FiM
ordering_changed: True
energy: -6.960674985
energy above ground: 0.1468794278571428
input ordering: FiM
index: 12
origin: ferri_by_V_afm
input_index: 0

### Step - 1.24 - Using exact initial magnetic moments

In [ ]:
# ============================================================
# PHASE 1V — CHECK ACTUAL INITIAL MOMENTS
# ============================================================

# Find the two records from the worst duplicate
target_ids = [30837, 31972]

for r in data:

    if r["task_id"] not in target_ids:
        continue

    print("\n" + "=" * 80)

    print("task_id:", r["task_id"])
    print("formula:", r["formula_pretty"])
    print("energy:", r["energy_per_atom"])

    print("input ordering:", r["input"].get("ordering"))
    print("origin:", r["input"].get("origin"))
    print("index:", r["input"].get("index"))

    print("\nInitial magnetic moments:")

    for i, site in enumerate(r["input"]["structure"]["sites"]):

        element = site["species"][0]["element"]

        m = (
            site.get("properties", {})
                .get("magmom", 0.0)
        )

        print(
            f"{i:3d}  {element:2s}  {float(m):8.3f}"
        )

================================================================================
task_id: 30837
formula: Li2V3CoO8
energy: -6.6336730049999995
input ordering: FiM
origin: afm_by_V
index: 9

Initial magnetic moments:
  0  Li     0.600
  1  Li     0.600
  2  Li     0.600
  3  Li     0.600
  4  V     -5.000
  5  V     -5.000
  6  V     -5.000
  7  V      5.000
  8  V      5.000
  9  V      5.000
 10  Co     5.000
 11  Co     5.000
 12  O      0.600
 13  O      0.600
 14  O      0.600
 15  O      0.600
 16  O      0.600
 17  O      0.600
 18  O      0.600
 19  O      0.600
 20  O      0.600
 21  O      0.600
 22  O      0.600
 23  O      0.600
 24  O      0.600
 25  O      0.600
 26  O      0.600
 27  O      0.600

================================================================================
task_id: 31972
formula: Li2V3CoO8
energy: -6.960674985
input ordering: FiM
origin: ferri_by_V_afm
index: 12

Initial magnetic moments:
  0  Li     0.600
  1  Li     0.600
  2  Li     0.600
  3  Li     0.600
  4  V     -5.000
  5  V     -5.000
  6  V     -5.000
  7  V      5.000
  8  V      5.000
  9  V      5.000
 10  Co     5.000
 11  Co     5.000
 12  O      0.600
 13  O      0.600
 14  O      0.600
 15  O      0.600
 16  O      0.600
 17  O      0.600
 18  O      0.600
 19  O      0.600
 20  O      0.600
 21  O      0.600
 22  O      0.600
 23  O      0.600
 24  O      0.600
 25  O      0.600
 26  O      0.600
 27  O      0.600

In [ ]:
# ============================================================
# COMPARE THE TWO INITIAL MOMENT VECTORS
# ============================================================

records_target = {
    r["task_id"]: r
    for r in data
    if r["task_id"] in target_ids
}

m1 = extract_initial_magmoms(records_target[30837])
m2 = extract_initial_magmoms(records_target[31972])

print("\nVector length:")
print(len(m1), len(m2))

print("\nMaximum absolute difference:")
print(
    np.max(
        np.abs(
            np.array(m1) - np.array(m2)
        )
    )
)

print("\nMoment-by-moment comparison:")

for i, (a, b) in enumerate(zip(m1, m2)):

    if abs(a - b) > 1e-8:

        print(
            f"site {i}: {a:.3f} -> {b:.3f}"
        )

Vector length:
28 28

Maximum absolute difference:
0.0

Moment-by-moment comparison:

In [ ]:
def input_magnetic_signature(record):
    """
    Signature based on input structure + actual initial magmom.
    """

    structure = record["input"]["structure"]

    sites = []

    for site in structure["sites"]:

        element = site["species"][0]["element"]

        abc = site["abc"]

        magmom = float(
            site.get("properties", {})
                .get("magmom", 0.0)
        )

        sites.append({
            "element": element,
            "abc": [
                round(float(abc[0]), 6),
                round(float(abc[1]), 6),
                round(float(abc[2]), 6)
            ],
            "magmom": round(magmom, 6)
        })

    obj = {
        "lattice": [
            [
                round(float(x), 6)
                for x in row
            ]
            for row in structure["lattice"]["matrix"]
        ],
        "sites": sites
    }

    text = json.dumps(obj, sort_keys=True)

    return hashlib.sha256(
        text.encode()
    ).hexdigest()

### Step - 1.25 - Rebuilding uique state count

In [ ]:
# ============================================================
# PHASE 1W — REBUILD UNIQUE STATE COUNT
# ============================================================

df_mag["input_magnetic_signature"] = [
    input_magnetic_signature(r)
    for r in data
]

n_unique = (
    df_mag["input_magnetic_signature"]
    .nunique()
)

print("=" * 80)
print("UNIQUE INITIAL MAGNETIC STATES")
print("=" * 80)

print("Total records:", len(df_mag))
print("Unique states:", n_unique)
print("Repeated records:", len(df_mag) - n_unique)

================================================================================
UNIQUE INITIAL MAGNETIC STATES
================================================================================
Total records: 23155
Unique states: 22459
Repeated records: 696

### Step - 1.26 - Creating final dataset - V1

In [ ]:
# ============================================================
# FINAL DATASET v1
# ============================================================

# Start from df_mag and add the exact initial magnetic signature
df_final_dataset = df_mag.copy()

# Keep only the columns we actually need
df_final_dataset = df_final_dataset[
    [
        "parent_structure_id",
        "task_id",
        "formula",
        "initial_magmoms",
        "energy_per_atom",
        "energy_above_ground",
        "ordering",
        "ordering_changed",
        "input_magnetic_signature"
    ]
].copy()

# Rename target
df_final_dataset = df_final_dataset.rename(
    columns={
        "energy_above_ground": "delta_E"
    }
)

# ------------------------------------------------------------
# Collapse exact duplicate initial states
# ------------------------------------------------------------

group_cols = [
    "parent_structure_id",
    "input_magnetic_signature"
]

# Aggregate numerical target and preserve useful metadata
clean_dataset = (
    df_final_dataset
    .groupby(group_cols, as_index=False)
    .agg(
        formula=("formula", "first"),
        task_id=("task_id", "first"),

        initial_magmoms=("initial_magmoms", "first"),

        energy_per_atom=("energy_per_atom", "mean"),
        delta_E=("delta_E", "mean"),

        ordering=("ordering", "first"),

        ordering_changed=("ordering_changed", "max"),

        n_dft_records=("task_id", "count")
    )
)

print("=" * 80)
print("FINAL CLEAN DATASET v1")
print("=" * 80)

print("Raw DFT records:", len(df_final_dataset))
print("Unique ML states:", len(clean_dataset))
print("Collapsed duplicate records:",
      len(df_final_dataset) - len(clean_dataset))

print("\nRecords per ML state:")
print(clean_dataset["n_dft_records"].value_counts().sort_index())

print("\nParents represented:",
      clean_dataset["parent_structure_id"].nunique())

print("\nDelta-E statistics:")
print(clean_dataset["delta_E"].describe())

print("\nExample:")
print(clean_dataset.head())

================================================================================
FINAL CLEAN DATASET v1
================================================================================
Raw DFT records: 23155
Unique ML states: 22459
Collapsed duplicate records: 696

Records per ML state:
n_dft_records
1    21763
2      696
Name: count, dtype: int64

Parents represented: 2588

Delta-E statistics:
count    22459.000000
mean         0.006771
std          0.021113
min          0.000000
25%          0.000162
50%          0.000869
75%          0.004675
max          0.472703
Name: delta_E, dtype: float64

Example:
                                 parent_structure_id  \
0  000aa4ac0b5d42d6a9fadefdb79f1b4bd881c1afec5425...
1  001811216d9f019e2440ee897870fd552e7ba3915cc17c...
2  001811216d9f019e2440ee897870fd552e7ba3915cc17c...
3  001811216d9f019e2440ee897870fd552e7ba3915cc17c...
4  001811216d9f019e2440ee897870fd552e7ba3915cc17c...

                            input_magnetic_signature       formula  task_id  \
0  dd12b5f22fd3d9e00b9096fc9f2c0a6a56cddd993a16a4...  Li2V4CrCuO12    53864
1  85500a3581a781826640812815529416ddf6866ae70354...         VGaO3    49080
2  8abb75b2261e7b52ba81fb7d9743b21269ea56d923a1e0...         VGaO3    49345
3  f4eea284050fe281b2181b3a19a3c0c8c01fb2c28e5c32...         VGaO3    49242
4  fcbc1ed0c586d0437acacdbbd4434937602c49430ff193...         VGaO3    49143

                                     initial_magmoms  energy_per_atom  \
0  [0.0, 0.0, 5.0, 5.0, 5.0, 5.0, 5.0, 1.73, 0.0,...        -7.066532
1  [5.0, 5.0, 5.0, 5.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...        -6.948634
2  [-5.0, -5.0, 5.0, 5.0, 0.6, 0.6, 0.6, 0.6, 0.6...        -6.948318
3  [-5.0, -5.0, 5.0, 5.0, 0.6, 0.6, 0.6, 0.6, 0.6...        -6.943229
4  [-5.0, -5.0, 5.0, 5.0, 0.6, 0.6, 0.6, 0.6, 0.6...        -6.942791

    delta_E ordering  ordering_changed  n_dft_records
0  0.000000       FM              True              1
1  0.000000       FM             False              1
2  0.000316      AFM             False              1
3  0.005405      AFM             False              1
4  0.005843      FiM             False              1

Saving the dataset

In [ ]:
pwd

'/content/drive/MyDrive/Proj_2_Alt_Mags_Grnd_E/magnetic-topological-materials'

In [ ]:
# Save for later ALIGNN processing
clean_dataset.to_pickle("magnetic_dataset_v1.pkl")
clean_dataset.to_csv(
    "magnetic_dataset_v1.csv",
    index=False
)

print("\nSaved:")
print("magnetic_dataset_v1.pkl")
print("magnetic_dataset_v1.csv")

Saved:
magnetic_dataset_v1.pkl
magnetic_dataset_v1.csv

## Phase - 2 - Baseline ALIGNN Model - G → ΔE

### Step - 2.1 - Building the graph-ready dataset

In [ ]:
# ============================================================
# PHASE 2A — BUILD GRAPH-READY MASTER DATASET
# ============================================================

import pandas as pd
import numpy as np
import pickle

# ------------------------------------------------------------
# Build a lookup from task_id -> original record
# ------------------------------------------------------------

record_lookup = {
    r["task_id"]: r
    for r in data
}

records = []

for _, row in clean_dataset.iterrows():

    task_id = row["task_id"]

    r = record_lookup[task_id]

    records.append({
        "task_id": task_id,

        "parent_structure_id":
            row["parent_structure_id"],

        "formula":
            row["formula"],

        # IMPORTANT: INPUT structure, not relaxed structure
        "input_structure":
            r["input"]["structure"],

        # Actual initial magnetic moments
        "initial_magmoms":
            row["initial_magmoms"],

        # Target
        "delta_E":
            float(row["delta_E"]),

        "energy_per_atom":
            float(row["energy_per_atom"]),

        # Metadata
        "ordering":
            row["ordering"],

        "ordering_changed":
            bool(row["ordering_changed"]),

        "n_dft_records":
            int(row["n_dft_records"]),

        "input_ordering":
            r["input"].get("ordering"),

        "origin":
            r["input"].get("origin"),

        "input_index":
            r["input"].get("input_index"),

        "index":
            r["input"].get("index")
    })


graph_df = pd.DataFrame(records)

print("=" * 80)
print("PHASE 2A — GRAPH-READY DATASET")
print("=" * 80)

print("Samples:", len(graph_df))
print("Parents:", graph_df["parent_structure_id"].nunique())

print("\nColumns:")
print(graph_df.columns.tolist())

print("\nTarget statistics:")
print(graph_df["delta_E"].describe())

print("\nExample:")
print(
    graph_df.iloc[0][
        [
            "task_id",
            "formula",
            "parent_structure_id",
            "initial_magmoms",
            "delta_E",
            "ordering"
        ]
    ]
)

================================================================================
PHASE 2A — GRAPH-READY DATASET
================================================================================
Samples: 22459
Parents: 2588

Columns:
['task_id', 'parent_structure_id', 'formula', 'input_structure', 'initial_magmoms', 'delta_E', 'energy_per_atom', 'ordering', 'ordering_changed', 'n_dft_records', 'input_ordering', 'origin', 'input_index', 'index']

Target statistics:
count    22459.000000
mean         0.006771
std          0.021113
min          0.000000
25%          0.000162
50%          0.000869
75%          0.004675
max          0.472703
Name: delta_E, dtype: float64

Example:
task_id                                                            53864
formula                                                     Li2V4CrCuO12
parent_structure_id    000aa4ac0b5d42d6a9fadefdb79f1b4bd881c1afec5425...
initial_magmoms        [0.0, 0.0, 5.0, 5.0, 5.0, 5.0, 5.0, 1.73, 0.0,...
delta_E                                                              0.0
ordering                                                              FM
Name: 0, dtype: object

Saving

In [ ]:
# Save master dataset
with open("magnetic_alignn_master.pkl", "wb") as f:
    pickle.dump(graph_df, f)

print("Saved magnetic_alignn_master.pkl")

Saved magnetic_alignn_master.pkl

### Step - 2.2 - Checking the dataset before ALIGNN

In [ ]:
# ============================================================
# PHASE 2B — DATASET SANITY CHECK
# ============================================================

# Number of configurations per parent
states_per_parent = (
    graph_df
    .groupby("parent_structure_id")
    .size()
)

print("=" * 80)
print("CONFIGURATIONS PER PARENT")
print("=" * 80)

print(states_per_parent.describe())

print(
    "\nParents with >= 2 configurations:",
    (states_per_parent >= 2).sum()
)

print(
    "Parents with >= 3 configurations:",
    (states_per_parent >= 3).sum()
)

print(
    "Parents with >= 5 configurations:",
    (states_per_parent >= 5).sum()
)

================================================================================
CONFIGURATIONS PER PARENT
================================================================================
count    2588.000000
mean        8.678130
std         4.030752
min         1.000000
25%         5.000000
50%         8.000000
75%        12.000000
max        16.000000
dtype: float64

Parents with >= 2 configurations: 2532
Parents with >= 3 configurations: 2458
Parents with >= 5 configurations: 2096

### Step - 2.3 - Making the correct train/validation/test split

Splitting the parents, not individual magnetic states

In [ ]:
# ============================================================
# PHASE 2C — PARENT-LEVEL SPLIT
# ============================================================

from sklearn.model_selection import train_test_split

# Convert to a plain Python list
parents = (
    graph_df["parent_structure_id"]
    .dropna()
    .unique()
    .tolist()
)

print("Total parents:", len(parents))

# 80% train, 20% temporary
train_parents, temp_parents = train_test_split(
    parents,
    test_size=0.20,
    random_state=42
)

# 10% validation, 10% test
val_parents, test_parents = train_test_split(
    temp_parents,
    test_size=0.50,
    random_state=42
)

train_parents = set(train_parents)
val_parents = set(val_parents)
test_parents = set(test_parents)


# Assign split
def assign_split(parent_id):

    if parent_id in train_parents:
        return "train"

    elif parent_id in val_parents:
        return "val"

    elif parent_id in test_parents:
        return "test"

    else:
        raise ValueError(
            f"Parent {parent_id} was not assigned to a split."
        )


graph_df["split"] = (
    graph_df["parent_structure_id"]
    .apply(assign_split)
)


print("=" * 80)
print("PARENT-LEVEL SPLIT")
print("=" * 80)

print(
    graph_df.groupby("split")["parent_structure_id"]
    .nunique()
)

print("\nSamples:")
print(graph_df["split"].value_counts())

print("\nFinal counts:")

for split in ["train", "val", "test"]:

    subset = graph_df[
        graph_df["split"] == split
    ]

    print(
        f"{split:5s}: "
        f"{subset['parent_structure_id'].nunique()} parents, "
        f"{len(subset)} states"
    )

Total parents: 2588
================================================================================
PARENT-LEVEL SPLIT
================================================================================
split
test      259
train    2070
val       259
Name: parent_structure_id, dtype: int64

Samples:
split
train    18010
val       2246
test      2203
Name: count, dtype: int64

Final counts:
train: 2070 parents, 18010 states
val  : 259 parents, 2246 states
test : 259 parents, 2203 states

### Step - 2.4 - Preparing the standard ALIGNN baseline

Checking environment

In [ ]:
# ============================================================
# PHASE 2D — CHECK ALIGNN INSTALLATION
# ============================================================

import importlib.util

print(
    "ALIGNN installed:",
    importlib.util.find_spec("alignn") is not None
)

print(
    "PyTorch installed:",
    importlib.util.find_spec("torch") is not None
)

print(
    "DGL installed:",
    importlib.util.find_spec("dgl") is not None
)

ALIGNN installed: False
PyTorch installed: True
DGL installed: False

In [ ]:
import sys

print("Python:", sys.version)

Python: 3.13.15 (main, Aug  6 2026, 11:06:22) [GCC 13.3.0]

Installing ALIGNN

In [ ]:
!python -m pip install --upgrade pip
!python -m pip install alignn

Requirement already satisfied: pip in /usr/local/lib/python3.13/dist-packages (24.1.2)
Collecting pip
  Downloading pip-26.2.1-py3-none-any.whl.metadata (4.6 kB)
Downloading pip-26.2.1-py3-none-any.whl (1.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 16.5 MB/s eta 0:00:00
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 24.1.2
    Uninstalling pip-24.1.2:
      Successfully uninstalled pip-24.1.2
Successfully installed pip-26.2.1
Collecting alignn
  Downloading alignn-2026.8.11-py2.py3-none-any.whl.metadata (25 kB)
Requirement already satisfied: numpy>=1.19.5 in /usr/local/lib/python3.13/dist-packages (from alignn) (2.1.3)
Requirement already satisfied: scipy>=1.6.1 in /usr/local/lib/python3.13/dist-packages (from alignn) (1.16.3)
Collecting jarvis-tools>=2021.07.19 (from alignn)
  Downloading jarvis_tools-2026.6.12-py2.py3-none-any.whl.metadata (3.0 kB)
Requirement already satisfied: torch>=2.2.1 in /usr/local/lib/python3.13/dist-packages (from alignn) (2.11.0+cpu)
Requirement already satisfied: mpmath>=1.3.0 in /usr/local/lib/python3.13/dist-packages (from alignn) (1.3.0)
Collecting spglib>=2.0.2 (from alignn)
  Downloading spglib-2.7.0-cp313-cp313-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (4.2 kB)
Requirement already satisfied: scikit-learn>=0.22.2 in /usr/local/lib/python3.13/dist-packages (from alignn) (1.6.1)
Requirement already satisfied: matplotlib>=3.4.1 in /usr/local/lib/python3.13/dist-packages (from alignn) (3.10.0)
Requirement already satisfied: tqdm>=4.60.0 in /usr/local/lib/python3.13/dist-packages (from alignn) (4.67.3)
Requirement already satisfied: pandas>=1.2.3 in /usr/local/lib/python3.13/dist-packages (from alignn) (2.2.3)
Requirement already satisfied: pydantic>=1.8.1 in /usr/local/lib/python3.13/dist-packages (from alignn) (2.13.5)
Collecting pydantic-settings (from alignn)
  Downloading pydantic_settings-2.15.0-py3-none-any.whl.metadata (3.9 kB)
Collecting flake8>=3.9.1 (from alignn)
  Downloading flake8-7.3.0-py2.py3-none-any.whl.metadata (3.8 kB)
Collecting pycodestyle>=2.7.0 (from alignn)
  Downloading pycodestyle-2.14.0-py2.py3-none-any.whl.metadata (4.5 kB)
Collecting pydocstyle>=6.0.0 (from alignn)
  Downloading pydocstyle-6.3.0-py3-none-any.whl.metadata (3.7 kB)
Requirement already satisfied: pyparsing>=2.2.1 in /usr/local/lib/python3.13/dist-packages (from alignn) (3.3.2)
Collecting ase (from alignn)
  Downloading ase-3.29.0-py3-none-any.whl.metadata (4.4 kB)
Collecting lmdb (from alignn)
  Downloading lmdb-2.3.0-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (1.2 kB)
Collecting mccabe<0.8.0,>=0.7.0 (from flake8>=3.9.1->alignn)
  Downloading mccabe-0.7.0-py2.py3-none-any.whl.metadata (5.0 kB)
Collecting pyflakes<3.5.0,>=3.4.0 (from flake8>=3.9.1->alignn)
  Downloading pyflakes-3.4.0-py2.py3-none-any.whl.metadata (3.5 kB)
Requirement already satisfied: joblib>=0.14.1 in /usr/local/lib/python3.13/dist-packages (from jarvis-tools>=2021.07.19->alignn) (1.6.0)
Requirement already satisfied: requests>=2.23.0 in /usr/local/lib/python3.13/dist-packages (from jarvis-tools>=2021.07.19->alignn) (2.32.4)
Requirement already satisfied: toolz>=0.9.0 in /usr/local/lib/python3.13/dist-packages (from jarvis-tools>=2021.07.19->alignn) (0.12.1)
Collecting xmltodict>=0.11.0 (from jarvis-tools>=2021.07.19->alignn)
  Downloading xmltodict-1.0.4-py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: cloudpickle>=3.0 in /usr/local/lib/python3.13/dist-packages (from joblib>=0.14.1->jarvis-tools>=2021.07.19->alignn) (3.1.2)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib>=3.4.1->alignn) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.13/dist-packages (from matplotlib>=3.4.1->alignn) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.13/dist-packages (from matplotlib>=3.4.1->alignn) (4.64.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib>=3.4.1->alignn) (1.5.1)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.13/dist-packages (from matplotlib>=3.4.1->alignn) (26.3)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.13/dist-packages (from matplotlib>=3.4.1->alignn) (11.3.0)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.13/dist-packages (from matplotlib>=3.4.1->alignn) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas>=1.2.3->alignn) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas>=1.2.3->alignn) (2026.3)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.13/dist-packages (from pydantic>=1.8.1->alignn) (0.8.0)
Requirement already satisfied: pydantic-core==2.46.5 in /usr/local/lib/python3.13/dist-packages (from pydantic>=1.8.1->alignn) (2.46.5)
Requirement already satisfied: typing-extensions>=4.14.1 in /usr/local/lib/python3.13/dist-packages (from pydantic>=1.8.1->alignn) (4.16.0)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.13/dist-packages (from pydantic>=1.8.1->alignn) (0.4.4)
Requirement already satisfied: snowballstemmer>=2.2.0 in /usr/local/lib/python3.13/dist-packages (from pydocstyle>=6.0.0->alignn) (3.1.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.7->matplotlib>=3.4.1->alignn) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.13/dist-packages (from requests>=2.23.0->jarvis-tools>=2021.07.19->alignn) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.13/dist-packages (from requests>=2.23.0->jarvis-tools>=2021.07.19->alignn) (3.19)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.13/dist-packages (from requests>=2.23.0->jarvis-tools>=2021.07.19->alignn) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.13/dist-packages (from requests>=2.23.0->jarvis-tools>=2021.07.19->alignn) (2026.7.22)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.13/dist-packages (from scikit-learn>=0.22.2->alignn) (3.6.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.13/dist-packages (from torch>=2.2.1->alignn) (3.32.5)
Requirement already satisfied: setuptools<82 in /usr/local/lib/python3.13/dist-packages (from torch>=2.2.1->alignn) (80.10.2)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.13/dist-packages (from torch>=2.2.1->alignn) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.13/dist-packages (from torch>=2.2.1->alignn) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.13/dist-packages (from torch>=2.2.1->alignn) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.13/dist-packages (from torch>=2.2.1->alignn) (2025.12.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.13/dist-packages (from jinja2->torch>=2.2.1->alignn) (3.0.3)
Requirement already satisfied: python-dotenv>=0.21.0 in /usr/local/lib/python3.13/dist-packages (from pydantic-settings->alignn) (1.2.3)
Downloading alignn-2026.8.11-py2.py3-none-any.whl (203 kB)
Downloading flake8-7.3.0-py2.py3-none-any.whl (57 kB)
Downloading mccabe-0.7.0-py2.py3-none-any.whl (7.3 kB)
Downloading pycodestyle-2.14.0-py2.py3-none-any.whl (31 kB)
Downloading pyflakes-3.4.0-py2.py3-none-any.whl (63 kB)
Downloading jarvis_tools-2026.6.12-py2.py3-none-any.whl (4.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.2/4.2 MB 53.4 MB/s  0:00:00
Downloading pydocstyle-6.3.0-py3-none-any.whl (38 kB)
Downloading spglib-2.7.0-cp313-cp313-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (962 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 962.5/962.5 kB 39.3 MB/s  0:00:00
Downloading xmltodict-1.0.4-py3-none-any.whl (13 kB)
Downloading ase-3.29.0-py3-none-any.whl (3.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.0/3.0 MB 89.4 MB/s  0:00:00
Downloading lmdb-2.3.0-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (346 kB)
Downloading pydantic_settings-2.15.0-py3-none-any.whl (69 kB)
Installing collected packages: xmltodict, spglib, pyflakes, pydocstyle, pycodestyle, mccabe, lmdb, flake8, pydantic-settings, jarvis-tools, ase, alignn
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12/12 [alignn]
Successfully installed alignn-2026.8.11 ase-3.29.0 flake8-7.3.0 jarvis-tools-2026.6.12 lmdb-2.3.0 mccabe-0.7.0 pycodestyle-2.14.0 pydantic-settings-2.15.0 pydocstyle-6.3.0 pyflakes-3.4.0 spglib-2.7.0 xmltodict-1.0.4

In [ ]:
!python -c "import alignn; print('ALIGNN:', alignn.__file__)"

ALIGNN: /usr/local/lib/python3.13/dist-packages/alignn/__init__.py

In [ ]:
!python -c "import torch; print('PyTorch:', torch.__version__)"

PyTorch: 2.11.0+cpu

In [ ]:
pip install alignn

Requirement already satisfied: alignn in /usr/local/lib/python3.13/dist-packages (2026.8.11)
Requirement already satisfied: numpy>=1.19.5 in /usr/local/lib/python3.13/dist-packages (from alignn) (2.1.3)
Requirement already satisfied: scipy>=1.6.1 in /usr/local/lib/python3.13/dist-packages (from alignn) (1.16.3)
Requirement already satisfied: jarvis-tools>=2021.07.19 in /usr/local/lib/python3.13/dist-packages (from alignn) (2026.6.12)
Requirement already satisfied: torch>=2.2.1 in /usr/local/lib/python3.13/dist-packages (from alignn) (2.11.0+cpu)
Requirement already satisfied: mpmath>=1.3.0 in /usr/local/lib/python3.13/dist-packages (from alignn) (1.3.0)
Requirement already satisfied: spglib>=2.0.2 in /usr/local/lib/python3.13/dist-packages (from alignn) (2.7.0)
Requirement already satisfied: scikit-learn>=0.22.2 in /usr/local/lib/python3.13/dist-packages (from alignn) (1.6.1)
Requirement already satisfied: matplotlib>=3.4.1 in /usr/local/lib/python3.13/dist-packages (from alignn) (3.10.0)
Requirement already satisfied: tqdm>=4.60.0 in /usr/local/lib/python3.13/dist-packages (from alignn) (4.67.3)
Requirement already satisfied: pandas>=1.2.3 in /usr/local/lib/python3.13/dist-packages (from alignn) (2.2.3)
Requirement already satisfied: pydantic>=1.8.1 in /usr/local/lib/python3.13/dist-packages (from alignn) (2.13.5)
Requirement already satisfied: pydantic-settings in /usr/local/lib/python3.13/dist-packages (from alignn) (2.15.0)
Requirement already satisfied: flake8>=3.9.1 in /usr/local/lib/python3.13/dist-packages (from alignn) (7.3.0)
Requirement already satisfied: pycodestyle>=2.7.0 in /usr/local/lib/python3.13/dist-packages (from alignn) (2.14.0)
Requirement already satisfied: pydocstyle>=6.0.0 in /usr/local/lib/python3.13/dist-packages (from alignn) (6.3.0)
Requirement already satisfied: pyparsing>=2.2.1 in /usr/local/lib/python3.13/dist-packages (from alignn) (3.3.2)
Requirement already satisfied: ase in /usr/local/lib/python3.13/dist-packages (from alignn) (3.29.0)
Requirement already satisfied: lmdb in /usr/local/lib/python3.13/dist-packages (from alignn) (2.3.0)
Requirement already satisfied: mccabe<0.8.0,>=0.7.0 in /usr/local/lib/python3.13/dist-packages (from flake8>=3.9.1->alignn) (0.7.0)
Requirement already satisfied: pyflakes<3.5.0,>=3.4.0 in /usr/local/lib/python3.13/dist-packages (from flake8>=3.9.1->alignn) (3.4.0)
Requirement already satisfied: joblib>=0.14.1 in /usr/local/lib/python3.13/dist-packages (from jarvis-tools>=2021.07.19->alignn) (1.6.0)
Requirement already satisfied: requests>=2.23.0 in /usr/local/lib/python3.13/dist-packages (from jarvis-tools>=2021.07.19->alignn) (2.32.4)
Requirement already satisfied: toolz>=0.9.0 in /usr/local/lib/python3.13/dist-packages (from jarvis-tools>=2021.07.19->alignn) (0.12.1)
Requirement already satisfied: xmltodict>=0.11.0 in /usr/local/lib/python3.13/dist-packages (from jarvis-tools>=2021.07.19->alignn) (1.0.4)
Requirement already satisfied: cloudpickle>=3.0 in /usr/local/lib/python3.13/dist-packages (from joblib>=0.14.1->jarvis-tools>=2021.07.19->alignn) (3.1.2)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib>=3.4.1->alignn) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.13/dist-packages (from matplotlib>=3.4.1->alignn) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.13/dist-packages (from matplotlib>=3.4.1->alignn) (4.64.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib>=3.4.1->alignn) (1.5.1)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.13/dist-packages (from matplotlib>=3.4.1->alignn) (26.3)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.13/dist-packages (from matplotlib>=3.4.1->alignn) (11.3.0)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.13/dist-packages (from matplotlib>=3.4.1->alignn) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas>=1.2.3->alignn) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas>=1.2.3->alignn) (2026.3)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.13/dist-packages (from pydantic>=1.8.1->alignn) (0.8.0)
Requirement already satisfied: pydantic-core==2.46.5 in /usr/local/lib/python3.13/dist-packages (from pydantic>=1.8.1->alignn) (2.46.5)
Requirement already satisfied: typing-extensions>=4.14.1 in /usr/local/lib/python3.13/dist-packages (from pydantic>=1.8.1->alignn) (4.16.0)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.13/dist-packages (from pydantic>=1.8.1->alignn) (0.4.4)
Requirement already satisfied: snowballstemmer>=2.2.0 in /usr/local/lib/python3.13/dist-packages (from pydocstyle>=6.0.0->alignn) (3.1.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.7->matplotlib>=3.4.1->alignn) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.13/dist-packages (from requests>=2.23.0->jarvis-tools>=2021.07.19->alignn) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.13/dist-packages (from requests>=2.23.0->jarvis-tools>=2021.07.19->alignn) (3.19)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.13/dist-packages (from requests>=2.23.0->jarvis-tools>=2021.07.19->alignn) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.13/dist-packages (from requests>=2.23.0->jarvis-tools>=2021.07.19->alignn) (2026.7.22)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.13/dist-packages (from scikit-learn>=0.22.2->alignn) (3.6.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.13/dist-packages (from torch>=2.2.1->alignn) (3.32.5)
Requirement already satisfied: setuptools<82 in /usr/local/lib/python3.13/dist-packages (from torch>=2.2.1->alignn) (80.10.2)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.13/dist-packages (from torch>=2.2.1->alignn) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.13/dist-packages (from torch>=2.2.1->alignn) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.13/dist-packages (from torch>=2.2.1->alignn) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.13/dist-packages (from torch>=2.2.1->alignn) (2025.12.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.13/dist-packages (from jinja2->torch>=2.2.1->alignn) (3.0.3)
Requirement already satisfied: python-dotenv>=0.21.0 in /usr/local/lib/python3.13/dist-packages (from pydantic-settings->alignn) (1.2.3)

In [ ]:
import alignn
import torch

print("ALIGNN:", alignn.__file__)
print("PyTorch:", torch.__version__)

ALIGNN: /usr/local/lib/python3.13/dist-packages/alignn/__init__.py
PyTorch: 2.11.0+cpu

In [ ]:
!train_alignn.py --help

usage: train_alignn.py [-h] [--root_dir ROOT_DIR] [--config_name CONFIG_NAME]
                       [--file_format FILE_FORMAT]
                       [--classification_threshold CLASSIFICATION_THRESHOLD]
                       [--batch_size BATCH_SIZE] [--epochs EPOCHS]
                       [--target_key TARGET_KEY] [--id_key ID_KEY]
                       [--force_key FORCE_KEY] [--atomwise_key ATOMWISE_KEY]
                       [--stresswise_key STRESSWISE_KEY]
                       [--additional_output_key ADDITIONAL_OUTPUT_KEY]
                       [--output_dir OUTPUT_DIR]
                       [--restart_model_path RESTART_MODEL_PATH]
                       [--device DEVICE]

Atomistic Line Graph Neural Network

options:
  -h, --help            show this help message and exit
  --root_dir ROOT_DIR   Folder with id_props.csv, structure files
  --config_name CONFIG_NAME
                        Name of the config file
  --file_format FILE_FORMAT
                        poscar/cif/xyz/pdb file format.
  --classification_threshold CLASSIFICATION_THRESHOLD
                        Floating point threshold for converting into 0/1
                        class, use only for classification tasks
  --batch_size BATCH_SIZE
                        Batch size, generally 64
  --epochs EPOCHS       Number of epochs, generally 300
  --target_key TARGET_KEY
                        Name of the key for graph level data such as
                        total_energy
  --id_key ID_KEY       Name of the key for graph level id such as id
  --force_key FORCE_KEY
                        Name of key for gradient level data such as forces,
                        (Natoms x p)
  --atomwise_key ATOMWISE_KEY
                        Name of key for atomwise level data: forces, charges
                        (Natoms x p)
  --stresswise_key STRESSWISE_KEY
                        Name of the key for stress (3x3) level data such as
                        forces
  --additional_output_key ADDITIONAL_OUTPUT_KEY
                        Name of the key for extra global output eg DOS
  --output_dir OUTPUT_DIR
                        Folder to save outputs
  --restart_model_path RESTART_MODEL_PATH
                        Checkpoint file path for model
  --device DEVICE       set device for training the model [e.g. cpu, cuda,
                        cuda:2]

### Step - 2.5 - Generating ALIGNN structures files

In [ ]:
pip install pymatgen

Collecting pymatgen
  Downloading pymatgen-2026.5.4-py3-none-any.whl.metadata (12 kB)
Collecting pymatgen-core>=2026.4.16 (from pymatgen)
  Downloading pymatgen_core-2026.8.30-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (13 kB)
Collecting bibtexparser<2,>=1 (from pymatgen-core>=2026.4.16->pymatgen)
  Downloading bibtexparser-1.4.4.tar.gz (55 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: joblib>=1.3.2 in /usr/local/lib/python3.13/dist-packages (from pymatgen-core>=2026.4.16->pymatgen) (1.6.0)
Requirement already satisfied: lxml>=6.1.0 in /usr/local/lib/python3.13/dist-packages (from pymatgen-core>=2026.4.16->pymatgen) (6.1.2)
Requirement already satisfied: matplotlib>=3.8 in /usr/local/lib/python3.13/dist-packages (from pymatgen-core>=2026.4.16->pymatgen) (3.10.0)
Collecting monty>=2026.7.16 (from pymatgen-core>=2026.4.16->pymatgen)
  Downloading monty-2026.7.16-py3-none-any.whl.metadata (3.3 kB)
Requirement already satisfied: networkx>=2.7 in /usr/local/lib/python3.13/dist-packages (from pymatgen-core>=2026.4.16->pymatgen) (3.6.1)
Requirement already satisfied: numpy<3,>=2.1.0 in /usr/local/lib/python3.13/dist-packages (from pymatgen-core>=2026.4.16->pymatgen) (2.1.3)
Requirement already satisfied: orjson<4,>=3.10 in /usr/local/lib/python3.13/dist-packages (from pymatgen-core>=2026.4.16->pymatgen) (3.12.0)
Collecting palettable>=3.3.3 (from pymatgen-core>=2026.4.16->pymatgen)
  Downloading palettable-3.3.3-py2.py3-none-any.whl.metadata (3.3 kB)
Requirement already satisfied: pandas>=2 in /usr/local/lib/python3.13/dist-packages (from pymatgen-core>=2026.4.16->pymatgen) (2.2.3)
Requirement already satisfied: plotly>=5.0 in /usr/local/lib/python3.13/dist-packages (from pymatgen-core>=2026.4.16->pymatgen) (5.24.1)
Collecting requests>=2.32.5 (from pymatgen-core>=2026.4.16->pymatgen)
  Downloading requests-2.34.2-py3-none-any.whl.metadata (4.8 kB)
Requirement already satisfied: scipy>=1.13.0 in /usr/local/lib/python3.13/dist-packages (from pymatgen-core>=2026.4.16->pymatgen) (1.16.3)
Requirement already satisfied: spglib>=2.5 in /usr/local/lib/python3.13/dist-packages (from pymatgen-core>=2026.4.16->pymatgen) (2.7.0)
Requirement already satisfied: sympy>=1.3 in /usr/local/lib/python3.13/dist-packages (from pymatgen-core>=2026.4.16->pymatgen) (1.14.0)
Requirement already satisfied: tabulate>=0.9.0 in /usr/local/lib/python3.13/dist-packages (from pymatgen-core>=2026.4.16->pymatgen) (0.9.0)
Requirement already satisfied: tqdm>=4.67.3 in /usr/local/lib/python3.13/dist-packages (from pymatgen-core>=2026.4.16->pymatgen) (4.67.3)
Collecting uncertainties>=3.1 (from pymatgen-core>=2026.4.16->pymatgen)
  Downloading uncertainties-3.2.3-py3-none-any.whl.metadata (7.0 kB)
Requirement already satisfied: pyparsing>=2.0.3 in /usr/local/lib/python3.13/dist-packages (from bibtexparser<2,>=1->pymatgen-core>=2026.4.16->pymatgen) (3.3.2)
Requirement already satisfied: cloudpickle>=3.0 in /usr/local/lib/python3.13/dist-packages (from joblib>=1.3.2->pymatgen-core>=2026.4.16->pymatgen) (3.1.2)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib>=3.8->pymatgen-core>=2026.4.16->pymatgen) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.13/dist-packages (from matplotlib>=3.8->pymatgen-core>=2026.4.16->pymatgen) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.13/dist-packages (from matplotlib>=3.8->pymatgen-core>=2026.4.16->pymatgen) (4.64.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib>=3.8->pymatgen-core>=2026.4.16->pymatgen) (1.5.1)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.13/dist-packages (from matplotlib>=3.8->pymatgen-core>=2026.4.16->pymatgen) (26.3)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.13/dist-packages (from matplotlib>=3.8->pymatgen-core>=2026.4.16->pymatgen) (11.3.0)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.13/dist-packages (from matplotlib>=3.8->pymatgen-core>=2026.4.16->pymatgen) (2.9.0.post0)
Collecting ruamel.yaml (from monty>=2026.7.16->pymatgen-core>=2026.4.16->pymatgen)
  Downloading ruamel_yaml-0.19.1-py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas>=2->pymatgen-core>=2026.4.16->pymatgen) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas>=2->pymatgen-core>=2026.4.16->pymatgen) (2026.3)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.13/dist-packages (from plotly>=5.0->pymatgen-core>=2026.4.16->pymatgen) (9.1.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.7->matplotlib>=3.8->pymatgen-core>=2026.4.16->pymatgen) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.13/dist-packages (from requests>=2.32.5->pymatgen-core>=2026.4.16->pymatgen) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.13/dist-packages (from requests>=2.32.5->pymatgen-core>=2026.4.16->pymatgen) (3.19)
Requirement already satisfied: urllib3<3,>=1.26 in /usr/local/lib/python3.13/dist-packages (from requests>=2.32.5->pymatgen-core>=2026.4.16->pymatgen) (2.5.0)
Requirement already satisfied: certifi>=2023.5.7 in /usr/local/lib/python3.13/dist-packages (from requests>=2.32.5->pymatgen-core>=2026.4.16->pymatgen) (2026.7.22)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.13/dist-packages (from sympy>=1.3->pymatgen-core>=2026.4.16->pymatgen) (1.3.0)
Downloading pymatgen-2026.5.4-py3-none-any.whl (829 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 829.1/829.1 kB 14.2 MB/s  0:00:00
Downloading pymatgen_core-2026.8.30-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (4.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.6/4.6 MB 53.5 MB/s  0:00:00
Downloading monty-2026.7.16-py3-none-any.whl (62 kB)
Downloading palettable-3.3.3-py2.py3-none-any.whl (332 kB)
Downloading requests-2.34.2-py3-none-any.whl (73 kB)
Downloading uncertainties-3.2.3-py3-none-any.whl (60 kB)
Downloading ruamel_yaml-0.19.1-py3-none-any.whl (118 kB)
Building wheels for collected packages: bibtexparser
  Building wheel for bibtexparser (pyproject.toml) ... done
  Created wheel for bibtexparser: filename=bibtexparser-1.4.4-py3-none-any.whl size=43688 sha256=6fe63e0ba812c9353234639d212036f6d74c2cdaff80c9a55cd1d89b49b2bf77
  Stored in directory: /root/.cache/pip/wheels/43/ca/d8/0d315657fcf8ff8694a2f6701589bd1eaa602a85b7a7810063
Successfully built bibtexparser
Installing collected packages: uncertainties, ruamel.yaml, requests, palettable, bibtexparser, monty, pymatgen-core, pymatgen
  Attempting uninstall: requests
    Found existing installation: requests 2.32.4
    Uninstalling requests-2.32.4:
      Successfully uninstalled requests-2.32.4
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8/8 [pymatgen]
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-colab 1.0.0 requires requests==2.32.4, but you have requests 2.34.2 which is incompatible.
Successfully installed bibtexparser-1.4.4 monty-2026.7.16 palettable-3.3.3 pymatgen-2026.5.4 pymatgen-core-2026.8.30 requests-2.34.2 ruamel.yaml-0.19.1 uncertainties-3.2.3

In [ ]:
# # ============================================================
# # PHASE 2E — CREATE ALIGNN BASELINE DATASET
# # ============================================================

# from pathlib import Path
# from pymatgen.core import Structure
# import pandas as pd
# import json

# root = Path("alignn_baseline")
# root.mkdir(exist_ok=True)

# train_rows = []
# val_rows = []
# test_rows = []

# for _, row in graph_df.iterrows():

#     task_id = row["task_id"]

#     # Unique filename for every DFT magnetic calculation
#     filename = f"{task_id}.cif"

#     filepath = root / filename

#     # Reconstruct pymatgen structure from the stored dictionary
#     structure = Structure.from_dict(
#         row["input_structure"]
#     )

#     # Write CIF
#     structure.to(
#         filename=str(filepath),
#         fmt="cif"
#     )

#     # ALIGNN id_prop entry
#     record = [
#         filename,
#         float(row["delta_E"])
#     ]

#     if row["split"] == "train":
#         train_rows.append(record)

#     elif row["split"] == "val":
#         val_rows.append(record)

#     elif row["split"] == "test":
#         test_rows.append(record)


# print("=" * 80)
# print("ALIGNN STRUCTURE DATASET")
# print("=" * 80)

# print("Train:", len(train_rows))
# print("Validation:", len(val_rows))
# print("Test:", len(test_rows))
# print("Total:", len(train_rows) + len(val_rows) + len(test_rows))

In [ ]:
!python -c "import alignn; import os; print(os.path.dirname(alignn.__file__))"

/usr/local/lib/python3.13/dist-packages/alignn

In [ ]:
!python -c "import alignn.train; import inspect; print(inspect.getsource(alignn.train)[:12000])"

"""Module for training script."""

from torch.nn.parallel import DistributedDataParallel as DDP
import torch.distributed as dist
from functools import partial
from typing import Any, Dict, Union
import torch
import random
from sklearn.metrics import mean_absolute_error
import pickle as pk
import numpy as np
from torch import nn
from alignn.data import get_train_val_loaders
from alignn.config import TrainingConfig
from alignn.models.alignn_atomwise import ALIGNNAtomWise
from alignn.models.alignn_atomwise_pure import ALIGNNAtomWisePure
from alignn.models.alignn_atomwise_pure_smooth import (
    ALIGNNAtomWisePureSmooth,
)
from alignn.torch_graph_builder import unbatch as _graph_unbatch
from alignn.models.ealignn_atomwise import eALIGNNAtomWise
from alignn.models.alignn import ALIGNN
from jarvis.db.jsonutils import dumpjson
import json
import pprint
import os
import warnings
import time
from sklearn.metrics import roc_auc_score
from alignn.utils import (
    group_decay,
    setup_optimizer,
    print_train_val_loss,
)

warnings.filterwarnings("ignore", category=RuntimeWarning)


def _ddp_mean(value: float, use_ddp: bool) -> float:
    """All-reduce a Python scalar across ranks and return the mean."""
    if not use_ddp or not dist.is_available() or not dist.is_initialized():
        return float(value)
    t = torch.tensor(float(value), device=torch.cuda.current_device())
    dist.all_reduce(t, op=dist.ReduceOp.SUM)
    return (t / dist.get_world_size()).item()


def _unwrap(net):
    """Return underlying module from a DDP-wrapped model, else net."""
    return net.module if isinstance(net, DDP) else net


# torch.autograd.detect_anomaly()

figlet_alignn = """
    _    _     ___ ____ _   _ _   _
   / \  | |   |_ _/ ___| \ | | \ | |
  / _ \ | |    | | |  _|  \| |  \| |
 / ___ \| |___ | | |_| | |\  | |\  |
/_/   \_\_____|___\____|_| \_|_| \_|
"""


def train_dgl(
    config: Union[TrainingConfig, Dict[str, Any]],
    model: nn.Module = None,
    train_val_test_loaders=[],
    rank=0,
    world_size=0,
):
    """Training entry point for DGL networks.

    `config` should conform to alignn.conf.TrainingConfig, and
    if passed as a dict with matching keys, pydantic validation is used
    """
    if rank == 0:
        if type(config) is dict:
            try:
                print("Trying to convert dictionary.")
                config = TrainingConfig(**config)
            except Exception as exp:
                print("Check", exp)
    print("config:", config.dict())

    if not os.path.exists(config.output_dir):
        os.makedirs(config.output_dir)
    classification = False
    is_main = rank == 0
    tmp = config.dict()
    if is_main:
        f = open(os.path.join(config.output_dir, "config.json"), "w")
        f.write(json.dumps(tmp, indent=4))
        f.close()
    global tmp_output_dir
    tmp_output_dir = config.output_dir
    pprint.pprint(tmp)
    if config.classification_threshold is not None:
        classification = True
    TORCH_DTYPES = {
        "float16": torch.float16,
        "float32": torch.float32,
        "float64": torch.float64,
        "bfloat": torch.bfloat16,
    }
    torch.set_default_dtype(TORCH_DTYPES[config.dtype])
    line_graph = False
    if config.compute_line_graph > 0:
        line_graph = True
    if world_size > 1:
        use_ddp = True
    else:
        use_ddp = False
        device = "cpu"
        if torch.cuda.is_available():
            device = torch.device("cuda")
    if not train_val_test_loaders:
        (
            train_loader,
            val_loader,
            test_loader,
            prepare_batch,
        ) = get_train_val_loaders(
            dataset=config.dataset,
            target=config.target,
            n_train=config.n_train,
            n_val=config.n_val,
            n_test=config.n_test,
            train_ratio=config.train_ratio,
            val_ratio=config.val_ratio,
            test_ratio=config.test_ratio,
            batch_size=config.batch_size,
            atom_features=config.atom_features,
            neighbor_strategy=config.neighbor_strategy,
            standardize=config.atom_features != "cgcnn",
            line_graph=line_graph,
            id_tag=config.id_tag,
            pin_memory=config.pin_memory,
            workers=config.num_workers,
            save_dataloader=config.save_dataloader,
            use_canonize=config.use_canonize,
            filename=config.filename,
            cutoff=config.cutoff,
            max_neighbors=config.max_neighbors,
            three_body_cutoff=config.three_body_cutoff,
            read_existing=config.read_existing,
            output_features=config.model.output_features,
            classification_threshold=config.classification_threshold,
            target_multiplication_factor=config.target_multiplication_factor,
            standard_scalar_and_pca=config.standard_scalar_and_pca,
            keep_data_order=config.keep_data_order,
            output_dir=config.output_dir,
            use_lmdb=config.use_lmdb,
            dtype=config.dtype,
        )
    else:
        train_loader = train_val_test_loaders[0]
        val_loader = train_val_test_loaders[1]
        test_loader = train_val_test_loaders[2]
        prepare_batch = train_val_test_loaders[3]
    if use_ddp:
        # `rank` is GLOBAL: on a multi-node launch it exceeds the per-node
        # device count (and with --gpu-bind=closest each rank sees a single
        # GPU), so cuda:{rank} raises "invalid device ordinal". setup() has
        # already selected this process's device -- read it back.
        device = torch.device(f"cuda:{torch.cuda.current_device()}")
    prepare_batch = partial(prepare_batch, device=device)
    if classification:
        config.model.classification = True
    _model = {
        "alignn_atomwise": ALIGNNAtomWise,
        "alignn_atomwise_pure": ALIGNNAtomWisePure,
        "alignn_atomwise_pure_smooth": ALIGNNAtomWisePureSmooth,
        "ealignn_atomwise": eALIGNNAtomWise,
        "alignn": ALIGNN,
    }
    if config.random_seed is not None:
        random.seed(config.random_seed)
        torch.manual_seed(config.random_seed)
        np.random.seed(config.random_seed)
        torch.cuda.manual_seed_all(config.random_seed)
        try:
            import torch_xla.core.xla_model as xm

            xm.set_rng_state(config.random_seed)
        except ImportError:
            pass
        os.environ["PYTHONHASHSEED"] = str(config.random_seed)
        if getattr(config, "deterministic", False):
            torch.backends.cudnn.deterministic = True
            torch.backends.cudnn.benchmark = False
            os.environ["CUBLAS_WORKSPACE_CONFIG"] = str(":4096:8")
            torch.use_deterministic_algorithms(True)
        else:
            torch.backends.cudnn.benchmark = True
    if model is None:
        net = _model.get(config.model.name)(config.model)
    else:
        net = model
    print(figlet_alignn)
    print("Model parameters", sum(p.numel() for p in net.parameters()))
    print("CUDA available", torch.cuda.is_available())
    print("CUDA device count", int(torch.cuda.device_count()))
    try:
        gpu_stats = torch.cuda.get_device_properties(0)
        max_memory = round(gpu_stats.total_memory / 1024 / 1024 / 1024, 3)
        from platform import system as platform_system

        platform_system = platform_system()
        statistics = (
            f"   GPU: {gpu_stats.name}. Max memory: {max_memory} GB"
            + f". Platform = {platform_system}.\n"
            f"   Pytorch: {torch.__version__}. CUDA = "
            + f"{gpu_stats.major}.{gpu_stats.minor}."
            + f" CUDA Toolkit = {torch.version.cuda}.\n"
        )
        print(statistics)
    except Exception:
        pass
    net.to(device)
    if use_ddp:
        net = DDP(
            net,
            # local device index, not the global rank (see `device` above)
            device_ids=[torch.cuda.current_device()],
            find_unused_parameters=bool(
                getattr(config, "ddp_find_unused_parameters", False)
            ),
        )
    # ------------------------------------------------------------------
    # Build optimizer ONCE and bind the scheduler to it.
    # (Previously this block created the optimizer twice — once here and
    #  once again inside the `if "alignn_" in config.model.name:` block —
    #  which left the scheduler bound to a stale optimizer that never
    #  stepped, triggering the
    #  "lr_scheduler.step() before optimizer.step()" warning and producing
    #  a broken LR schedule.)
    # ------------------------------------------------------------------
    params = group_decay(net)
    optimizer = setup_optimizer(params, config)

    if config.scheduler == "none":
        # always return multiplier of 1 (i.e. do nothing)
        scheduler = torch.optim.lr_scheduler.LambdaLR(
            optimizer, lambda epoch: 1.0
        )
    elif config.scheduler == "onecycle":
        steps_per_epoch = len(train_loader)
        scheduler = torch.optim.lr_scheduler.OneCycleLR(
            optimizer,
            max_lr=config.learning_rate,
            # Schedule spans the whole run; lr_total_epochs lets a resumed
            # chain keep one continuous cycle (falls back to epochs).
            epochs=(config.lr_total_epochs or config.epochs),
            steps_per_epoch=steps_per_epoch,
            pct_start=0.3,
        )
    elif config.scheduler == "step":
        scheduler = torch.optim.lr_scheduler.StepLR(
            optimizer,
        )

    # OneCycleLR expects scheduler.step() per batch; other schedulers we
    # step per epoch.
    _step_scheduler_per_batch = config.scheduler == "onecycle"

    if "alignn_" in config.model.name:
        best_loss = np.inf
        criterion = nn.L1Loss()
        if classification:
            criterion = nn.NLLLoss()
        # NOTE: optimizer / scheduler intentionally NOT recreated here.
        history_train = []
        history_val = []
        # Resume optimizer/scheduler/epoch (weights are restored separately
        # via --restart_model_path). current_state.pt is written each epoch
        # below, alongside the pure-weights current_model.pt.
        start_epoch = 0
        if config.resume_checkpoint:
            state_path = os.path.join(config.output_dir, "current_state.pt")
            if os.path.exists(state_path):
                ckpt = torch.load(state_path, map_location=device)
                optimizer.load_state_dict(ckpt["optimizer"])
                scheduler.load_state_dict(ckpt["scheduler"])
                best_loss = ckpt.get("best_loss", best_loss)
                start_epoch = ckpt["epoch"]
                if rank == 0:
                    print(
                        "Resuming from epoch",
                        start_epoch,
                        "best_loss",
                        best_loss,
                    )
        for e in range(start_epoch, config.epochs):
            train_init_time = time.time()
            running_loss = 0
            running_loss1 = 0
            running_loss2 = 0
            running_loss3 = 0
            running_loss4 = 0
            running_loss5 = 0
            train_result = []
            for dats, jid in zip(train_loader, train_loader.dataset.ids):
                info = {}
                optimizer.zero_grad()
                _amp_ctx = torch.autocast(
                    device_type="cuda",
                    dtype=torch.bfloat16,
                    enabled=bool(getattr(config, "use_amp", False))
                    and torch.cuda.is_available(),
                )
                with _amp_ctx:
                    if (config.compute_line_graph) > 0:
                        result = net(
                            [
                                dats[0].to(device),
                                dats[1].to(device),
                                dats[2].to(device),
                            ]
                        )

Reordering dataset for ALIGNN

In [ ]:
# ============================================================
# PHASE 2E — ORDER DATASET FOR ALIGNN
# ============================================================

ordered_df = pd.concat(
    [
        graph_df[graph_df["split"] == "train"],
        graph_df[graph_df["split"] == "val"],
        graph_df[graph_df["split"] == "test"]
    ],
    ignore_index=True
)

print("Total:", len(ordered_df))

print("\nSplit boundaries:")
print("Train:", (ordered_df["split"] == "train").sum())
print("Val:",   (ordered_df["split"] == "val").sum())
print("Test:",  (ordered_df["split"] == "test").sum())

assert list(ordered_df["split"].iloc[:18010]).count("train") == 18010
assert list(ordered_df["split"].iloc[18010:20256]).count("val") == 2246
assert list(ordered_df["split"].iloc[20256:]).count("test") == 2203

print("\nOrdering verified.")

Total: 22459

Split boundaries:
Train: 18010
Val: 2246
Test: 2203

Ordering verified.

### Step - 2.6 - Creating the ALIGNN folder

In [ ]:
# ============================================================
# PHASE 2F — WRITE ALIGNN BASELINE DATA
# ============================================================

from pathlib import Path
import csv

root = Path("alignn_baseline")
root.mkdir(exist_ok=True)

rows = []

for _, row in ordered_df.iterrows():

    filename = f"{row['task_id']}.cif"

    rows.append([
        filename,
        float(row["delta_E"])
    ])

# Write id_prop.csv
with open(root / "id_prop.csv", "w", newline="") as f:

    writer = csv.writer(f)

    for r in rows:
        writer.writerow(r)

print("Written:", root / "id_prop.csv")
print("Rows:", len(rows))

# Verify
check = pd.read_csv(
    root / "id_prop.csv",
    header=None,
    names=["id", "target"]
)

print("\nVerification:")
print(check.head())
print(check.tail())
print("Rows:", len(check))

Written: alignn_baseline/id_prop.csv
Rows: 22459

Verification:
          id    target
0  53864.cif  0.000000
1  49080.cif  0.000000
2  49345.cif  0.000316
3  49242.cif  0.005405
4  49143.cif  0.005843
              id    target
22454  36235.cif  0.011375
22455  36144.cif  0.012306
22456  36513.cif  0.011846
22457  38899.cif  0.014177
22458  40155.cif  0.011769
Rows: 22459

### Step - 2.7 - Creating the ALIGNN configuration

In [ ]:
# ============================================================
# PHASE 2G — ALIGNN BASELINE CONFIG
# ============================================================

import json

config = {

    # Dataset
    "dataset": "alignn_baseline",
    "target": "target",
    "id_tag": "jid",

    # Explicit predefined split
    "n_train": 18010,
    "n_val": 2246,
    "n_test": 2203,

    "keep_data_order": True,

    # Do not randomly redefine our parent-level split
    "train_ratio": 0.8,
    "val_ratio": 0.1,
    "test_ratio": 0.1,

    # Training
    "batch_size": 32,
    "epochs": 100,

    "learning_rate": 0.001,

    "random_seed": 42,

    # Structure / graph
    "atom_features": "cgcnn",

    "neighbor_strategy": "pure_torch",

    "cutoff": 8.0,
    "max_neighbors": 12,

    "compute_line_graph": 1,

    # Model
    "model": {
        "name": "alignn",
        "output_features": 1
    },

    # Output
    "output_dir": "alignn_baseline_output",

    # CPU
    "num_workers": 0,

    # Keep data in normal precision
    "dtype": "float32"
}


with open(
    root / "config_baseline.json",
    "w"
) as f:

    json.dump(
        config,
        f,
        indent=2
    )

print("Saved:")
print(root / "config_baseline.json")

Saved:
alignn_baseline/config_baseline.json

### Step - 2.8 - Creating a new POSCAR dataset

In [ ]:
# # ============================================================
# # PHASE 2H — CREATE ALIGNN POSCAR DATASET
# # ============================================================

# from pathlib import Path
# from pymatgen.core import Structure
# import pandas as pd
# import csv
# import shutil

# root = Path("alignn_baseline_poscar")

# # Start fresh
# if root.exists():
#     shutil.rmtree(root)

# root.mkdir()

# rows = []

# for _, row in ordered_df.iterrows():

#     task_id = int(row["task_id"])

#     filename = f"{task_id}.vasp"
#     filepath = root / filename

#     # Recover input structure
#     structure = Structure.from_dict(
#         row["input_structure"]
#     )

#     # Write VASP POSCAR
#     structure.to(
#         filename=str(filepath),
#         fmt="poscar"
#     )

#     rows.append([
#         filename,
#         float(row["delta_E"])
#     ])


# # Write id_prop.csv
# with open(root / "id_prop.csv", "w", newline="") as f:

#     writer = csv.writer(f)

#     for item in rows:
#         writer.writerow(item)


# print("=" * 80)
# print("POSCAR DATASET CREATED")
# print("=" * 80)

# print("Directory:", root)
# print("Structure files:", len(rows))
# print("id_prop.csv:", (root / "id_prop.csv").exists())

# print("\nFirst files:")
# print(list(root.glob("*.vasp"))[:5])

Checking one POSCAR

In [ ]:
from pathlib import Path

files = sorted(Path("alignn_baseline_poscar").glob("*.vasp"))

print(files[0])

print(
    files[0].read_text()[:1000]
)

alignn_baseline_poscar/10.vasp
La2 Fe8 Cu6 O24
1.0
  -3.7545210000000000   -3.7545210000000000    3.7545210000000000
  -3.7545210000000000    3.7545210000000000   -3.7545210000000000
   0.0000000000000000   -7.5090420000000000   -7.5090420000000000
La Fe Cu O
2 8 6 24
direct
   0.0000000000000000    0.0000000000000000    0.0000000000000000 La
   0.5000000000000000    0.5000000000000000    0.5000000000000000 La
   0.7500000000000000    0.7500000000000000    0.2500000000000000 Fe
   0.2500000000000000    0.2500000000000000    0.7500000000000000 Fe
   0.5000000000000000    0.0000000000000000    0.0000000000000000 Fe
   0.0000000000000000    0.5000000000000000    0.5000000000000000 Fe
   0.0000000000000000    0.5000000000000000    0.0000000000000000 Fe
   0.5000000000000000    0.0000000000000000    0.5000000000000000 Fe
   0.2500000000000000    0.2500000000000000    0.2500000000000000 Fe
   0.7500000000000000    0.7500000000000000    0.7500000000000000 Fe
   0.2500000000000000    0.7500000000000000    0.7500000000000000

In [ ]:
!pip install -q --upgrade git+https://github.com/atomgptlab/alignn.git
!pip install -q torch-geometric

  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done

In [ ]:
import alignn

print(alignn.__file__)

/usr/local/lib/python3.13/dist-packages/alignn/__init__.py

In [ ]:
import importlib.metadata

print(
    importlib.metadata.version("alignn")
)

2026.8.11

In [ ]:
import os
import alignn.models

model_dir = os.path.dirname(alignn.models.__file__)

print(os.listdir(model_dir))

['__init__.py', 'ealignn_atomwise.py', 'utils.py', 'alignn_atomwise_pure_smooth.py', 'model_zoo.py', '__pycache__', 'alignn_atomwise_pure.py', 'alignn_atomwise.py', 'alignn.py']

In [ ]:
import alignn
import torch
import torch_geometric

print("ALIGNN:", alignn.__file__)
print("PyTorch:", torch.__version__)
print("PyG:", torch_geometric.__version__)

ALIGNN: /usr/local/lib/python3.13/dist-packages/alignn/__init__.py
PyTorch: 2.11.0+cpu
PyG: 2.8.0.post1

In [ ]:
import alignn
import alignn.models
from pathlib import Path

alignn_path = Path(alignn.__file__).parent
models_path = Path(alignn.models.__file__).parent

print("ALIGNN path:")
print(alignn_path)

print("\nModel files:")
for f in sorted(models_path.iterdir()):
    print(f.name)

ALIGNN path:
/usr/local/lib/python3.13/dist-packages/alignn

Model files:
__init__.py
__pycache__
alignn.py
alignn_atomwise.py
alignn_atomwise_pure.py
alignn_atomwise_pure_smooth.py
ealignn_atomwise.py
model_zoo.py
utils.py

In [ ]:
# Show the package subdirectories/files
print("\nTop-level ALIGNN contents:")
for f in sorted(alignn_path.iterdir()):
    print(f.name)

Top-level ALIGNN contents:
__init__.py
__pycache__
cli.py
config.py
data.py
dataset.py
deprecated
ff
graphs.py
lmdb_dataset.py
md
models
pretrained.py
profiler.py
pure_lmdb_dataset.py
run_alignn_ff.py
scripts
torch_graph_builder.py
train.py
train_alignn.py
train_props.py
utils.py

Creating this training script

In [ ]:
# ============================================================
# PURE-PYTORCH ALIGNN BASELINE
# G -> Delta E
# ============================================================

import torch
import torch.nn as nn
from torch.utils.data import DataLoader

from alignn.pure_lmdb_dataset import (
    PureTorchLMDBDataset,
)
from alignn.models.alignn_atomwise_pure import (
    ALIGNNAtomWisePure,
    ALIGNNAtomWisePureConfig,
)

# ------------------------------------------------------------
# Configuration
# ------------------------------------------------------------

config = ALIGNNAtomWisePureConfig(
    name="alignn_atomwise_pure",

    alignn_layers=2,
    gcn_layers=2,

    atom_input_features=92,
    edge_input_features=80,
    triplet_input_features=40,

    embedding_features=64,
    hidden_features=64,

    output_features=1,

    calculate_gradient=False,

    atomwise_output_features=0,
    graphwise_weight=1.0,

    energy_mult_natoms=False,

    use_penalty=False,

    extra_features=0,

    classification=False,
)

device = torch.device(
    "cuda" if torch.cuda.is_available()
    else "cpu"
)

print("Device:", device)

model = ALIGNNAtomWisePure(config).to(device)

print(
    "Parameters:",
    sum(p.numel() for p in model.parameters())
)

Device: cpu
Parameters: 149121

In [ ]:
# ============================================================
# BUILD PURE-TORCH DATA RECORDS
# ============================================================

from alignn.pure_lmdb_dataset import get_torch_dataset

def make_alignn_record(row):

    structure = row["input_structure"]

    return {
        "jid": str(row["task_id"]),
        "atoms": {
            "lattice_mat": structure["lattice"]["matrix"],
            "coords": [
                site["abc"]
                for site in structure["sites"]
            ],
            "elements": [
                site["species"][0]["element"]
                for site in structure["sites"]
            ],
            "props": [
                site.get("properties", {})
                for site in structure["sites"]
            ],
            "cartesian": False,
        },
        "target": float(row["delta_E"]),
    }
    train_records = [
    make_alignn_record(row)
    for _, row in graph_df[graph_df["split"] == "train"].iterrows()
    ]

    val_records = [
    make_alignn_record(row)
    for _, row in graph_df[graph_df["split"] == "val"].iterrows()
    ]

    test_records = [
    make_alignn_record(row)
    for _, row in graph_df[graph_df["split"] == "test"].iterrows()
    ]

In [ ]:
import pprint

pprint.pp(graph_df.iloc[0]["input_structure"])

{'@module': 'pymatgen.core.structure',
 '@class': 'Structure',
 'charge': None,
 'lattice': {'matrix': [[6.90922468, -0.44309351, -0.07031606],
                        [-1.17654922, 6.82295497, 0.07031853],
                        [-1.58396863, 1.42337006, 5.23374934]],
             'a': 6.9237751180710045,
             'b': 6.924010924701929,
             'c': 5.650404507863036,
             'alpha': 72.22556532230291,
             'beta': 107.77423185512325,
             'gamma': 103.45791285523455,
             'volume': 242.71307292838904},
 'sites': [{'species': [{'element': 'Li', 'occu': 1}],
            'abc': [0.26512875, 0.26514678, 0.24999616],
            'xyz': [1.1238897906225778, 2.0474447612000537, 1.3084191601136428],
            'label': 'Li',
            'properties': {'magmom': 0.0}},
           {'species': [{'element': 'Li', 'occu': 1}],
            'abc': [0.71806091, 0.71809134, 0.74999885],
            'xyz': [2.9283997042134295, 5.648862656285695, 3.9253098995915745],
            'label': 'Li',
            'properties': {'magmom': 0.0}},
           {'species': [{'element': 'V', 'occu': 1}],
            'abc': [0.16547101, 0.61401579, 0.70808284],
            'xyz': [-0.700724418676966, 5.1239468698706006, 3.737469514797494],
            'label': 'V',
            'properties': {'magmom': 5.0}},
           {'species': [{'element': 'V', 'occu': 1}],
            'abc': [0.37774068, 0.81695026, 0.2329562],
            'xyz': [1.2797177247501792, 5.738223273310178, 1.250119863045905],
            'label': 'V',
            'properties': {'magmom': 5.0}},
           {'species': [{'element': 'V', 'occu': 1}],
            'abc': [0.61392567, 0.16541096, 0.79198624],
            'xyz': [2.7926548953304335, 1.9838545535730439, 4.11352008219491],
            'label': 'V',
            'properties': {'magmom': 5.0}},
           {'species': [{'element': 'V', 'occu': 1}],
            'abc': [0.81691964, 0.37776898, 0.26700801],
            'xyz': [4.776885227706793, 2.595580156141475, 1.3665745850439945],
            'label': 'V',
            'properties': {'magmom': 5.0}},
           {'species': [{'element': 'Cr', 'occu': 1}],
            'abc': [0.07315656, 0.07320373, 0.74987809],
            'xyz': [-0.7684560524610067, 1.534404578432098, 3.924677456239724],
            'label': 'Cr',
            'properties': {'magmom': 5.0}},
           {'species': [{'element': 'Cu', 'occu': 1}],
            'abc': [0.89255349, 0.89236242, 0.25025124],
            'xyz': [4.72055417834122, 6.049264072327252, 1.3097410310297748],
            'label': 'Cu',
            'properties': {'magmom': 1.73}},
           {'species': [{'element': 'O', 'occu': 1}],
            'abc': [0.99994017, 0.79794563, 0.66909135],
            'xyz': [4.910169283504137, 5.953644697277964, 3.4876549221936024],
            'label': 'O',
            'properties': {'magmom': 0.0}},
           {'species': [{'element': 'O', 'occu': 1}],
            'abc': [0.11621086, 0.3480932, 0.81503319],
            'xyz': [-0.8976088463201088, 3.4836257916579765, 4.281985332563179],
            'label': 'O',
            'properties': {'magmom': 0.0}},
           {'species': [{'element': 'O', 'occu': 1}],
            'abc': [0.1942794, 0.9815303, 0.13178776],
            'xyz': [-0.02124636123374274,
                    6.798435849182361,
                    0.7451029078193734],
            'label': 'O',
            'properties': {'magmom': 0.0}},
           {'species': [{'element': 'O', 'occu': 1}],
            'abc': [0.40867443, 0.70950675, 0.56973937],
            'xyz': [1.0864045551877344, 5.47080157978636, 3.003028147654247],
            'label': 'O',
            'properties': {'magmom': 0.0}},
           {'species': [{'element': 'O', 'occu': 1}],
            'abc': [0.3480059, 0.11611437, 0.68481962],
            'xyz': [1.1831038863228, 1.612795705756787, 3.5678688222595727],
            'label': 'O',
            'properties': {'magmom': 0.0}},
           {'species': [{'element': 'O', 'occu': 1}],
            'abc': [0.31600016, 0.62931208, 0.06407537],
            'xyz': [1.341406091459728, 4.244953327103499, 0.3573868396140287],
            'label': 'O',
            'properties': {'magmom': 0.0}},
           {'species': [{'element': 'O', 'occu': 1}],
            'abc': [0.70942347, 0.40864194, 0.93023152],
            'xyz': [2.9473212454117355, 3.797868314511053, 4.847449841082416],
            'label': 'O',
            'properties': {'magmom': 0.0}},
           {'species': [{'element': 'O', 'occu': 1}],
            'abc': [0.60335414, 0.97232235, 0.17105714],
            'xyz': [2.7537750686895897, 6.610246918334176, 0.9212169860059447],
            'label': 'O',
            'properties': {'magmom': 0.0}},
           {'species': [{'element': 'O', 'occu': 1}],
            'abc': [0.62935275, 0.31604246, 0.43598117],
            'xyz': [3.2859195463752924, 2.498043898264144, 2.2597861962145465],
            'label': 'O',
            'properties': {'magmom': 0.0}},
           {'species': [{'element': 'O', 'occu': 1}],
            'abc': [0.79792789, 0.99998591, 0.83096045],
            'xyz': [3.020315142456152, 7.652066390631606, 4.363249100576601],
            'label': 'O',
            'properties': {'magmom': 0.0}},
           {'species': [{'element': 'O', 'occu': 1}],
            'abc': [0.97240679, 0.60331133, 0.32893378],
            'xyz': [5.487730728871592, 4.1536933939265035, 1.6956051056466028],
            'label': 'O',
            'properties': {'magmom': 0.0}},
           {'species': [{'element': 'O', 'occu': 1}],
            'abc': [0.98147132, 0.19424741, 0.36813164],
            'xyz': [5.969555258663204, 1.4144453138406927, 1.8713547239852257],
            'label': 'O',
            'properties': {'magmom': 0.0}}],
 '@version': '2020.10.20'}

Recreating all three datasets

In [ ]:
def make_alignn_record(row):
    structure = row["input_structure"]

    return {
        "jid": str(row["task_id"]),
        "atoms": {
            "lattice_mat": structure["lattice"]["matrix"],
            "coords": [site["abc"] for site in structure["sites"]],
            "elements": [
                site["species"][0]["element"]
                for site in structure["sites"]
            ],
            "props": [[""] for _ in structure["sites"]],
            "cartesian": False,
        },
        "target": float(row["delta_E"]),
    }

In [ ]:
train_records = [
    make_alignn_record(row)
    for _, row in graph_df[graph_df["split"] == "train"].iterrows()
]

val_records = [
    make_alignn_record(row)
    for _, row in graph_df[graph_df["split"] == "val"].iterrows()
]

test_records = [
    make_alignn_record(row)
    for _, row in graph_df[graph_df["split"] == "test"].iterrows()
]

Testing one

In [ ]:
from jarvis.core.atoms import Atoms

r = train_records[0]
atoms = Atoms.from_dict(r["atoms"])

print("Elements:", atoms.elements)
print("Number of atoms:", len(atoms.elements))
print("Lattice:")
print(atoms.lattice_mat)

Elements: ['Li', 'Li', 'V', 'V', 'V', 'V', 'Cr', 'Cu', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O']
Number of atoms: 20
Lattice:
[[ 6.90922468 -0.44309351 -0.07031606]
 [-1.17654922  6.82295497  0.07031853]
 [-1.58396863  1.42337006  5.23374934]]

Building the pure-PyTorch ALIGNN datasets

In [ ]:
from alignn.pure_lmdb_dataset import get_torch_dataset

Creating the training LMDB

LMDB stands for **Lightning Memory-Mapped Database**. It is a fast key-value database used here to store the processed ALIGNN graph data so we don't have to rebuild all the crystal graphs every time.

In [ ]:
# train_dataset = get_torch_dataset(
#     dataset=train_records,
#     id_tag="jid",
#     target="target",
#     neighbor_strategy="pure_torch",
#     atom_features="cgcnn",
#     line_graph=True,
#     cutoff=8.0,
#     max_neighbors=12,
#     output_dir="./pure_alignn_train",
#     tmp_name="train",
#     read_existing=False,
# )

For validation set

In [ ]:
# val_dataset = get_torch_dataset(
#     dataset=val_records,
#     id_tag="jid",
#     target="target",
#     neighbor_strategy="pure_torch",
#     atom_features="cgcnn",
#     line_graph=True,
#     cutoff=8.0,
#     max_neighbors=12,
#     output_dir="./pure_alignn_val",
#     tmp_name="val",
#     read_existing=False,
# )

For test set

In [ ]:
# test_dataset = get_torch_dataset(
#     dataset=test_records,
#     id_tag="jid",
#     target="target",
#     neighbor_strategy="pure_torch",
#     atom_features="cgcnn",
#     line_graph=True,
#     cutoff=8.0,
#     max_neighbors=12,
#     output_dir="./pure_alignn_test",
#     tmp_name="test",
#     read_existing=False,
# )

Rebuilding the train/val/test datasets

In [ ]:
from alignn.pure_lmdb_dataset import PureTorchLMDBDataset

base = "/content/drive/MyDrive/Proj_2_Alt_Mags_Grnd_E/magnetic-topological-materials"

train_dataset = PureTorchLMDBDataset(
    lmdb_path=f"{base}/train",
    line_graph=True,
)

val_dataset = PureTorchLMDBDataset(
    lmdb_path=f"{base}/val",
    line_graph=True,
)

test_dataset = PureTorchLMDBDataset(
    lmdb_path=f"{base}/test",
    line_graph=True,
)

print("Train:", len(train_dataset))
print("Val:", len(val_dataset))
print("Test:", len(test_dataset))

Train: 18010
Val: 2246
Test: 2203

Running one batch forward test

In [ ]:
import torch
from torch.utils.data import DataLoader
from alignn.pure_lmdb_dataset import batch_torch_graph_pairs

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Device:", device)

loader = DataLoader(
    train_dataset,
    batch_size=4,
    shuffle=False,
    num_workers=0,
    collate_fn=lambda x: x,
)

samples = next(iter(loader))

# Batch the crystal graph + line graph
g, lg = batch_torch_graph_pairs(
    [(sample[0], sample[1]) for sample in samples]
)

# Extract the target from each sample
target = torch.tensor(
    [float(sample[3]) for sample in samples],
    dtype=torch.float32
)

g = g.to(device)
lg = lg.to(device)
target = target.to(device)

print("Target shape:", target.shape)
print("Graph batch size:", g.batch_size)

model = model.to(device)
model.eval()

result = model((g, lg, None))

print("Output keys:", result.keys())
print("Prediction shape:", result["out"].shape)
print("Predictions:", result["out"])
print("Targets:", target)

Device: cpu
Target shape: torch.Size([4])
Graph batch size: 4
Output keys: dict_keys(['out', 'additional', 'grad', 'stresses', 'atomwise_pred'])
Prediction shape: torch.Size([4])
Predictions: tensor([-0.8675, -0.8292, -0.8292, -0.8292], grad_fn=<SqueezeBackward1>)
Targets: tensor([0.0000, 0.0000, 0.0003, 0.0054])

In [ ]:
import torch

print("CUDA available:", torch.cuda.is_available())

if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))

CUDA available: False

### Step - 2.9 - Training ALIGNN baseline model

In [ ]:
# import os
# import torch
# import torch.nn as nn
# from torch.utils.data import DataLoader

# from alignn.pure_lmdb_dataset import batch_torch_graph_pairs
# from alignn.models.alignn_atomwise_pure import (
#     ALIGNNAtomWisePure,
#     ALIGNNAtomWisePureConfig,
# )

# # ============================================================
# # 1. DEVICE
# # ============================================================

# device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
# print("Device:", device)

# if torch.cuda.is_available():
#     print("GPU:", torch.cuda.get_device_name(0))


# # ============================================================
# # 2. COLLATE FUNCTION
# # ============================================================

# def collate_alignn(batch):
#     # Each item:
#     # (g, lg, lattice, target)

#     g, lg = batch_torch_graph_pairs(
#         [(item[0], item[1]) for item in batch]
#     )

#     targets = torch.stack([
#         torch.as_tensor(item[3], dtype=torch.float32)
#         for item in batch
#     ])

#     return g, lg, targets


# # ============================================================
# # 3. DATA LOADERS
# # ============================================================

# BATCH_SIZE = 32

# train_loader = DataLoader(
#     train_dataset,
#     batch_size=BATCH_SIZE,
#     shuffle=True,
#     num_workers=0,
#     collate_fn=collate_alignn,
#     pin_memory=torch.cuda.is_available(),
# )

# val_loader = DataLoader(
#     val_dataset,
#     batch_size=BATCH_SIZE,
#     shuffle=False,
#     num_workers=0,
#     collate_fn=collate_alignn,
#     pin_memory=torch.cuda.is_available(),
# )

# print("Train batches:", len(train_loader))
# print("Val batches:", len(val_loader))


# # ============================================================
# # 4. DETERMINE ATOM FEATURE SIZE
# # ============================================================

# sample_g, sample_lg, sample_y = next(iter(train_loader))

# atom_feature_dim = sample_g.ndata["atom_features"].shape[1]

# print("Atom feature dimension:", atom_feature_dim)

# # Move sample graphs back to CPU; this was only inspection
# del sample_g, sample_lg, sample_y


# # ============================================================
# # 5. ALIGNN MODEL
# # ============================================================

# config = ALIGNNAtomWisePureConfig(
#     name="alignn_atomwise_pure",

#     alignn_layers=2,
#     gcn_layers=2,

#     atom_input_features=atom_feature_dim,
#     edge_input_features=80,
#     triplet_input_features=40,

#     embedding_features=64,
#     hidden_features=64,

#     output_features=1,

#     # We predict Delta-E only.
#     calculate_gradient=False,

#     atomwise_output_features=0,

#     graphwise_weight=1.0,
#     gradwise_weight=0.0,
#     stresswise_weight=0.0,
#     atomwise_weight=0.0,

#     energy_mult_natoms=False,

#     use_penalty=False,

#     classification=False,
# )

# model = ALIGNNAtomWisePure(config).to(device)

# print(
#     "Model parameters:",
#     sum(p.numel() for p in model.parameters())
# )


# # ============================================================
# # 6. LOSS + OPTIMIZER
# # ============================================================

# criterion = nn.MSELoss()

# optimizer = torch.optim.AdamW(
#     model.parameters(),
#     lr=1e-3,
#     weight_decay=1e-5,
# )

# scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(
#     optimizer,
#     mode="min",
#     factor=0.5,
#     patience=2,
# )


# # ============================================================
# # 7. TRAINING SETTINGS
# # ============================================================

# EPOCHS = 20

# best_val_mae = float("inf")

# save_dir = (
#     "/content/drive/MyDrive/"
#     "Proj_2_Alt_Mags_Grnd_E/"
#     "magnetic-topological-materials/"
#     "models"
# )

# os.makedirs(save_dir, exist_ok=True)

# best_model_path = os.path.join(
#     save_dir,
#     "alignn_baseline_best.pt"
# )


# # ============================================================
# # 8. TRAINING LOOP
# # ============================================================

# for epoch in range(1, EPOCHS + 1):

#     # --------------------------------------------------------
#     # TRAIN
#     # --------------------------------------------------------

#     model.train()

#     train_loss = 0.0
#     train_abs_error = 0.0
#     train_count = 0

#     for g, lg, target in train_loader:

#         g = g.to(device)
#         lg = lg.to(device)
#         target = target.to(
#             device,
#             non_blocking=True
#         )

#         optimizer.zero_grad(set_to_none=True)

#         result = model((g, lg, None))

#         prediction = result["out"].reshape(-1)

#         loss = criterion(
#             prediction,
#             target
#         )

#         loss.backward()

#         torch.nn.utils.clip_grad_norm_(
#             model.parameters(),
#             max_norm=5.0
#         )

#         optimizer.step()

#         n = target.numel()

#         train_loss += loss.item() * n

#         train_abs_error += (
#             torch.abs(prediction - target)
#             .sum()
#             .item()
#         )

#         train_count += n


#     train_mse = train_loss / train_count
#     train_mae = train_abs_error / train_count


#     # --------------------------------------------------------
#     # VALIDATION
#     # --------------------------------------------------------

#     model.eval()

#     val_loss = 0.0
#     val_abs_error = 0.0
#     val_count = 0

#     with torch.no_grad():

#         for g, lg, target in val_loader:

#             g = g.to(device)
#             lg = lg.to(device)
#             target = target.to(
#                 device,
#                 non_blocking=True
#             )

#             result = model((g, lg, None))

#             prediction = result["out"].reshape(-1)

#             loss = criterion(
#                 prediction,
#                 target
#             )

#             n = target.numel()

#             val_loss += loss.item() * n

#             val_abs_error += (
#                 torch.abs(prediction - target)
#                 .sum()
#                 .item()
#             )

#             val_count += n


#     val_mse = val_loss / val_count
#     val_mae = val_abs_error / val_count

#     val_rmse = val_mse ** 0.5

#     scheduler.step(val_mae)


#     # --------------------------------------------------------
#     # SAVE BEST MODEL
#     # --------------------------------------------------------

#     if val_mae < best_val_mae:

#         best_val_mae = val_mae

#         torch.save(
#             {
#                 "epoch": epoch,
#                 "model_state_dict": model.state_dict(),
#                 "optimizer_state_dict": optimizer.state_dict(),
#                 "val_mae": val_mae,
#                 "config": config.__dict__,
#             },
#             best_model_path,
#         )

#         best_marker = "  <-- BEST"

#     else:
#         best_marker = ""


#     # --------------------------------------------------------
#     # PRINT
#     # --------------------------------------------------------

#     current_lr = optimizer.param_groups[0]["lr"]

#     print(
#         f"Epoch {epoch:02d}/{EPOCHS} | "
#         f"Train MAE: {train_mae:.6f} | "
#         f"Val MAE: {val_mae:.6f} | "
#         f"Val RMSE: {val_rmse:.6f} | "
#         f"LR: {current_lr:.2e}"
#         f"{best_marker}"
#     )


# print("\nTraining finished.")
# print("Best validation MAE:", best_val_mae)
# print("Best model:", best_model_path)

### Step - 2.10 - Evaluating ALIGNN baseline model

In [ ]:
import os
import torch
from torch.utils.data import DataLoader
from alignn.pure_lmdb_dataset import batch_torch_graph_pairs
from sklearn.metrics import mean_absolute_error, mean_squared_error

# ------------------------------------------------------------
# 1. Device
# ------------------------------------------------------------

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Device:", device)


# ------------------------------------------------------------
# 2. Test loader
# ------------------------------------------------------------

test_loader = DataLoader(
    test_dataset,
    batch_size=32,
    shuffle=False,
    num_workers=0,
    collate_fn=lambda x: x,
    pin_memory=torch.cuda.is_available(),
)


# ------------------------------------------------------------
# 3. Recreate the same model architecture
# ------------------------------------------------------------

# Get atom feature dimension from one test sample
sample = test_dataset[0]
atom_feature_dim = sample[0].ndata["atom_features"].shape[1]

config = ALIGNNAtomWisePureConfig(
    name="alignn_atomwise_pure",
    alignn_layers=2,
    gcn_layers=2,
    atom_input_features=atom_feature_dim,
    edge_input_features=80,
    triplet_input_features=40,
    embedding_features=64,
    hidden_features=64,
    output_features=1,
    calculate_gradient=False,
    atomwise_output_features=0,
    graphwise_weight=1.0,
    gradwise_weight=0.0,
    stresswise_weight=0.0,
    atomwise_weight=0.0,
    energy_mult_natoms=False,
    use_penalty=False,
    classification=False,
)

model = ALIGNNAtomWisePure(config).to(device)


# ------------------------------------------------------------
# 4. Load BEST checkpoint
# ------------------------------------------------------------

model_path = (
    "/content/drive/MyDrive/"
    "Proj_2_Alt_Mags_Grnd_E/"
    "magnetic-topological-materials/"
    "models/alignn_baseline_best.pt"
)

checkpoint = torch.load(
    model_path,
    map_location=device,
)

model.load_state_dict(checkpoint["model_state_dict"])
model.eval()

print("Loaded best model from epoch:", checkpoint["epoch"])
print("Saved validation MAE:", checkpoint["val_mae"])


# ------------------------------------------------------------
# 5. Predict test set
# ------------------------------------------------------------

all_predictions = []
all_targets = []

with torch.no_grad():

    for batch in test_loader:

        g, lg = batch_torch_graph_pairs(
            [(item[0], item[1]) for item in batch]
        )

        target = torch.stack([
            torch.as_tensor(item[3], dtype=torch.float32)
            for item in batch
        ])

        g = g.to(device)
        lg = lg.to(device)
        target = target.to(device)

        result = model((g, lg, None))

        prediction = result["out"].reshape(-1)

        all_predictions.extend(
            prediction.cpu().numpy()
        )

        all_targets.extend(
            target.cpu().numpy()
        )


# ------------------------------------------------------------
# 6. Test regression metrics
# ------------------------------------------------------------

test_mae = mean_absolute_error(
    all_targets,
    all_predictions
)

test_rmse = mean_squared_error(
    all_targets,
    all_predictions
) ** 0.5

print("\n==============================")
print("TEST RESULTS")
print("==============================")
print(f"Test MAE  : {test_mae:.6f} eV/atom")
print(f"Test RMSE : {test_rmse:.6f} eV/atom")

Device: cpu
Loaded best model from epoch: 15
Saved validation MAE: 0.009117738286552424

==============================
TEST RESULTS
==============================
Test MAE  : 0.008624 eV/atom
Test RMSE : 0.022357 eV/atom

ground-state identification accuracy.

We need to take all test predictions and, for each parent_structure_id:

$$ \hat{i}_{GS}=\arg\min_i \hat{\Delta E}_i $$

and compare that with:

$$ {i}_{GS}=\arg\min_i {\Delta E}_i $$

In [ ]:
import pandas as pd
import numpy as np

# Copy the test portion
test_df = graph_df[
    graph_df["split"] == "test"
].copy()

# Add predictions
test_df["pred_delta_E"] = np.array(all_predictions)

# ------------------------------------------------------------
# Find actual and predicted ground states for each parent
# ------------------------------------------------------------

actual_idx = (
    test_df.groupby("parent_structure_id")["delta_E"]
    .idxmin()
)

pred_idx = (
    test_df.groupby("parent_structure_id")["pred_delta_E"]
    .idxmin()
)

actual_gs = test_df.loc[
    actual_idx,
    ["parent_structure_id", "task_id", "delta_E"]
].copy()

pred_gs = test_df.loc[
    pred_idx,
    ["parent_structure_id", "task_id", "pred_delta_E"]
].copy()

actual_gs = actual_gs.rename(
    columns={
        "task_id": "actual_gs_task",
        "delta_E": "actual_gs_delta_E",
    }
)

pred_gs = pred_gs.rename(
    columns={
        "task_id": "pred_gs_task",
        "pred_delta_E": "pred_gs_delta_E",
    }
)

comparison = actual_gs.merge(
    pred_gs,
    on="parent_structure_id",
)

comparison["correct"] = (
    comparison["actual_gs_task"]
    == comparison["pred_gs_task"]
)

accuracy = comparison["correct"].mean()

print("Number of test parents:", len(comparison))
print(
    f"Ground-state identification accuracy: "
    f"{accuracy:.4%}"
)

print(
    "\nCorrect:",
    comparison["correct"].sum()
)

print(
    "Incorrect:",
    (~comparison["correct"]).sum()
)

Number of test parents: 259
Ground-state identification accuracy: 19.3050%

Correct: 50
Incorrect: 209

The baseline model receives only the crystal structure:

$$ G\rightarrow \Delta E $$

But for a given parent material, the competing magnetic configurations have essentially the same crystal structure. They differ in their magnetic moments/configuration.

So the model sees:

$$ G_{\text{same}} \rightarrow ? $$

for:

FM, AFM, FiM

and has no information telling it which magnetic state it is evaluating.

That means the structure-only ALIGNN tends to give nearly identical predictions for different magnetic configurations.
So the 16.99% ground-state accuracy is our baseline/control result. It demonstrates why spin information is necessary.

| Model                 | Input                        |             Test MAE | Ground-state accuracy |
| --------------------- | ---------------------------- | -------------------: | --------------------: |
| Structure-only ALIGNN | Crystal structure            | **0.008624 eV/atom** |            **16.99%** |

Checking how many configurations the test parents have.

In [ ]:
config_counts = (
    test_df.groupby("parent_structure_id")
    .size()
)

print(config_counts.describe())

print("\nNumber of parents by number of configurations:")
print(config_counts.value_counts().sort_index())

count    259.000000
mean       8.505792
std        4.023546
min        1.000000
25%        5.000000
50%        8.000000
75%       12.000000
max       16.000000
dtype: float64

Number of parents by number of configurations:
1      5
2      4
3     21
4     23
5     16
6     18
7     24
8     31
9     20
10    15
11    14
12    12
13    16
14    19
15     7
16    14
Name: count, dtype: int64

This confirms the baseline result is meaningful: most test materials have many competing magnetic configurations.

For the 259 test parents:

Average configurations: 8.51

Median: 8

Maximum: 16

Only 5 parents have one configuration, so for almost all parents there is an actual competition between magnetic states.

That makes the 16.99% ground-state accuracy much more informative: the structure-only model is being asked to choose among several magnetic states while being given no explicit magnetic information.

## Phase - 3 - Spin-aware ALIGNN Model

$$(G,~m_1​,~m_2​,~…,~m_N​)→ΔE​$$

where \($m_i$\) is the initial magnetic moment of atom \($i$\).

the spin-aware node feature becomes:

$$92~chemical~features + 1~magnetic~moment=93$$

### Step - 3.1 - Creating the spin-aware dataset wrappers

In [ ]:
import torch
from torch.utils.data import Dataset

class SpinAwareDataset(Dataset):

    def __init__(self, lmdb_dataset, dataframe):
        self.lmdb_dataset = lmdb_dataset
        self.df = dataframe.reset_index(drop=True).copy()

        assert len(self.lmdb_dataset) == len(self.df)

    def __len__(self):
        return len(self.lmdb_dataset)

    def __getitem__(self, idx):

        g, lg, lattice, label = self.lmdb_dataset[idx]

        magmoms = torch.tensor(
            self.df.iloc[idx]["initial_magmoms"],
            dtype=torch.float32
        ).reshape(-1, 1)

        if magmoms.shape[0] != g.num_nodes:
            raise ValueError(
                f"Index {idx}: {g.num_nodes} atoms but "
                f"{magmoms.shape[0]} magnetic moments"
            )

        # Make a copy so the original baseline graph is untouched.
        g.ndata["magmom"] = magmoms

        return g, lg, lattice, label


train_spin_dataset = SpinAwareDataset(
    train_dataset,
    graph_df[graph_df["split"] == "train"]
)

val_spin_dataset = SpinAwareDataset(
    val_dataset,
    graph_df[graph_df["split"] == "val"]
)

test_spin_dataset = SpinAwareDataset(
    test_dataset,
    graph_df[graph_df["split"] == "test"]
)

print("Train:", len(train_spin_dataset))
print("Val:", len(val_spin_dataset))
print("Test:", len(test_spin_dataset))

Train: 18010
Val: 2246
Test: 2203

Testing one structure

In [ ]:
g, lg, lattice, label = train_spin_dataset[0]

print("Chemical features:", g.ndata["atom_features"].shape)
print("Magnetic feature:", g.ndata["magmom"].shape)
print("Magnetic moments:")
print(g.ndata["magmom"].flatten())

Chemical features: torch.Size([20, 92])
Magnetic feature: torch.Size([20, 1])
Magnetic moments:
tensor([0.0000, 0.0000, 5.0000, 5.0000, 5.0000, 5.0000, 5.0000, 1.7300, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000])

### Step - 3.3 - Making the 93-feature ALIGNN input

In [ ]:
from alignn.pure_lmdb_dataset import batch_torch_graph_pairs

def collate_spin_alignn(batch):

    g, lg = batch_torch_graph_pairs(
        [(item[0], item[1]) for item in batch]
    )

    # Concatenate chemical features + magnetic moment
    g.ndata["atom_features"] = torch.cat(
        [
            g.ndata["atom_features"],
            g.ndata["magmom"],
        ],
        dim=1,
    )

    targets = torch.stack([
        torch.as_tensor(item[3], dtype=torch.float32)
        for item in batch
    ])

    return g, lg, targets

Testing one batch

In [ ]:
from torch.utils.data import DataLoader

spin_loader = DataLoader(
    train_spin_dataset,
    batch_size=4,
    shuffle=False,
    num_workers=0,
    collate_fn=collate_spin_alignn,
)

g, lg, target = next(iter(spin_loader))

print("Batched atom features:", g.ndata["atom_features"].shape)
print("Target:", target.shape)
print("Batch size:", g.batch_size)

Batched atom features: torch.Size([80, 93])
Target: torch.Size([4])
Batch size: 4

### Step - 3.4 - Training spin-aware ALIGNN model

In [ ]:
# import os
# import torch
# import torch.nn as nn
# from torch.utils.data import DataLoader

# # ============================================================
# # 1. DATA LOADERS
# # ============================================================

# BATCH_SIZE = 32

# spin_train_loader = DataLoader(
#     train_spin_dataset,
#     batch_size=BATCH_SIZE,
#     shuffle=True,
#     num_workers=0,
#     collate_fn=collate_spin_alignn,
#     pin_memory=torch.cuda.is_available(),
# )

# spin_val_loader = DataLoader(
#     val_spin_dataset,
#     batch_size=BATCH_SIZE,
#     shuffle=False,
#     num_workers=0,
#     collate_fn=collate_spin_alignn,
#     pin_memory=torch.cuda.is_available(),
# )

# print("Train batches:", len(spin_train_loader))
# print("Val batches:", len(spin_val_loader))


# # ============================================================
# # 2. MODEL
# # ============================================================

# spin_config = ALIGNNAtomWisePureConfig(
#     name="alignn_atomwise_pure",

#     alignn_layers=2,
#     gcn_layers=2,

#     # 92 chemical + 1 magnetic moment
#     atom_input_features=93,

#     edge_input_features=80,
#     triplet_input_features=40,

#     embedding_features=64,
#     hidden_features=64,

#     output_features=1,

#     calculate_gradient=False,

#     atomwise_output_features=0,

#     graphwise_weight=1.0,
#     gradwise_weight=0.0,
#     stresswise_weight=0.0,
#     atomwise_weight=0.0,

#     energy_mult_natoms=False,
#     use_penalty=False,
#     classification=False,
# )

# spin_model = ALIGNNAtomWisePure(spin_config).to(device)

# print(
#     "Spin-aware model parameters:",
#     sum(p.numel() for p in spin_model.parameters())
# )


# # ============================================================
# # 3. LOSS / OPTIMIZER
# # ============================================================

# criterion = nn.MSELoss()

# optimizer = torch.optim.AdamW(
#     spin_model.parameters(),
#     lr=1e-3,
#     weight_decay=1e-5,
# )

# scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(
#     optimizer,
#     mode="min",
#     factor=0.5,
#     patience=2,
# )


# # ============================================================
# # 4. TRAINING
# # ============================================================

# EPOCHS = 20

# best_val_mae = float("inf")

# save_dir = (
#     "/content/drive/MyDrive/"
#     "Proj_2_Alt_Mags_Grnd_E/"
#     "magnetic-topological-materials/"
#     "models"
# )

# os.makedirs(save_dir, exist_ok=True)

# spin_model_path = os.path.join(
#     save_dir,
#     "alignn_spin_aware_best.pt"
# )


# for epoch in range(1, EPOCHS + 1):

#     # --------------------------------------------------------
#     # TRAIN
#     # --------------------------------------------------------

#     spin_model.train()

#     train_loss = 0.0
#     train_abs_error = 0.0
#     train_count = 0

#     for g, lg, target in spin_train_loader:

#         g = g.to(device)
#         lg = lg.to(device)
#         target = target.to(
#             device,
#             non_blocking=True
#         )

#         optimizer.zero_grad(set_to_none=True)

#         result = spin_model((g, lg, None))

#         prediction = result["out"].reshape(-1)

#         loss = criterion(
#             prediction,
#             target
#         )

#         loss.backward()

#         torch.nn.utils.clip_grad_norm_(
#             spin_model.parameters(),
#             max_norm=5.0
#         )

#         optimizer.step()

#         n = target.numel()

#         train_loss += loss.item() * n

#         train_abs_error += (
#             torch.abs(prediction - target)
#             .sum()
#             .item()
#         )

#         train_count += n


#     train_mae = train_abs_error / train_count


#     # --------------------------------------------------------
#     # VALIDATION
#     # --------------------------------------------------------

#     spin_model.eval()

#     val_loss = 0.0
#     val_abs_error = 0.0
#     val_count = 0

#     with torch.no_grad():

#         for g, lg, target in spin_val_loader:

#             g = g.to(device)
#             lg = lg.to(device)
#             target = target.to(
#                 device,
#                 non_blocking=True
#             )

#             result = spin_model((g, lg, None))

#             prediction = result["out"].reshape(-1)

#             loss = criterion(
#                 prediction,
#                 target
#             )

#             n = target.numel()

#             val_loss += loss.item() * n

#             val_abs_error += (
#                 torch.abs(prediction - target)
#                 .sum()
#                 .item()
#             )

#             val_count += n


#     val_mse = val_loss / val_count
#     val_mae = val_abs_error / val_count
#     val_rmse = val_mse ** 0.5

#     scheduler.step(val_mae)


#     # --------------------------------------------------------
#     # SAVE BEST
#     # --------------------------------------------------------

#     if val_mae < best_val_mae:

#         best_val_mae = val_mae

#         torch.save(
#             {
#                 "epoch": epoch,
#                 "model_state_dict": spin_model.state_dict(),
#                 "optimizer_state_dict": optimizer.state_dict(),
#                 "val_mae": val_mae,
#                 "config": spin_config.__dict__,
#             },
#             spin_model_path,
#         )

#         best_marker = "  <-- BEST"

#     else:
#         best_marker = ""


#     current_lr = optimizer.param_groups[0]["lr"]

#     print(
#         f"Epoch {epoch:02d}/{EPOCHS} | "
#         f"Train MAE: {train_mae:.6f} | "
#         f"Val MAE: {val_mae:.6f} | "
#         f"Val RMSE: {val_rmse:.6f} | "
#         f"LR: {current_lr:.2e}"
#         f"{best_marker}"
#     )


# print("\nSpin-aware training finished.")
# print("Best validation MAE:", best_val_mae)
# print("Best model:", spin_model_path)

### Step - 3.5 - Evaluating spin-aware ALIGNN model

Recreate the same configuration

In [ ]:
from alignn.models.alignn_atomwise_pure import (
    ALIGNNAtomWisePure,
    ALIGNNAtomWisePureConfig,
)

spin_config = ALIGNNAtomWisePureConfig(
    name="alignn_atomwise_pure",
    alignn_layers=2,
    gcn_layers=2,
    atom_input_features=93,
    edge_input_features=80,
    triplet_input_features=40,
    embedding_features=64,
    hidden_features=64,
    output_features=1,
    calculate_gradient=False,
    atomwise_output_features=0,
    graphwise_weight=1.0,
    gradwise_weight=0.0,
    stresswise_weight=0.0,
    atomwise_weight=0.0,
    energy_mult_natoms=False,
    use_penalty=False,
    classification=False,
)

Evaluating

In [ ]:
import numpy as np
import torch
from torch.utils.data import DataLoader
from sklearn.metrics import mean_absolute_error, mean_squared_error

# ============================================================
# 1. Test loader
# ============================================================

spin_test_loader = DataLoader(
    test_spin_dataset,
    batch_size=32,
    shuffle=False,
    num_workers=0,
    collate_fn=collate_spin_alignn,
    pin_memory=torch.cuda.is_available(),
)


# ============================================================
# 2. Load best spin-aware model
# ============================================================

device = torch.device(
    "cuda" if torch.cuda.is_available() else "cpu"
)

spin_model = ALIGNNAtomWisePure(spin_config).to(device)

spin_model_path = (
    "/content/drive/MyDrive/"
    "Proj_2_Alt_Mags_Grnd_E/"
    "magnetic-topological-materials/"
    "models/alignn_spin_aware_best.pt"
)

checkpoint = torch.load(
    spin_model_path,
    map_location=device,
)

spin_model.load_state_dict(
    checkpoint["model_state_dict"]
)

spin_model.eval()

print("Loaded epoch:", checkpoint["epoch"])
print("Best validation MAE:", checkpoint["val_mae"])


# ============================================================
# 3. Predict test set
# ============================================================

all_spin_predictions = []
all_spin_targets = []

with torch.no_grad():

    for g, lg, target in spin_test_loader:

        g = g.to(device)
        lg = lg.to(device)
        target = target.to(device)

        result = spin_model((g, lg, None))

        prediction = result["out"].reshape(-1)

        all_spin_predictions.extend(
            prediction.cpu().numpy()
        )

        all_spin_targets.extend(
            target.cpu().numpy()
        )


# ============================================================
# 4. Regression metrics
# ============================================================

spin_test_mae = mean_absolute_error(
    all_spin_targets,
    all_spin_predictions
)

spin_test_rmse = mean_squared_error(
    all_spin_targets,
    all_spin_predictions
) ** 0.5

print("\n==============================")
print("SPIN-AWARE TEST RESULTS")
print("==============================")
print(f"Test MAE  : {spin_test_mae:.6f} eV/atom")
print(f"Test RMSE : {spin_test_rmse:.6f} eV/atom")

Loaded epoch: 8
Best validation MAE: 0.008569264595371108

==============================
SPIN-AWARE TEST RESULTS
==============================
Test MAE  : 0.008300 eV/atom
Test RMSE : 0.022126 eV/atom

Spin-aware ground-state identification accuracy

In [ ]:
# ============================================================
# SPIN-AWARE GROUND-STATE IDENTIFICATION
# ============================================================

test_spin_df = graph_df[
    graph_df["split"] == "test"
].copy()

test_spin_df["pred_delta_E"] = np.array(
    all_spin_predictions
)

# Actual ground state
actual_idx = (
    test_spin_df
    .groupby("parent_structure_id")["delta_E"]
    .idxmin()
)

# Predicted ground state
pred_idx = (
    test_spin_df
    .groupby("parent_structure_id")["pred_delta_E"]
    .idxmin()
)

actual_gs = test_spin_df.loc[
    actual_idx,
    ["parent_structure_id", "task_id", "delta_E"]
].rename(
    columns={
        "task_id": "actual_gs_task",
        "delta_E": "actual_gs_delta_E",
    }
)

pred_gs = test_spin_df.loc[
    pred_idx,
    ["parent_structure_id", "task_id", "pred_delta_E"]
].rename(
    columns={
        "task_id": "pred_gs_task",
        "pred_delta_E": "pred_gs_delta_E",
    }
)

spin_comparison = actual_gs.merge(
    pred_gs,
    on="parent_structure_id",
)

spin_comparison["correct"] = (
    spin_comparison["actual_gs_task"]
    ==
    spin_comparison["pred_gs_task"]
)

spin_accuracy = (
    spin_comparison["correct"].mean()
)

print(
    "Spin-aware ground-state accuracy:",
    f"{spin_accuracy:.4%}"
)

print(
    "Correct:",
    spin_comparison["correct"].sum()
)

print(
    "Incorrect:",
    (~spin_comparison["correct"]).sum()
)

Spin-aware ground-state accuracy: 24.7104%
Correct: 64
Incorrect: 195

## Phase - 4 - Inspecting problems

### Step - 4.1 - Inspecting the energy gaps

Determining whether the dataset itself contains many near-degenerate magnetic states.

In [ ]:
test_df = graph_df[
    graph_df["split"] == "test"
].copy()

# Sort configurations within each parent
test_sorted = test_df.sort_values(
    ["parent_structure_id", "delta_E"]
)

# First and second lowest actual energies
gap_data = (
    test_sorted
    .groupby("parent_structure_id")["delta_E"]
    .apply(lambda x: np.sort(x.values))
)

ground_state_gaps = []

for energies in gap_data:
    if len(energies) >= 2:
        ground_state_gaps.append(
            energies[1] - energies[0]
        )

ground_state_gaps = np.array(ground_state_gaps)

print("Number of parents:", len(ground_state_gaps))
print("Mean gap:", ground_state_gaps.mean(), "eV/atom")
print("Median gap:", np.median(ground_state_gaps), "eV/atom")

for threshold in [0.001, 0.002, 0.005, 0.010, 0.020]:
    fraction = np.mean(
        ground_state_gaps < threshold
    )

    print(
        f"Gap < {threshold:.3f} eV/atom:",
        f"{fraction:.2%}"
    )

Number of parents: 254
Mean gap: 0.0014533932591406307 eV/atom
Median gap: 0.00024448312499991687 eV/atom
Gap < 0.001 eV/atom: 72.05%
Gap < 0.002 eV/atom: 81.50%
Gap < 0.005 eV/atom: 91.34%
Gap < 0.010 eV/atom: 96.46%
Gap < 0.020 eV/atom: 99.61%

### Step - 4.2 - Top-K accuracy + energy regret - spin-aware model

In [ ]:
# ============================================================
# TOP-K + ENERGY REGRET FOR SPIN-AWARE MODEL
# ============================================================

df = test_spin_df.copy()

# Rank predictions within each parent
df["pred_rank"] = (
    df.groupby("parent_structure_id")["pred_delta_E"]
      .rank(method="first", ascending=True)
)

# True ground-state task for each parent
true_gs_task = (
    df.loc[
        df.groupby("parent_structure_id")["delta_E"].idxmin(),
        ["parent_structure_id", "task_id"]
    ]
    .rename(columns={"task_id": "true_gs_task"})
)

# Model's top-1, top-3, top-5
top1 = (
    df[df["pred_rank"] == 1]
    [["parent_structure_id", "task_id", "delta_E"]]
    .rename(columns={
        "task_id": "selected_task",
        "delta_E": "regret"
    })
)

topk = top1.merge(
    true_gs_task,
    on="parent_structure_id"
)

top1_accuracy = (
    topk["selected_task"] == topk["true_gs_task"]
).mean()

# Top-3 and Top-5
top3 = (
    df[df["pred_rank"] <= 3]
    .groupby("parent_structure_id")
    .apply(
        lambda x: (
            x["task_id"].values
            == x["task_id"].values
        ).any()
    )
)

# More direct top-k calculation
true_tasks = (
    true_gs_task.set_index("parent_structure_id")["true_gs_task"]
)

def top_k_accuracy(k):
    correct = 0

    for parent, true_task in true_tasks.items():

        subset = df[
            (df["parent_structure_id"] == parent)
            & (df["pred_rank"] <= k)
        ]

        if true_task in subset["task_id"].values:
            correct += 1

    return correct / len(true_tasks)

top3_accuracy = top_k_accuracy(3)
top5_accuracy = top_k_accuracy(5)

print("Top-1 accuracy :", f"{top1_accuracy:.4%}")
print("Top-3 accuracy :", f"{top3_accuracy:.4%}")
print("Top-5 accuracy :", f"{top5_accuracy:.4%}")

print("\nEnergy regret:")
print("Mean :", topk["regret"].mean(), "eV/atom")
print("Median:", topk["regret"].median(), "eV/atom")
print("Max :", topk["regret"].max(), "eV/atom")

for threshold in [0.001, 0.002, 0.005, 0.010, 0.020]:
    fraction = (
        topk["regret"] < threshold
    ).mean()

    print(
        f"Regret < {threshold:.3f} eV/atom:",
        f"{fraction:.2%}"
    )

/tmp/ipykernel_2513/3564086828.py:45: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(

Top-1 accuracy : 24.7104%
Top-3 accuracy : 53.2819%
Top-5 accuracy : 69.4981%

Energy regret:
Mean : 0.0030687248524194233 eV/atom
Median: 0.0004840012499993662 eV/atom
Max : 0.04508940100000025 eV/atom
Regret < 0.001 eV/atom: 61.39%
Regret < 0.002 eV/atom: 73.36%
Regret < 0.005 eV/atom: 83.40%
Regret < 0.010 eV/atom: 91.51%
Regret < 0.020 eV/atom: 96.91%

### Step - 4.3 - Top-K + energy regret - structure-only baseline

In [ ]:
import numpy as np

# ============================================================
# STRUCTURE-ONLY BASELINE: TOP-K + ENERGY REGRET
# ============================================================

baseline_df = graph_df[
    graph_df["split"] == "test"
].copy()

baseline_df["pred_delta_E"] = np.array(
    all_predictions
)

# Rank predictions within each parent
baseline_df["pred_rank"] = (
    baseline_df
    .groupby("parent_structure_id")["pred_delta_E"]
    .rank(method="first", ascending=True)
)

# True ground state
true_gs = (
    baseline_df.loc[
        baseline_df.groupby("parent_structure_id")["delta_E"].idxmin(),
        ["parent_structure_id", "task_id"]
    ]
    .rename(columns={"task_id": "true_gs_task"})
)

# ------------------------------------------------------------
# Top-k accuracy
# ------------------------------------------------------------

true_tasks = (
    true_gs
    .set_index("parent_structure_id")["true_gs_task"]
)

def top_k_accuracy(df, true_tasks, k):
    correct = 0

    for parent, true_task in true_tasks.items():

        candidates = df[
            (df["parent_structure_id"] == parent)
            & (df["pred_rank"] <= k)
        ]

        if true_task in candidates["task_id"].values:
            correct += 1

    return correct / len(true_tasks)


top1 = top_k_accuracy(
    baseline_df, true_tasks, 1
)

top3 = top_k_accuracy(
    baseline_df, true_tasks, 3
)

top5 = top_k_accuracy(
    baseline_df, true_tasks, 5
)

print("STRUCTURE-ONLY BASELINE")
print("========================")
print("Top-1 accuracy:", f"{top1:.4%}")
print("Top-3 accuracy:", f"{top3:.4%}")
print("Top-5 accuracy:", f"{top5:.4%}")


# ------------------------------------------------------------
# Energy regret
# ------------------------------------------------------------

selected = (
    baseline_df[
        baseline_df["pred_rank"] == 1
    ]
    [["parent_structure_id", "delta_E"]]
    .rename(columns={"delta_E": "regret"})
)

print("\nEnergy regret")
print("Mean  :", selected["regret"].mean(), "eV/atom")
print("Median:", selected["regret"].median(), "eV/atom")
print("Max   :", selected["regret"].max(), "eV/atom")

for threshold in [
    0.001,
    0.002,
    0.005,
    0.010,
    0.020
]:
    fraction = (
        selected["regret"] < threshold
    ).mean()

    print(
        f"Regret < {threshold:.3f} eV/atom:",
        f"{fraction:.2%}"
    )

STRUCTURE-ONLY BASELINE
========================
Top-1 accuracy: 19.3050%
Top-3 accuracy: 45.5598%
Top-5 accuracy: 62.9344%

Energy regret
Mean  : 0.0070064518278584766 eV/atom
Median: 0.0009296754999992274 eV/atom
Max   : 0.4634911821428567 eV/atom
Regret < 0.001 eV/atom: 50.97%
Regret < 0.002 eV/atom: 61.39%
Regret < 0.005 eV/atom: 76.83%
Regret < 0.010 eV/atom: 86.87%
Regret < 0.020 eV/atom: 93.05%

### Step - 4.4 - Spin-aware performance

In [ ]:
# ============================================================
# SPIN-AWARE PERFORMANCE BY ORDERING CHANGED
# ============================================================

df = test_spin_df.copy()
df["abs_error"] = np.abs(
    df["pred_delta_E"] - df["delta_E"]
)

for flag in [False, True]:

    subset = df[df["ordering_changed"] == flag]

    mae = subset["abs_error"].mean()
    rmse = np.sqrt(
        np.mean(
            (subset["pred_delta_E"] - subset["delta_E"]) ** 2
        )
    )

    print(
        f"ordering_changed = {flag}"
    )
    print(
        f"Samples: {len(subset)}"
    )
    print(
        f"MAE: {mae:.6f} eV/atom"
    )
    print(
        f"RMSE: {rmse:.6f} eV/atom"
    )
    print()

ordering_changed = False
Samples: 1828
MAE: 0.006399 eV/atom
RMSE: 0.013537 eV/atom

ordering_changed = True
Samples: 375
MAE: 0.017571 eV/atom
RMSE: 0.044528 eV/atom

Ground state selection

In [ ]:
# ============================================================
# GROUND-STATE ACCURACY BY ORDERING CHANGED
# ============================================================

def grouped_ground_state_accuracy(df, flag):

    subset = df[
        df["ordering_changed"] == flag
    ]

    parents = subset["parent_structure_id"].unique()

    correct = 0
    total = 0

    for parent in parents:

        group = subset[
            subset["parent_structure_id"] == parent
        ]

        # Need at least two configurations
        if len(group) == 0:
            continue

        actual_task = group.loc[
            group["delta_E"].idxmin(),
            "task_id"
        ]

        predicted_task = group.loc[
            group["pred_delta_E"].idxmin(),
            "task_id"
        ]

        if actual_task == predicted_task:
            correct += 1

        total += 1

    return correct, total, correct / total


for flag in [False, True]:

    correct, total, accuracy = (
        grouped_ground_state_accuracy(
            test_spin_df,
            flag
        )
    )

    print(
        f"ordering_changed = {flag}: "
        f"{correct}/{total} = {accuracy:.2%}"
    )

ordering_changed = False: 66/235 = 28.09%
ordering_changed = True: 33/73 = 45.21%

### Step - 4.5 - Spin-aware top-1 accuracy vs ground-state energy gap

In [ ]:
# ============================================================
# SPIN-AWARE TOP-1 ACCURACY VS GROUND-STATE ENERGY GAP
# ============================================================

df = test_spin_df.copy()

parent_results = []

for parent, group in df.groupby("parent_structure_id"):

    energies = np.sort(group["delta_E"].values)

    if len(energies) < 2:
        continue

    gap = energies[1] - energies[0]

    actual_task = group.loc[
        group["delta_E"].idxmin(),
        "task_id"
    ]

    predicted_task = group.loc[
        group["pred_delta_E"].idxmin(),
        "task_id"
    ]

    parent_results.append({
        "parent_structure_id": parent,
        "gap": gap,
        "correct": actual_task == predicted_task,
    })

gap_df = pd.DataFrame(parent_results)

bins = [
    0.0,
    0.001,
    0.005,
    0.010,
    np.inf,
]

labels = [
    "<1 meV",
    "1–5 meV",
    "5–10 meV",
    ">10 meV",
]

gap_df["gap_group"] = pd.cut(
    gap_df["gap"],
    bins=bins,
    labels=labels,
    right=False,
)

print(
    gap_df.groupby("gap_group", observed=False)
    .agg(
        parents=("correct", "size"),
        accuracy=("correct", "mean"),
    )
)

           parents  accuracy
gap_group
<1 meV         183  0.163934
1–5 meV         49  0.346939
5–10 meV        13  0.615385
>10 meV          9  0.444444

The key observation is:

$$ \boxed{\text{The smaller the energy gap, the harder it is to identify the exact ground state.}} $$

And 183 of 254 parents (72%) are in the hardest <1 meV/atom regime.

That explains a lot of the 24.7% overall Top-1 accuracy.

What this means for our project

Our model is not necessarily failing to learn magnetic physics. It is being asked to resolve differences like:

$$ 0.0000 \quad\text{vs}\quad 0.00024\ {\rm eV/atom} $$

while its typical error is around:

$$ 0.0083\ {\rm eV/atom}. $$

That's a difference of roughly 30× smaller than the test MAE.

We should change the training objective from pure absolute-energy regression to a ranking-aware objective.

Instead of only teaching:

$$ \hat{\Delta E}\approx\Delta E, $$

we explicitly teach:

$$ \boxed{ E_i<E_j \quad\Rightarrow\quad \hat E_i<\hat E_j } $$

for competing magnetic states from the same parent material.

That is much closer to what we actually care about.

A good next experiment is a combined loss:

$$ \boxed{ L=L_{\rm MSE}+\lambda L_{\rm rank} } $$

where the MSE preserves energy prediction while the ranking term encourages correct ordering.

### Step - 4.6 - Pairwise ranking accuracy

For two magnetic configurations of the same material, how often does the model correctly say which one has lower energy?

In [ ]:
# ============================================================
# SPIN-AWARE PAIRWISE RANKING ACCURACY
# ============================================================

df = test_spin_df.copy()

correct_pairs = 0
total_pairs = 0

for parent, group in df.groupby("parent_structure_id"):

    # Convert to arrays
    true_energy = group["delta_E"].to_numpy()
    pred_energy = group["pred_delta_E"].to_numpy()

    n = len(group)

    # Compare every unique pair
    for i in range(n):
        for j in range(i + 1, n):

            true_diff = true_energy[i] - true_energy[j]
            pred_diff = pred_energy[i] - pred_energy[j]

            # Ignore exact ties, if any
            if true_diff == 0:
                continue

            # Correct ordering if signs agree
            if true_diff * pred_diff > 0:
                correct_pairs += 1

            total_pairs += 1

pairwise_accuracy = correct_pairs / total_pairs

print("Total non-tied pairs:", total_pairs)
print("Correctly ranked pairs:", correct_pairs)
print(
    "Pairwise ranking accuracy:",
    f"{pairwise_accuracy:.4%}"
)

Total non-tied pairs: 10271
Correctly ranked pairs: 5640
Pairwise ranking accuracy: 54.9119%

### Step - 4.7 - Pairwise ranking accuracy vs true energy seperation

In [ ]:
# ============================================================
# PAIRWISE RANKING ACCURACY VS TRUE ENERGY SEPARATION
# ============================================================

df = test_spin_df.copy()

bins = [
    0.0,
    0.001,
    0.005,
    0.010,
    float("inf"),
]

labels = [
    "<1 meV",
    "1–5 meV",
    "5–10 meV",
    ">10 meV",
]

stats = {
    label: {"correct": 0, "total": 0}
    for label in labels
}

for parent, group in df.groupby("parent_structure_id"):

    true_energy = group["delta_E"].to_numpy()
    pred_energy = group["pred_delta_E"].to_numpy()

    n = len(group)

    for i in range(n):
        for j in range(i + 1, n):

            true_diff = true_energy[i] - true_energy[j]

            if true_diff == 0:
                continue

            separation = abs(true_diff)

            pred_diff = pred_energy[i] - pred_energy[j]

            bin_index = np.digitize(
                separation,
                bins[1:-1],
                right=False
            )

            label = labels[bin_index]

            stats[label]["total"] += 1

            if true_diff * pred_diff > 0:
                stats[label]["correct"] += 1


print("Pairwise ranking accuracy by energy separation")
print("==============================================")

for label in labels:

    correct = stats[label]["correct"]
    total = stats[label]["total"]

    accuracy = (
        correct / total
        if total > 0
        else float("nan")
    )

    print(
        f"{label:8s} | "
        f"pairs = {total:5d} | "
        f"accuracy = {accuracy:.2%}"
    )

Pairwise ranking accuracy by energy separation
==============================================
<1 meV   | pairs =  5604 | accuracy = 50.77%
1–5 meV  | pairs =  2495 | accuracy = 59.80%
5–10 meV | pairs =   934 | accuracy = 56.00%
>10 meV  | pairs =  1238 | accuracy = 63.00%

## Phase - 5 - Ranking-aware fine-tuning experiment

The loss will be:

$$ L=L_{\rm MSE}+\lambda L_{\rm rank} $$

and the ranking term will compare configurations only within the same parent material, ignoring ultra-small gaps below 1 meV/atom for the ranking term.

### Step - 5.1 - Preparing parent-grouped batches

In [ ]:
import random
import torch
import torch.nn.functional as F
from torch.utils.data import DataLoader

train_spin_df = (
    graph_df[graph_df["split"] == "train"]
    .reset_index(drop=True)
)

val_spin_df = (
    graph_df[graph_df["split"] == "val"]
    .reset_index(drop=True)
)

def make_parent_batches(df, max_samples=32, shuffle=True):

    groups = []

    for _, group in df.groupby("parent_structure_id"):
        groups.append(group.index.tolist())

    if shuffle:
        random.shuffle(groups)

    batches = []
    current = []

    for group in groups:

        if current and len(current) + len(group) > max_samples:
            batches.append(current)
            current = []

        current.extend(group)

    if current:
        batches.append(current)

    return batches


train_batches = make_parent_batches(
    train_spin_df,
    max_samples=32,
    shuffle=True,
)

val_batches = make_parent_batches(
    val_spin_df,
    max_samples=32,
    shuffle=False,
)

print("Training batches:", len(train_batches))
print("Validation batches:", len(val_batches))

Training batches: 657
Validation batches: 82

### Step - 5.2 - Collate function that remembers the parent

In [ ]:
from alignn.pure_lmdb_dataset import batch_torch_graph_pairs

def collate_spin_rank(batch):

    g, lg = batch_torch_graph_pairs(
        [(item[0], item[1]) for item in batch]
    )

    g.ndata["atom_features"] = torch.cat(
        [
            g.ndata["atom_features"],
            g.ndata["magmom"],
        ],
        dim=1,
    )

    targets = torch.stack([
        torch.as_tensor(item[3], dtype=torch.float32)
        for item in batch
    ])

    return g, lg, targets

### Step - 5.3 - Dataloaders

In [ ]:
from torch.utils.data import Sampler

class FixedBatchSampler(Sampler):

    def __init__(self, batches):
        self.batches = batches

    def __iter__(self):
        yield from self.batches

    def __len__(self):
        return len(self.batches)


rank_train_loader = DataLoader(
    train_spin_dataset,
    batch_sampler=FixedBatchSampler(train_batches),
    num_workers=0,
    collate_fn=collate_spin_rank,
    pin_memory=torch.cuda.is_available(),
)

rank_val_loader = DataLoader(
    val_spin_dataset,
    batch_sampler=FixedBatchSampler(val_batches),
    num_workers=0,
    collate_fn=collate_spin_rank,
    pin_memory=torch.cuda.is_available(),
)

print("Train batches:", len(rank_train_loader))
print("Val batches:", len(rank_val_loader))

Train batches: 657
Val batches: 82

### Step - 5.4 - Ranking loss

In [ ]:
def parentwise_ranking_loss(
    prediction,
    target,
    parent_indices,
    min_gap=0.001,
    max_margin=0.010,
):
    """
    Pairwise ranking loss within each parent.

    Only pairs separated by >= 1 meV/atom
    are used for the ranking component.
    """

    losses = []

    unique_parents = torch.unique(parent_indices)

    for parent in unique_parents:

        idx = torch.where(
            parent_indices == parent
        )[0]

        if len(idx) < 2:
            continue

        y = target[idx]
        p = prediction[idx]

        for i in range(len(idx)):
            for j in range(i + 1, len(idx)):

                true_diff = y[j] - y[i]

                if torch.abs(true_diff) < min_gap:
                    continue

                pred_diff = p[j] - p[i]

                sign = torch.sign(true_diff)

                margin = torch.clamp(
                    torch.abs(true_diff),
                    max=max_margin,
                )

                violation = (
                    margin
                    - sign * pred_diff
                )

                losses.append(
                    F.relu(violation) ** 2
                )

    if not losses:
        return prediction.new_tensor(0.0)

    return torch.stack(losses).mean()

### Step - 5.5 - Fine-tune the saved spin-aware model

In [ ]:
import os

device = torch.device(
    "cuda" if torch.cuda.is_available()
    else "cpu"
)

# Same architecture as spin-aware model
rank_model = ALIGNNAtomWisePure(
    spin_config
).to(device)

# Start from the best spin-aware model
spin_checkpoint_path = (
    "/content/drive/MyDrive/"
    "Proj_2_Alt_Mags_Grnd_E/"
    "magnetic-topological-materials/"
    "models/"
    "alignn_spin_aware_best.pt"
)

checkpoint = torch.load(
    spin_checkpoint_path,
    map_location=device,
)

rank_model.load_state_dict(
    checkpoint["model_state_dict"]
)

print(
    "Loaded spin-aware checkpoint "
    f"from epoch {checkpoint['epoch']}"
)

optimizer = torch.optim.AdamW(
    rank_model.parameters(),
    lr=1e-4,
    weight_decay=1e-5,
)

lambda_rank = 1.0
EPOCHS = 10

best_val_mae = float("inf")

rank_model_path = (
    "/content/drive/MyDrive/"
    "Proj_2_Alt_Mags_Grnd_E/"
    "magnetic-topological-materials/"
    "models/"
    "alignn_spin_rank_best.pt"
)

Loaded spin-aware checkpoint from epoch 8

### Step - 5.6 - Training

In [ ]:
# for epoch in range(1, EPOCHS + 1):

#     rank_model.train()

#     train_mse_sum = 0.0
#     train_rank_sum = 0.0
#     train_abs_sum = 0.0
#     train_count = 0

#     for batch_indices, (g, lg, target) in zip(
#         train_batches,
#         rank_train_loader
#     ):

#         batch_parent_names = [
#             train_spin_df.iloc[i]["parent_structure_id"]
#             for i in batch_indices
#         ]

#         parent_map = {
#             parent: j
#             for j, parent in enumerate(
#                 dict.fromkeys(batch_parent_names)
#             )
#         }

#         parent_ids = torch.tensor(
#             [
#                 parent_map[parent]
#                 for parent in batch_parent_names
#             ],
#             dtype=torch.long,
#             device=device,
#         )

#         g = g.to(device)
#         lg = lg.to(device)
#         target = target.to(device)

#         optimizer.zero_grad(set_to_none=True)

#         result = rank_model((g, lg, None))
#         prediction = result["out"].reshape(-1)

#         mse_loss = F.mse_loss(
#             prediction,
#             target
#         )

#         rank_loss = parentwise_ranking_loss(
#             prediction,
#             target,
#             parent_ids,
#             min_gap=0.001,
#             max_margin=0.010,
#         )

#         loss = mse_loss + lambda_rank * rank_loss

#         loss.backward()

#         torch.nn.utils.clip_grad_norm_(
#             rank_model.parameters(),
#             max_norm=5.0
#         )

#         optimizer.step()

#         n = target.numel()

#         train_mse_sum += mse_loss.item() * n
#         train_rank_sum += rank_loss.item() * n

#         train_abs_sum += (
#             torch.abs(prediction - target)
#             .sum()
#             .item()
#         )

#         train_count += n


#     train_mae = (
#         train_abs_sum / train_count
#     )

#     train_mse = (
#         train_mse_sum / train_count
#     )

#     train_rank = (
#         train_rank_sum / train_count
#     )


#     # --------------------------------------------------------
#     # Validation
#     # --------------------------------------------------------

#     rank_model.eval()

#     val_abs_sum = 0.0
#     val_mse_sum = 0.0
#     val_count = 0

#     with torch.no_grad():

#         for g, lg, target in rank_val_loader:

#             g = g.to(device)
#             lg = lg.to(device)
#             target = target.to(device)

#             result = rank_model(
#                 (g, lg, None)
#             )

#             prediction = result["out"].reshape(-1)

#             n = target.numel()

#             val_mse_sum += (
#                 F.mse_loss(
#                     prediction,
#                     target
#                 ).item() * n
#             )

#             val_abs_sum += (
#                 torch.abs(
#                     prediction - target
#                 ).sum().item()
#             )

#             val_count += n


#     val_mae = val_abs_sum / val_count
#     val_mse = val_mse_sum / val_count
#     val_rmse = val_mse ** 0.5


#     if val_mae < best_val_mae:

#         best_val_mae = val_mae

#         torch.save(
#             {
#                 "model_state_dict":
#                     rank_model.state_dict(),
#                 "epoch": epoch,
#                 "val_mae": val_mae,
#                 "config":
#                     spin_config.__dict__,
#             },
#             rank_model_path,
#         )

#         marker = " <-- BEST"

#     else:
#         marker = ""


#     print(
#         f"Epoch {epoch:02d}/{EPOCHS} | "
#         f"Train MAE: {train_mae:.6f} | "
#         f"Rank loss: {train_rank:.6f} | "
#         f"Val MAE: {val_mae:.6f} | "
#         f"Val RMSE: {val_rmse:.6f}"
#         f"{marker}"
#     )


# print("\nRanking-aware fine-tuning finished.")
# print("Best validation MAE:", best_val_mae)
# print("Saved:", rank_model_path)

### Step - 5.7 - Evaluating

In [ ]:
import numpy as np
import torch
from torch.utils.data import DataLoader
from sklearn.metrics import mean_absolute_error, mean_squared_error

# ============================================================
# 1. Test loader
# ============================================================

rank_test_loader = DataLoader(
    test_spin_dataset,
    batch_size=32,
    shuffle=False,
    num_workers=0,
    collate_fn=collate_spin_alignn,
    pin_memory=torch.cuda.is_available(),
)


# ============================================================
# 2. Recreate ranking-aware model
# ============================================================

device = torch.device(
    "cuda" if torch.cuda.is_available() else "cpu"
)

rank_model = ALIGNNAtomWisePure(
    spin_config
).to(device)


rank_model_path = (
    "/content/drive/MyDrive/"
    "Proj_2_Alt_Mags_Grnd_E/"
    "magnetic-topological-materials/"
    "models/"
    "alignn_spin_rank_best.pt"
)

checkpoint = torch.load(
    rank_model_path,
    map_location=device
)

rank_model.load_state_dict(
    checkpoint["model_state_dict"]
)

rank_model.eval()

print("Loaded epoch:", checkpoint["epoch"])
print("Validation MAE:", checkpoint["val_mae"])


# ============================================================
# 3. Test predictions
# ============================================================

rank_predictions = []
rank_targets = []

with torch.no_grad():

    for g, lg, target in rank_test_loader:

        g = g.to(device)
        lg = lg.to(device)
        target = target.to(device)

        result = rank_model((g, lg, None))

        prediction = result["out"].reshape(-1)

        rank_predictions.extend(
            prediction.cpu().numpy()
        )

        rank_targets.extend(
            target.cpu().numpy()
        )


# ============================================================
# 4. Regression metrics
# ============================================================

rank_test_mae = mean_absolute_error(
    rank_targets,
    rank_predictions
)

rank_test_rmse = mean_squared_error(
    rank_targets,
    rank_predictions
) ** 0.5

print("\n==============================")
print("RANKING-AWARE TEST RESULTS")
print("==============================")
print(
    f"Test MAE  : {rank_test_mae:.6f} eV/atom"
)
print(
    f"Test RMSE : {rank_test_rmse:.6f} eV/atom"
)

Loaded epoch: 5
Validation MAE: 0.010788808207716776

==============================
RANKING-AWARE TEST RESULTS
==============================
Test MAE  : 0.010610 eV/atom
Test RMSE : 0.022730 eV/atom

Ranking metrics

In [ ]:
# ============================================================
# 5. Ranking metrics
# ============================================================

rank_test_df = graph_df[
    graph_df["split"] == "test"
].copy()

rank_test_df["pred_delta_E"] = np.array(
    rank_predictions
)

rank_test_df["pred_rank"] = (
    rank_test_df
    .groupby("parent_structure_id")["pred_delta_E"]
    .rank(method="first", ascending=True)
)

true_tasks = (
    rank_test_df.loc[
        rank_test_df.groupby(
            "parent_structure_id"
        )["delta_E"].idxmin(),
        ["parent_structure_id", "task_id"]
    ]
    .set_index("parent_structure_id")["task_id"]
)


def top_k_accuracy(df, true_tasks, k):

    correct = 0

    for parent, true_task in true_tasks.items():

        candidates = df[
            (df["parent_structure_id"] == parent)
            & (df["pred_rank"] <= k)
        ]

        if true_task in candidates["task_id"].values:
            correct += 1

    return correct / len(true_tasks)


top1 = top_k_accuracy(
    rank_test_df,
    true_tasks,
    1
)

top3 = top_k_accuracy(
    rank_test_df,
    true_tasks,
    3
)

top5 = top_k_accuracy(
    rank_test_df,
    true_tasks,
    5
)

selected = (
    rank_test_df[
        rank_test_df["pred_rank"] == 1
    ][["parent_structure_id", "delta_E"]]
    .rename(columns={"delta_E": "regret"})
)

print("\n==============================")
print("RANKING-AWARE RANKING RESULTS")
print("==============================")
print("Top-1:", f"{top1:.4%}")
print("Top-3:", f"{top3:.4%}")
print("Top-5:", f"{top5:.4%}")

print("\nEnergy regret")
print(
    "Mean  :", selected["regret"].mean(),
    "eV/atom"
)
print(
    "Median:", selected["regret"].median(),
    "eV/atom"
)

for threshold in [
    0.001,
    0.002,
    0.005,
    0.010,
    0.020
]:

    fraction = (
        selected["regret"] < threshold
    ).mean()

    print(
        f"Regret < {threshold:.3f} eV/atom:",
        f"{fraction:.2%}"
    )

==============================
RANKING-AWARE RANKING RESULTS
==============================
Top-1: 27.0270%
Top-3: 51.3514%
Top-5: 67.9537%

Energy regret
Mean  : 0.003844814680183307 eV/atom
Median: 0.00043152156249970375 eV/atom
Regret < 0.001 eV/atom: 60.23%
Regret < 0.002 eV/atom: 72.20%
Regret < 0.005 eV/atom: 81.85%
Regret < 0.010 eV/atom: 90.73%
Regret < 0.020 eV/atom: 95.75%

Pairwise ranking

In [ ]:
# ============================================================
# 6. Pairwise ranking accuracy
# ============================================================

correct_pairs = 0
total_pairs = 0

for parent, group in rank_test_df.groupby(
    "parent_structure_id"
):

    true_energy = group["delta_E"].to_numpy()
    pred_energy = group["pred_delta_E"].to_numpy()

    n = len(group)

    for i in range(n):
        for j in range(i + 1, n):

            true_diff = (
                true_energy[i] - true_energy[j]
            )

            if true_diff == 0:
                continue

            pred_diff = (
                pred_energy[i] - pred_energy[j]
            )

            if true_diff * pred_diff > 0:
                correct_pairs += 1

            total_pairs += 1


pairwise_accuracy = (
    correct_pairs / total_pairs
)

print(
    "\nPairwise ranking accuracy:",
    f"{pairwise_accuracy:.4%}"
)

Pairwise ranking accuracy: 56.6644%

## Phase - 6 - Energy prediction to magnetic-symmetry classification.

### Step - 6.1 - Inspecting data records

In [ ]:
# Find one test parent ground-state task
test_df = graph_df[
    graph_df["split"] == "test"
].copy()

gs_rows = (
    test_df.loc[
        test_df.groupby("parent_structure_id")["delta_E"].idxmin()
    ]
)

task_id = str(gs_rows.iloc[0]["task_id"])

record = next(
    r for r in data
    if str(r.get("task_id")) == task_id
)

print("Ground-state task:", task_id)
print("\nTop-level keys:")
print(record.keys())

print("\nmagmoms:")
print(record.get("magmoms"))

print("\nPotential structure-related keys:")
for k in record.keys():
    if "struct" in k.lower() or "output" in k.lower() or "final" in k.lower():
        print(k)

Ground-state task: 28294

Top-level keys:
dict_keys(['formula', 'formula_pretty', 'parent_structure', 'wf_meta', 'task_id', 'structure', 'magmoms', 'input', 'total_magnetization', 'total_magnetization_per_formula_unit', 'total_magnetization_per_unit_volume', 'ordering', 'ordering_changed', 'symmetry', 'symmetry_changed', 'energy_per_atom', 'stable', 'decomposes_to', 'energy_above_ground_state_per_atom', 'energy_diff_relax_static'])

magmoms:
{'vasp': [-0.0, 0.0, 0.0, -0.0, -3.766, 3.766, -0.002, -0.002, 0.002, 0.002, -0.001, 0.001, 0.001, -0.001, 0.011, -0.011, -0.011, 0.011, 0.01, -0.01, -0.01, 0.01, -0.006, 0.006, 0.006, -0.006], 'bader': [-9e-05, 5.6e-05, 4.1e-05, -7.9e-05, -3.756551, 3.756801, -0.00144, -0.001234, 0.001304, 0.001137, -0.000306, 0.000243, 0.000256, -0.000309, 0.029005, -0.029146, -0.029141, 0.029021, 0.021611, -0.022107, -0.021929, 0.02186, -0.017933, 0.018472, 0.01846, -0.018001]}

Potential structure-related keys:
parent_structure
structure

### Step - 6.2 - Inspecting the actual symmetry information

In [ ]:
print("Formula:", record["formula_pretty"])
print("Ordering:", record["ordering"])
print("Ordering changed:", record["ordering_changed"])

print("\nTotal magnetization:")
print(record["total_magnetization"])

print("\nSymmetry:")
print(record["symmetry"])

print("\nStructure type:")
print(type(record["structure"]))

print("\nStructure keys:")
print(record["structure"].keys())

Formula: Li2Fe(WO4)2
Ordering: AFM
Ordering changed: True

Total magnetization:
1e-06

Symmetry:
P-1

Structure type:
<class 'dict'>

Structure keys:
dict_keys(['@module', '@class', 'charge', 'lattice', 'sites', '@version'])

Magnetic moments alongside the sites

In [ ]:
structure = record["structure"]
final_magmoms = record["magmoms"]["vasp"]

print("\nNumber of sites:", len(structure["sites"]))
print("Number of VASP moments:", len(final_magmoms))

for i, (site, m) in enumerate(
    zip(structure["sites"], final_magmoms)
):
    print(
        i,
        site["species"][0]["element"],
        site["abc"],
        m
    )

Number of sites: 26
Number of VASP moments: 26
0 Li [0.310149, 0.148135, 0.603655] -0.0
1 Li [0.810526, 0.648534, 0.103457] 0.0
2 Li [0.689434, 0.851499, 0.39654] 0.0
3 Li [0.189802, 0.351915, 0.896345] -0.0
4 Fe [0.249996, 0.749986, 0.749982] -3.766
5 Fe [0.750209, 0.249702, 0.250111] 3.766
6 W [0.774298, 0.458261, 0.702266] -0.002
7 W [0.725677, 0.041803, 0.79776] -0.002
8 W [0.274361, 0.958433, 0.201607] 0.002
9 W [0.225639, 0.541535, 0.298386] 0.002
10 O [0.029267, 0.789182, 0.252879] -0.001
11 O [0.529029, 0.28917, 0.753317] 0.001
12 O [0.971001, 0.210815, 0.746688] 0.001
13 O [0.470701, 0.710877, 0.247068] -0.001
14 O [0.718062, 0.054142, 0.522737] 0.011
15 O [0.218635, 0.555168, 0.022509] -0.011
16 O [0.281336, 0.944866, 0.477486] -0.011
17 O [0.781886, 0.445807, 0.977296] 0.011
18 O [0.611304, 0.056464, 0.10843] 0.01
19 O [0.1117, 0.555707, 0.60837] -0.01
20 O [0.388274, 0.944362, 0.891609] -0.01
21 O [0.888695, 0.443569, 0.391557] 0.01
22 O [0.603319, 0.654043, 0.64862] -0.006
23 O [0.101168, 0.153483, 0.148099] 0.006
24 O [0.398893, 0.346544, 0.351855] 0.006
25 O [0.896638, 0.845997, 0.851368] -0.006

PT test directly from the final DFT structure + final VASP moments.

In [ ]:
import numpy as np
from pymatgen.core import Structure
from pymatgen.symmetry.analyzer import SpacegroupAnalyzer

# ------------------------------------------------------------
# Build pymatgen Structure from the final DFT structure
# ------------------------------------------------------------

pmg_structure = Structure.from_dict(record["structure"])

final_magmoms = np.array(
    record["magmoms"]["vasp"],
    dtype=float
)

pmg_structure.add_site_property(
    "magmom",
    final_magmoms.tolist()
)

print("Formula:", pmg_structure.composition.reduced_formula)
print("Sites:", len(pmg_structure))
print("Net moment:", final_magmoms.sum())


# ------------------------------------------------------------
# Crystallographic symmetry operations
# ------------------------------------------------------------

sga = SpacegroupAnalyzer(
    pmg_structure,
    symprec=1e-3,
    angle_tolerance=5
)

symm_ops = sga.get_symmetry_operations(
    cartesian=False
)

print("Crystallographic SG:", sga.get_space_group_symbol())
print("Number of symmetry operations:", len(symm_ops))


# ------------------------------------------------------------
# Find inversion operation P
# ------------------------------------------------------------

P_ops = []

for op in symm_ops:

    R = np.array(op.rotation_matrix, dtype=float)

    if np.allclose(
        R,
        -np.eye(3),
        atol=1e-5
    ):
        P_ops.append(op)

print("Number of inversion operations:", len(P_ops))

Formula: Li2Fe(WO4)2
Sites: 26
Net moment: 0.0
Crystallographic SG: P1
Number of symmetry operations: 1
Number of inversion operations: 0

PT (inversion + time reversal) test

In [ ]:
# ------------------------------------------------------------
# Check whether any inversion + time reversal (PT)
# preserves the magnetic structure
# ------------------------------------------------------------

coord_tol = 1e-3
mag_tol = 0.05

pt_found = False

for op_number, op in enumerate(P_ops):

    all_sites_match = True

    for i, site in enumerate(pmg_structure):

        # Apply inversion operation in fractional coordinates
        transformed = op.operate(
            site.frac_coords
        )

        # Bring into [0,1)
        transformed = transformed % 1.0

        # Find matching crystallographic site
        distances = []

        for j, target_site in enumerate(
            pmg_structure
        ):

            diff = (
                transformed
                - target_site.frac_coords
            )

            # Minimum-image fractional difference
            diff -= np.round(diff)

            distances.append(
                np.linalg.norm(diff)
            )

        j = int(np.argmin(distances))

        if distances[j] > coord_tol:
            all_sites_match = False
            break

        # For inversion, an axial magnetic moment
        # is unchanged by P.
        #
        # Time reversal then changes:
        #
        #       m -> -m
        #
        # Therefore PT requires:
        #
        #       m_j = -m_i

        if abs(
            final_magmoms[j]
            + final_magmoms[i]
        ) > mag_tol:

            all_sites_match = False
            break

    if all_sites_match:
        pt_found = True
        print(
            "PT symmetry FOUND using inversion operation:",
            op_number
        )
        break


print("\nPT symmetry:", pt_found)

if pt_found:
    print(
        "This magnetic structure is NOT "
        "altermagnetic under the PT criterion."
    )
else:
    print(
        "PT is broken. Together with full spin "
        "compensation, this is an altermagnet candidate."
    )

PT symmetry: False
PT is broken. Together with full spin compensation, this is an altermagnet candidate.

In [ ]:
from pymatgen.core import Structure
from pymatgen.symmetry.analyzer import SpacegroupAnalyzer
import numpy as np

s = Structure.from_dict(record["structure"])
m = np.array(record["magmoms"]["vasp"], dtype=float)

sga = SpacegroupAnalyzer(
    s,
    symprec=1e-2,
    angle_tolerance=5
)

ops = sga.get_symmetry_operations(cartesian=False)

print("Space group:", sga.get_space_group_symbol())
print("Number of operations:", len(ops))

for k, op in enumerate(ops):

    R = np.array(op.rotation_matrix)

    print("\nOperation", k)
    print("Rotation:")
    print(R)
    print("Translation:", op.translation_vector)

Space group: P-1
Number of operations: 2

Operation 0
Rotation:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Translation: [0. 0. 0.]

Operation 1
Rotation:
[[-1.  0.  0.]
 [ 0. -1.  0.]
 [ 0.  0. -1.]]
Translation: [0.5 0.5 0.5]

### Step - 6.3 - Checking test parents as AM or not

In [ ]:
import numpy as np
import pandas as pd
from pymatgen.core import Structure
from pymatgen.symmetry.analyzer import SpacegroupAnalyzer

# ------------------------------------------------------------
# Map task_id -> original DFT record
# ------------------------------------------------------------

record_by_task = {
    str(r["task_id"]): r
    for r in data
}

# ------------------------------------------------------------
# PT checker
# ------------------------------------------------------------

def check_PT_symmetry(
    structure,
    magmoms,
    op,
    coord_tol=0.01,
    mag_tol=0.05,
):
    """
    Test whether inversion + time reversal preserves
    the collinear magnetic structure.

    For PT:
        position -> inversion(position)
        moment  -> -moment
    """

    for i, site in enumerate(structure):

        transformed = (
            op.operate(site.frac_coords) % 1.0
        )

        best_j = None
        best_dist = np.inf

        for j, target in enumerate(structure):

            diff = (
                transformed
                - target.frac_coords
            )

            # minimum-image fractional distance
            diff -= np.round(diff)

            dist = np.linalg.norm(diff)

            if dist < best_dist:
                best_dist = dist
                best_j = j

        if best_dist > coord_tol:
            return False

        # Under PT the magnetic moment changes sign
        if abs(
            magmoms[best_j] + magmoms[i]
        ) > mag_tol:
            return False

    return True


# ------------------------------------------------------------
# Altermagnet screening
# ------------------------------------------------------------

def screen_altermagnet_corrected(
    record,
    symprec=1e-2,
    angle_tolerance=5,
    net_tol=1e-4,
    coord_tol=0.01,
    mag_tol=0.05,
):
    """
    Preliminary altermagnet screen.

    Criterion:
        1. Fully compensated magnetic ground state
        2. Broken PT symmetry

    If inversion P is absent, PT is automatically absent
    because PT requires P.
    """

    structure = Structure.from_dict(
        record["structure"]
    )

    magmoms = np.asarray(
        record["magmoms"]["vasp"],
        dtype=float
    )

    net_moment = abs(magmoms.sum())

    compensated = net_moment <= net_tol

    if not compensated:
        return {
            "task_id": str(record["task_id"]),
            "formula": record["formula_pretty"],
            "ordering": record["ordering"],
            "net_moment": net_moment,
            "compensated": False,
            "spacegroup": None,
            "inversion_found": False,
            "PT_preserved": None,
            "AM_candidate": False,
        }

    sga = SpacegroupAnalyzer(
        structure,
        symprec=symprec,
        angle_tolerance=angle_tolerance,
    )

    ops = sga.get_symmetry_operations(
        cartesian=False
    )

    inversion_found = False
    pt_preserved = False

    # Search for an inversion operation.
    for op in ops:

        R = np.asarray(
            op.rotation_matrix,
            dtype=float
        )

        if np.allclose(
            R,
            -np.eye(3),
            atol=1e-5
        ):

            inversion_found = True

            if check_PT_symmetry(
                structure,
                magmoms,
                op,
                coord_tol=coord_tol,
                mag_tol=mag_tol,
            ):
                pt_preserved = True

            break

    # If P does not exist, PT cannot exist.
    if not inversion_found:
        pt_preserved = False

    # Correct AM screening criterion
    am_candidate = (
        compensated
        and not pt_preserved
    )

    return {
        "task_id": str(record["task_id"]),
        "formula": record["formula_pretty"],
        "ordering": record["ordering"],
        "net_moment": net_moment,
        "compensated": compensated,
        "spacegroup": sga.get_space_group_symbol(),
        "inversion_found": inversion_found,
        "PT_preserved": pt_preserved,
        "AM_candidate": am_candidate,
    }

Screening the DFT ground states

In [ ]:
# ------------------------------------------------------------
# DFT ground state of each test parent
# ------------------------------------------------------------

test_ground_states = (
    graph_df[
        graph_df["split"] == "test"
    ]
    .loc[
        lambda x:
        x.groupby("parent_structure_id")["delta_E"]
        .transform("min")
        == x["delta_E"]
    ]
    .drop_duplicates(
        subset=["parent_structure_id"]
    )
    .copy()
)

print(
    "Test parent ground states:",
    len(test_ground_states)
)

Test parent ground states: 259

In [ ]:
results = []

for task_id in test_ground_states["task_id"]:

    record = record_by_task[
        str(task_id)
    ]

    result = screen_altermagnet_corrected(
        record
    )

    results.append(result)

am_df = pd.DataFrame(results)

print(am_df.head())

  task_id        formula ordering  net_moment  compensated spacegroup  \
0   28294    Li2Fe(WO4)2      AFM       0.000         True        P-1
1   32410       LiCrSnO4      FiM       0.002        False       None
2   29656         V2CoO4      FiM       2.013        False       None
3   34225   CoH5CN(ClO)2      FiM       0.001        False       None
4   45309  NaCo2H3(SO5)2      AFM       0.000         True         Cm

   inversion_found PT_preserved  AM_candidate
0             True        False          True
1            False         None         False
2            False         None         False
3            False         None         False
4            False        False          True

Counting the candidates

In [ ]:
print("\n==============================")
print("ALTERMAGNET SCREENING")
print("==============================")

print(
    "Total ground states:",
    len(am_df)
)

print(
    "Compensated:",
    am_df["compensated"].sum()
)

print(
    "Inversion found:",
    am_df["inversion_found"].sum()
)

print(
    "PT preserved:",
    am_df["PT_preserved"].sum()
)

print(
    "AM candidates:",
    am_df["AM_candidate"].sum()
)

print(
    "AM candidate fraction:",
    f"{am_df['AM_candidate'].mean():.2%}"
)

==============================
ALTERMAGNET SCREENING
==============================
Total ground states: 259
Compensated: 111
Inversion found: 75
PT preserved: 35
AM candidates: 76
AM candidate fraction: 29.34%

In [ ]:
am_candidates = am_df[
    am_df["AM_candidate"]
].sort_values("formula")

print(
    am_candidates[
        [
            "task_id",
            "formula",
            "ordering",
            "net_moment",
            "spacegroup",
            "PT_preserved",
        ]
    ].to_string(index=False)
)

task_id         formula ordering   net_moment spacegroup PT_preserved
  27974      Ba2CoSi2O7      AFM 3.885781e-16    P-42_1m        False
  16085        Ba2Fe2O5      AFM 0.000000e+00     P4/mmm        False
   5585        Ba2FeWO6      AFM 0.000000e+00     I4/mmm        False
   7605        Ba3Mn2O8      AFM 0.000000e+00       R-3m        False
   9705      Ba3Ta2NiO9      AFM 0.000000e+00      P-3m1        False
  40225     BaCo2(PO4)2      AFM 0.000000e+00     P2_1/c        False
  17836      BaLaMnSbO6      AFM 0.000000e+00        I-4        False
  17885      BaLaTiFeO6      AFM 0.000000e+00      F-43m        False
  17961       BaSrNiWO6      AFM 0.000000e+00      F-43m        False
  11073         Ca2MnO3      AFM 0.000000e+00     I4/mmm        False
   4189         Ca2MnO4      AFM 0.000000e+00   I4_1/acd        False
  20011        Ca2MnWO6      AFM 0.000000e+00         P1        False
  14652         Ca3MnO4      AFM 0.000000e+00       C2/m        False
  10560          CaV2O5      AFM 0.000000e+00       Pmmn        False
   7162       Co(ClO4)2      FiM 3.365364e-16        P-1        False
   2552             CoO      AFM 0.000000e+00      F-43m        False
  25497          CoTeO4      AFM 0.000000e+00         Pc        False
  10423       Cs2LiMnO4      FiM 2.237793e-16     Cmc2_1        False
  28203      CsCr(SO4)2      AFM 0.000000e+00       P321        False
   4924          FeCuO2      AFM 0.000000e+00       R-3m        False
   1791          K3NiO2      AFM 0.000000e+00       P2_1        False
  48723     KFeH5(SO5)2      AFM 3.365364e-16         P1        False
   4981          LaCrO3      AFM 0.000000e+00       Pnma        False
  32751      Li2Cr3BiO8      AFM 0.000000e+00       R-3m        False
  28294     Li2Fe(WO4)2      AFM 0.000000e+00        P-1        False
  40753       Li2MnGeO4      AFM 0.000000e+00     Pmn2_1        False
  38352        Li2NiBO4      AFM 0.000000e+00     C222_1        False
  42065       Li2SiNiO4      AFM 1.179612e-16         P1        False
  49391      Li2TiFe2O5      AFM 0.000000e+00         Cc        False
  27522       Li2V3O3F5      FiM 4.440892e-16         P1        False
  40596         Li2VOF4      AFM 0.000000e+00       C2/c        False
  50092       Li3CrSiO5      AFM 0.000000e+00        P-1        False
  49603    Li3Ni(SbO3)4      AFM 0.000000e+00         P1        False
  40214      Li4CrGa3O8      AFM 0.000000e+00         P1        False
  43985        Li4FeO3F      AFM 0.000000e+00     Cmc2_1        False
  47297    Li4Ti2Mn3O10      AFM 8.881784e-16        P-1        False
  52663   Li4VCr(TeO6)2      FiM 1.040834e-17         P1        False
  52083   Li5Co3(SbO5)2      FiM 8.881784e-16        P-1        False
  38191        Li8CoO5F      FiM 3.330669e-16         P1        False
  35686         Li8FeO6      AFM 0.000000e+00        P-1        False
  30688        LiCo2OF3      AFM 0.000000e+00         C2        False
  14465        LiCoAsO4      AFM 2.081668e-17       Pnma        False
   8924          LiFeOF      AFM 0.000000e+00         P2        False
  30779        LiMnSnO4      AFM 0.000000e+00       Imma        False
  33213        LiNiAsO4      AFM 0.000000e+00       Imma        False
  30169        LiTiNiO4      AFM 0.000000e+00       C2/c        False
  12082         LiVSiO4      AFM 0.000000e+00        I-4        False
   2797         MgMn2O4      AFM 1.526557e-16   I4_1/amd        False
  41088          MgMnO2      AFM 0.000000e+00      Fd-3m        False
  13559        Mn(IO3)2      AFM 0.000000e+00       P2_1        False
   8096         Mn2CdO4      AFM 0.000000e+00   I4_1/amd        False
  55367      Mn3(P2O7)2      FiM 6.678685e-16         P1        False
  24064         Mn3SnO8      AFM 0.000000e+00       R-3m        False
    477            MnO2      FiM 2.203099e-16       Pnma        False
  51934 NaCaMgCr(SiO3)4      AFM 0.000000e+00         C2        False
  45309   NaCo2H3(SO5)2      AFM 0.000000e+00         Cm        False
  46201  NaCo2H3(SeO5)2      AFM 0.000000e+00         Cm        False
  26498         NaCoBO3      AFM 0.000000e+00       C2/c        False
  14450          NaNiO2      FiM 2.220446e-16       Cmcm        False
  10652           NbVO4      FiM 1.092876e-16         Cm        False
   6112         Ni2P2O7      AFM 0.000000e+00       C2/m        False
   5140          NiSeO3      AFM 0.000000e+00       Pnma        False
   1908       Sr2CoTeO6      FiM 5.620504e-16        P-1        False
  19228        Sr2CrWO6      AFM 0.000000e+00     I4/mmm        False
   2136        Sr2MnWO6      AFM 0.000000e+00     P2_1/c        False
   5659       Sr2NiTeO6      AFM 0.000000e+00       C2/m        False
  51857     SrCo(GeO3)2      FiM 1.110223e-16         P1        False
   2950        SrFe2S2O      AFM 0.000000e+00     Pmn2_1        False
  49844      SrLaTiMnO6      AFM 0.000000e+00         Pc        False
  53935     SrMn(GeO3)2      AFM 0.000000e+00        P-1        False
  44801         Ta2MnO6      AFM 0.000000e+00   P4_2/mnm        False
  23771         Ti2CrO5      AFM 0.000000e+00       C2/c        False
  45367    TiMnH12(OF)6      AFM 0.000000e+00        P-1        False
  43891        V3(O2F)2      FiM 2.272488e-16         Pc        False
  31341          VZn2O4      AFM 0.000000e+00       Imma        False
   4286       Zn(FeO2)2      AFM 3.608225e-16      Fd-3m        False

### Step - 6.4 - ML-predicted ground states

In [ ]:
# ============================================================
# ML-PREDICTED GROUND STATES -> ALTERMAGNET SCREENING
# ============================================================

# test_spin_df already contains:
# task_id
# parent_structure_id
# pred_delta_E
# delta_E

predicted_gs = (
    test_spin_df.loc[
        test_spin_df.groupby("parent_structure_id")[
            "pred_delta_E"
        ].idxmin()
    ]
    .copy()
    .reset_index(drop=True)
)

print(
    "Predicted ground states:",
    len(predicted_gs)
)

# ------------------------------------------------------------
# Screen the ML-selected configurations
# ------------------------------------------------------------

predicted_am_results = []

for task_id in predicted_gs["task_id"]:

    rec = record_by_task[str(task_id)]

    result = screen_altermagnet_corrected(rec)

    predicted_am_results.append(result)

predicted_am_df = pd.DataFrame(
    predicted_am_results
)

print(
    "\nML-selected AM candidates:",
    predicted_am_df["AM_candidate"].sum()
)

print(
    "ML-selected AM fraction:",
    f"{predicted_am_df['AM_candidate'].mean():.2%}"
)

Predicted ground states: 259

ML-selected AM candidates: 59
ML-selected AM fraction: 22.78%

Comparing ML-selected AM states with the actual DFT AM ground states

In [ ]:
# ============================================================
# CLEAN END-TO-END AM RECOVERY
# ============================================================

# 1. Build task_id -> parent mapping
task_parent = (
    graph_df[graph_df["split"] == "test"]
    [["task_id", "parent_structure_id"]]
    .copy()
)

task_parent["task_id"] = task_parent["task_id"].astype(str)


# ------------------------------------------------------------
# 2. ACTUAL DFT GROUND-STATE AM STATUS
# ------------------------------------------------------------

actual_am = am_df[
    ["task_id", "AM_candidate"]
].copy()

actual_am["task_id"] = actual_am["task_id"].astype(str)

actual_am = actual_am.merge(
    task_parent,
    on="task_id",
    how="left"
)

# One actual ground state per parent
actual_am = actual_am[
    [
        "parent_structure_id",
        "task_id",
        "AM_candidate"
    ]
].copy()


# ------------------------------------------------------------
# 3. SCREEN THE ML-SELECTED GROUND STATES DIRECTLY
# ------------------------------------------------------------

predicted_results = []

for task_id in predicted_gs["task_id"]:

    rec = record_by_task[str(task_id)]

    result = screen_altermagnet_corrected(rec)

    predicted_results.append(result)

predicted_am = pd.DataFrame(predicted_results)

predicted_am["task_id"] = (
    predicted_am["task_id"].astype(str)
)

predicted_am = predicted_am.merge(
    task_parent,
    on="task_id",
    how="left"
)

predicted_am = predicted_am[
    [
        "parent_structure_id",
        "task_id",
        "AM_candidate"
    ]
].copy()


# ------------------------------------------------------------
# 4. COMPARE THE ACTUAL AND ML-SELECTED GROUND STATES
# ------------------------------------------------------------

comparison = actual_am.merge(
    predicted_am[
        [
            "parent_structure_id",
            "AM_candidate"
        ]
    ].rename(
        columns={
            "AM_candidate":
                "ML_selected_AM"
        }
    ),
    on="parent_structure_id",
    how="left"
)

comparison["ML_selected_AM"] = (
    comparison["ML_selected_AM"]
    .fillna(False)
)


# ------------------------------------------------------------
# 5. REPORT
# ------------------------------------------------------------

actual_count = int(
    comparison["AM_candidate"].sum()
)

ml_count = int(
    comparison["ML_selected_AM"].sum()
)

recovered_count = int(
    (
        comparison["AM_candidate"]
        &
        comparison["ML_selected_AM"]
    ).sum()
)

print("Actual DFT AM ground states:", actual_count)
print("ML-selected AM states:", ml_count)
print(
    "Actual AM ground states recovered by ML:",
    recovered_count
)

if actual_count > 0:
    print(
        "AM recovery rate:",
        f"{recovered_count / actual_count:.2%}"
    )

Actual DFT AM ground states: 76
ML-selected AM states: 59
Actual AM ground states recovered by ML: 33
AM recovery rate: 43.42%

| Metric                                      |       Result |
| ------------------------------------------- | -----------: |
| Actual DFT AM ground states                 | **19 / 259** |
| AM candidates selected by spin-aware ALIGNN | **16 / 259** |
| Actual AM ground states recovered           |  **10 / 19** |
| **AM recovery rate**                        |   **52.63%** |


So the spin-aware ALIGNN recovered:

$$ \boxed{10/19=52.63\%} $$

of the DFT-screened altermagnetic ground states.

That's quite different from the earlier:

$$ 24.71\% $$

which asked a much stricter question:

Did the model select the exact DFT magnetic configuration?

Here we're asking:

Did the model select a configuration that is classified as an AM candidate?

That is much closer to the actual goal of your project.

But there is an important caution

We currently have:

$$ 19\text{ actual AM} $$

and

$$ 16\text{ ML-selected AM}. $$

Only 10 overlap.

That means the ML screen found 16 candidates, but 6 of them are false positives relative to our DFT screen, and 9 actual AM ground states were missed.

### Step - 6.5 - Calculating the AM screening quality now

In [ ]:
# ============================================================
# AM SCREENING METRICS
# ============================================================

tp = int(
    (
        comparison["AM_candidate"]
        & comparison["ML_selected_AM"]
    ).sum()
)

fp = int(
    (
        ~comparison["AM_candidate"]
        & comparison["ML_selected_AM"]
    ).sum()
)

fn = int(
    (
        comparison["AM_candidate"]
        & ~comparison["ML_selected_AM"]
    ).sum()
)

tn = int(
    (
        ~comparison["AM_candidate"]
        & ~comparison["ML_selected_AM"]
    ).sum()
)

precision = tp / (tp + fp) if (tp + fp) else 0.0
recall = tp / (tp + fn) if (tp + fn) else 0.0
f1 = (
    2 * precision * recall / (precision + recall)
    if (precision + recall) else 0.0
)

print("True positives :", tp)
print("False positives:", fp)
print("False negatives:", fn)
print("True negatives :", tn)

print("\nPrecision:", f"{precision:.2%}")
print("Recall   :", f"{recall:.2%}")
print("F1 score :", f"{f1:.2%}")

True positives : 33
False positives: 26
False negatives: 43
True negatives : 157

Precision: 55.93%
Recall   : 43.42%
F1 score : 48.89%

Inspecting which materials were missed

In [ ]:
# ============================================================
# RECOVERED / MISSED / FALSE-POSITIVE AM MATERIALS
# ============================================================

# Add formula information
task_formula = (
    graph_df[graph_df["split"] == "test"]
    [["task_id", "formula"]]
    .copy()
)

task_formula["task_id"] = (
    task_formula["task_id"].astype(str)
)

comparison_detail = comparison.merge(
    task_formula,
    left_on="task_id",
    right_on="task_id",
    how="left"
)

recovered = comparison_detail[
    comparison_detail["AM_candidate"]
    & comparison_detail["ML_selected_AM"]
]

missed = comparison_detail[
    comparison_detail["AM_candidate"]
    & ~comparison_detail["ML_selected_AM"]
]

false_positive = comparison_detail[
    ~comparison_detail["AM_candidate"]
    & comparison_detail["ML_selected_AM"]
]

print("\n=== RECOVERED AM ===")
print(
    recovered[
        ["task_id", "formula", "parent_structure_id"]
    ].to_string(index=False)
)

print("\n=== MISSED AM ===")
print(
    missed[
        ["task_id", "formula", "parent_structure_id"]
    ].to_string(index=False)
)

print("\n=== FALSE-POSITIVE AM ===")
print(
    false_positive[
        ["task_id", "formula", "parent_structure_id"]
    ].to_string(index=False)
)

=== RECOVERED AM ===
task_id        formula                                              parent_structure_id
  28294    Li2Fe(WO4)2 03184e0f328eb3520417711ec3daa327f40c3aedc29a710f7b7ac5c6ce7d08c9
  45309  NaCo2H3(SO5)2 058f1a5e5a832ef8c60446520b8dfe10343754673fe52c8a9b9225c891214424
   7605       Ba3Mn2O8 0c2d52183c38df88fee8ae11f97c4ed7a98349063c3b54c3dea0c06f7ca5a7ab
  53935    SrMn(GeO3)2 0f5565d0c48c229ab549efc48dd1361c336bb28c6697e7ccfd13939dc6add7a0
   8924         LiFeOF 1910aa503022352be10602ee45456856eb48216f7bdd2cbac9bffb1083abe0ad
  51857    SrCo(GeO3)2 1c689144a8fa2b1e01a9abdd1c6efc23390a0d9734b4e1bcc409e473a935818d
  30688       LiCo2OF3 29ccbd6f06c3cc20d8d62a98e00d922671cbb021eaca047bdd6696a0838fb924
  43985       Li4FeO3F 32681fcb7fbf882d4088e0f114c8089cfd680a4134a1a6a745879224fcb100d8
  30169       LiTiNiO4 381f7dc1954277c062d5485c198d3eefa1d264d3ac2d172a9286471d6c5957b0
   8096        Mn2CdO4 39f21068b0506f31457fb9c11763958139a4cf50690e66c639ae5e7a1d5cf9cd
  14652        Ca3MnO4 5499c5f541b6f90d6596fd53a508f28b4f0117fb399c49881fa8c021ca97d94c
  49391     Li2TiFe2O5 679712ac88b126edaa3f9c88d13411d5a7ce779a8084cd3a28596032968be4b2
   2136       Sr2MnWO6 7353cfdc609979cbbfe59301a78729f07473eb7576aa34dc4fa95104199a2784
   5140         NiSeO3 784b3d22bdee22c3dcab20c5db548ce44c779ac9ddeb08f8ae5f3feff6574b8b
  13559       Mn(IO3)2 7e6f6611eec92036dc036610212e90f8ce34638de9fed87df0abbb728b2e413e
  35686        Li8FeO6 8690e65e1b282b3c8c3e849530379f5a6adaaf595b7724fb302616f117796950
  20011       Ca2MnWO6 8769a205cbc8df73ff2981aeee5c9f9ed89a4bf73d3aadabdd6efd8c2e92b9d5
   2950       SrFe2S2O 876a4c4191d9779bb370fcd1e57ad95c76c93125c3c2ddebf4bb73ceef0faa1d
  40225    BaCo2(PO4)2 985cb44ab09cce0126cab0a8c138ad145bc5f06a880bb466694cad2068c0229e
  46201 NaCo2H3(SeO5)2 9b4d20574778eff634e8b9585c58a8a96db0e3ba9a4805344cf8aceeb28c14f9
  47297   Li4Ti2Mn3O10 9bdc651a2bc63ae1578d92dd5b5aeda830be9ff343cc33877f1c608208c28f7d
  40214     Li4CrGa3O8 9c5691ee4112c3cc937659509a2050fc3342f47bb83ede580b7b0a53aa6a20a9
  48723    KFeH5(SO5)2 a45e5d7a5ee45e1e3251174d374cb6c0e3a5eefe49372741fcd5e524bf37f8bb
  30779       LiMnSnO4 a6694a1039f77658846b3269c8605f15f325be59f29897e77ac696194d97fc1c
   4286      Zn(FeO2)2 a89c62e6c89bad9cf0e60e86991ab2eccbed34d7beeb5886d2c79f3fac8a7662
   2797        MgMn2O4 ac571dd6c064ce62d2de96c73e8b196a415b9023e89d3f434f7fde2e69be2d1b
  41088         MgMnO2 cb30962588df8e0b75f301a7b781e1fddd9c033c9177dffa3e24a1e41b1c3895
  27974     Ba2CoSi2O7 cc80a522c8935056347795cec3c076b46a13926b245970c442d9ea2b883eb3c8
  26498        NaCoBO3 cd598889e1ba47663e97e288a2aa7b01f30f6eebfc83bca76270120220fb57b5
  17885     BaLaTiFeO6 d45dfdc46fdb7333ce31420aabc5a8737c5c3ad4e8c90fcdbcf26bc72b05c3d1
  14450         NaNiO2 dd6f98324a32bc9baa55c72f4733af117c32bc0285bc81188701cbffca2722b3
  45367   TiMnH12(OF)6 eb78abfc6f5d595be1e1f80c3a6942fdce4aba410b24b2cad574a79dd5d8ff04
   9705     Ba3Ta2NiO9 fe9a025dbbca17efc222c39370c505b78434c0251fc14d656512f4989537f27d

=== MISSED AM ===
task_id         formula                                              parent_structure_id
  42065       Li2SiNiO4 1335ae835b85cac9354d750d6202caee4bc14714989dd3f60477dc7966465b88
    477            MnO2 1eed303aa078193df0050a090385bf7cae36f07937271493c9f148fc266e68bb
   5585        Ba2FeWO6 1f14fd73fee38e689e79bc251edd3e629007fb159670d401f7ea142e4293d8b6
  12082         LiVSiO4 21ebaa1b9a0f2515f98ce0fb7a4337d874656cdef0e5b5278402b1cf796a8d81
  27522       Li2V3O3F5 27060f1b9f444e7df298cd0af4953303647037d78f5d85d78986e990bb61317b
   7162       Co(ClO4)2 2762c995c964620bbc4929a2697eb6dd4944cb0b20625befd824529c3316a1fd
  38191        Li8CoO5F 28d763ec00f15c8351396c921791209e148c4f6b9cf6bd2a6f4c04d887454634
  52083   Li5Co3(SbO5)2 2a380302313b1b966588afaf909a6cb362ac433bf50bb93fd284ba738116b1f5
  49603    Li3Ni(SbO3)4 327bdefd7de287c816099a6efc1977cde36cc20a83fa5ac576ef3495431b094f
  55367      Mn3(P2O7)2 39c303c199612ecb0a6b430358b65b0f5a72937035c7fc039fd27d62f8967b61
   6112         Ni2P2O7 3dd018ce066394470e995a3218e3dad2c0e37227e5fffda87a1f3254928ae0fd
  28203      CsCr(SO4)2 4499079a57c870530724a9ecd8fd2d0ae116c3609c8e8adf861a31ed5a89fc6d
  33213        LiNiAsO4 4a5d049498693a0be19f93facaa657a93e71d2f69a13268ba8fc4832e99583e0
  51934 NaCaMgCr(SiO3)4 4b3f4f83eb5b13ffae2c1193cafc2a3be4de161d3ca4b677e809384e1313b50b
   4189         Ca2MnO4 50e13313c7faafb11129ca77f77e911293686826bfe41f48ae958a132f588e04
  49844      SrLaTiMnO6 510d57095b6a2e5041ebad6e66926670ae6e54bbe507ea4beff1c8bfe0a05652
  10652           NbVO4 52b728b2bb9518f1f980c94dc8c4689b9d2943a83e0acb5166c8e971d9cf60c7
  38352        Li2NiBO4 5330545db84bc3fe3603b3b34aa2dfecb22017f777bbc29bef7d1025de58c01b
   5659       Sr2NiTeO6 5497dbf8cd951bb7d91511d8a460a1f144c03db73284335684546e3e625bac89
  31341          VZn2O4 6bd858f396b22c6b26d15d57cdfd9396675ba9f6fac10fd06f013c7c3d32b8b0
  11073         Ca2MnO3 73f4bd37278a6a38b593e717339a0a86afd47520c569195eae00f4cc50513b9a
  19228        Sr2CrWO6 77f79cc68e6906a246f9bf1786ea78d8f125ec91ceeae322bd4a40c60f1181bf
   1908       Sr2CoTeO6 7d9d135cc9797297db38d9fab909cfe8e33fefbad6c0b54eab486c038cd76ad6
  17961       BaSrNiWO6 8c8af08376deab5d84bebd54de9ef0c741ca5676765b44ca3aa910f6969de22e
  14465        LiCoAsO4 91f126881707dc8d165a34318fe881c568b1b246be0ebd6c4e0036e719ac2a58
  43891        V3(O2F)2 9a05c8cb4d513e17328ec6f24526a5b98bb70b101170a14a2fe49bd769395d77
   2552             CoO 9d001c4b1750487c8102725cd86fee706ae40d7d0c73c74286b8bad557c431e6
  10560          CaV2O5 a64ed520bf95fade997d19253b2b7810a1368341bb34eff9933ea9d4dfe9e31c
   4924          FeCuO2 ab9bce210c52aa26bab4d805a88dae0e6a044df5171ca5405648b5ca2dbeeb68
   1791          K3NiO2 b75b6a24f45a8636ee150a4702aa758476b5b9efb0883b88471479a2f79e2018
  50092       Li3CrSiO5 bd69eb21526b40507bb2149579f2ebda89264aaf9bbfe028e38c43183db748a5
   4981          LaCrO3 bfe7a5a05a3f9306e11d192056279680b556ccde3154b007b764d3915dddede5
  10423       Cs2LiMnO4 c09704c5a3cbebf823f642b7e035b2862c8a7c5eb7035ccb2f08bd6752bae4d5
  16085        Ba2Fe2O5 c4b6943f41c56eaa868ae46bbbd0ef341f28422113d2659c828083d804467bcc
  23771         Ti2CrO5 c9415a84144a36479c753b545ca64dcffaa0ed8d427e996e2cd5bceb839c26a8
  40753       Li2MnGeO4 cabe9ea153db1a665c195d1878622aed23dcd804d92377565e22a14646e0a2ca
  17836      BaLaMnSbO6 d22c9cb3cd0f21e2920aa778f93bdfedde05c669ed72414cbe13423a18361b65
  52663   Li4VCr(TeO6)2 d65b667edc08d60da6998b5ca23353c51998fedb5279dfce9028c8bfbc932a62
  25497          CoTeO4 dd0ff3db84a552f3754728ac9b5666d2c013f6574c0ccdaced7f2d2dc52d3b31
  44801         Ta2MnO6 e56f8da9db2fc40f44b74fb9dbcba2ca5a24806d3c01d4dd5effbf6aed7dfc9b
  32751      Li2Cr3BiO8 f1684e311e05adb8f4c1bfa854ff3ba924fd097b1c64878578bf9924577555a1
  24064         Mn3SnO8 f34ead6d55afd9719bea9d269b761cc624adcfca13ae682b13eb4111861d1177
  40596         Li2VOF4 fb54e9b2421cc6bac24387967d21ebace3c10d1eaf0cd7b22865e176404b1311

=== FALSE-POSITIVE AM ===
task_id        formula                                              parent_structure_id
  34225   CoH5CN(ClO)2 04cc4f9f56be07e7246735311948061e37779c4b9a8f2cf7848efb4ffeecd62b
  52889        Mn3TeO6 1038d9d2669e5a3effc9d793059a22e841361444e02f96046004fc09723ee20b
  32614       LiTiMnO4 2f733798662a8b81f31ed83ae9e7fb2058a50f37e17a0a652bf3b17cc5afb34d
  50561       MnCd9O10 2fa6369e75b0922b55606540f6de1326a8ae7e6a7b187caac01c346b208b4e46
   4736          FeClO 3a97cfb400815729155977f770cdd7e7f3f45e5c11412fc47ed984754f294c97
  18547      Sr2NbFeO6 3d23f2d7c7f15bbba9615b9f627a40fcc1a887a94345f4dff1c612ad84fc019d
  56410        Na6FeO4 3e6de35153e09542a954e9ca329cf11ff6411d1e57536a0982fab5e4c1fa93f4
  23348         CoTeO4 5b78083b94ab1d63922922681b9a46b8e86812092048ce401a3504ece394beb9
   5294        Cr2HgO4 6331855167912169b52159a9cf0a7a57dfefd654f7f28f4bb570be9a3b650c2d
   9019            CrO 73de295fc0ff138960c11a8c9522b7fbcf0fac2c1fdd04372ac4c826ae6798e5
  36830     Ni3(AsO4)2 74d28ffca62782fb8c0fb446aed05904d327a4a2a49abf56d2ae0c7627e46b98
  27115   BaCo2(AsO4)2 7599bf09ebcf7b53f677ad3ec8f5d44a1f51a39c4c0f400cc2ea6e8677e6cc88
  42230        Li4CrO4 7c27fc17d55aac71c9143eec7f1be727128a853321a2ad75cf2ff04feef7f104
  45830  NaFe2Mo2H3O10 80f25f6cabda3d2c737605e7d400094492b3a57d74690b5850c22004cf937be8
   4198         LiCrO2 819df99752ef38167adb7f1f4f3e9d3fcf5661017903c0e2f680d42287cdca58
  55881     Li2Ti2FeO6 861063371151de15da9e69d938d90344728eacdc36c1c524ec0f1d3cc936580e
  12467          V2HO4 9d55b73476b87b62e5017d61813db0028a19d0b3ac333f19f4aa1c7ecd786582
  36917 Sr4CaCr2(SO3)2 a67a2c456c09bec75eaa48d9b11abfcc667a364d4a41725927de10b34bea72a5
  36988      Li4Y3FeO8 c5b942af1855dfa4270c38478d769e94938b918b2580f8063f9cd237fc601126
  34616       LiTiCoO4 ca037194cc9ff15d1d1eca17cd9331d287431ac9b18ae75d1258aa67e90bbddc
  22175       Li5NiOF5 d05b0a419b404a2d1d21a7012579ccf5975832fa05295fc7c0dc12c6e3201d23
  27911    Li2Fe2Si2O7 de217240ba9fb79e4f773713b98c60dd03c3cf835e0cd11fb6182a648cb2222e
   9016         CaMnO2 e47aaecacbb8ea8687b75817aae11c562a70dbc9ae759e713790865432870db8
  54179       LiCoSiO4 e5a79c551872c53420162807392791c6ffc1d65412b27cbb0c40f361524b3189
  17152         MnZnO3 f8bc93f1464c09bcf925f569d67ac805fe594cb924cd535d4fa0e31abaf2a920
  39389   SrZnNi(PO4)2 f8d60071db1d7650d413a4feffa9b781c0b10ee16de1cdf4593593fbdae6baac

The 10 recovered candidates:

$Li_2Fe(WO4)_2$

$Mn_2CdO_4$

$Sr_2MnWO_6$

$NiSeO_3$

$BaCo_2(PO_4)_2$

$LiMnSnO_4$

$Zn(FeO_2)_2$

$MgMn_2O_4$

$MgMnO_2$

$NaNiO_2$

These are the materials where the spin-aware model selected a configuration that our symmetry screen also classified as an AM candidate.

The 9 missed candidates

$MnO_2$

$Co(ClO_4)_2$

$Li_5Co_3(SbO_5)_2$

$LiTiNiO_4$

$Ca_2MnO_4$

$Sr_2CoTeO_6$

$LiCoAsO_4$

$CaV2O_5$

$LaCrO_3$

These are especially valuable because they tell us where the ground-state prediction needs improvement.

The 6 false positives

$CoH_5CN(ClO)_2$
_
$Mn_3TeO_6$

$LiTiMnO_4$

$MnCd_9O_10$

$Cr_2HgO_4$

$Ni_3(AsO_4)_2$

These should not immediately be called model failures, because our AM classifier itself is still only a preliminary \(PT\)-screen.

19 candidates remain \(PT\)-broken analysis

In [ ]:
# ============================================================
# ROBUSTNESS OF AM SCREENING VS SYMPREC
# ============================================================

candidate_tasks = am_df.loc[
    am_df["AM_candidate"],
    "task_id"
].astype(str).tolist()

symprecs = [5e-3, 1e-2, 2e-2]

robust_rows = []

for task_id in candidate_tasks:

    rec = record_by_task[task_id]

    row = {
        "task_id": task_id,
        "formula": rec["formula_pretty"],
        "ordering": rec["ordering"],
    }

    for sp in symprecs:

        structure = Structure.from_dict(
            rec["structure"]
        )

        magmoms = np.asarray(
            rec["magmoms"]["vasp"],
            dtype=float,
        )

        sga = SpacegroupAnalyzer(
            structure,
            symprec=sp,
            angle_tolerance=5,
        )

        ops = sga.get_symmetry_operations(
            cartesian=False
        )

        pt_preserved = False
        inversion_found = False

        for op in ops:

            R = np.asarray(
                op.rotation_matrix,
                dtype=float
            )

            if np.allclose(
                R,
                -np.eye(3),
                atol=1e-5
            ):

                inversion_found = True

                if check_PT_symmetry(
                    structure,
                    magmoms,
                    op,
                    coord_tol=0.01,
                    mag_tol=0.05,
                ):
                    pt_preserved = True
                    break

        row[f"sg_{sp}"] = (
            sga.get_space_group_symbol()
        )

        row[f"inv_{sp}"] = inversion_found
        row[f"PT_{sp}"] = pt_preserved
        row[f"AM_{sp}"] = (
            abs(magmoms.sum()) <= 1e-4
            and inversion_found
            and not pt_preserved
        )

    robust_rows.append(row)

robust_df = pd.DataFrame(robust_rows)

print(robust_df.to_string(index=False))

task_id         formula ordering sg_0.005  inv_0.005  PT_0.005  AM_0.005  sg_0.01  inv_0.01  PT_0.01  AM_0.01  sg_0.02  inv_0.02  PT_0.02  AM_0.02
  28294     Li2Fe(WO4)2      AFM       P1      False     False     False      P-1      True    False     True      P-1      True     True    False
  45309   NaCo2H3(SO5)2      AFM       Cm      False     False     False       Cm     False    False    False       Cm     False    False    False
   7605        Ba3Mn2O8      AFM     R-3m       True      True     False     R-3m      True     True    False     R-3m      True     True    False
  53935     SrMn(GeO3)2      AFM      P-1       True      True     False      P-1      True     True    False     C2/c      True     True    False
  42065       Li2SiNiO4      AFM       P1      False     False     False       P1     False    False    False       P1     False    False    False
   8924          LiFeOF      AFM       Cm      False     False     False       P2     False    False    False       P2     False    False    False
  51857     SrCo(GeO3)2      FiM       P1      False     False     False       P1     False    False    False       P1     False    False    False
    477            MnO2      FiM     Pnma       True     False      True     Pnma      True    False     True     Pnma      True    False     True
   5585        Ba2FeWO6      AFM   I4/mmm       True      True     False   I4/mmm      True     True    False   I4/mmm      True     True    False
  12082         LiVSiO4      AFM       P1      False     False     False      I-4     False    False    False      I-4     False    False    False
  27522       Li2V3O3F5      FiM       P1      False     False     False       P1     False    False    False       P1     False    False    False
   7162       Co(ClO4)2      FiM       P1      False     False     False      P-1      True    False     True      R-3      True    False     True
  38191        Li8CoO5F      FiM       P1      False     False     False       P1     False    False    False       P1     False    False    False
  30688        LiCo2OF3      AFM       C2      False     False     False       C2     False    False    False       C2     False    False    False
  52083   Li5Co3(SbO5)2      FiM      P-1       True     False      True      P-1      True    False     True      P-1      True     True    False
  43985        Li4FeO3F      AFM   Cmc2_1      False     False     False   Cmc2_1     False    False    False   Cmc2_1     False    False    False
  49603    Li3Ni(SbO3)4      AFM       P1      False     False     False       P1     False    False    False       P1     False    False    False
  30169        LiTiNiO4      AFM     C2/c       True     False      True     C2/c      True    False     True     C2/c      True    False     True
  55367      Mn3(P2O7)2      FiM       P1      False     False     False       P1     False    False    False      P-1     False    False    False
   8096         Mn2CdO4      AFM     Fddd       True     False      True I4_1/amd      True    False     True I4_1/amd      True    False     True
   6112         Ni2P2O7      AFM     C2/m       True      True     False     C2/m      True     True    False     C2/m      True     True    False
  28203      CsCr(SO4)2      AFM       C2      False     False     False     P321     False    False    False     P321     False    False    False
  33213        LiNiAsO4      AFM     Imma       True      True     False     Imma      True     True    False     Imma      True     True    False
  51934 NaCaMgCr(SiO3)4      AFM       C2      False     False     False       C2     False    False    False       C2     False    False    False
   4189         Ca2MnO4      AFM I4_1/acd       True     False      True I4_1/acd      True    False     True I4_1/acd      True    False     True
  49844      SrLaTiMnO6      AFM       Pc      False     False     False       Pc     False    False    False       Pc     False    False    False
  10652           NbVO4      FiM       Cm      False     False     False       Cm     False    False    False       Cm     False    False    False
  38352        Li2NiBO4      AFM   C222_1      False     False     False   C222_1     False    False    False   C222_1     False    False    False
   5659       Sr2NiTeO6      AFM     C2/m       True      True     False     C2/m      True     True    False     C2/m      True     True    False
  14652         Ca3MnO4      AFM     C2/m       True      True     False     C2/m      True     True    False     C2/m      True     True    False
  49391      Li2TiFe2O5      AFM       Cc      False     False     False       Cc     False    False    False       Cc     False    False    False
  31341          VZn2O4      AFM     Imma       True      True     False     Imma      True     True    False     Imma      True     True    False
   2136        Sr2MnWO6      AFM   P2_1/c       True     False      True   P2_1/c      True    False     True   P2_1/c      True    False     True
  11073         Ca2MnO3      AFM   I4/mmm       True      True     False   I4/mmm      True     True    False   I4/mmm      True     True    False
  19228        Sr2CrWO6      AFM   I4/mmm       True      True     False   I4/mmm      True     True    False   I4/mmm      True     True    False
   5140          NiSeO3      AFM     Pnma       True     False      True     Pnma      True    False     True     Pnma      True    False     True
   1908       Sr2CoTeO6      FiM      P-1       True     False      True      P-1      True    False     True   P2_1/c      True    False     True
  13559        Mn(IO3)2      AFM     P2_1      False     False     False     P2_1     False    False    False     P2_1     False    False    False
  35686         Li8FeO6      AFM      P-1       True      True     False      P-1      True     True    False      P-1      True     True    False
  20011        Ca2MnWO6      AFM       P1      False     False     False       P1     False    False    False       P1     False    False    False
   2950        SrFe2S2O      AFM   Pmn2_1      False     False     False   Pmn2_1     False    False    False   Pmn2_1     False    False    False
  17961       BaSrNiWO6      AFM    F-43m      False     False     False    F-43m     False    False    False    F-43m     False    False    False
  14465        LiCoAsO4      AFM     Pnma       True     False      True     Pnma      True    False     True     Pnma      True    False     True
  40225     BaCo2(PO4)2      AFM   P2_1/c       True     False      True   P2_1/c      True    False     True   P2_1/c      True    False     True
  43891        V3(O2F)2      FiM       Pc      False     False     False       Pc     False    False    False       Pc     False    False    False
  46201  NaCo2H3(SeO5)2      AFM       Cm      False     False     False       Cm     False    False    False       Cm     False    False    False
  47297    Li4Ti2Mn3O10      AFM      P-1       True      True     False      P-1      True     True    False      P-1      True     True    False
  40214      Li4CrGa3O8      AFM       P1      False     False     False       P1     False    False    False       P1     False    False    False
   2552             CoO      AFM      R3m      False     False     False    F-43m     False    False    False    F-43m     False    False    False
  48723     KFeH5(SO5)2      AFM       P1      False     False     False       P1     False    False    False       P1     False    False    False
  10560          CaV2O5      AFM     Pmmn       True     False      True     Pmmn      True    False     True     Pmmn      True    False     True
  30779        LiMnSnO4      AFM     Imma       True     False      True     Imma      True    False     True     Imma      True    False     True
   4286       Zn(FeO2)2      AFM    Fd-3m       True     False      True    Fd-3m      True    False     True    Fd-3m      True    False     True
   4924          FeCuO2      AFM     C2/m       True      True     False     R-3m      True     True    False     R-3m      True     True    False
   2797         MgMn2O4      AFM I4_1/amd       True     False      True I4_1/amd      True    False     True I4_1/amd      True    False     True
   1791          K3NiO2      AFM       P1      False     False     False     P2_1     False    False    False P4_12_12     False    False    False
  50092       Li3CrSiO5      AFM      P-1       True      True     False      P-1      True     True    False      P-1      True     True    False
   4981          LaCrO3      AFM     Pnma       True     False      True     Pnma      True    False     True     Pnma      True    False     True
  10423       Cs2LiMnO4      FiM   Cmc2_1      False     False     False   Cmc2_1     False    False    False   Cmc2_1     False    False    False
  16085        Ba2Fe2O5      AFM   P4/mmm       True      True     False   P4/mmm      True     True    False   P4/mmm      True     True    False
  23771         Ti2CrO5      AFM     C2/c       True      True     False     C2/c      True     True    False     C2/c      True     True    False
  40753       Li2MnGeO4      AFM   Pmn2_1      False     False     False   Pmn2_1     False    False    False   Pmn2_1     False    False    False
  41088          MgMnO2      AFM    Fd-3m       True     False      True    Fd-3m      True    False     True    Fd-3m      True    False     True
  27974      Ba2CoSi2O7      AFM  P-42_1m      False     False     False  P-42_1m     False    False    False  P-42_1m     False    False    False
  26498         NaCoBO3      AFM     C2/c      False     False     False     C2/c     False    False    False     C2/c     False    False    False
  17836      BaLaMnSbO6      AFM      I-4      False     False     False      I-4     False    False    False      I-4     False    False    False
  17885      BaLaTiFeO6      AFM    F-43m      False     False     False    F-43m     False    False    False    F-43m     False    False    False
  52663   Li4VCr(TeO6)2      FiM       P1      False     False     False       P1     False    False    False       P1     False    False    False
  25497          CoTeO4      AFM       Pc      False     False     False       Pc     False    False    False   P2_1/c      True     True    False
  14450          NaNiO2      FiM   P2_1/m       True      True     False     Cmcm      True    False     True     Cmcm      True     True    False
  44801         Ta2MnO6      AFM P4_2/mnm       True      True     False P4_2/mnm      True     True    False P4_2/mnm      True     True    False
  45367    TiMnH12(OF)6      AFM      P-1       True      True     False      P-1      True     True    False      R-3      True     True    False
  32751      Li2Cr3BiO8      AFM     R-3m       True      True     False     R-3m      True     True    False     R-3m      True     True    False
  24064         Mn3SnO8      AFM     R-3m       True      True     False     R-3m      True     True    False     R-3m      True     True    False
  40596         Li2VOF4      AFM     C2/c      False     False     False     C2/c     False    False    False     C2/c     False    False    False
   9705      Ba3Ta2NiO9      AFM    P-3m1       True      True     False    P-3m1      True     True    False    P-3m1      True     True    False

Summarizing

In [ ]:
print("\nAM classification stability:")

for sp in symprecs:
    col = f"AM_{sp}"

    print(
        f"symprec={sp:.0e}:",
        int(robust_df[col].sum()),
        "/",
        len(robust_df)
    )

# Columns are named AM_0.005, AM_0.01, AM_0.02
stable_am = robust_df[
    robust_df["AM_0.005"]
    & robust_df["AM_0.01"]
    & robust_df["AM_0.02"]
]

print(
    "\nStable AM candidates:",
    len(stable_am)
)

print(
    stable_am[
        ["task_id", "formula", "ordering"]
    ].to_string(index=False)
)

AM classification stability:
symprec=5e-03: 16 / 76
symprec=1e-02: 19 / 76
symprec=2e-02: 16 / 76

Stable AM candidates: 15
task_id     formula ordering
    477        MnO2      FiM
  30169    LiTiNiO4      AFM
   8096     Mn2CdO4      AFM
   4189     Ca2MnO4      AFM
   2136    Sr2MnWO6      AFM
   5140      NiSeO3      AFM
   1908   Sr2CoTeO6      FiM
  14465    LiCoAsO4      AFM
  40225 BaCo2(PO4)2      AFM
  10560      CaV2O5      AFM
  30779    LiMnSnO4      AFM
   4286   Zn(FeO2)2      AFM
   2797     MgMn2O4      AFM
   4981      LaCrO3      AFM
  41088      MgMnO2      AFM

Rescreening all 259 DFT ground states

In [ ]:
corrected_results = []

for task_id in test_ground_states["task_id"]:

    rec = record_by_task[str(task_id)]

    result = screen_altermagnet_corrected(rec)

    corrected_results.append(result)

corrected_am_df = pd.DataFrame(
    corrected_results
)

print("==============================")
print("CORRECTED AM SCREEN")
print("==============================")

print(
    "Total ground states:",
    len(corrected_am_df)
)

print(
    "Compensated:",
    int(corrected_am_df["compensated"].sum())
)

print(
    "PT preserved:",
    int(corrected_am_df["PT_preserved"].fillna(False).sum())
)

print(
    "AM candidates:",
    int(corrected_am_df["AM_candidate"].sum())
)

print(
    "AM candidate fraction:",
    f"{corrected_am_df['AM_candidate'].mean():.2%}"
)

==============================
CORRECTED AM SCREEN
==============================
Total ground states: 259
Compensated: 111
PT preserved: 35
AM candidates: 76
AM candidate fraction: 29.34%

/tmp/ipykernel_2513/253434999.py:31: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  int(corrected_am_df["PT_preserved"].fillna(False).sum())

Listing them

In [ ]:
corrected_candidates = corrected_am_df[
    corrected_am_df["AM_candidate"]
].sort_values("formula")

print(
    corrected_candidates[
        [
            "task_id",
            "formula",
            "ordering",
            "net_moment",
            "spacegroup",
            "inversion_found",
            "PT_preserved",
        ]
    ].to_string(index=False)
)

task_id         formula ordering   net_moment spacegroup  inversion_found PT_preserved
  27974      Ba2CoSi2O7      AFM 3.885781e-16    P-42_1m            False        False
  16085        Ba2Fe2O5      AFM 0.000000e+00     P4/mmm             True        False
   5585        Ba2FeWO6      AFM 0.000000e+00     I4/mmm             True        False
   7605        Ba3Mn2O8      AFM 0.000000e+00       R-3m             True        False
   9705      Ba3Ta2NiO9      AFM 0.000000e+00      P-3m1             True        False
  40225     BaCo2(PO4)2      AFM 0.000000e+00     P2_1/c             True        False
  17836      BaLaMnSbO6      AFM 0.000000e+00        I-4            False        False
  17885      BaLaTiFeO6      AFM 0.000000e+00      F-43m            False        False
  17961       BaSrNiWO6      AFM 0.000000e+00      F-43m            False        False
  11073         Ca2MnO3      AFM 0.000000e+00     I4/mmm             True        False
   4189         Ca2MnO4      AFM 0.000000e+00   I4_1/acd             True        False
  20011        Ca2MnWO6      AFM 0.000000e+00         P1            False        False
  14652         Ca3MnO4      AFM 0.000000e+00       C2/m             True        False
  10560          CaV2O5      AFM 0.000000e+00       Pmmn             True        False
   7162       Co(ClO4)2      FiM 3.365364e-16        P-1             True        False
   2552             CoO      AFM 0.000000e+00      F-43m            False        False
  25497          CoTeO4      AFM 0.000000e+00         Pc            False        False
  10423       Cs2LiMnO4      FiM 2.237793e-16     Cmc2_1            False        False
  28203      CsCr(SO4)2      AFM 0.000000e+00       P321            False        False
   4924          FeCuO2      AFM 0.000000e+00       R-3m             True        False
   1791          K3NiO2      AFM 0.000000e+00       P2_1            False        False
  48723     KFeH5(SO5)2      AFM 3.365364e-16         P1            False        False
   4981          LaCrO3      AFM 0.000000e+00       Pnma             True        False
  32751      Li2Cr3BiO8      AFM 0.000000e+00       R-3m             True        False
  28294     Li2Fe(WO4)2      AFM 0.000000e+00        P-1             True        False
  40753       Li2MnGeO4      AFM 0.000000e+00     Pmn2_1            False        False
  38352        Li2NiBO4      AFM 0.000000e+00     C222_1            False        False
  42065       Li2SiNiO4      AFM 1.179612e-16         P1            False        False
  49391      Li2TiFe2O5      AFM 0.000000e+00         Cc            False        False
  27522       Li2V3O3F5      FiM 4.440892e-16         P1            False        False
  40596         Li2VOF4      AFM 0.000000e+00       C2/c            False        False
  50092       Li3CrSiO5      AFM 0.000000e+00        P-1             True        False
  49603    Li3Ni(SbO3)4      AFM 0.000000e+00         P1            False        False
  40214      Li4CrGa3O8      AFM 0.000000e+00         P1            False        False
  43985        Li4FeO3F      AFM 0.000000e+00     Cmc2_1            False        False
  47297    Li4Ti2Mn3O10      AFM 8.881784e-16        P-1             True        False
  52663   Li4VCr(TeO6)2      FiM 1.040834e-17         P1            False        False
  52083   Li5Co3(SbO5)2      FiM 8.881784e-16        P-1             True        False
  38191        Li8CoO5F      FiM 3.330669e-16         P1            False        False
  35686         Li8FeO6      AFM 0.000000e+00        P-1             True        False
  30688        LiCo2OF3      AFM 0.000000e+00         C2            False        False
  14465        LiCoAsO4      AFM 2.081668e-17       Pnma             True        False
   8924          LiFeOF      AFM 0.000000e+00         P2            False        False
  30779        LiMnSnO4      AFM 0.000000e+00       Imma             True        False
  33213        LiNiAsO4      AFM 0.000000e+00       Imma             True        False
  30169        LiTiNiO4      AFM 0.000000e+00       C2/c             True        False
  12082         LiVSiO4      AFM 0.000000e+00        I-4            False        False
   2797         MgMn2O4      AFM 1.526557e-16   I4_1/amd             True        False
  41088          MgMnO2      AFM 0.000000e+00      Fd-3m             True        False
  13559        Mn(IO3)2      AFM 0.000000e+00       P2_1            False        False
   8096         Mn2CdO4      AFM 0.000000e+00   I4_1/amd             True        False
  55367      Mn3(P2O7)2      FiM 6.678685e-16         P1            False        False
  24064         Mn3SnO8      AFM 0.000000e+00       R-3m             True        False
    477            MnO2      FiM 2.203099e-16       Pnma             True        False
  51934 NaCaMgCr(SiO3)4      AFM 0.000000e+00         C2            False        False
  45309   NaCo2H3(SO5)2      AFM 0.000000e+00         Cm            False        False
  46201  NaCo2H3(SeO5)2      AFM 0.000000e+00         Cm            False        False
  26498         NaCoBO3      AFM 0.000000e+00       C2/c            False        False
  14450          NaNiO2      FiM 2.220446e-16       Cmcm             True        False
  10652           NbVO4      FiM 1.092876e-16         Cm            False        False
   6112         Ni2P2O7      AFM 0.000000e+00       C2/m             True        False
   5140          NiSeO3      AFM 0.000000e+00       Pnma             True        False
   1908       Sr2CoTeO6      FiM 5.620504e-16        P-1             True        False
  19228        Sr2CrWO6      AFM 0.000000e+00     I4/mmm             True        False
   2136        Sr2MnWO6      AFM 0.000000e+00     P2_1/c             True        False
   5659       Sr2NiTeO6      AFM 0.000000e+00       C2/m             True        False
  51857     SrCo(GeO3)2      FiM 1.110223e-16         P1            False        False
   2950        SrFe2S2O      AFM 0.000000e+00     Pmn2_1            False        False
  49844      SrLaTiMnO6      AFM 0.000000e+00         Pc            False        False
  53935     SrMn(GeO3)2      AFM 0.000000e+00        P-1             True        False
  44801         Ta2MnO6      AFM 0.000000e+00   P4_2/mnm             True        False
  23771         Ti2CrO5      AFM 0.000000e+00       C2/c             True        False
  45367    TiMnH12(OF)6      AFM 0.000000e+00        P-1             True        False
  43891        V3(O2F)2      FiM 2.272488e-16         Pc            False        False
  31341          VZn2O4      AFM 0.000000e+00       Imma             True        False
   4286       Zn(FeO2)2      AFM 3.608225e-16      Fd-3m             True        False

The new result is a major correction to our earlier count:

$$ \boxed{76/259=29.34\%} $$

are now preliminary AM candidates, rather than 19. The reason is that we corrected the logic to allow non-centrosymmetric compensated states. That is consistent with the modern classification: altermagnets require full spin compensation and broken \(PT\), and A/S-A types can have broken \(P\).

For these 76 candidates, determine whether time reversal \(T\) itself is broken.

For your dataset, because these are mostly AFM/FiM states with nonzero local moments, I expect almost all to have broken \(T\). Then we can preliminarily separate them into:

$$ \boxed{ P\ \text{present},\ PT\ \text{broken} \Rightarrow S\text{-type} } $$

and

$$ \boxed{ P\ \text{broken},\ T\ \text{broken},\ PT\ \text{broken} \Rightarrow S/A\text{-type} } $$

where the 2025 classification distinguishes these using \(P\) and \(T\).

In [ ]:
# ============================================================
# PRELIMINARY M/S/A-TYPE SCREEN
# ============================================================

candidates = corrected_am_df[
    corrected_am_df["AM_candidate"]
].copy()

candidates["T_broken"] = False

for task_id in candidates["task_id"].astype(str):

    rec = record_by_task[task_id]

    m = np.asarray(
        rec["magmoms"]["vasp"],
        dtype=float
    )

    # T changes every magnetic moment sign.
    # T is preserved only when all moments are zero.
    t_broken = np.any(
        np.abs(m) > 0.05
    )

    candidates.loc[
        candidates["task_id"].astype(str) == task_id,
        "T_broken"
    ] = t_broken


def preliminary_type(row):

    if not row["AM_candidate"]:
        return "non-AM"

    if row["T_broken"] and row["inversion_found"]:
        return "S-type"

    if row["T_broken"] and not row["inversion_found"]:
        return "S/A-type"

    if (not row["T_broken"]) and not row["inversion_found"]:
        return "A-type"

    return "check"


candidates["AM_type_preliminary"] = candidates.apply(
    preliminary_type,
    axis=1
)

print(
    candidates[
        "AM_type_preliminary"
    ].value_counts()
)

print("\nCandidates by type:")
print(
    candidates[
        [
            "task_id",
            "formula",
            "ordering",
            "spacegroup",
            "inversion_found",
            "T_broken",
            "AM_type_preliminary",
        ]
    ].to_string(index=False)
)

AM_type_preliminary
S-type      40
S/A-type    36
Name: count, dtype: int64

Candidates by type:
task_id         formula ordering spacegroup  inversion_found  T_broken AM_type_preliminary
  28294     Li2Fe(WO4)2      AFM        P-1             True      True              S-type
  45309   NaCo2H3(SO5)2      AFM         Cm            False      True            S/A-type
   7605        Ba3Mn2O8      AFM       R-3m             True      True              S-type
  53935     SrMn(GeO3)2      AFM        P-1             True      True              S-type
  42065       Li2SiNiO4      AFM         P1            False      True            S/A-type
   8924          LiFeOF      AFM         P2            False      True            S/A-type
  51857     SrCo(GeO3)2      FiM         P1            False      True            S/A-type
    477            MnO2      FiM       Pnma             True      True              S-type
   5585        Ba2FeWO6      AFM     I4/mmm             True      True              S-type
  12082         LiVSiO4      AFM        I-4            False      True            S/A-type
  27522       Li2V3O3F5      FiM         P1            False      True            S/A-type
   7162       Co(ClO4)2      FiM        P-1             True      True              S-type
  38191        Li8CoO5F      FiM         P1            False      True            S/A-type
  30688        LiCo2OF3      AFM         C2            False      True            S/A-type
  52083   Li5Co3(SbO5)2      FiM        P-1             True      True              S-type
  43985        Li4FeO3F      AFM     Cmc2_1            False      True            S/A-type
  49603    Li3Ni(SbO3)4      AFM         P1            False      True            S/A-type
  30169        LiTiNiO4      AFM       C2/c             True      True              S-type
  55367      Mn3(P2O7)2      FiM         P1            False      True            S/A-type
   8096         Mn2CdO4      AFM   I4_1/amd             True      True              S-type
   6112         Ni2P2O7      AFM       C2/m             True      True              S-type
  28203      CsCr(SO4)2      AFM       P321            False      True            S/A-type
  33213        LiNiAsO4      AFM       Imma             True      True              S-type
  51934 NaCaMgCr(SiO3)4      AFM         C2            False      True            S/A-type
   4189         Ca2MnO4      AFM   I4_1/acd             True      True              S-type
  49844      SrLaTiMnO6      AFM         Pc            False      True            S/A-type
  10652           NbVO4      FiM         Cm            False      True            S/A-type
  38352        Li2NiBO4      AFM     C222_1            False      True            S/A-type
   5659       Sr2NiTeO6      AFM       C2/m             True      True              S-type
  14652         Ca3MnO4      AFM       C2/m             True      True              S-type
  49391      Li2TiFe2O5      AFM         Cc            False      True            S/A-type
  31341          VZn2O4      AFM       Imma             True      True              S-type
   2136        Sr2MnWO6      AFM     P2_1/c             True      True              S-type
  11073         Ca2MnO3      AFM     I4/mmm             True      True              S-type
  19228        Sr2CrWO6      AFM     I4/mmm             True      True              S-type
   5140          NiSeO3      AFM       Pnma             True      True              S-type
   1908       Sr2CoTeO6      FiM        P-1             True      True              S-type
  13559        Mn(IO3)2      AFM       P2_1            False      True            S/A-type
  35686         Li8FeO6      AFM        P-1             True      True              S-type
  20011        Ca2MnWO6      AFM         P1            False      True            S/A-type
   2950        SrFe2S2O      AFM     Pmn2_1            False      True            S/A-type
  17961       BaSrNiWO6      AFM      F-43m            False      True            S/A-type
  14465        LiCoAsO4      AFM       Pnma             True      True              S-type
  40225     BaCo2(PO4)2      AFM     P2_1/c             True      True              S-type
  43891        V3(O2F)2      FiM         Pc            False      True            S/A-type
  46201  NaCo2H3(SeO5)2      AFM         Cm            False      True            S/A-type
  47297    Li4Ti2Mn3O10      AFM        P-1             True      True              S-type
  40214      Li4CrGa3O8      AFM         P1            False      True            S/A-type
   2552             CoO      AFM      F-43m            False      True            S/A-type
  48723     KFeH5(SO5)2      AFM         P1            False      True            S/A-type
  10560          CaV2O5      AFM       Pmmn             True      True              S-type
  30779        LiMnSnO4      AFM       Imma             True      True              S-type
   4286       Zn(FeO2)2      AFM      Fd-3m             True      True              S-type
   4924          FeCuO2      AFM       R-3m             True      True              S-type
   2797         MgMn2O4      AFM   I4_1/amd             True      True              S-type
   1791          K3NiO2      AFM       P2_1            False      True            S/A-type
  50092       Li3CrSiO5      AFM        P-1             True      True              S-type
   4981          LaCrO3      AFM       Pnma             True      True              S-type
  10423       Cs2LiMnO4      FiM     Cmc2_1            False      True            S/A-type
  16085        Ba2Fe2O5      AFM     P4/mmm             True      True              S-type
  23771         Ti2CrO5      AFM       C2/c             True      True              S-type
  40753       Li2MnGeO4      AFM     Pmn2_1            False      True            S/A-type
  41088          MgMnO2      AFM      Fd-3m             True      True              S-type
  27974      Ba2CoSi2O7      AFM    P-42_1m            False      True            S/A-type
  26498         NaCoBO3      AFM       C2/c            False      True            S/A-type
  17836      BaLaMnSbO6      AFM        I-4            False      True            S/A-type
  17885      BaLaTiFeO6      AFM      F-43m            False      True            S/A-type
  52663   Li4VCr(TeO6)2      FiM         P1            False      True            S/A-type
  25497          CoTeO4      AFM         Pc            False      True            S/A-type
  14450          NaNiO2      FiM       Cmcm             True      True              S-type
  44801         Ta2MnO6      AFM   P4_2/mnm             True      True              S-type
  45367    TiMnH12(OF)6      AFM        P-1             True      True              S-type
  32751      Li2Cr3BiO8      AFM       R-3m             True      True              S-type
  24064         Mn3SnO8      AFM       R-3m             True      True              S-type
  40596         Li2VOF4      AFM       C2/c            False      True            S/A-type
   9705      Ba3Ta2NiO9      AFM      P-3m1             True      True              S-type

### Step - 6.6 - Using pymatgen's magnetic symmetry machinery

For one candidate first

In [ ]:
from pymatgen.symmetry import maggroups

print("MagneticSpaceGroup:")
print(maggroups.MagneticSpaceGroup)

print("\nAvailable magnetic symmetry names:")
print([
    x for x in dir(maggroups)
    if "mag" in x.lower() or "sym" in x.lower()
])

MagneticSpaceGroup:
<class 'pymatgen.symmetry.maggroups.MagneticSpaceGroup'>

Available magnetic symmetry names:
['MAGSYMM_DATA', 'MagSymmOp', 'Magmom', 'MagneticSpaceGroup', 'SymmetryGroup', '_write_all_magnetic_space_groups_to_file']

In [ ]:
from pymatgen.analysis.magnetism.analyzer import CollinearMagneticStructureAnalyzer

print(CollinearMagneticStructureAnalyzer)

<class 'pymatgen.analysis.magnetism.analyzer.CollinearMagneticStructureAnalyzer'>

Inspecting interfaces

In [ ]:
import inspect
from pymatgen.symmetry.maggroups import MagneticSpaceGroup
from pymatgen.analysis.magnetism.analyzer import (
    CollinearMagneticStructureAnalyzer
)

print("MagneticSpaceGroup:")
print(inspect.signature(MagneticSpaceGroup))

print("\nMagneticSpaceGroup methods:")
print([
    x for x in dir(MagneticSpaceGroup)
    if not x.startswith("_")
])

print("\nCollinearMagneticStructureAnalyzer:")
print(inspect.signature(
    CollinearMagneticStructureAnalyzer
))

print("\nAnalyzer methods:")
print([
    x for x in dir(CollinearMagneticStructureAnalyzer)
    if not x.startswith("_")
])

MagneticSpaceGroup:
(label, setting_transformation='a,b,c;0,0,0')

MagneticSpaceGroup methods:
['STRING_MODE', 'count', 'crystal_system', 'data_str', 'from_og', 'get_orbit', 'index', 'is_compatible', 'is_subgroup', 'is_supergroup', 'sg_symbol', 'symmetry_ops', 'to_html_string', 'to_latex_string', 'to_pretty_string', 'to_unicode_string']

CollinearMagneticStructureAnalyzer:
(structure: 'Structure', overwrite_magmom_mode: 'str | OverwriteMagmomMode' = <OverwriteMagmomMode.none: 'none'>, round_magmoms: 'bool' = False, detect_valences: 'bool' = False, make_primitive: 'bool' = True, default_magmoms: 'dict | None' = None, set_net_positive: 'bool' = True, threshold: 'float' = 0, threshold_nonmag: 'float' = 0.1, threshold_ordering: 'float' = 1e-08) -> 'None'

Analyzer methods:
['get_exchange_group_info', 'get_ferromagnetic_structure', 'get_nonmagnetic_structure', 'get_structure_with_only_magnetic_atoms', 'get_structure_with_spin', 'is_magnetic', 'magmoms', 'magnetic_species_and_magmoms', 'matches_ordering', 'number_of_magnetic_sites', 'number_of_unique_magnetic_sites', 'ordering', 'types_of_magnetic_specie', 'types_of_magnetic_species']

Using the analyzer to get the exchange-group information for a known candidate first

In [ ]:
from pymatgen.core import Structure
from pymatgen.analysis.magnetism.analyzer import (
    CollinearMagneticStructureAnalyzer
)

# Use our known AM candidate: Li2Fe(WO4)2
rec = record_by_task["28294"]

s = Structure.from_dict(rec["structure"])
s.add_site_property(
    "magmom",
    rec["magmoms"]["vasp"]
)

mag_analyzer = CollinearMagneticStructureAnalyzer(
    s,
    make_primitive=False,
    threshold_nonmag=0.05,
)

print("Ordering:", mag_analyzer.ordering)
print("Magnetic sites:", mag_analyzer.number_of_magnetic_sites)
print(
    "Unique magnetic sites:",
    mag_analyzer.number_of_unique_magnetic_sites()
)

print(
    "Exchange group:",
    mag_analyzer.get_exchange_group_info(
        symprec=0.01,
        angle_tolerance=5
    )
)

Ordering: Ordering.AFM
Magnetic sites: 6
Unique magnetic sites: 3
Exchange group: ('P-1', 2)

Inspecting spin-decorated structures

In [ ]:
spin_structure = mag_analyzer.get_structure_with_spin()

print("First 10 species with spin:")
for site in spin_structure[:10]:
    print(site.species_string)

First 10 species with spin:
Li,spin=0
Li,spin=0
Li,spin=0
Li,spin=0
Fe,spin=-3.766
Fe,spin=3.766
W,spin=-0.002
W,spin=-0.002
W,spin=0.002
W,spin=0.002

Inspecting the actual magnetic symmetry operations

In [ ]:
from pymatgen.core import Structure
from pymatgen.symmetry.maggroups import MagneticSpaceGroup

rec = record_by_task["28294"]

s = Structure.from_dict(rec["structure"])
s.add_site_property(
    "magmom",
    rec["magmoms"]["vasp"]
)

print("Magnetic structure:")
print(s)

print("\nTrying MagneticSpaceGroup objects for the crystal SG...")

msg = MagneticSpaceGroup("P-1")

print("MSG symbol:", msg.sg_symbol)
print("Crystal system:", msg.crystal_system)
print("Number of magnetic operations:", len(msg.symmetry_ops))

for i, op in enumerate(msg.symmetry_ops):
    print(i, op)

Magnetic structure:
Full Formula (Li4 Fe2 W4 O16)
Reduced Formula: Li2Fe(WO4)2
abc   :   5.750483   7.935968   6.780777
angles:  76.533813  75.811518  87.286303
pbc   :       True       True       True
Sites (26)
  #  SP           a         b         c    magmom
---  ----  --------  --------  --------  --------
  0  Li    0.310149  0.148135  0.603655    -0
  1  Li    0.810526  0.648534  0.103457     0
  2  Li    0.689434  0.851499  0.39654      0
  3  Li    0.189802  0.351915  0.896345    -0
  4  Fe    0.249996  0.749986  0.749982    -3.766
  5  Fe    0.750209  0.249702  0.250111     3.766
  6  W     0.774298  0.458261  0.702266    -0.002
  7  W     0.725677  0.041803  0.79776     -0.002
  8  W     0.274361  0.958433  0.201607     0.002
  9  W     0.225639  0.541535  0.298386     0.002
 10  O     0.029267  0.789182  0.252879    -0.001
 11  O     0.529029  0.28917   0.753317     0.001
 12  O     0.971001  0.210815  0.746688     0.001
 13  O     0.470701  0.710877  0.247068    -0.001
 14  O     0.718062  0.054142  0.522737     0.011
 15  O     0.218635  0.555168  0.022509    -0.011
 16  O     0.281336  0.944866  0.477486    -0.011
 17  O     0.781886  0.445807  0.977296     0.011
 18  O     0.611304  0.056464  0.10843      0.01
 19  O     0.1117    0.555707  0.60837     -0.01
 20  O     0.388274  0.944362  0.891609    -0.01
 21  O     0.888695  0.443569  0.391557     0.01
 22  O     0.603319  0.654043  0.64862     -0.006
 23  O     0.101168  0.153483  0.148099     0.006
 24  O     0.398893  0.346544  0.351855     0.006
 25  O     0.896638  0.845997  0.851368    -0.006

Trying MagneticSpaceGroup objects for the crystal SG...
MSG symbol: P-1
Crystal system: triclinic
Number of magnetic operations: 2
0 x, y, z, +1
1 -x, -y, -z, +1

Diagnostic

In [ ]:
# ============================================================
# ACTUAL MAGNETIC SYMMETRY: P / T / PT
# ============================================================

def magnetic_operation_preserves(
    structure,
    magmoms,
    op,
    time_reversal=+1,
    coord_tol=0.01,
    mag_tol=0.05,
):
    for i, site in enumerate(structure):

        transformed = (
            op.operate(site.frac_coords) % 1.0
        )

        best_j = None
        best_dist = np.inf

        for j, target in enumerate(structure):

            diff = transformed - target.frac_coords
            diff -= np.round(diff)

            dist = np.linalg.norm(diff)

            if dist < best_dist:
                best_dist = dist
                best_j = j

        if best_dist > coord_tol:
            return False

        expected = time_reversal * magmoms[i]

        if abs(
            magmoms[best_j] - expected
        ) > mag_tol:
            return False

    return True


rec = record_by_task["28294"]

s = Structure.from_dict(rec["structure"])

m = np.asarray(
    rec["magmoms"]["vasp"],
    dtype=float
)

sga = SpacegroupAnalyzer(
    s,
    symprec=1e-2,
    angle_tolerance=5
)

ops = sga.get_symmetry_operations(
    cartesian=False
)

print(
    "Crystallographic SG:",
    sga.get_space_group_symbol()
)

P_found = False
PT_found = False
T_found = False

identity = None

for op in ops:

    R = np.asarray(
        op.rotation_matrix,
        dtype=float
    )

    ordinary = magnetic_operation_preserves(
        s,
        m,
        op,
        time_reversal=+1,
    )

    with_T = magnetic_operation_preserves(
        s,
        m,
        op,
        time_reversal=-1,
    )

    # Identity operation
    if (
        np.allclose(R, np.eye(3), atol=1e-5)
        and np.allclose(
            op.translation_vector,
            [0, 0, 0],
            atol=1e-5,
        )
    ):
        identity = op

    # Inversion / inversion + T
    if np.allclose(
        R,
        -np.eye(3),
        atol=1e-5
    ):
        if ordinary:
            P_found = True

        if with_T:
            PT_found = True

    print(
        "\nRotation matrix:\n",
        R
    )

    print(
        "Translation:",
        op.translation_vector
    )

    print(
        "Preserves magnetic moments:",
        ordinary
    )

    print(
        "Preserves with time reversal:",
        with_T
    )


# Plain T = identity + time reversal
if identity is not None:

    T_found = magnetic_operation_preserves(
        s,
        m,
        identity,
        time_reversal=-1,
    )


print("\n==============================")
print("MAGNETIC SYMMETRY RESULT")
print("==============================")
print("P preserved :", P_found)
print("T preserved :", T_found)
print("PT preserved:", PT_found)

Crystallographic SG: P-1

Rotation matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Translation: [0. 0. 0.]
Preserves magnetic moments: True
Preserves with time reversal: False

Rotation matrix:
 [[-1.  0.  0.]
 [ 0. -1.  0.]
 [ 0.  0. -1.]]
Translation: [0.5 0.5 0.5]
Preserves magnetic moments: True
Preserves with time reversal: False

==============================
MAGNETIC SYMMETRY RESULT
==============================
P preserved : True
T preserved : False
PT preserved: False

Applying this proper \(P/T/PT\) test to all 76 candidates by using the magnetic_operation_preserves() function

In [ ]:
# ============================================================
# RIGOROUS PRELIMINARY MAGNETIC-SYMMETRY SCREEN
# FOR ALL 76 COMPENSATED PT-BROKEN CANDIDATES
# ============================================================

def get_PTR_symmetry(record, symprec=0.01):

    structure = Structure.from_dict(
        record["structure"]
    )

    magmoms = np.asarray(
        record["magmoms"]["vasp"],
        dtype=float
    )

    sga = SpacegroupAnalyzer(
        structure,
        symprec=symprec,
        angle_tolerance=5,
    )

    ops = sga.get_symmetry_operations(
        cartesian=False
    )

    P_found = False
    PT_found = False
    T_found = False
    identity = None

    for op in ops:

        R = np.asarray(
            op.rotation_matrix,
            dtype=float
        )

        ordinary = magnetic_operation_preserves(
            structure,
            magmoms,
            op,
            time_reversal=+1,
        )

        with_T = magnetic_operation_preserves(
            structure,
            magmoms,
            op,
            time_reversal=-1,
        )

        if (
            np.allclose(R, np.eye(3), atol=1e-5)
            and np.allclose(
                op.translation_vector,
                [0, 0, 0],
                atol=1e-5,
            )
        ):
            identity = op

        if np.allclose(
            R,
            -np.eye(3),
            atol=1e-5
        ):
            if ordinary:
                P_found = True

            if with_T:
                PT_found = True

    if identity is not None:

        T_found = magnetic_operation_preserves(
            structure,
            magmoms,
            identity,
            time_reversal=-1,
        )

    return {
        "spacegroup": sga.get_space_group_symbol(),
        "P_preserved": P_found,
        "T_preserved": T_found,
        "PT_preserved": PT_found,
    }

In [ ]:
rigorous_rows = []

for task_id in corrected_am_df.loc[
    corrected_am_df["AM_candidate"],
    "task_id"
].astype(str):

    rec = record_by_task[task_id]

    result = get_PTR_symmetry(rec)

    result["task_id"] = task_id
    result["formula"] = rec["formula_pretty"]
    result["ordering"] = rec["ordering"]
    result["net_moment"] = abs(
        np.asarray(
            rec["magmoms"]["vasp"],
            dtype=float
        ).sum()
    )

    rigorous_rows.append(result)

rigorous_am_df = pd.DataFrame(
    rigorous_rows
)

print(
    rigorous_am_df[
        [
            "task_id",
            "formula",
            "ordering",
            "P_preserved",
            "T_preserved",
            "PT_preserved",
        ]
    ].to_string(index=False)
)

task_id         formula ordering  P_preserved  T_preserved  PT_preserved
  28294     Li2Fe(WO4)2      AFM         True        False         False
  45309   NaCo2H3(SO5)2      AFM        False        False         False
   7605        Ba3Mn2O8      AFM         True        False          True
  53935     SrMn(GeO3)2      AFM         True        False          True
  42065       Li2SiNiO4      AFM        False        False         False
   8924          LiFeOF      AFM        False        False         False
  51857     SrCo(GeO3)2      FiM        False        False         False
    477            MnO2      FiM         True        False         False
   5585        Ba2FeWO6      AFM         True        False          True
  12082         LiVSiO4      AFM        False        False         False
  27522       Li2V3O3F5      FiM        False        False         False
   7162       Co(ClO4)2      FiM         True        False         False
  38191        Li8CoO5F      FiM        False        False         False
  30688        LiCo2OF3      AFM        False        False         False
  52083   Li5Co3(SbO5)2      FiM         True        False         False
  43985        Li4FeO3F      AFM        False        False         False
  49603    Li3Ni(SbO3)4      AFM        False        False         False
  30169        LiTiNiO4      AFM         True        False         False
  55367      Mn3(P2O7)2      FiM        False        False         False
   8096         Mn2CdO4      AFM         True        False         False
   6112         Ni2P2O7      AFM         True        False          True
  28203      CsCr(SO4)2      AFM        False        False         False
  33213        LiNiAsO4      AFM         True        False          True
  51934 NaCaMgCr(SiO3)4      AFM        False        False         False
   4189         Ca2MnO4      AFM         True        False         False
  49844      SrLaTiMnO6      AFM        False        False         False
  10652           NbVO4      FiM        False        False         False
  38352        Li2NiBO4      AFM        False        False         False
   5659       Sr2NiTeO6      AFM         True        False          True
  14652         Ca3MnO4      AFM         True        False          True
  49391      Li2TiFe2O5      AFM        False        False         False
  31341          VZn2O4      AFM         True        False          True
   2136        Sr2MnWO6      AFM         True        False         False
  11073         Ca2MnO3      AFM         True        False          True
  19228        Sr2CrWO6      AFM         True        False          True
   5140          NiSeO3      AFM         True        False         False
   1908       Sr2CoTeO6      FiM         True        False         False
  13559        Mn(IO3)2      AFM        False        False         False
  35686         Li8FeO6      AFM         True        False          True
  20011        Ca2MnWO6      AFM        False        False         False
   2950        SrFe2S2O      AFM        False        False         False
  17961       BaSrNiWO6      AFM        False        False         False
  14465        LiCoAsO4      AFM         True        False         False
  40225     BaCo2(PO4)2      AFM         True        False         False
  43891        V3(O2F)2      FiM        False        False         False
  46201  NaCo2H3(SeO5)2      AFM        False        False         False
  47297    Li4Ti2Mn3O10      AFM         True        False          True
  40214      Li4CrGa3O8      AFM        False        False         False
   2552             CoO      AFM        False        False         False
  48723     KFeH5(SO5)2      AFM        False        False         False
  10560          CaV2O5      AFM         True        False         False
  30779        LiMnSnO4      AFM         True        False         False
   4286       Zn(FeO2)2      AFM         True        False         False
   4924          FeCuO2      AFM         True        False          True
   2797         MgMn2O4      AFM         True        False         False
   1791          K3NiO2      AFM        False        False         False
  50092       Li3CrSiO5      AFM         True        False          True
   4981          LaCrO3      AFM         True        False         False
  10423       Cs2LiMnO4      FiM        False        False         False
  16085        Ba2Fe2O5      AFM         True        False          True
  23771         Ti2CrO5      AFM         True        False          True
  40753       Li2MnGeO4      AFM        False        False         False
  41088          MgMnO2      AFM         True        False         False
  27974      Ba2CoSi2O7      AFM        False        False         False
  26498         NaCoBO3      AFM        False        False         False
  17836      BaLaMnSbO6      AFM        False        False         False
  17885      BaLaTiFeO6      AFM        False        False         False
  52663   Li4VCr(TeO6)2      FiM        False        False         False
  25497          CoTeO4      AFM        False        False         False
  14450          NaNiO2      FiM         True        False         False
  44801         Ta2MnO6      AFM         True        False          True
  45367    TiMnH12(OF)6      AFM         True        False          True
  32751      Li2Cr3BiO8      AFM         True        False          True
  24064         Mn3SnO8      AFM         True        False          True
  40596         Li2VOF4      AFM        False        False         False
   9705      Ba3Ta2NiO9      AFM         True        False          True

Summarizing

In [ ]:
print("\n==============================")
print("P / T / PT SUMMARY")
print("==============================")

print(
    "P preserved:",
    rigorous_am_df["P_preserved"].sum()
)

print(
    "T preserved:",
    rigorous_am_df["T_preserved"].sum()
)

print(
    "PT preserved:",
    rigorous_am_df["PT_preserved"].sum()
)

print("\nCombinations:")
print(
    rigorous_am_df[
        [
            "P_preserved",
            "T_preserved",
            "PT_preserved",
        ]
    ]
    .value_counts()
)

==============================
P / T / PT SUMMARY
==============================
P preserved: 40
T preserved: 0
PT preserved: 21

Combinations:
P_preserved  T_preserved  PT_preserved
False        False        False           36
True         False        True            21
                          False           19
Name: count, dtype: int64

Among the 76 preliminary compensated + \(PT\)-broken candidates:

| \(P\)     | \(T\)  | \(PT\)    |  Count |
| --------- | ------ | --------- | -----: |
| preserved | broken | broken    | **19** |
| broken    | broken | broken    | **36** |
| preserved | broken | preserved | **21** |


The last group is not altermagnetic, because altermagnetism requires broken \(PT\).

Therefore our corrected count is:

$$ \boxed{19+36=55\ \text{preliminary AM candidates}} $$

not 76.

Classification

The 19 cases with

$$ P\ \text{preserved},\quad T\ \text{broken},\quad PT\ \text{broken} $$

are the clean S-type pattern: fully compensated, \(T\)-broken, \(PT\)-broken.

The 36 cases with

$$ P\ \text{broken},\quad T\ \text{broken},\quad PT\ \text{broken} $$

belong to the S/A-type sector: they have both S-type and A-type symmetry-breaking characteristics.

There are zero A-type candidates in this particular test set because every compensated \(PT\)-broken state we found also has \(T\) broken.

So, for the current 259 test-parent ground states:

$$ \boxed{55/259=21.24\%} $$

are preliminary altermagnet candidates:

19 S-type+36 S/A-type
	​

Our previous:

$$ 10/19=52.63\% $$

AM recovery result is obsolete, because it was based on the old 19-candidate screen.

The correct ground-truth set is now 55 candidates.

So our next step is to rerun the end-to-end ML screening:

$$ \boxed{\text{spin-aware ALIGNN-selected state}} \rightarrow \boxed{P/T/PT\text{ symmetry}} \rightarrow \boxed{\text{AM candidate}} $$

and calculate the new AM precision, recall, and F1 against the corrected 55-candidate ground truth.

In [ ]:
# ============================================================
# FINAL PRELIMINARY AM RECOVERY — CLEAN CALCULATION
# ============================================================

import numpy as np
import pandas as pd

# ------------------------------------------------------------
# Helper: AM status from the actual magnetic symmetry
# ------------------------------------------------------------

def get_am_status(task_id, symprec=0.01):

    rec = record_by_task[str(task_id)]

    magmoms = np.asarray(
        rec["magmoms"]["vasp"],
        dtype=float
    )

    net_moment = abs(magmoms.sum())

    # First condition: compensated
    compensated = net_moment <= 1e-4

    if not compensated:
        return {
            "task_id": str(task_id),
            "compensated": False,
            "P_preserved": None,
            "T_preserved": None,
            "PT_preserved": None,
            "AM": False,
        }

    ptr = get_PTR_symmetry(
        rec,
        symprec=symprec
    )

    return {
        "task_id": str(task_id),
        "compensated": True,
        "P_preserved": ptr["P_preserved"],
        "T_preserved": ptr["T_preserved"],
        "PT_preserved": ptr["PT_preserved"],
        "AM": not ptr["PT_preserved"],
    }


# ------------------------------------------------------------
# Parent mapping
# ------------------------------------------------------------

task_parent = (
    graph_df[
        graph_df["split"] == "test"
    ]
    [["task_id", "parent_structure_id"]]
    .copy()
)

task_parent["task_id"] = (
    task_parent["task_id"].astype(str)
)


# ============================================================
# 1. ACTUAL DFT GROUND STATES
# ============================================================

actual_rows = []

for task_id in test_ground_states["task_id"]:

    status = get_am_status(task_id)

    status["task_id"] = str(task_id)

    actual_rows.append(status)

actual_df = pd.DataFrame(actual_rows)

actual_df = actual_df.merge(
    task_parent,
    on="task_id",
    how="left"
)

print(
    "Actual AM ground states:",
    int(actual_df["AM"].sum())
)


# ============================================================
# 2. ML-PREDICTED GROUND STATES
# ============================================================

predicted_rows = []

for task_id in predicted_gs["task_id"]:

    status = get_am_status(task_id)

    status["task_id"] = str(task_id)

    predicted_rows.append(status)

predicted_df = pd.DataFrame(
    predicted_rows
)

predicted_df = predicted_df.merge(
    task_parent,
    on="task_id",
    how="left"
)

print(
    "ML-selected AM states:",
    int(predicted_df["AM"].sum())
)


# ============================================================
# 3. COMPARE BY PARENT
# ============================================================

actual_status = actual_df[
    [
        "parent_structure_id",
        "task_id",
        "AM",
    ]
].rename(
    columns={
        "task_id": "actual_task",
        "AM": "actual_AM",
    }
)

predicted_status = predicted_df[
    [
        "parent_structure_id",
        "task_id",
        "AM",
    ]
].rename(
    columns={
        "task_id": "predicted_task",
        "AM": "predicted_AM",
    }
)

comparison_final = actual_status.merge(
    predicted_status,
    on="parent_structure_id",
    how="inner",
)


# ============================================================
# 4. CONFUSION MATRIX
# ============================================================

tp = int(
    (
        comparison_final["actual_AM"]
        &
        comparison_final["predicted_AM"]
    ).sum()
)

fp = int(
    (
        ~comparison_final["actual_AM"]
        &
        comparison_final["predicted_AM"]
    ).sum()
)

fn = int(
    (
        comparison_final["actual_AM"]
        &
        ~comparison_final["predicted_AM"]
    ).sum()
)

tn = int(
    (
        ~comparison_final["actual_AM"]
        &
        ~comparison_final["predicted_AM"]
    ).sum()
)


precision = (
    tp / (tp + fp)
    if tp + fp > 0
    else 0.0
)

recall = (
    tp / (tp + fn)
    if tp + fn > 0
    else 0.0
)

f1 = (
    2 * precision * recall / (precision + recall)
    if precision + recall > 0
    else 0.0
)


# ============================================================
# 5. RESULTS
# ============================================================

print("\n==============================")
print("FINAL PRELIMINARY AM SCREEN")
print("==============================")

print("True positives :", tp)
print("False positives:", fp)
print("False negatives:", fn)
print("True negatives :", tn)

print(
    "\nPrecision:",
    f"{precision:.2%}"
)

print(
    "Recall   :",
    f"{recall:.2%}"
)

print(
    "F1 score :",
    f"{f1:.2%}"
)

Actual AM ground states: 55
ML-selected AM states: 37

==============================
FINAL PRELIMINARY AM SCREEN
==============================
True positives : 24
False positives: 13
False negatives: 31
True negatives : 191

Precision: 64.86%
Recall   : 43.64%
F1 score : 52.17%

Inspecting the actual successes and failures

In [ ]:
# ============================================================
# AM SUCCESSES / MISSES / FALSE POSITIVES
# ============================================================

task_formula = (
    graph_df[
        graph_df["split"] == "test"
    ]
    [["task_id", "formula"]]
    .copy()
)

task_formula["task_id"] = (
    task_formula["task_id"].astype(str)
)

details = comparison_final.merge(
    task_formula,
    left_on="actual_task",
    right_on="task_id",
    how="left"
).drop(
    columns=["task_id"]
)

print("\n=== RECOVERED AM ===")

print(
    details[
        details["actual_AM"]
        &
        details["predicted_AM"]
    ][
        [
            "actual_task",
            "predicted_task",
            "formula",
        ]
    ].to_string(index=False)
)

print("\n=== MISSED AM ===")

print(
    details[
        details["actual_AM"]
        &
        ~details["predicted_AM"]
    ][
        [
            "actual_task",
            "predicted_task",
            "formula",
        ]
    ].to_string(index=False)
)

print("\n=== FALSE POSITIVE AM ===")

print(
    details[
        ~details["actual_AM"]
        &
        details["predicted_AM"]
    ][
        [
            "actual_task",
            "predicted_task",
            "formula",
        ]
    ].to_string(index=False)
)

=== RECOVERED AM ===
actual_task predicted_task        formula
      28294          28096    Li2Fe(WO4)2
      45309          45670  NaCo2H3(SO5)2
       8924           8848         LiFeOF
      51857          51835    SrCo(GeO3)2
      30688          30688       LiCo2OF3
      43985          44250       Li4FeO3F
       8096           8096        Mn2CdO4
      49391          49391     Li2TiFe2O5
       2136           2136       Sr2MnWO6
       5140           5140         NiSeO3
      13559          13657       Mn(IO3)2
      20011          20031       Ca2MnWO6
       2950           2950       SrFe2S2O
      40225          40225    BaCo2(PO4)2
      46201          46266 NaCo2H3(SeO5)2
      40214          38949     Li4CrGa3O8
      48723          47421    KFeH5(SO5)2
      30779          30779       LiMnSnO4
       4286           4286      Zn(FeO2)2
       2797           2797        MgMn2O4
      41088          41088         MgMnO2
      27974          28333     Ba2CoSi2O7
      17885          18035     BaLaTiFeO6
      14450          14450         NaNiO2

=== MISSED AM ===
actual_task predicted_task         formula
      42065          37011       Li2SiNiO4
        477            563            MnO2
      12082          11755         LiVSiO4
      27522          27518       Li2V3O3F5
       7162           6287       Co(ClO4)2
      38191          37253        Li8CoO5F
      52083          51990   Li5Co3(SbO5)2
      49603          49923    Li3Ni(SbO3)4
      30169          30357        LiTiNiO4
      55367          54202      Mn3(P2O7)2
      28203          26065      CsCr(SO4)2
      51934          50506 NaCaMgCr(SiO3)4
       4189           4108         Ca2MnO4
      49844          49856      SrLaTiMnO6
      10652          24284           NbVO4
      38352          38429        Li2NiBO4
       1908           1557       Sr2CoTeO6
      17961          17935       BaSrNiWO6
      14465          14777        LiCoAsO4
      43891          46043        V3(O2F)2
       2552           2584             CoO
      10560          10462          CaV2O5
       1791           1650          K3NiO2
       4981           4947          LaCrO3
      10423          10400       Cs2LiMnO4
      40753          39854       Li2MnGeO4
      26498          26409         NaCoBO3
      17836          17783      BaLaMnSbO6
      52663          51303   Li4VCr(TeO6)2
      25497          25329          CoTeO4
      40596          39899         Li2VOF4

=== FALSE POSITIVE AM ===
actual_task predicted_task        formula
      34225          33877   CoH5CN(ClO)2
      52889          52096        Mn3TeO6
      32614          31711       LiTiMnO4
      50561          49479       MnCd9O10
       5294           4723        Cr2HgO4
       9019           9128            CrO
      36830          36596     Ni3(AsO4)2
      45830          45786  NaFe2Mo2H3O10
      12467          12320          V2HO4
      36917          37282 Sr4CaCr2(SO3)2
      36988          37116      Li4Y3FeO8
      27911          30276    Li2Fe2Si2O7
      54179          54236       LiCoSiO4

Final preliminary classification table

In [ ]:
# ============================================================
# PRELIMINARY ALTERMAGNET CLASSIFICATION
# ============================================================

classified_am = rigorous_am_df[
    rigorous_am_df["PT_preserved"] == False
].copy()

def classify_am(row):

    P = row["P_preserved"]
    T = row["T_preserved"]
    PT = row["PT_preserved"]

    if PT:
        return "Not AM"

    # Fully compensated + broken PT + broken T
    if T is False:

        if P is True:
            return "S-type"

        if P is False:
            return "S/A-type"

    # Broken P + unbroken T + broken PT
    if T is True and P is False:
        return "A-type"

    return "Check"


classified_am["AM_type"] = classified_am.apply(
    classify_am,
    axis=1
)

# These structures come from collinear VASP magnetic moments,
# so the S/S-A candidates are classified as strong in the
# preliminary strong/weak scheme.
classified_am["strength"] = classified_am[
    "AM_type"
].map({
    "S-type": "Strong",
    "S/A-type": "Strong",
    "A-type": "Weak",
})

print("==============================")
print("PRELIMINARY AM CLASSIFICATION")
print("==============================")

print(
    classified_am["AM_type"].value_counts()
)

print("\nStrength:")
print(
    classified_am["strength"].value_counts()
)

==============================
PRELIMINARY AM CLASSIFICATION
==============================
AM_type
S/A-type    36
S-type      19
Name: count, dtype: int64

Strength:
strength
Strong    55
Name: count, dtype: int64

Actual candidates list

In [ ]:
# ============================================================
# FINAL CANDIDATE TABLE
# ============================================================

final_am_table = classified_am[
    [
        "task_id",
        "formula",
        "ordering",
        "spacegroup",
        "P_preserved",
        "T_preserved",
        "PT_preserved",
        "AM_type",
        "strength",
    ]
].sort_values(
    ["AM_type", "formula"]
)

print(
    final_am_table.to_string(index=False)
)

task_id         formula ordering spacegroup  P_preserved  T_preserved  PT_preserved  AM_type strength
  40225     BaCo2(PO4)2      AFM     P2_1/c         True        False         False   S-type   Strong
   4189         Ca2MnO4      AFM   I4_1/acd         True        False         False   S-type   Strong
  10560          CaV2O5      AFM       Pmmn         True        False         False   S-type   Strong
   7162       Co(ClO4)2      FiM        P-1         True        False         False   S-type   Strong
   4981          LaCrO3      AFM       Pnma         True        False         False   S-type   Strong
  28294     Li2Fe(WO4)2      AFM        P-1         True        False         False   S-type   Strong
  52083   Li5Co3(SbO5)2      FiM        P-1         True        False         False   S-type   Strong
  14465        LiCoAsO4      AFM       Pnma         True        False         False   S-type   Strong
  30779        LiMnSnO4      AFM       Imma         True        False         False   S-type   Strong
  30169        LiTiNiO4      AFM       C2/c         True        False         False   S-type   Strong
   2797         MgMn2O4      AFM   I4_1/amd         True        False         False   S-type   Strong
  41088          MgMnO2      AFM      Fd-3m         True        False         False   S-type   Strong
   8096         Mn2CdO4      AFM   I4_1/amd         True        False         False   S-type   Strong
    477            MnO2      FiM       Pnma         True        False         False   S-type   Strong
  14450          NaNiO2      FiM       Cmcm         True        False         False   S-type   Strong
   5140          NiSeO3      AFM       Pnma         True        False         False   S-type   Strong
   1908       Sr2CoTeO6      FiM        P-1         True        False         False   S-type   Strong
   2136        Sr2MnWO6      AFM     P2_1/c         True        False         False   S-type   Strong
   4286       Zn(FeO2)2      AFM      Fd-3m         True        False         False   S-type   Strong
  27974      Ba2CoSi2O7      AFM    P-42_1m        False        False         False S/A-type   Strong
  17836      BaLaMnSbO6      AFM        I-4        False        False         False S/A-type   Strong
  17885      BaLaTiFeO6      AFM      F-43m        False        False         False S/A-type   Strong
  17961       BaSrNiWO6      AFM      F-43m        False        False         False S/A-type   Strong
  20011        Ca2MnWO6      AFM         P1        False        False         False S/A-type   Strong
   2552             CoO      AFM      F-43m        False        False         False S/A-type   Strong
  25497          CoTeO4      AFM         Pc        False        False         False S/A-type   Strong
  10423       Cs2LiMnO4      FiM     Cmc2_1        False        False         False S/A-type   Strong
  28203      CsCr(SO4)2      AFM       P321        False        False         False S/A-type   Strong
   1791          K3NiO2      AFM       P2_1        False        False         False S/A-type   Strong
  48723     KFeH5(SO5)2      AFM         P1        False        False         False S/A-type   Strong
  40753       Li2MnGeO4      AFM     Pmn2_1        False        False         False S/A-type   Strong
  38352        Li2NiBO4      AFM     C222_1        False        False         False S/A-type   Strong
  42065       Li2SiNiO4      AFM         P1        False        False         False S/A-type   Strong
  49391      Li2TiFe2O5      AFM         Cc        False        False         False S/A-type   Strong
  27522       Li2V3O3F5      FiM         P1        False        False         False S/A-type   Strong
  40596         Li2VOF4      AFM       C2/c        False        False         False S/A-type   Strong
  49603    Li3Ni(SbO3)4      AFM         P1        False        False         False S/A-type   Strong
  40214      Li4CrGa3O8      AFM         P1        False        False         False S/A-type   Strong
  43985        Li4FeO3F      AFM     Cmc2_1        False        False         False S/A-type   Strong
  52663   Li4VCr(TeO6)2      FiM         P1        False        False         False S/A-type   Strong
  38191        Li8CoO5F      FiM         P1        False        False         False S/A-type   Strong
  30688        LiCo2OF3      AFM         C2        False        False         False S/A-type   Strong
   8924          LiFeOF      AFM         P2        False        False         False S/A-type   Strong
  12082         LiVSiO4      AFM        I-4        False        False         False S/A-type   Strong
  13559        Mn(IO3)2      AFM       P2_1        False        False         False S/A-type   Strong
  55367      Mn3(P2O7)2      FiM         P1        False        False         False S/A-type   Strong
  51934 NaCaMgCr(SiO3)4      AFM         C2        False        False         False S/A-type   Strong
  45309   NaCo2H3(SO5)2      AFM         Cm        False        False         False S/A-type   Strong
  46201  NaCo2H3(SeO5)2      AFM         Cm        False        False         False S/A-type   Strong
  26498         NaCoBO3      AFM       C2/c        False        False         False S/A-type   Strong
  10652           NbVO4      FiM         Cm        False        False         False S/A-type   Strong
  51857     SrCo(GeO3)2      FiM         P1        False        False         False S/A-type   Strong
   2950        SrFe2S2O      AFM     Pmn2_1        False        False         False S/A-type   Strong
  49844      SrLaTiMnO6      AFM         Pc        False        False         False S/A-type   Strong
  43891        V3(O2F)2      FiM         Pc        False        False         False S/A-type   Strong

Inspecting the spin-rotation symmetry information

In [ ]:
import inspect
from pymatgen.analysis.magnetism.analyzer import (
    CollinearMagneticStructureAnalyzer
)

print(inspect.getsource(
    CollinearMagneticStructureAnalyzer.get_exchange_group_info
))

    def get_exchange_group_info(
        self,
        symprec: float = 1e-2,
        angle_tolerance: float = 5,
    ) -> tuple[str, int]:
        """Get the information on the symmetry of the Hamiltonian
        describing the exchange energy of the system, taking into
        account relative direction of magnetic moments but not their
        absolute direction.

        This is not strictly accurate (e.g. some/many atoms will
        have zero magnetic moments), but defining symmetry this
        way is a useful way of keeping track of distinct magnetic
        orderings within pymatgen.

        Args:
            symprec (float): same as SpacegroupAnalyzer (Default value = 1e-2)
            angle_tolerance (float): same as SpacegroupAnalyzer (Default value = 5)

        Returns:
            tuple[str, int]: spacegroup_symbol, international_number
        """
        structure = self.get_structure_with_spin()

        return structure.get_space_group_info(symprec=symprec, angle_tolerance=angle_tolerance)

In [ ]:
print([
    x for x in dir(s)
    if "spin" in x.lower()
    or "mag" in x.lower()
])

['add_spin_by_element', 'add_spin_by_site', 'from_magnetic_spacegroup', 'remove_spin']

Testing it on the known Li₂Fe(WO₄)₂ candidate

In [ ]:
import spglib
import numpy as np
from pymatgen.core import Structure

rec = record_by_task["28294"]

structure = Structure.from_dict(
    rec["structure"]
)

# Correct way to get element symbols
elements = [
    site.species.elements[0].symbol
    for site in structure
]

print("First elements:", elements[:10])

# Give each chemical element an integer type
unique_elements = {
    el: i + 1
    for i, el in enumerate(sorted(set(elements)))
}

numbers = [
    unique_elements[el]
    for el in elements
]

magmoms = np.asarray(
    rec["magmoms"]["vasp"],
    dtype=float
)

cell = (
    np.asarray(
        structure.lattice.matrix,
        dtype=float
    ),
    np.asarray(
        structure.frac_coords,
        dtype=float
    ),
    np.asarray(
        numbers,
        dtype=int
    ),
    magmoms,
)

print("spglib version:", spglib.__version__)

mag_sym = spglib.get_magnetic_symmetry(
    cell,
    symprec=1e-2,
    angle_tolerance=5,
    mag_symprec=0.05,
    is_axial=False,
    with_time_reversal=True,
)

print(
    "Magnetic symmetry found:",
    mag_sym is not None
)

if mag_sym is not None:

    print(
        "Number of magnetic operations:",
        len(mag_sym["rotations"])
    )

    unique_tau, counts = np.unique(
        mag_sym["time_reversals"],
        return_counts=True
    )

    print(
        "Time-reversal operations:"
    )

    for tau, count in zip(
        unique_tau,
        counts
    ):
        print(
            f"  {tau:+d}: {count}"
        )

First elements: ['Li', 'Li', 'Li', 'Li', 'Fe', 'Fe', 'W', 'W', 'W', 'W']
spglib version: 2.7.0
Magnetic symmetry found: True
Number of magnetic operations: 2
Time-reversal operations:
  +0: 2

In [ ]:
mst = spglib.get_magnetic_spacegroup_type_from_symmetry(
    mag_sym["rotations"],
    mag_sym["translations"],
    mag_sym["time_reversals"],
    lattice=cell[0],
)

print(mst)

MagneticSpaceGroupType(uni_number=4, litvin_number=4, bns_number='2.4', og_number='2.1.4', number=2, type=1)

In [ ]:
print("UNI number:", mst.uni_number)
print("BNS number:", mst.bns_number)
print("OG number :", mst.og_number)
print("Number    :", mst.number)
print("Type      :", mst.type)

UNI number: 4
BNS number: 2.4
OG number : 2.1.4
Number    : 2
Type      : 1

In [ ]:
# ============================================================
# MAGNETIC SPACE GROUP DATA FOR ALL 55 CANDIDATES
# ============================================================

def get_magnetic_spacegroup_info(record, symprec=1e-2):
    structure = Structure.from_dict(record["structure"])

    elements = [
        site.species.elements[0].symbol
        for site in structure
    ]

    element_types = {
        el: i + 1
        for i, el in enumerate(sorted(set(elements)))
    }

    numbers = [
        element_types[el]
        for el in elements
    ]

    magmoms = np.asarray(
        record["magmoms"]["vasp"],
        dtype=float
    )

    cell = (
        np.asarray(structure.lattice.matrix, dtype=float),
        np.asarray(structure.frac_coords, dtype=float),
        np.asarray(numbers, dtype=int),
        magmoms,
    )

    mag_sym = spglib.get_magnetic_symmetry(
        cell,
        symprec=symprec,
        angle_tolerance=5,
        mag_symprec=0.05,
        is_axial=False,
        with_time_reversal=True,
    )

    if mag_sym is None:
        return {
            "task_id": str(record["task_id"]),
            "formula": record["formula_pretty"],
            "status": "magnetic_symmetry_not_found",
        }

    mst = spglib.get_magnetic_spacegroup_type_from_symmetry(
        mag_sym["rotations"],
        mag_sym["translations"],
        mag_sym["time_reversals"],
        lattice=cell[0],
    )

    # Spglib found operations, but could not assign an MSG type
    if mst is None:
        return {
            "task_id": str(record["task_id"]),
            "formula": record["formula_pretty"],
            "status": "msg_type_not_identified",
            "n_operations": len(mag_sym["rotations"]),
            "n_time_reversal_ops": int(
                np.sum(
                    np.asarray(
                        mag_sym["time_reversals"]
                    ) == 1
                )
            ),
        }

    return {
        "task_id": str(record["task_id"]),
        "formula": record["formula_pretty"],
        "status": "ok",
        "BNS_number": mst.bns_number,
        "OG_number": mst.og_number,
        "MSG_number": mst.number,
        "MSG_type": mst.type,
        "n_operations": len(
            mag_sym["rotations"]
        ),
        "n_time_reversal_ops": int(
            np.sum(
                np.asarray(
                    mag_sym["time_reversals"]
                ) == 1
            )
        ),
    }

In [ ]:
msg_rows = []

for task_id in corrected_am_df.loc[
    corrected_am_df["AM_candidate"],
    "task_id"
].astype(str):

    info = get_magnetic_spacegroup_info(
        record_by_task[task_id]
    )

    if info is not None:
        msg_rows.append(info)

msg_df = pd.DataFrame(msg_rows)

print(msg_df.to_string(index=False))

print("\nMSG type counts:")
print(msg_df["MSG_type"].value_counts())

task_id         formula                  status BNS_number   OG_number  MSG_number  MSG_type  n_operations  n_time_reversal_ops
  28294     Li2Fe(WO4)2                      ok        2.4       2.1.4         2.0       1.0             2                    0
  45309   NaCo2H3(SO5)2                      ok       8.34      8.3.40         8.0       3.0             2                    1
   7605        Ba3Mn2O8                      ok      12.63     12.6.71        12.0       4.0             8                    4
  53935     SrMn(GeO3)2                      ok        2.7       2.4.7         2.0       4.0             4                    2
  42065       Li2SiNiO4                      ok        1.1       1.1.1         1.0       1.0             1                    0
   8924          LiFeOF                      ok       5.17      3.6.13         5.0       4.0             4                    2
  51857     SrCo(GeO3)2                      ok        1.1       1.1.1         1.0       1.0             1                    0
    477            MnO2                      ok     62.448    62.8.509        62.0       3.0             8                    4
   5585        Ba2FeWO6                      ok     65.490    69.6.610        65.0       4.0            16                    8
  12082         LiVSiO4                      ok        1.3       1.3.3         1.0       4.0             2                    1
  27522       Li2V3O3F5                      ok        1.3       1.3.3         1.0       4.0             2                    1
   7162       Co(ClO4)2                      ok        2.4       2.1.4         2.0       1.0             2                    0
  38191        Li8CoO5F                      ok        1.3       1.3.3         1.0       4.0             2                    1
  30688        LiCo2OF3                      ok       5.15      5.3.21         5.0       3.0             2                    1
  52083   Li5Co3(SbO5)2                      ok        2.4       2.1.4         2.0       1.0             2                    0
  43985        Li4FeO3F                      ok      26.76    36.6.254        26.0       4.0             8                    4
  49603    Li3Ni(SbO3)4                      ok        1.3       1.3.3         1.0       4.0             2                    1
  30169        LiTiNiO4                      ok      15.89     15.5.96        15.0       3.0             4                    2
  55367      Mn3(P2O7)2                      ok        1.1       1.1.1         1.0       1.0             1                    0
   8096         Mn2CdO4                      ok     70.530    70.4.619        70.0       3.0             8                    4
   6112         Ni2P2O7                      ok      15.90     12.8.73        15.0       4.0             8                    4
  28203      CsCr(SO4)2                      ok     150.28  150.4.1258       150.0       4.0            12                    6
  33213        LiNiAsO4                      ok     53.336   74.10.659        53.0       4.0            16                    8
  51934 NaCaMgCr(SiO3)4                      ok       5.16      5.4.22         5.0       4.0             4                    2
   4189         Ca2MnO4                      ok    142.567  142.7.1228       142.0       3.0            16                    8
  49844      SrLaTiMnO6                      ok       7.26      7.3.34         7.0       3.0             2                    1
  10652           NbVO4                      ok       8.32      8.1.38         8.0       1.0             2                    0
  38352        Li2NiBO4                      ok      18.22    20.7.128        18.0       4.0             8                    4
   5659       Sr2NiTeO6                      ok      15.91     13.8.84        15.0       4.0             8                    4
  14652         Ca3MnO4                      ok        2.7       2.4.7         2.0       4.0             4                    2
  49391      Li2TiFe2O5                      ok       9.39      9.3.47         9.0       3.0             2                    1
  31341          VZn2O4                      ok      15.90     12.8.73        15.0       4.0             8                    4
   2136        Sr2MnWO6                      ok      14.79     14.5.90        14.0       3.0             4                    2
  11073         Ca2MnO3                      ok     59.413    59.8.485        59.0       4.0            16                    8
  19228        Sr2CrWO6                      ok    123.350 139.10.1188       123.0       4.0            32                   16
   5140          NiSeO3                      ok     62.447    62.7.508        62.0       3.0             8                    4
   1908       Sr2CoTeO6                      ok        2.4       2.1.4         2.0       1.0             2                    0
  13559        Mn(IO3)2                      ok        4.9      4.3.17         4.0       3.0             2                    1
  35686         Li8FeO6                      ok        2.7       2.4.7         2.0       4.0             4                    2
  20011        Ca2MnWO6                      ok        1.3       1.3.3         1.0       4.0             2                    1
   2950        SrFe2S2O                      ok     31.123    31.1.212        31.0       1.0             4                    0
  17961       BaSrNiWO6                      ok     160.68  160.4.1298       160.0       4.0            12                    6
  14465        LiCoAsO4                      ok     62.448    62.8.509        62.0       3.0             8                    4
  40225     BaCo2(PO4)2                      ok      14.79     14.5.90        14.0       3.0             4                    2
  43891        V3(O2F)2                      ok       7.26      7.3.34         7.0       3.0             2                    1
  46201  NaCo2H3(SeO5)2                      ok       9.40      8.6.43         9.0       4.0             4                    2
  47297    Li4Ti2Mn3O10                      ok        2.7       2.4.7         2.0       4.0             4                    2
  40214      Li4CrGa3O8                      ok        1.3       1.3.3         1.0       4.0             2                    1
   2552             CoO                      ok    122.338   118.6.970       122.0       4.0            16                    8
  48723     KFeH5(SO5)2                      ok        1.3       1.3.3         1.0       4.0             2                    1
  10560          CaV2O5                      ok     59.410    59.6.483        59.0       3.0             8                    4
  30779        LiMnSnO4                      ok     74.559    74.6.655        74.0       3.0             8                    4
   4286       Zn(FeO2)2                      ok    141.555  141.5.1217       141.0       3.0            16                    8
   4924          FeCuO2                      ok      10.49     12.7.72        10.0       4.0             8                    4
   2797         MgMn2O4                      ok     70.530    70.4.619        70.0       3.0             8                    4
   1791          K3NiO2                      ok        4.7      4.1.15         4.0       1.0             2                    0
  50092       Li3CrSiO5                      ok        2.7       2.4.7         2.0       4.0             4                    2
   4981          LaCrO3                      ok     62.447    62.7.508        62.0       3.0             8                    4
  10423       Cs2LiMnO4                      ok     31.133    36.8.256        31.0       4.0             8                    4
  16085        Ba2Fe2O5                      ok    139.540 123.12.1010       139.0       4.0            32                   16
  23771         Ti2CrO5                      ok      13.74     15.6.97        13.0       4.0             8                    4
  40753       Li2MnGeO4                      ok       9.41      7.6.37         9.0       4.0             4                    2
  41088          MgMnO2                      ok    141.555  141.5.1217       141.0       3.0            16                    8
  27974      Ba2CoSi2O7                      ok    113.271   113.5.933       113.0       3.0             8                    4
  26498         NaCoBO3                      ok       5.16      5.4.22         5.0       4.0             4                    2
  17836      BaLaMnSbO6                      ok      81.38    82.4.702        81.0       4.0             8                    4
  17885      BaLaTiFeO6                      ok     160.68  160.4.1298       160.0       4.0            12                    6
  52663   Li4VCr(TeO6)2                      ok        1.3       1.3.3         1.0       4.0             2                    1
  25497          CoTeO4                      ok       7.27      7.4.35         7.0       4.0             4                    2
  14450          NaNiO2 msg_type_not_identified        NaN         NaN         NaN       NaN             6                    2
  44801         Ta2MnO6                      ok      14.80     14.6.91        14.0       4.0             8                    4
  45367    TiMnH12(OF)6                      ok        2.7       2.4.7         2.0       4.0             4                    2
  32751      Li2Cr3BiO8                      ok    166.102  166.6.1332       166.0       4.0            24                   12
  24064         Mn3SnO8                      ok    166.102  166.6.1332       166.0       4.0            24                   12
  40596         Li2VOF4                      ok       5.16      5.4.22         5.0       4.0             4                    2
   9705      Ba3Ta2NiO9                      ok      11.55     11.6.64        11.0       4.0             8                    4

MSG type counts:
MSG_type
4.0    44
3.0    21
1.0    10
Name: count, dtype: int64

In [ ]:
print("\nSuccessful magnetic-space-group identifications:")
print(
    msg_df[
        msg_df["status"] == "ok"
    ][
        [
            "task_id",
            "formula",
            "BNS_number",
            "MSG_number",
            "MSG_type",
            "n_operations",
            "n_time_reversal_ops",
        ]
    ].to_string(index=False)
)

print("\nMSG type counts:")
print(
    msg_df.loc[
        msg_df["status"] == "ok",
        "MSG_type"
    ].value_counts()
)

Successful magnetic-space-group identifications:
task_id         formula BNS_number  MSG_number  MSG_type  n_operations  n_time_reversal_ops
  28294     Li2Fe(WO4)2        2.4         2.0       1.0             2                    0
  45309   NaCo2H3(SO5)2       8.34         8.0       3.0             2                    1
   7605        Ba3Mn2O8      12.63        12.0       4.0             8                    4
  53935     SrMn(GeO3)2        2.7         2.0       4.0             4                    2
  42065       Li2SiNiO4        1.1         1.0       1.0             1                    0
   8924          LiFeOF       5.17         5.0       4.0             4                    2
  51857     SrCo(GeO3)2        1.1         1.0       1.0             1                    0
    477            MnO2     62.448        62.0       3.0             8                    4
   5585        Ba2FeWO6     65.490        65.0       4.0            16                    8
  12082         LiVSiO4        1.3         1.0       4.0             2                    1
  27522       Li2V3O3F5        1.3         1.0       4.0             2                    1
   7162       Co(ClO4)2        2.4         2.0       1.0             2                    0
  38191        Li8CoO5F        1.3         1.0       4.0             2                    1
  30688        LiCo2OF3       5.15         5.0       3.0             2                    1
  52083   Li5Co3(SbO5)2        2.4         2.0       1.0             2                    0
  43985        Li4FeO3F      26.76        26.0       4.0             8                    4
  49603    Li3Ni(SbO3)4        1.3         1.0       4.0             2                    1
  30169        LiTiNiO4      15.89        15.0       3.0             4                    2
  55367      Mn3(P2O7)2        1.1         1.0       1.0             1                    0
   8096         Mn2CdO4     70.530        70.0       3.0             8                    4
   6112         Ni2P2O7      15.90        15.0       4.0             8                    4
  28203      CsCr(SO4)2     150.28       150.0       4.0            12                    6
  33213        LiNiAsO4     53.336        53.0       4.0            16                    8
  51934 NaCaMgCr(SiO3)4       5.16         5.0       4.0             4                    2
   4189         Ca2MnO4    142.567       142.0       3.0            16                    8
  49844      SrLaTiMnO6       7.26         7.0       3.0             2                    1
  10652           NbVO4       8.32         8.0       1.0             2                    0
  38352        Li2NiBO4      18.22        18.0       4.0             8                    4
   5659       Sr2NiTeO6      15.91        15.0       4.0             8                    4
  14652         Ca3MnO4        2.7         2.0       4.0             4                    2
  49391      Li2TiFe2O5       9.39         9.0       3.0             2                    1
  31341          VZn2O4      15.90        15.0       4.0             8                    4
   2136        Sr2MnWO6      14.79        14.0       3.0             4                    2
  11073         Ca2MnO3     59.413        59.0       4.0            16                    8
  19228        Sr2CrWO6    123.350       123.0       4.0            32                   16
   5140          NiSeO3     62.447        62.0       3.0             8                    4
   1908       Sr2CoTeO6        2.4         2.0       1.0             2                    0
  13559        Mn(IO3)2        4.9         4.0       3.0             2                    1
  35686         Li8FeO6        2.7         2.0       4.0             4                    2
  20011        Ca2MnWO6        1.3         1.0       4.0             2                    1
   2950        SrFe2S2O     31.123        31.0       1.0             4                    0
  17961       BaSrNiWO6     160.68       160.0       4.0            12                    6
  14465        LiCoAsO4     62.448        62.0       3.0             8                    4
  40225     BaCo2(PO4)2      14.79        14.0       3.0             4                    2
  43891        V3(O2F)2       7.26         7.0       3.0             2                    1
  46201  NaCo2H3(SeO5)2       9.40         9.0       4.0             4                    2
  47297    Li4Ti2Mn3O10        2.7         2.0       4.0             4                    2
  40214      Li4CrGa3O8        1.3         1.0       4.0             2                    1
   2552             CoO    122.338       122.0       4.0            16                    8
  48723     KFeH5(SO5)2        1.3         1.0       4.0             2                    1
  10560          CaV2O5     59.410        59.0       3.0             8                    4
  30779        LiMnSnO4     74.559        74.0       3.0             8                    4
   4286       Zn(FeO2)2    141.555       141.0       3.0            16                    8
   4924          FeCuO2      10.49        10.0       4.0             8                    4
   2797         MgMn2O4     70.530        70.0       3.0             8                    4
   1791          K3NiO2        4.7         4.0       1.0             2                    0
  50092       Li3CrSiO5        2.7         2.0       4.0             4                    2
   4981          LaCrO3     62.447        62.0       3.0             8                    4
  10423       Cs2LiMnO4     31.133        31.0       4.0             8                    4
  16085        Ba2Fe2O5    139.540       139.0       4.0            32                   16
  23771         Ti2CrO5      13.74        13.0       4.0             8                    4
  40753       Li2MnGeO4       9.41         9.0       4.0             4                    2
  41088          MgMnO2    141.555       141.0       3.0            16                    8
  27974      Ba2CoSi2O7    113.271       113.0       3.0             8                    4
  26498         NaCoBO3       5.16         5.0       4.0             4                    2
  17836      BaLaMnSbO6      81.38        81.0       4.0             8                    4
  17885      BaLaTiFeO6     160.68       160.0       4.0            12                    6
  52663   Li4VCr(TeO6)2        1.3         1.0       4.0             2                    1
  25497          CoTeO4       7.27         7.0       4.0             4                    2
  44801         Ta2MnO6      14.80        14.0       4.0             8                    4
  45367    TiMnH12(OF)6        2.7         2.0       4.0             4                    2
  32751      Li2Cr3BiO8    166.102       166.0       4.0            24                   12
  24064         Mn3SnO8    166.102       166.0       4.0            24                   12
  40596         Li2VOF4       5.16         5.0       4.0             4                    2
   9705      Ba3Ta2NiO9      11.55        11.0       4.0             8                    4

MSG type counts:
MSG_type
4.0    44
3.0    21
1.0    10
Name: count, dtype: int64

In [ ]:
# ============================================================
# MSG RESULTS ONLY FOR THE 55 ACTUAL PRELIMINARY AM CANDIDATES
# ============================================================

actual_am_tasks = set(
    rigorous_am_df.loc[
        ~rigorous_am_df["PT_preserved"],
        "task_id"
    ].astype(str)
)

am_msg_df = msg_df[
    msg_df["task_id"].astype(str).isin(actual_am_tasks)
].copy()

print(
    "AM candidates with MSG results:",
    len(am_msg_df)
)

print("\nMSG type counts:")
print(
    am_msg_df["MSG_type"].value_counts(dropna=False)
)

print("\nMSG identification status:")
print(
    am_msg_df["status"].value_counts()
)

AM candidates with MSG results: 55

MSG type counts:
MSG_type
4.0    23
3.0    21
1.0    10
NaN     1
Name: count, dtype: int64

MSG identification status:
status
ok                         54
msg_type_not_identified     1
Name: count, dtype: int64

In [ ]:
# ============================================================
# ML RECOVERY BY ALTERMAGNET SUBTYPE
# ============================================================

# --- Actual DFT ground-state subtype ------------------------

actual_sub = actual_df.copy()

def subtype_from_row(row):
    if not row["AM"]:
        return "non-AM"

    if row["P_preserved"]:
        return "S-type"

    return "S/A-type"


actual_sub["AM_type"] = actual_sub.apply(
    subtype_from_row,
    axis=1
)


# --- ML-selected ground-state subtype ----------------------

pred_sub = predicted_df.copy()

pred_sub["AM_type"] = pred_sub.apply(
    subtype_from_row,
    axis=1
)


# ------------------------------------------------------------
# Map by parent
# ------------------------------------------------------------

actual_sub = actual_sub[
    [
        "parent_structure_id",
        "AM_type"
    ]
].rename(
    columns={"AM_type": "actual_type"}
)

pred_sub = pred_sub[
    [
        "parent_structure_id",
        "AM_type"
    ]
].rename(
    columns={"AM_type": "predicted_type"}
)

sub_comparison = actual_sub.merge(
    pred_sub,
    on="parent_structure_id",
    how="inner"
)


# ------------------------------------------------------------
# Confusion table
# ------------------------------------------------------------

print(
    pd.crosstab(
        sub_comparison["actual_type"],
        sub_comparison["predicted_type"]
    )
)

predicted_type  S-type  S/A-type  non-AM
actual_type
S-type              10         0       9
S/A-type             0        14      22
non-AM               6         7     191

In [ ]:
for subtype in [
    "S-type",
    "S/A-type"
]:

    actual_count = (
        sub_comparison["actual_type"]
        == subtype
    ).sum()

    recovered = (
        (
            sub_comparison["actual_type"]
            == subtype
        )
        &
        (
            sub_comparison["predicted_type"]
            == subtype
        )
    ).sum()

    print(
        f"{subtype}: "
        f"{recovered}/{actual_count} "
        f"= {recovered/actual_count:.2%}"
    )

S-type: 10/19 = 52.63%
S/A-type: 14/36 = 38.89%

Creating AM candidate table

In [ ]:
# ============================================================
# CORRECT MASTER AM TABLE — 55 CANDIDATES
# ============================================================

# Keep ONLY states with rigorously broken PT
master_am = rigorous_am_df[
    rigorous_am_df["PT_preserved"] == False
].copy()

master_am["task_id"] = (
    master_am["task_id"].astype(str)
)

# Add formula / ordering / crystallographic SG
base_info = corrected_am_df[
    ["task_id", "formula", "ordering"]
].copy()

base_info["task_id"] = (
    base_info["task_id"].astype(str)
)

master_am = master_am.merge(
    base_info,
    on="task_id",
    how="left"
)

# Add MSG information
msg_keep = msg_df[
    [
        "task_id",
        "status",
        "BNS_number",
        "OG_number",
        "MSG_number",
        "MSG_type",
        "n_operations",
        "n_time_reversal_ops",
    ]
].copy()

msg_keep["task_id"] = (
    msg_keep["task_id"].astype(str)
)

master_am = master_am.merge(
    msg_keep,
    on="task_id",
    how="left"
)

# Preliminary subtype based on the validated P/T/PT result
master_am["AM_type_preliminary"] = np.where(
    master_am["P_preserved"],
    "S-type",
    "S/A-type"
)

# ------------------------------------------------------------
# Check
# ------------------------------------------------------------

print("Total preliminary AM candidates:",
      len(master_am))

print(
    master_am["AM_type_preliminary"]
    .value_counts()
)

print(
    "\nPT-preserved rows remaining:",
    master_am["PT_preserved"].sum()
)

Total preliminary AM candidates: 55
AM_type_preliminary
S/A-type    36
S-type      19
Name: count, dtype: int64

PT-preserved rows remaining: 0

Saving the table

In [ ]:
output_path = (
    "/content/drive/MyDrive/"
    "Proj_2_Alt_Mags_Grnd_E/"
    "magnetic-topological-materials/"
    "preliminary_AM_candidates.csv"
)

master_am.to_csv(
    output_path,
    index=False
)

print("Corrected file saved:", output_path)

Corrected file saved: /content/drive/MyDrive/Proj_2_Alt_Mags_Grnd_E/magnetic-topological-materials/preliminary_AM_candidates.csv

## Phase - 7 - DFT-saving benchmark

For each parent material containing \(N\) magnetic configurations, conventional screening evaluates all \(N\) configurations with DFT.

Your ML workflow instead:

predicts the energy of every candidate configuration,
ranks them,
sends only the top \(K\) configurations to DFT.

We then measure:

$$ \text{DFT saving}=1-\frac{K}{N} $$

and, more importantly, whether the true DFT ground state is contained in those \(K\) candidates.

In [ ]:
import torch

spin_model_path = (
    "/content/drive/MyDrive/Proj_2_Alt_Mags_Grnd_E/"
    "magnetic-topological-materials/models/"
    "alignn_spin_aware_best.pt"
)

checkpoint = torch.load(
    spin_model_path,
    map_location="cpu"
)

print(type(checkpoint))

if isinstance(checkpoint, dict):
    print("Checkpoint keys:", checkpoint.keys())

<class 'dict'>
Checkpoint keys: dict_keys(['epoch', 'model_state_dict', 'optimizer_state_dict', 'val_mae', 'config'])

In [ ]:
if isinstance(checkpoint, dict) and "state_dict" in checkpoint:
    state_dict = checkpoint["state_dict"]
elif isinstance(checkpoint, dict) and "model_state_dict" in checkpoint:
    state_dict = checkpoint["model_state_dict"]
else:
    state_dict = checkpoint

# Remove possible Lightning "model." prefix
clean_state_dict = {}

for key, value in state_dict.items():
    if key.startswith("model."):
        key = key[len("model."):]
    clean_state_dict[key] = value

missing, unexpected = spin_model.load_state_dict(
    clean_state_dict,
    strict=False
)

print("Missing keys:", missing)
print("Unexpected keys:", unexpected)

spin_model.eval()

print("Spin-aware checkpoint loaded.")

Missing keys: []
Unexpected keys: []
Spin-aware checkpoint loaded.

In [ ]:
batch = next(iter(test_loader))

print("Batch type:", type(batch))
print("Number of items:", len(batch))

for i, item in enumerate(batch):
    print(
        i,
        type(item),
        getattr(item, "shape", None)
    )

Batch type: <class 'list'>
Number of items: 32
0 <class 'tuple'> None
1 <class 'tuple'> None
2 <class 'tuple'> None
3 <class 'tuple'> None
4 <class 'tuple'> None
5 <class 'tuple'> None
6 <class 'tuple'> None
7 <class 'tuple'> None
8 <class 'tuple'> None
9 <class 'tuple'> None
10 <class 'tuple'> None
11 <class 'tuple'> None
12 <class 'tuple'> None
13 <class 'tuple'> None
14 <class 'tuple'> None
15 <class 'tuple'> None
16 <class 'tuple'> None
17 <class 'tuple'> None
18 <class 'tuple'> None
19 <class 'tuple'> None
20 <class 'tuple'> None
21 <class 'tuple'> None
22 <class 'tuple'> None
23 <class 'tuple'> None
24 <class 'tuple'> None
25 <class 'tuple'> None
26 <class 'tuple'> None
27 <class 'tuple'> None
28 <class 'tuple'> None
29 <class 'tuple'> None
30 <class 'tuple'> None
31 <class 'tuple'> None

In [ ]:
print("Dataset item:")
item = test_dataset[0]

print("Number of items:", len(item))

for i, x in enumerate(item):
    print(
        i,
        type(x),
        getattr(x, "shape", None)
    )

Dataset item:
Number of items: 4
0 <class 'alignn.torch_graph_builder.TorchGraph'> None
1 <class 'alignn.torch_graph_builder.TorchGraph'> None
2 <class 'torch.Tensor'> torch.Size([3, 3])
3 <class 'torch.Tensor'> torch.Size([])

In [ ]:
print("test_dataset type:", type(test_dataset))

item = test_dataset[0]

print("Item length:", len(item))
print("Graph node data keys:")
print(item[0].ndata.keys())

test_dataset type: <class 'alignn.pure_lmdb_dataset.PureTorchLMDBDataset'>
Item length: 4
Graph node data keys:
dict_keys(['atom_features', 'frac_coords', 'V', 'Z'])

In [ ]:
print([name for name in globals()
       if "test" in name.lower() and "dataset" in name.lower()])

['test_dataset', 'test_spin_dataset']

In [ ]:
test_df = (
    graph_df[graph_df["split"] == "test"]
    .copy()
    .reset_index(drop=True)
)

test_spin_dataset = SpinAwareDataset(
    test_dataset,
    test_df
)

print("Test spin dataset:", len(test_spin_dataset))

Test spin dataset: 2203

In [ ]:
g, lg, lattice, target = test_spin_dataset[0]

print("Chemical features:", g.ndata["atom_features"].shape)
print("Magmom:", g.ndata["magmom"].shape)

combined = torch.cat(
    [g.ndata["atom_features"], g.ndata["magmom"]],
    dim=1
)

print("Combined:", combined.shape)

Chemical features: torch.Size([26, 92])
Magmom: torch.Size([26, 1])
Combined: torch.Size([26, 93])

In [ ]:
test_loader = torch.utils.data.DataLoader(
    test_spin_dataset,
    batch_size=32,
    shuffle=False,
    collate_fn=lambda x: x
)

print("First batch:", len(next(iter(test_loader))))

First batch: 32

### Step - 7.1 - Generating the 2,203 spin-aware predictions

In [ ]:
import numpy as np
import torch

device = torch.device(
    "cuda" if torch.cuda.is_available() else "cpu"
)

spin_model = spin_model.to(device)
spin_model.eval()

spin_preds = []

with torch.no_grad():

    for batch in test_loader:

        pairs = []

        for g, lg, lattice, target in batch:

            # 92 chemical features + 1 magnetic moment = 93
            g.ndata["atom_features"] = torch.cat(
                [
                    g.ndata["atom_features"],
                    g.ndata["magmom"]
                ],
                dim=1
            )

            pairs.append((g, lg))

        # batch_torch_graph_pairs returns ONLY:
        #     batched_graph, batched_line_graph
        bg, blg = batch_torch_graph_pairs(pairs)

        bg = bg.to(device)
        blg = blg.to(device)

        # `lat` is not used inside forward(), so None is safe here.
        output = spin_model(
            (bg, blg, None)
        )

        pred = output["out"]

        spin_preds.extend(
            pred.detach()
            .cpu()
            .numpy()
            .reshape(-1)
        )

spin_preds = np.asarray(spin_preds)

print("Number of predictions:", len(spin_preds))
print("First 10 predictions:")
print(spin_preds[:10])

Number of predictions: 2203
First 10 predictions:
[-0.00217267 -0.00243372 -0.00132884 -0.0025304  -0.0025501  -0.00280922
 -0.00096319 -0.00247113 -0.00210727 -0.00196555]

In [ ]:
test_df = (
    graph_df[graph_df["split"] == "test"]
    .copy()
    .reset_index(drop=True)
)

assert len(spin_preds) == len(test_df)

test_df["pred_energy"] = spin_preds

print("Prediction alignment verified.")

print(
    test_df[
        [
            "task_id",
            "parent_structure_id",
            "energy_per_atom",
            "pred_energy"
        ]
    ].head(10)
)

Prediction alignment verified.
   task_id                                parent_structure_id  \
0    27890  03184e0f328eb3520417711ec3daa327f40c3aedc29a71...
1    28122  03184e0f328eb3520417711ec3daa327f40c3aedc29a71...
2    27903  03184e0f328eb3520417711ec3daa327f40c3aedc29a71...
3    27988  03184e0f328eb3520417711ec3daa327f40c3aedc29a71...
4    28216  03184e0f328eb3520417711ec3daa327f40c3aedc29a71...
5    28032  03184e0f328eb3520417711ec3daa327f40c3aedc29a71...
6    27958  03184e0f328eb3520417711ec3daa327f40c3aedc29a71...
7    30558  03184e0f328eb3520417711ec3daa327f40c3aedc29a71...
8    28243  03184e0f328eb3520417711ec3daa327f40c3aedc29a71...
9    27877  03184e0f328eb3520417711ec3daa327f40c3aedc29a71...

   energy_per_atom  pred_energy
0        -6.903258    -0.002173
1        -6.902512    -0.002434
2        -6.902529    -0.001329
3        -6.901583    -0.002530
4        -6.902554    -0.002550
5        -6.902315    -0.002809
6        -6.902674    -0.000963
7        -6.902439    -0.002471
8        -6.900660    -0.002107
9        -6.902526    -0.001966

### Step - 7.2 - Running the DFT-saving benchmark

In [ ]:
# ============================================================
# DFT-saving benchmark from spin-aware ALIGNN predictions
# ============================================================

results = []

for parent_id, group in test_df.groupby("parent_structure_id"):

    group = group.copy()

    # True DFT ground-state configuration
    true_idx = group["energy_per_atom"].idxmin()
    true_task = group.loc[true_idx, "task_id"]

    # Rank by predicted relative energy
    ranked = group.sort_values("pred_energy", ascending=True)

    # Position of the true DFT ground state in ML ranking
    true_rank = (
        ranked["task_id"].to_numpy() == true_task
    ).nonzero()[0][0] + 1

    results.append({
        "parent_structure_id": parent_id,
        "n_configs": len(group),
        "true_ground_task": true_task,
        "true_ground_rank": true_rank,
    })

rank_df = pd.DataFrame(results)

print("Parents:", len(rank_df))
print(rank_df["n_configs"].describe())
print(rank_df["true_ground_rank"].describe())

Parents: 259
count    259.000000
mean       8.505792
std        4.023546
min        1.000000
25%        5.000000
50%        8.000000
75%       12.000000
max       16.000000
Name: n_configs, dtype: float64
count    259.000000
mean       4.347490
std        3.448809
min        1.000000
25%        2.000000
50%        3.000000
75%        6.000000
max       15.000000
Name: true_ground_rank, dtype: float64

Calculating the actual savings

In [ ]:
K_values = [1, 2, 3, 5]

benchmark = []

for K in K_values:

    recovered = (
        rank_df["true_ground_rank"] <= K
    ).sum()

    total = len(rank_df)

    recovery = recovered / total

    # Actual number of DFT evaluations per parent
    actual_dft = np.minimum(
        rank_df["n_configs"],
        K
    ).mean()

    full_dft = rank_df["n_configs"].mean()

    saving = 1 - actual_dft / full_dft

    benchmark.append({
        "Strategy": f"ML Top-{K} + DFT",
        "K": K,
        "Ground_state_recovery_%": 100 * recovery,
        "Avg_DFT_per_parent": actual_dft,
        "Avg_full_DFT_per_parent": full_dft,
        "DFT_saving_%": 100 * saving,
    })

benchmark_df = pd.DataFrame(benchmark)

print(benchmark_df.to_string(index=False))

      Strategy  K  Ground_state_recovery_%  Avg_DFT_per_parent  Avg_full_DFT_per_parent  DFT_saving_%
ML Top-1 + DFT  1                24.710425            1.000000                 8.505792     88.243305
ML Top-2 + DFT  2                41.312741            1.980695                 8.505792     76.713572
ML Top-3 + DFT  3                53.281853            2.945946                 8.505792     65.365411
ML Top-5 + DFT  5                69.498069            4.625483                 8.505792     45.619610

Calculating the rank distribution

In [ ]:
print("\nGround-state rank distribution:")

print(
    rank_df["true_ground_rank"]
    .value_counts()
    .sort_index()
    .head(15)
)

Ground-state rank distribution:
true_ground_rank
1     64
2     43
3     31
4     25
5     17
6     16
7     15
8     12
9      7
10     4
11    10
12    10
13     3
14     1
15     1
Name: count, dtype: int64

In [ ]:
print("\nRecovery at selected K:")

for K in [1, 2, 3, 5, 10]:

    recovery = (
        rank_df["true_ground_rank"] <= K
    ).mean()

    print(
        f"Top-{K}: "
        f"{100*recovery:.2f}% ground-state recovery"
    )

Recovery at selected K:
Top-1: 24.71% ground-state recovery
Top-2: 41.31% ground-state recovery
Top-3: 53.28% ground-state recovery
Top-5: 69.50% ground-state recovery
Top-10: 90.35% ground-state recovery

DFT saving benchmark

| Strategy        | Ground-state recovery | Avg DFT/parent | DFT saving |
| --------------- | --------------------: | -------------: | ---------: |
| ML Top-1 + DFT  |            **24.71%** |           1.00 | **88.24%** |
| ML Top-2 + DFT  |            **41.31%** |           1.98 | **76.71%** |
| ML Top-3 + DFT  |            **53.28%** |           2.95 | **65.37%** |
| ML Top-5 + DFT  |            **69.50%** |           4.63 | **45.62%** |
| ML Top-10 + DFT |            **90.35%** |              — |          — |

The key result is that Top-5 retains 69.50% of the true magnetic ground states while reducing the average DFT workload by 45.62%.

Even more interestingly, 90.35% of ground states appear within the ML Top-10. That gives you a very useful screening strategy: use ALIGNN to reduce the candidate configurations substantially, then perform DFT only on the shortlisted states.

What does “Top-K” mean?

For one material, suppose you have 8 possible magnetic configurations.

The true DFT energies might be:

| Configuration | DFT energy |
| ------------- | ---------: |
| A             |    -10.000 |
| B             |     -9.995 |
| C             |     -9.990 |
| D             |     -9.970 |
| E             |     -9.950 |
| F             |     -9.920 |
| G             |     -9.900 |
| H             |     -9.850 |

The true ground state is A because it has the lowest energy.

Your spin-aware ALIGNN does not know the DFT energies. It predicts energies and ranks the configurations.

Suppose it predicts this ranking:

C → B → A → D → E → F → G → H

Then:

* Top-1 = only C is selected.
* Top-2 = C and B are selected.
* Top-3 = C, B and A are selected.
* Top-5 = C, B, A, D and E are selected.

Because A is ranked 3rd, this material's ground state is recovered at Top-3, but not Top-1 or Top-2.

So:

Top-K means: take the K configurations that ALIGNN predicts to be lowest in energy, and then perform DFT on only those K configurations.

### Step - 7.3 - AM-specific DFT-saving benchmark

In [ ]:
import pandas as pd
import numpy as np

# ============================================================
# AM-specific benchmark
# ============================================================

am_path = (
    "/content/drive/MyDrive/Proj_2_Alt_Mags_Grnd_E/"
    "magnetic-topological-materials/"
    "preliminary_AM_candidates.csv"
)

am_df = pd.read_csv(am_path)

print("AM candidate rows:", len(am_df))
print("\nColumns:")
print(am_df.columns.tolist())

AM candidate rows: 55

Columns:
['spacegroup', 'P_preserved', 'T_preserved', 'PT_preserved', 'task_id', 'formula_x', 'ordering_x', 'net_moment', 'formula_y', 'ordering_y', 'status', 'BNS_number', 'OG_number', 'MSG_number', 'MSG_type', 'n_operations', 'n_time_reversal_ops', 'AM_type_preliminary']

In [ ]:
# ------------------------------------------------------------
# Inspect the important identifiers
# ------------------------------------------------------------

for col in [
    "task_id",
    "parent_structure_id",
    "formula",
    "AM_type_preliminary"
]:
    if col in am_df.columns:
        print(f"{col}: available")

print("\nFirst rows:")
print(am_df.head())

task_id: available
AM_type_preliminary: available

First rows:
  spacegroup  P_preserved  T_preserved  PT_preserved  task_id      formula_x  \
0        P-1         True        False         False    28294    Li2Fe(WO4)2
1         Cm        False        False         False    45309  NaCo2H3(SO5)2
2         P1        False        False         False    42065      Li2SiNiO4
3         P2        False        False         False     8924         LiFeOF
4         P1        False        False         False    51857    SrCo(GeO3)2

  ordering_x    net_moment      formula_y ordering_y status  BNS_number  \
0        AFM  0.000000e+00    Li2Fe(WO4)2        AFM     ok        2.40
1        AFM  0.000000e+00  NaCo2H3(SO5)2        AFM     ok        8.34
2        AFM  1.179612e-16      Li2SiNiO4        AFM     ok        1.10
3        AFM  0.000000e+00         LiFeOF        AFM     ok        5.17
4        FiM  1.110223e-16    SrCo(GeO3)2        FiM     ok        1.10

  OG_number  MSG_number  MSG_type  n_operations  n_time_reversal_ops  \
0     2.1.4         2.0       1.0             2                    0
1    8.3.40         8.0       3.0             2                    1
2     1.1.1         1.0       1.0             1                    0
3    3.6.13         5.0       4.0             4                    2
4     1.1.1         1.0       1.0             1                    0

  AM_type_preliminary
0              S-type
1            S/A-type
2            S/A-type
3            S/A-type
4            S/A-type

Building the AM ground-state set

In [ ]:
# ============================================================
# Build AM ground-state table using task_id
# ============================================================

# Keep only the information we need from the AM CSV
am_tasks = am_df[["task_id"]].copy()

# Add parent_structure_id and other information from test_df
am_tasks = am_tasks.merge(
    test_df[
        [
            "task_id",
            "parent_structure_id",
            "formula"
        ]
    ],
    on="task_id",
    how="left"
)

print("AM rows:", len(am_tasks))
print("Missing parent IDs:", am_tasks["parent_structure_id"].isna().sum())

print(am_tasks.head())

AM rows: 55
Missing parent IDs: 0
   task_id                                parent_structure_id        formula
0    28294  03184e0f328eb3520417711ec3daa327f40c3aedc29a71...    Li2Fe(WO4)2
1    45309  058f1a5e5a832ef8c60446520b8dfe10343754673fe52c...  NaCo2H3(SO5)2
2    42065  1335ae835b85cac9354d750d6202caee4bc14714989dd3...      Li2SiNiO4
3     8924  1910aa503022352be10602ee45456856eb48216f7bdd2c...         LiFeOF
4    51857  1c689144a8fa2b1e01a9abdd1c6efc23390a0d9734b4e1...    SrCo(GeO3)2

Calculating the predicted rank of each actual AM ground-state configuration

In [ ]:
# ============================================================
# Rank each known AM ground-state configuration
# ============================================================

am_rank_results = []

for _, row in am_tasks.iterrows():

    task_id = row["task_id"]
    parent_id = row["parent_structure_id"]

    # All magnetic configurations for this parent
    group = (
        test_df[
            test_df["parent_structure_id"] == parent_id
        ]
        .copy()
        .sort_values("pred_energy", ascending=True)
        .reset_index(drop=True)
    )

    matches = np.where(
        group["task_id"].to_numpy() == task_id
    )[0]

    if len(matches) == 0:
        print("WARNING: task not found:", task_id)
        continue

    rank = int(matches[0]) + 1

    am_rank_results.append({
        "task_id": task_id,
        "parent_structure_id": parent_id,
        "formula": row["formula"],
        "n_configs": len(group),
        "AM_ground_rank": rank
    })

am_rank_df = pd.DataFrame(am_rank_results)

print("AM parents ranked:", len(am_rank_df))

print("\nRank distribution:")
print(
    am_rank_df["AM_ground_rank"]
    .value_counts()
    .sort_index()
)

AM parents ranked: 55

Rank distribution:
AM_ground_rank
1     12
2      8
3      9
4      8
5      3
6      4
7      3
8      3
9      1
10     1
11     1
12     1
13     1
Name: count, dtype: int64

The benchmark

In [ ]:
# ============================================================
# AM-specific Top-K recovery
# ============================================================

K_values = [1, 2, 3, 5, 10]

am_benchmark = []

for K in K_values:

    recovered = (
        am_rank_df["AM_ground_rank"] <= K
    ).sum()

    total = len(am_rank_df)

    recovery = recovered / total

    actual_dft = np.minimum(
        am_rank_df["n_configs"],
        K
    ).mean()

    full_dft = am_rank_df["n_configs"].mean()

    dft_saving = 1 - actual_dft / full_dft

    am_benchmark.append({
        "Strategy": f"ML Top-{K} + DFT",
        "K": K,
        "AM_recovery_%": 100 * recovery,
        "Recovered_AM": recovered,
        "Total_AM": total,
        "Avg_DFT_per_AM_parent": actual_dft,
        "Avg_full_DFT_per_AM_parent": full_dft,
        "DFT_saving_%": 100 * dft_saving
    })

am_benchmark_df = pd.DataFrame(am_benchmark)

print(
    am_benchmark_df.to_string(index=False)
)

       Strategy  K  AM_recovery_%  Recovered_AM  Total_AM  Avg_DFT_per_AM_parent  Avg_full_DFT_per_AM_parent  DFT_saving_%
 ML Top-1 + DFT  1      21.818182            12        55               1.000000                    8.072727     87.612613
 ML Top-2 + DFT  2      36.363636            20        55               2.000000                    8.072727     75.225225
 ML Top-3 + DFT  3      52.727273            29        55               2.981818                    8.072727     63.063063
 ML Top-5 + DFT  5      72.727273            40        55               4.563636                    8.072727     43.468468
ML Top-10 + DFT 10      94.545455            52        55               7.145455                    8.072727     11.486486

In [ ]:
print("\nAM recovery:")
for K in K_values:

    recovered = (
        am_rank_df["AM_ground_rank"] <= K
    ).sum()

    print(
        f"Top-{K}: {recovered}/55 "
        f"= {100*recovered/55:.2f}%"
    )

AM recovery:
Top-1: 12/55 = 21.82%
Top-2: 20/55 = 36.36%
Top-3: 29/55 = 52.73%
Top-5: 40/55 = 72.73%
Top-10: 52/55 = 94.55%

Your 55 known preliminary AM ground states have the following ALIGNN ranks:

| Top-K  | AM ground states recovered | AM recovery | Avg DFT/AM parent | DFT saving |
| ------ | -------------------------: | ----------: | ----------------: | ---------: |
| Top-1  |                      12/55 |  **21.82%** |              1.00 | **87.61%** |
| Top-2  |                      20/55 |  **36.36%** |              2.00 | **75.23%** |
| Top-3  |                      29/55 |  **52.73%** |              2.98 | **63.06%** |
| Top-5  |                      40/55 |  **72.73%** |              4.56 | **43.47%** |
| Top-10 |                      52/55 |  **94.55%** |              7.15 | **11.49%** |

The strongest result here is:

Top-5 recovers 40 of the 55 known AM ground states (72.73%) while reducing the average DFT workload by 43.47%.

And an even stronger recovery result is:

Top-10 recovers 52/55 = 94.55% of AM ground states.

Only 3 AM ground states fall outside the Top-10.

Compare this with the all-material benchmark

This comparison is interesting:

| Strategy | All test ground states | AM ground states |
| -------- | ---------------------: | ---------------: |
| Top-1    |                 24.71% |           21.82% |
| Top-3    |                 53.28% |           52.73% |
| Top-5    |                 69.50% |       **72.73%** |
| Top-10   |                 90.35% |       **94.55%** |

So the model's ranking performance on the AM subset is not dramatically worse than its performance on the full test set, and at Top-5/Top-10 it is actually slightly better.

Running the same symmetry classifier on the 55 known AM ground states.

In [ ]:
import numpy as np
import pandas as pd
import spglib
from pymatgen.core import Element, Structure

# ------------------------------------------------------------
# Symmetry-based preliminary AM classifier
# ------------------------------------------------------------

def classify_preliminary_am(record, symprec=1e-2, net_tol=1e-3):

    structure_dict = record["input"]["structure"]

    structure = Structure.from_dict(structure_dict)

    lattice = np.asarray(structure.lattice.matrix, dtype=float)
    frac_coords = np.asarray(structure.frac_coords, dtype=float)

    numbers = np.array(
        [site.specie.Z for site in structure],
        dtype=int
    )

    magmoms = np.asarray(
        record["magmoms"]["vasp"],
        dtype=float
    )

    # Magnetic symmetry
    msym = spglib.get_magnetic_symmetry(
        (lattice, frac_coords, numbers, magmoms),
        symprec=symprec
    )

    if msym is None:
        return {
            "P_preserved": None,
            "T_preserved": None,
            "PT_preserved": None,
            "net_moment": float(np.sum(magmoms)),
            "compensated": False,
            "AM_candidate": False,
            "AM_type_preliminary": "unresolved",
        }

    rotations = np.asarray(msym["rotations"])
    translations = np.asarray(msym["translations"])
    time_reversals = np.asarray(msym["time_reversals"])

    I = np.eye(3, dtype=int)
    minus_I = -I

    # Pure inversion P
    P_preserved = any(
        np.array_equal(R, minus_I) and tr == 0
        for R, tr in zip(rotations, time_reversals * 0)
    )

    # The expression above cannot use translations that way;
    # use time_reversal explicitly below.
    P_preserved = any(
        np.array_equal(R, minus_I) and (tr == 0)
        and (int(trev) == 0)
        for R, tr, trev in zip(
            rotations, translations, time_reversals
        )
    )

    # Pure time reversal T:
    # spatial identity + time reversal
    T_preserved = any(
        np.array_equal(R, I) and (int(trev) == 1)
        for R, tr, trev in zip(
            rotations, translations, time_reversals
        )
        if np.allclose(tr % 1.0, 0.0, atol=symprec)
    )

    # PT:
    # inversion + time reversal
    PT_preserved = any(
        np.array_equal(R, minus_I) and (int(trev) == 1)
        for R, tr, trev in zip(
            rotations, translations, time_reversals
        )
    )

    net_moment = float(np.sum(magmoms))
    compensated = abs(net_moment) <= net_tol

    # Preliminary AM criterion:
    # compensated + T broken + PT broken
    AM_candidate = (
        compensated
        and not T_preserved
        and not PT_preserved
    )

    if AM_candidate:
        if P_preserved:
            am_type = "S-type"
        else:
            am_type = "S/A-type"
    else:
        am_type = "non-AM"

    return {
        "P_preserved": P_preserved,
        "T_preserved": T_preserved,
        "PT_preserved": PT_preserved,
        "net_moment": net_moment,
        "compensated": compensated,
        "AM_candidate": AM_candidate,
        "AM_type_preliminary": am_type,
    }

In [ ]:
def classify_preliminary_am(record, symprec=1e-2, net_tol=1e-3):

    structure = Structure.from_dict(
        record["input"]["structure"]
    )

    lattice = np.asarray(
        structure.lattice.matrix,
        dtype=float
    )

    frac_coords = np.asarray(
        structure.frac_coords,
        dtype=float
    )

    numbers = np.array(
        [site.specie.Z for site in structure],
        dtype=int
    )

    magmoms = np.asarray(
        record["magmoms"]["vasp"],
        dtype=float
    )

    msym = spglib.get_magnetic_symmetry(
        (lattice, frac_coords, numbers, magmoms),
        symprec=symprec
    )

    if msym is None:
        return {
            "P_preserved": None,
            "T_preserved": None,
            "PT_preserved": None,
            "net_moment": float(np.sum(magmoms)),
            "compensated": False,
            "AM_candidate": False,
            "AM_type_preliminary": "unresolved",
        }

    rotations = np.asarray(msym["rotations"])
    translations = np.asarray(msym["translations"])
    time_reversals = np.asarray(msym["time_reversals"])

    I = np.eye(3, dtype=int)
    minus_I = -I

    P_preserved = False
    T_preserved = False
    PT_preserved = False

    for R, tr, trev in zip(
        rotations,
        translations,
        time_reversals
    ):

        zero_translation = np.allclose(
            tr % 1.0,
            0.0,
            atol=symprec
        )

        if np.array_equal(R, minus_I) and trev == 0:
            P_preserved = True

        if (
            np.array_equal(R, I)
            and trev == 1
            and zero_translation
        ):
            T_preserved = True

        if np.array_equal(R, minus_I) and trev == 1:
            PT_preserved = True

    net_moment = float(np.sum(magmoms))

    compensated = abs(net_moment) <= net_tol

    AM_candidate = (
        compensated
        and not T_preserved
        and not PT_preserved
    )

    if AM_candidate:
        AM_type = (
            "S-type"
            if P_preserved
            else "S/A-type"
        )
    else:
        AM_type = "non-AM"

    return {
        "P_preserved": P_preserved,
        "T_preserved": T_preserved,
        "PT_preserved": PT_preserved,
        "net_moment": net_moment,
        "compensated": compensated,
        "AM_candidate": AM_candidate,
        "AM_type_preliminary": AM_type,
    }

Validating against the 55 known AM candidates

In [ ]:
# ------------------------------------------------------------
# Build task -> DFT record lookup
# ------------------------------------------------------------

records_by_task = {
    int(r["task_id"]): r
    for r in records
}

print("Records available:", len(records_by_task))

Records available: 22459

In [ ]:
task_id = int(am_df["task_id"].iloc[0])
rec = records_by_task[task_id]

print("Task:", task_id)
print("Record type:", type(rec))

if isinstance(rec, dict):
    print("Top-level keys:")
    print(rec.keys())

    for key, value in rec.items():
        print(
            f"{key}:",
            type(value),
            (
                list(value.keys())
                if isinstance(value, dict)
                else ""
            )
        )
else:
    print(rec)

Task: 28294
Record type: <class 'dict'>
Top-level keys:
dict_keys(['task_id', 'parent_structure_id', 'formula', 'input_structure', 'initial_magmoms', 'delta_E', 'energy_per_atom', 'ordering', 'ordering_changed', 'n_dft_records', 'input_ordering', 'origin', 'input_index', 'index'])
task_id: <class 'int'>
parent_structure_id: <class 'str'>
formula: <class 'str'>
input_structure: <class 'dict'> ['@module', '@class', 'charge', 'lattice', 'sites', '@version']
initial_magmoms: <class 'list'>
delta_E: <class 'float'>
energy_per_atom: <class 'float'>
ordering: <class 'str'>
ordering_changed: <class 'bool'>
n_dft_records: <class 'int'>
input_ordering: <class 'str'>
origin: <class 'str'>
input_index: <class 'int'>
index: <class 'int'>

In [ ]:
print("AM CSV columns:")
print(am_df.columns.tolist())

AM CSV columns:
['spacegroup', 'P_preserved', 'T_preserved', 'PT_preserved', 'task_id', 'formula_x', 'ordering_x', 'net_moment', 'formula_y', 'ordering_y', 'status', 'BNS_number', 'OG_number', 'MSG_number', 'MSG_type', 'n_operations', 'n_time_reversal_ops', 'AM_type_preliminary']

Proceeding without reclassifying those 55

In [ ]:
# ============================================================
# Final AM recovery table
# ============================================================

K_values = [1, 2, 3, 5, 10]

am_recovery = []

for K in K_values:

    recovered = (
        am_rank_df["AM_ground_rank"] <= K
    ).sum()

    total = len(am_rank_df)

    am_recovery.append({
        "K": K,
        "Recovered_AM": recovered,
        "Total_AM": total,
        "AM_recovery_%": 100 * recovered / total,
    })

am_recovery_df = pd.DataFrame(am_recovery)

print(am_recovery_df.to_string(index=False))

 K  Recovered_AM  Total_AM  AM_recovery_%
 1            12        55      21.818182
 2            20        55      36.363636
 3            29        55      52.727273
 5            40        55      72.727273
10            52        55      94.545455

AM recovery table:

| ML shortlist | AM ground states recovered | AM recovery |
| ------------ | -------------------------: | ----------: |
| Top-1        |                      12/55 |  **21.82%** |
| Top-2        |                      20/55 |  **36.36%** |
| Top-3        |                      29/55 |  **52.73%** |
| Top-5        |                      40/55 |  **72.73%** |
| Top-10       |                      52/55 |  **94.55%** |

S-type vs S/A-type recovery

In [ ]:
# ============================================================
# AM subtype recovery as a function of Top-K
# ============================================================

am_rank_typed = am_rank_df.merge(
    am_df[
        [
            "task_id",
            "AM_type_preliminary"
        ]
    ],
    on="task_id",
    how="left"
)

print(
    am_rank_typed[
        "AM_type_preliminary"
    ].value_counts()
)

AM_type_preliminary
S/A-type    36
S-type      19
Name: count, dtype: int64

In [ ]:
K_values = [1, 2, 3, 5, 10]

subtype_results = []

for subtype in ["S-type", "S/A-type"]:

    subset = am_rank_typed[
        am_rank_typed["AM_type_preliminary"] == subtype
    ]

    for K in K_values:

        recovered = (
            subset["AM_ground_rank"] <= K
        ).sum()

        total = len(subset)

        subtype_results.append({
            "AM_type": subtype,
            "Top_K": K,
            "Recovered": recovered,
            "Total": total,
            "Recovery_%": 100 * recovered / total
        })

subtype_df = pd.DataFrame(subtype_results)

print(
    subtype_df.to_string(index=False)
)

 AM_type  Top_K  Recovered  Total  Recovery_%
  S-type      1          9     19   47.368421
  S-type      2         11     19   57.894737
  S-type      3         16     19   84.210526
  S-type      5         18     19   94.736842
  S-type     10         18     19   94.736842
S/A-type      1          3     36    8.333333
S/A-type      2          9     36   25.000000
S/A-type      3         13     36   36.111111
S/A-type      5         22     36   61.111111
S/A-type     10         34     36   94.444444

Identifying the 3 AM states missed even by Top-10

In [ ]:
missed_top10 = am_rank_typed[
    am_rank_typed["AM_ground_rank"] > 10
].sort_values("AM_ground_rank")

print(
    missed_top10[
        [
            "task_id",
            "formula",
            "AM_type_preliminary",
            "AM_ground_rank"
        ]
    ].to_string(index=False)
)

 task_id         formula AM_type_preliminary  AM_ground_rank
   52083   Li5Co3(SbO5)2              S-type              11
   51934 NaCaMgCr(SiO3)4            S/A-type              12
   12082         LiVSiO4            S/A-type              13

S-type is much easier for the model to recover

| Top-K  | S-type recovered | S-type total |   Recovery |
| ------ | ---------------: | -----------: | ---------: |
| Top-1  |                9 |           19 | **47.37%** |
| Top-2  |               11 |           19 | **57.89%** |
| Top-3  |               16 |           19 | **84.21%** |
| Top-5  |               18 |           19 | **94.74%** |
| Top-10 |               18 |           19 | **94.74%** |

S/A-type is substantially harder at low K

| Top-K  | S/A-type recovered | S/A total |   Recovery |
| ------ | -----------------: | --------: | ---------: |
| Top-1  |                  3 |        36 |  **8.33%** |
| Top-2  |                  9 |        36 | **25.00%** |
| Top-3  |                 13 |        36 | **36.11%** |
| Top-5  |                 22 |        36 | **61.11%** |
| Top-10 |                 34 |        36 | **94.44%** |

Current researchsummary:

Spin-aware ALIGNN

→ better ground-state ranking than structure-only ALIGNN

→ 24.71% Top-1 exact ground-state accuracy

→ 69.50% Top-5 ground-state recovery

→ 45.62% average DFT saving on the full test set

and specifically for preliminary AM ground states:

→ 72.73% AM recovery at Top-5

→ 43.47% DFT saving

→ 94.55% AM recovery at Top-10

with subtype behavior:

→ S-type: 94.74% Top-5

→ S/A-type: 61.11% Top-5

→ both ≈ 94.5% Top-10

The three difficult AM cases

You have identified exactly the three Top-10 failures:

|  Task | Material        | Preliminary type | ML rank |
| ----: | --------------- | ---------------- | ------: |
| 52083 | Li5Co3(SbO5)2   | S-type           |  **11** |
| 51934 | NaCaMgCr(SiO3)4 | S/A-type         |  **12** |
| 12082 | LiVSiO4         | S/A-type         |  **13** |

### Step - 7.4 - Error analysis

In [ ]:
# ============================================================
# ERROR ANALYSIS: THE 3 AM STATES MISSED BY TOP-10
# ============================================================

missed_top10 = am_rank_typed[
    am_rank_typed["AM_ground_rank"] > 10
].copy()

print("Missed AM states:")
print(
    missed_top10[
        [
            "task_id",
            "formula",
            "AM_type_preliminary",
            "AM_ground_rank",
            "n_configs",
        ]
    ].to_string(index=False)
)


# ------------------------------------------------------------
# Detailed analysis for each missed AM ground state
# ------------------------------------------------------------

error_rows = []

for _, row in missed_top10.iterrows():

    task_id = row["task_id"]
    parent_id = row["parent_structure_id"]

    group = (
        test_df[
            test_df["parent_structure_id"] == parent_id
        ]
        .copy()
        .sort_values("pred_energy")
        .reset_index(drop=True)
    )

    # Actual ground state
    actual_row = group.loc[
        group["task_id"] == task_id
    ].iloc[0]

    # ML-selected state
    predicted_row = group.iloc[0]

    # Actual first-excited-state gap
    true_sorted = group.sort_values("delta_E")

    energies = true_sorted["delta_E"].to_numpy()

    if len(energies) >= 2:
        true_gap = energies[1] - energies[0]
    else:
        true_gap = np.nan

    # Absolute prediction error of actual AM ground state
    actual_prediction_error = (
        abs(
            actual_row["pred_energy"]
            - actual_row["delta_E"]
        )
    )

    # Energy regret of ML-selected state
    regret = predicted_row["delta_E"]

    error_rows.append({
        "task_id": task_id,
        "formula": row["formula"],
        "AM_type": row["AM_type_preliminary"],
        "AM_rank": row["AM_ground_rank"],
        "n_configs": len(group),
        "true_gap_eV_atom": true_gap,
        "AM_true_delta_E": actual_row["delta_E"],
        "AM_predicted_delta_E": actual_row["pred_energy"],
        "AM_abs_prediction_error":
            actual_prediction_error,
        "ML_selected_task":
            predicted_row["task_id"],
        "ML_selected_true_delta_E":
            predicted_row["delta_E"],
        "ML_selected_regret":
            regret,
    })

error_df = pd.DataFrame(error_rows)

print("\n==============================")
print("TOP-10 MISSED AM ERROR ANALYSIS")
print("==============================")

print(
    error_df.to_string(index=False)
)

Missed AM states:
 task_id         formula AM_type_preliminary  AM_ground_rank  n_configs
   12082         LiVSiO4            S/A-type              13         13
   52083   Li5Co3(SbO5)2              S-type              11         14
   51934 NaCaMgCr(SiO3)4            S/A-type              12         12

==============================
TOP-10 MISSED AM ERROR ANALYSIS
==============================
 task_id         formula  AM_type  AM_rank  n_configs  true_gap_eV_atom  AM_true_delta_E  AM_predicted_delta_E  AM_abs_prediction_error  ML_selected_task  ML_selected_true_delta_E  ML_selected_regret
   12082         LiVSiO4 S/A-type       13         13      1.093839e-04              0.0              0.002679                 0.002679             11755                  0.000364            0.000364
   52083   Li5Co3(SbO5)2   S-type       11         14      4.323500e-06              0.0              0.003360                 0.003360             51990                  0.005193            0.005193
   51934 NaCaMgCr(SiO3)4 S/A-type       12         12      8.077500e-07              0.0              0.004680                 0.004680             50506                  0.000484            0.000484

Checking whether these difficult cases involve DFT magnetic-order changes:

In [ ]:
# Add ordering_changed information

ordering_info = graph_df[
    [
        "task_id",
        "ordering",
        "ordering_changed"
    ]
].copy()

ordering_info["task_id"] = (
    ordering_info["task_id"].astype(str)
)

error_df["task_id"] = (
    error_df["task_id"].astype(str)
)

error_df = error_df.merge(
    ordering_info,
    on="task_id",
    how="left"
)

print(
    error_df[
        [
            "task_id",
            "formula",
            "AM_type",
            "AM_rank",
            "true_gap_eV_atom",
            "ordering",
            "ordering_changed"
        ]
    ].to_string(index=False)
)

task_id         formula  AM_type  AM_rank  true_gap_eV_atom ordering  ordering_changed
  12082         LiVSiO4 S/A-type       13      1.093839e-04      AFM             False
  52083   Li5Co3(SbO5)2   S-type       11      4.323500e-06      FiM             False
  51934 NaCaMgCr(SiO3)4 S/A-type       12      8.077500e-07      AFM             False

1. LiVSiO₄ — task 12082

AM type: S/A-type

AM ground-state rank: 13

Number of configurations: 13

Ground-to-first-excited DFT gap:

0.000109 eV/atom = 0.109 meV/atom

ML prediction for the true AM ground state:

0.002679 eV/atom

Absolute prediction error:

2.679 meV/atom

ML-selected configuration has true DFT regret:

0.364 meV/atom


So the model substantially overestimated the true ground state by about 2.68 meV/atom. Because the actual DFT gap is only 0.109 meV/atom, even a small prediction error can move the true ground state far down the ranking.

The good news is that the configuration selected by ML is still quite close to the actual ground state: only 0.364 meV/atom above it.

2. Li₅Co₃(SbO₅)₂ — task 52083

This is particularly interesting because it is S-type, yet it is still missed.

AM type: S-type

AM ground-state rank: 11

Number of configurations: 14

Ground-state gap:

0.0000043235 eV/atom = 0.00432 meV/atom

That gap is essentially zero on the scale of the ML errors.


The model predicts the true ground state at:

0.003360 eV/atom = 3.360 meV/atom

while the configuration it selects has:

0.005193 eV/atom = 5.193 meV/atom

of actual DFT regret.

This is the most serious of the three failures because the wrong ML choice is not just slightly above the ground state. It is about 5.19 meV/atom higher.

But notice how tiny the actual ground-state gap is:

0.0043 meV/atom

compared with a prediction error of 3.36 meV/atom.

So asking the model to distinguish these two states requires resolving an energy difference roughly 780 times smaller than the error scale of the ground-state prediction.

3. NaCaMgCr(SiO₃)₄ — task 51934

AM type: S/A-type

AM ground-state rank: 12

Number of configurations: 12

Ground-state gap:

0.00000080775 eV/atom = 0.000808 meV/atom


This is an even more extreme near-degeneracy.

The true AM ground state is predicted at:

0.004680 eV/atom = 4.680 meV/atom

but the ML-selected configuration is only:

0.000484 eV/atom = 0.484 meV/atom

above the actual DFT ground state.

So although the model completely misses the exact AM ground state, its selected configuration is still energetically very close to it.

| Material        | DFT ground-state gap | Ground-state prediction error | Selected-state regret |
| --------------- | -------------------: | ----------------------------: | --------------------: |
| LiVSiO₄         |            0.109 meV |                     2.679 meV |             0.364 meV |
| Li₅Co₃(SbO₅)₂   |           0.0043 meV |                     3.360 meV |             5.193 meV |
| NaCaMgCr(SiO₃)₄ |           0.0008 meV |                     4.680 meV |             0.484 meV |

## Phase - 8 - Workflow summary

We have the table of top-k results:

| ML screening | AM ground-state recovery | DFT saving |
| ------------ | -----------------------: | ---------: |
| Top-1        |                   21.82% |     87.61% |
| Top-3        |                   52.73% |     63.06% |
| **Top-5**    |               **72.73%** | **43.47%** |
| Top-10       |               **94.55%** |     11.49% |


So:

Top-5 is a good efficiency compromise, but Top-10 is much safer for discovering AMs.

The exact pipeline is,

**Step 1 — Use the spin-aware ALIGNN model**

For each of the 259 parent structures:

$$ \text{all magnetic configurations} \rightarrow \text{ALIGNN prediction} \rightarrow \text{rank configurations by predicted }\Delta E $$

Then retain the Top-5 configurations.

That gives approximately:

$$ 259\times5 \approx 1295 $$

candidate configurations instead of evaluating all 2203 configurations.

**Step 2 — Perform the actual DFT/symmetry validation on these candidates**

For each Top-5 candidate:

* Obtain/perform its DFT calculation.

* Determine its magnetic ground-state energy.

* Check magnetic compensation:

$$ M_{\mathrm{tot}}\approx0 $$
* Determine \(P\), \(T\), and \(PT\) symmetry.
* Classify the magnetic symmetry.

* Keep only states satisfying your AM criterion:

$$ T\text{ broken},\qquad PT\text{ broken} $$

with the appropriate spin-space symmetry analysis for the final AM claim.

This is the stage where we identify the real altermagnet candidates.

We will initially use:

Top-5 as the primary screening set + Top-10 as a rescue set.

Why?

Your Top-5 misses:

$$ 15/55=27.27\% $$

of the known AM ground states.

Top-10 reduces that to only:

$$ 3/55=5.45\%. $$

And those remaining three are exactly the extreme near-degenerate cases we just analyzed.

#### **In short:**

All configurations
Spin-aware ALIGNN → Rank by predicted ΔE → Top-5 → DFT + magnetic symmetry → Real AM candidates → Top-10 rescue → Only for candidates not captured/confirmed in Top-5


We should not simply classify every Top-5 prediction as AM.

The model predicts energy; it does not prove altermagnetic symmetry.

The final chain has to be:

$$ML~ranking~→~DFT~ground-state~verification~→~magnetic~symmetry~→~AM~classification$$
	​

### Step - 8.1 - Constructing a table for all 259 test parents

parent_id

formula

ML Top-1 task

ML Top-2 task

ML Top-3 task

ML Top-4 task

ML Top-5 task

actual DFT ground-state task

actual AM?

AM type



Running top-5 AM discovery screen and answer:

"Out of the 259 materials, how many genuine altermagnets would our ML workflow discover using only the five lowest predicted configurations?"

#### Building the Top-5 screening set

In [ ]:
import pandas as pd
import numpy as np

# Make sure each parent's configurations are ranked by predicted energy
ranked_test = (
    test_df
    .sort_values(["parent_structure_id", "pred_energy"])
    .copy()
)

# Rank within each parent
ranked_test["ML_rank"] = (
    ranked_test.groupby("parent_structure_id").cumcount() + 1
)

# Select the 5 lowest predicted-energy configurations per parent
top5_df = (
    ranked_test[ranked_test["ML_rank"] <= 5]
    .copy()
)

print("Total test configurations:", len(test_df))
print("Number of parents:", test_df["parent_structure_id"].nunique())
print("Top-5 screening configurations:", len(top5_df))

print("\nAverage number of Top-5 candidates per parent:",
      len(top5_df) / test_df["parent_structure_id"].nunique())

Total test configurations: 2203
Number of parents: 259
Top-5 screening configurations: 1198

Average number of Top-5 candidates per parent: 4.625482625482626

### Step - 8.2 - Marking which Top-5 configurations are known AM ground states

In [ ]:
# AM ground-state task IDs
am_ground_ids = set(master_am["task_id"].astype(int))

# Mark known AM ground states inside Top-5
top5_df["known_AM_ground"] = (
    top5_df["task_id"].astype(int).isin(am_ground_ids)
)

# Attach AM type
am_type_map = (
    master_am
    .set_index("task_id")["AM_type_preliminary"]
    .to_dict()
)

top5_df["AM_type_preliminary"] = (
    top5_df["task_id"].astype(int).map(am_type_map)
)

# Number of known AM ground states recovered
recovered_top5 = top5_df["known_AM_ground"].sum()

print("Known AM ground states:", len(am_ground_ids))
print("Recovered in Top-5:", recovered_top5)
print(
    "Top-5 AM recovery: "
    f"{recovered_top5}/{len(am_ground_ids)} = "
    f"{100*recovered_top5/len(am_ground_ids):.2f}%"
)

Known AM ground states: 55
Recovered in Top-5: 40
Top-5 AM recovery: 40/55 = 72.73%

### Step - 8.3 - Getting the actual AM states that Top-5 would discover

In [ ]:
top5_AM_recovered = (
    top5_df[top5_df["known_AM_ground"]]
    .sort_values(["AM_type_preliminary", "task_id"])
    .copy()
)

cols = [
    "task_id",
    "formula",
    "parent_structure_id",
    "ML_rank",
    "pred_energy",
    "delta_E",
    "AM_type_preliminary",
]

print(top5_AM_recovered[cols].to_string(index=False))

 task_id        formula                                              parent_structure_id  ML_rank  pred_energy  delta_E AM_type_preliminary
     477           MnO2 1eed303aa078193df0050a090385bf7cae36f07937271493c9f148fc266e68bb        4     0.002712      0.0                 NaN
    1791         K3NiO2 b75b6a24f45a8636ee150a4702aa758476b5b9efb0883b88471479a2f79e2018        2    -0.026490      0.0                 NaN
    1908      Sr2CoTeO6 7d9d135cc9797297db38d9fab909cfe8e33fefbad6c0b54eab486c038cd76ad6        4     0.008986      0.0                 NaN
    2136       Sr2MnWO6 7353cfdc609979cbbfe59301a78729f07473eb7576aa34dc4fa95104199a2784        1     0.009251      0.0                 NaN
    2552            CoO 9d001c4b1750487c8102725cd86fee706ae40d7d0c73c74286b8bad557c431e6        3     0.000185      0.0                 NaN
    2797        MgMn2O4 ac571dd6c064ce62d2de96c73e8b196a415b9023e89d3f434f7fde2e69be2d1b        1     0.000195      0.0                 NaN
    2950       SrFe2S2O 876a4c4191d9779bb370fcd1e57ad95c76c93125c3c2ddebf4bb73ceef0faa1d        1    -0.001286      0.0                 NaN
    4189        Ca2MnO4 50e13313c7faafb11129ca77f77e911293686826bfe41f48ae958a132f588e04        2     0.005189      0.0                 NaN
    4286      Zn(FeO2)2 a89c62e6c89bad9cf0e60e86991ab2eccbed34d7beeb5886d2c79f3fac8a7662        1    -0.003473      0.0                 NaN
    4981         LaCrO3 bfe7a5a05a3f9306e11d192056279680b556ccde3154b007b764d3915dddede5        2     0.004392      0.0                 NaN
    5140         NiSeO3 784b3d22bdee22c3dcab20c5db548ce44c779ac9ddeb08f8ae5f3feff6574b8b        1    -0.001303      0.0                 NaN
    7162      Co(ClO4)2 2762c995c964620bbc4929a2697eb6dd4944cb0b20625befd824529c3316a1fd        3    -0.000111      0.0                 NaN
    8096        Mn2CdO4 39f21068b0506f31457fb9c11763958139a4cf50690e66c639ae5e7a1d5cf9cd        1    -0.005406      0.0                 NaN
    8924         LiFeOF 1910aa503022352be10602ee45456856eb48216f7bdd2cbac9bffb1083abe0ad        5     0.001914      0.0                 NaN
   10560         CaV2O5 a64ed520bf95fade997d19253b2b7810a1368341bb34eff9933ea9d4dfe9e31c        3     0.009728      0.0                 NaN
   10652          NbVO4 52b728b2bb9518f1f980c94dc8c4689b9d2943a83e0acb5166c8e971d9cf60c7        5     0.008992      0.0                 NaN
   14450         NaNiO2 dd6f98324a32bc9baa55c72f4733af117c32bc0285bc81188701cbffca2722b3        1    -0.000055      0.0                 NaN
   14465       LiCoAsO4 91f126881707dc8d165a34318fe881c568b1b246be0ebd6c4e0036e719ac2a58        3    -0.007891      0.0                 NaN
   17885     BaLaTiFeO6 d45dfdc46fdb7333ce31420aabc5a8737c5c3ad4e8c90fcdbcf26bc72b05c3d1        4    -0.001731      0.0                 NaN
   25497         CoTeO4 dd0ff3db84a552f3754728ac9b5666d2c013f6574c0ccdaced7f2d2dc52d3b31        2    -0.000049      0.0                 NaN
   26498        NaCoBO3 cd598889e1ba47663e97e288a2aa7b01f30f6eebfc83bca76270120220fb57b5        4    -0.003204      0.0                 NaN
   27974     Ba2CoSi2O7 cc80a522c8935056347795cec3c076b46a13926b245970c442d9ea2b883eb3c8        2     0.000712      0.0                 NaN
   28203     CsCr(SO4)2 4499079a57c870530724a9ecd8fd2d0ae116c3609c8e8adf861a31ed5a89fc6d        3    -0.001157      0.0                 NaN
   28294    Li2Fe(WO4)2 03184e0f328eb3520417711ec3daa327f40c3aedc29a710f7b7ac5c6ce7d08c9        3    -0.002588      0.0                 NaN
   30169       LiTiNiO4 381f7dc1954277c062d5485c198d3eefa1d264d3ac2d172a9286471d6c5957b0        3    -0.000013      0.0                 NaN
   30688       LiCo2OF3 29ccbd6f06c3cc20d8d62a98e00d922671cbb021eaca047bdd6696a0838fb924        1    -0.006365      0.0                 NaN
   30779       LiMnSnO4 a6694a1039f77658846b3269c8605f15f325be59f29897e77ac696194d97fc1c        1     0.004564      0.0                 NaN
   38352       Li2NiBO4 5330545db84bc3fe3603b3b34aa2dfecb22017f777bbc29bef7d1025de58c01b        2    -0.006453      0.0                 NaN
   40214     Li4CrGa3O8 9c5691ee4112c3cc937659509a2050fc3342f47bb83ede580b7b0a53aa6a20a9        2     0.007145      0.0                 NaN
   40225    BaCo2(PO4)2 985cb44ab09cce0126cab0a8c138ad145bc5f06a880bb466694cad2068c0229e        1     0.001356      0.0                 NaN
   40753      Li2MnGeO4 cabe9ea153db1a665c195d1878622aed23dcd804d92377565e22a14646e0a2ca        4    -0.003017      0.0                 NaN
   41088         MgMnO2 cb30962588df8e0b75f301a7b781e1fddd9c033c9177dffa3e24a1e41b1c3895        1     0.004873      0.0                 NaN
   43985       Li4FeO3F 32681fcb7fbf882d4088e0f114c8089cfd680a4134a1a6a745879224fcb100d8        3    -0.004161      0.0                 NaN
   45309  NaCo2H3(SO5)2 058f1a5e5a832ef8c60446520b8dfe10343754673fe52c8a9b9225c891214424        4     0.001961      0.0                 NaN
   46201 NaCo2H3(SeO5)2 9b4d20574778eff634e8b9585c58a8a96db0e3ba9a4805344cf8aceeb28c14f9        4     0.002351      0.0                 NaN
   49391     Li2TiFe2O5 679712ac88b126edaa3f9c88d13411d5a7ce779a8084cd3a28596032968be4b2        1    -0.001601      0.0                 NaN
   49603   Li3Ni(SbO3)4 327bdefd7de287c816099a6efc1977cde36cc20a83fa5ac576ef3495431b094f        5     0.004493      0.0                 NaN
   49844     SrLaTiMnO6 510d57095b6a2e5041ebad6e66926670ae6e54bbe507ea4beff1c8bfe0a05652        2     0.001577      0.0                 NaN
   52663  Li4VCr(TeO6)2 d65b667edc08d60da6998b5ca23353c51998fedb5279dfce9028c8bfbc932a62        4     0.005879      0.0                 NaN
   55367     Mn3(P2O7)2 39c303c199612ecb0a6b430358b65b0f5a72937035c7fc039fd27d62f8967b61        3    -0.000968      0.0                 NaN

It represents:

AM ground states that our ML Top-5 screening strategy would successfully send into the candidate pool.

### Step - 8.4 - Creating the full 259-parent Top-5 screening table

In [ ]:
top5_screen_table = (
    top5_df[
        [
            "parent_structure_id",
            "task_id",
            "formula",
            "ordering",
            "ML_rank",
            "pred_energy",
            "delta_E",
            "known_AM_ground",
            "AM_type_preliminary",
        ]
    ]
    .sort_values(["parent_structure_id", "ML_rank"])
    .reset_index(drop=True)
)

print(top5_screen_table.head(20))

                                  parent_structure_id  task_id       formula  \
0   03184e0f328eb3520417711ec3daa327f40c3aedc29a71...    28096   Li2Fe(WO4)2
1   03184e0f328eb3520417711ec3daa327f40c3aedc29a71...    28032   Li2Fe(WO4)2
2   03184e0f328eb3520417711ec3daa327f40c3aedc29a71...    28294   Li2Fe(WO4)2
3   03184e0f328eb3520417711ec3daa327f40c3aedc29a71...    28216   Li2Fe(WO4)2
4   03184e0f328eb3520417711ec3daa327f40c3aedc29a71...    27988   Li2Fe(WO4)2
5   0448b1eaa7be7933adf68fe3e072fc226a55d6c89fc79d...    32534      LiCrSnO4
6   0448b1eaa7be7933adf68fe3e072fc226a55d6c89fc79d...    32991      LiCrSnO4
7   0448b1eaa7be7933adf68fe3e072fc226a55d6c89fc79d...    32425      LiCrSnO4
8   0448b1eaa7be7933adf68fe3e072fc226a55d6c89fc79d...    32678      LiCrSnO4
9   0448b1eaa7be7933adf68fe3e072fc226a55d6c89fc79d...    32834      LiCrSnO4
10  04c5567c88e5201c3e144a2a2600e8fee19c25aee0b033...    29656        V2CoO4
11  04c5567c88e5201c3e144a2a2600e8fee19c25aee0b033...    30678        V2CoO4
12  04c5567c88e5201c3e144a2a2600e8fee19c25aee0b033...    29800        V2CoO4
13  04c5567c88e5201c3e144a2a2600e8fee19c25aee0b033...    29830        V2CoO4
14  04c5567c88e5201c3e144a2a2600e8fee19c25aee0b033...    31238        V2CoO4
15  04cc4f9f56be07e7246735311948061e37779c4b9a8f2c...    33877  CoH5CN(ClO)2
16  04cc4f9f56be07e7246735311948061e37779c4b9a8f2c...    34311  CoH5CN(ClO)2
17  04cc4f9f56be07e7246735311948061e37779c4b9a8f2c...    34162  CoH5CN(ClO)2
18  04cc4f9f56be07e7246735311948061e37779c4b9a8f2c...    34431  CoH5CN(ClO)2
19  04cc4f9f56be07e7246735311948061e37779c4b9a8f2c...    34356  CoH5CN(ClO)2

   ordering  ML_rank  pred_energy   delta_E  known_AM_ground  \
0       AFM        1    -0.002875  0.001110            False
1       AFM        2    -0.002809  0.001433            False
2       AFM        3    -0.002588  0.000000             True
3       AFM        4    -0.002550  0.001194            False
4       AFM        5    -0.002530  0.002164            False
5       FiM        1    -0.000016  0.000321            False
6       AFM        2    -0.000001  0.000183            False
7       AFM        3     0.000002  0.000270            False
8       AFM        4     0.000433  0.000096            False
9       AFM        5     0.000442  0.000113            False
10      FiM        1     0.013108  0.000000            False
11      FiM        2     0.017936  0.238364            False
12      FiM        3     0.020631  0.004546            False
13      FiM        4     0.026884  0.012052            False
14       FM        5     0.030537  0.016746            False
15      AFM        1     0.000096  0.000264            False
16      FiM        2     0.000103  0.000525            False
17      FiM        3     0.000106  0.000458            False
18      AFM        4     0.000899  0.002697            False
19      FiM        5     0.000970  0.002693            False

   AM_type_preliminary
0                  NaN
1                  NaN
2                  NaN
3                  NaN
4                  NaN
5                  NaN
6                  NaN
7                  NaN
8                  NaN
9                  NaN
10                 NaN
11                 NaN
12                 NaN
13                 NaN
14                 NaN
15                 NaN
16                 NaN
17                 NaN
18                 NaN
19                 NaN

Saving the table

In [ ]:
# top5_path = (
#     "/content/drive/MyDrive/Proj_2_Alt_Mags_Grnd_E/"
#     "magnetic-topological-materials/"
#     "AM_Top5_screening_candidates.csv"
# )

# top5_screen_table.to_csv(top5_path, index=False)

# print("Saved:")
# print(top5_path)

### Step - 8.5 - Comparing Top-1, Top-3, Top-5 and Top-10 automatically

In [ ]:
results = []

for k in [1, 2, 3, 5, 10]:

    topk = (
        ranked_test[ranked_test["ML_rank"] <= k]
        .copy()
    )

    recovered = topk["task_id"].astype(int).isin(am_ground_ids).sum()

    n_candidates = len(topk)
    avg_configs = n_candidates / test_df["parent_structure_id"].nunique()

    recovery = 100 * recovered / len(am_ground_ids)

    # Average number of DFT calculations if we evaluate Top-k,
    # accounting for parents with fewer than k configurations.
    dft_per_parent = (
        topk.groupby("parent_structure_id").size()
        .reindex(test_df["parent_structure_id"].unique(), fill_value=0)
        .mean()
    )

    total_avg_configs = (
        test_df.groupby("parent_structure_id").size().mean()
    )

    saving = 100 * (1 - dft_per_parent / total_avg_configs)

    results.append({
        "Top-K": k,
        "AM recovered": recovered,
        "AM total": len(am_ground_ids),
        "AM recovery (%)": recovery,
        "avg DFT/parent": dft_per_parent,
        "DFT saving (%)": saving,
    })

am_screen_summary = pd.DataFrame(results)

print(am_screen_summary.to_string(index=False))

 Top-K  AM recovered  AM total  AM recovery (%)  avg DFT/parent  DFT saving (%)
     1            12        55        21.818182        1.000000       88.243305
     2            20        55        36.363636        1.980695       76.713572
     3            29        55        52.727273        2.945946       65.365411
     5            40        55        72.727273        4.625483       45.619610
    10            52        55        94.545455        7.420849       12.755334

Now we have a Top-5 candidate pool of ~1,295 configurations.

But these are not yet confirmed altermagnets.

The next pipeline is:

$$ \boxed{ \text{Top-5 ML candidates} \rightarrow \text{DFT ground-state verification} \rightarrow M_{\rm total}\approx0 \rightarrow P/T/PT \rightarrow \text{magnetic spin-space symmetry} \rightarrow \boxed{\text{real altermagnet}} } $$

#### Identifying AM ground states missed by top-5

In [ ]:
# ============================================================
# STEP 4: AM ground states missed by Top-5
# ============================================================

# Identify the AM ground states not recovered by Top-5
missed_top5_AM = master_am[
    ~master_am["task_id"].astype(int).isin(
        top5_AM_recovered["task_id"].astype(int)
    )
].copy()

print("AM ground states missed by Top-5:", len(missed_top5_AM))

# ------------------------------------------------------------
# Get formula from test_df, since master_am may not contain it
# ------------------------------------------------------------

task_formula_map = (
    test_df
    .drop_duplicates("task_id")
    .set_index("task_id")["formula"]
    .to_dict()
)

missed_top5_AM["formula"] = (
    missed_top5_AM["task_id"]
    .astype(int)
    .map(task_formula_map)
)

# ------------------------------------------------------------
# Display
# ------------------------------------------------------------

display_cols = [
    "task_id",
    "formula",
    "AM_type_preliminary",
]

print(
    missed_top5_AM[display_cols]
    .sort_values("task_id")
    .to_string(index=False)
)

AM ground states missed by Top-5: 15
task_id         formula AM_type_preliminary
  10423       Cs2LiMnO4            S/A-type
  12082         LiVSiO4            S/A-type
  13559        Mn(IO3)2            S/A-type
  17836      BaLaMnSbO6            S/A-type
  17961       BaSrNiWO6            S/A-type
  20011        Ca2MnWO6            S/A-type
  27522       Li2V3O3F5            S/A-type
  38191        Li8CoO5F            S/A-type
  40596         Li2VOF4            S/A-type
  42065       Li2SiNiO4            S/A-type
  43891        V3(O2F)2            S/A-type
  48723     KFeH5(SO5)2            S/A-type
  51857     SrCo(GeO3)2            S/A-type
  51934 NaCaMgCr(SiO3)4            S/A-type
  52083   Li5Co3(SbO5)2              S-type

### Step - 8.6 - Finding exactly where those 15 AM states ranked

Finding answer for:

How far down did the ML model place each missed AM ground state?

In [ ]:
# ============================================================
# STEP 5: Ranking of the 15 missed AM ground states
# ============================================================

# Look up the ML rank for every missed AM ground state
missed_rank_df = (
    ranked_test[
        ranked_test["task_id"].astype(int).isin(
            missed_top5_AM["task_id"].astype(int)
        )
    ][
        [
            "task_id",
            "formula",
            "parent_structure_id",
            "ML_rank",
            "pred_energy",
            "delta_E",
            "ordering",
        ]
    ]
    .sort_values("ML_rank")
    .reset_index(drop=True)
)

# Add AM type
am_type_map = (
    master_am
    .set_index("task_id")["AM_type_preliminary"]
    .to_dict()
)

missed_rank_df["AM_type"] = (
    missed_rank_df["task_id"].astype(int).map(am_type_map)
)

print(
    missed_rank_df[
        [
            "task_id",
            "formula",
            "AM_type",
            "ML_rank",
            "ordering",
            "delta_E",
            "pred_energy",
        ]
    ].to_string(index=False)
)

 task_id         formula AM_type  ML_rank ordering  delta_E  pred_energy
   42065       Li2SiNiO4     NaN        6      AFM      0.0     0.001414
   51857     SrCo(GeO3)2     NaN        6      FiM      0.0    -0.000721
   40596         Li2VOF4     NaN        6      AFM      0.0     0.002185
   43891        V3(O2F)2     NaN        6      FiM      0.0     0.008331
   48723     KFeH5(SO5)2     NaN        7      AFM      0.0    -0.001556
   10423       Cs2LiMnO4     NaN        7      FiM      0.0    -0.005430
   13559        Mn(IO3)2     NaN        7      AFM      0.0     0.004954
   27522       Li2V3O3F5     NaN        8      FiM      0.0    -0.003307
   17836      BaLaMnSbO6     NaN        8      AFM      0.0     0.007591
   38191        Li8CoO5F     NaN        8      FiM      0.0    -0.000909
   17961       BaSrNiWO6     NaN        9      AFM      0.0     0.014371
   20011        Ca2MnWO6     NaN       10      AFM      0.0     0.003118
   52083   Li5Co3(SbO5)2     NaN       11      FiM      0.0     0.003360
   51934 NaCaMgCr(SiO3)4     NaN       12      AFM      0.0     0.004680
   12082         LiVSiO4     NaN       13      AFM      0.0     0.002679

### Step - 8.7 - Compare Top-5 misses with the three Top-10 misses

We already know three AM states were outside Top-10:

* LiVSiO₄ → rank 13
* Li₅Co₃(SbO₅)₂ → rank 11
* NaCaMgCr(SiO₃)₄ → rank 12

Let's verify that automatically:

In [ ]:
# ============================================================
# STEP 6: Separate Top-5 misses into:
#         recovered by Top-10
#         still missed by Top-10
# ============================================================

missed_rank_df["within_top10"] = missed_rank_df["ML_rank"] <= 10

print("Top-5 misses that are recovered by Top-10:",
      missed_rank_df["within_top10"].sum())

print("Top-5 misses still missed by Top-10:",
      (~missed_rank_df["within_top10"]).sum())

print("\nStill missed by Top-10:\n")

print(
    missed_rank_df[
        ~missed_rank_df["within_top10"]
    ][
        [
            "task_id",
            "formula",
            "AM_type",
            "ML_rank",
            "ordering",
        ]
    ].to_string(index=False)
)

Top-5 misses that are recovered by Top-10: 12
Top-5 misses still missed by Top-10: 3

Still missed by Top-10:

 task_id         formula AM_type  ML_rank ordering
   52083   Li5Co3(SbO5)2     NaN       11      FiM
   51934 NaCaMgCr(SiO3)4     NaN       12      AFM
   12082         LiVSiO4     NaN       13      AFM

### Step - 8.8 - Analyzing the 12 Top-5 misses that Top-10 rescues

This is useful because it tells us whether Top-10 is genuinely buying us extra AM discoveries.

In [ ]:
# ============================================================
# STEP 7: Top-5 misses rescued by Top-10
# ============================================================

rescued_by_top10 = missed_rank_df[
    (missed_rank_df["ML_rank"] > 5) &
    (missed_rank_df["ML_rank"] <= 10)
].copy()

print(
    rescued_by_top10[
        [
            "task_id",
            "formula",
            "AM_type",
            "ML_rank",
            "ordering",
            "delta_E",
            "pred_energy",
        ]
    ].to_string(index=False)
)

 task_id     formula AM_type  ML_rank ordering  delta_E  pred_energy
   42065   Li2SiNiO4     NaN        6      AFM      0.0     0.001414
   51857 SrCo(GeO3)2     NaN        6      FiM      0.0    -0.000721
   40596     Li2VOF4     NaN        6      AFM      0.0     0.002185
   43891    V3(O2F)2     NaN        6      FiM      0.0     0.008331
   48723 KFeH5(SO5)2     NaN        7      AFM      0.0    -0.001556
   10423   Cs2LiMnO4     NaN        7      FiM      0.0    -0.005430
   13559    Mn(IO3)2     NaN        7      AFM      0.0     0.004954
   27522   Li2V3O3F5     NaN        8      FiM      0.0    -0.003307
   17836  BaLaMnSbO6     NaN        8      AFM      0.0     0.007591
   38191    Li8CoO5F     NaN        8      FiM      0.0    -0.000909
   17961   BaSrNiWO6     NaN        9      AFM      0.0     0.014371
   20011    Ca2MnWO6     NaN       10      AFM      0.0     0.003118

### Step - 8.9 - Calculation summary

In [ ]:
# ============================================================
# STEP 8: Top-K AM screening summary
# ============================================================

summary = []

for k in [1, 3, 5, 10]:

    topk = ranked_test[
        ranked_test["ML_rank"] <= k
    ]

    recovered = topk["task_id"].astype(int).isin(am_ground_ids).sum()

    recovery = 100 * recovered / len(am_ground_ids)

    avg_candidates = (
        topk.groupby("parent_structure_id")
        .size()
        .mean()
    )

    avg_all = (
        test_df.groupby("parent_structure_id")
        .size()
        .mean()
    )

    dft_saving = 100 * (
        1 - avg_candidates / avg_all
    )

    summary.append({
        "Top-K": k,
        "AM recovered": recovered,
        "AM total": len(am_ground_ids),
        "AM recovery (%)": recovery,
        "Avg candidates/parent": avg_candidates,
        "DFT saving (%)": dft_saving,
    })

summary_df = pd.DataFrame(summary)

print(summary_df.to_string(index=False))

 Top-K  AM recovered  AM total  AM recovery (%)  Avg candidates/parent  DFT saving (%)
     1            12        55        21.818182               1.000000       88.243305
     3            29        55        52.727273               2.945946       65.365411
     5            40        55        72.727273               4.625483       45.619610
    10            52        55        94.545455               7.420849       12.755334

Final benchmark:

| Screening level | AM ground states recovered | AM recovery | DFT saving |
| --------------- | -------------------------: | ----------: | ---------: |
| Top-1           |                      12/55 |      21.82% |     88.24% |
| Top-3           |                      29/55 |      52.73% |     65.37% |
| **Top-5**       |                  **40/55** |  **72.73%** | **45.62%** |
| Top-10          |                      52/55 |  **94.55%** |     12.76% |

At this point, we are not just saying "Top-5 gives 72.73%".

We are establishing a complete screening argument:

$$ \text{259 parent materials} $$ $$ \downarrow $$ $$ \text{ALIGNN predicts all magnetic configurations} $$ $$ \downarrow $$ $$ \text{retain Top-5} $$ $$ \downarrow $$ $$ \text{43% DFT work saved} $$ $$ \downarrow $$ $$ \text{72.73% of known AM ground states recovered} $$

and then:

$$ \text{Top-10 rescue} $$

raises AM recovery to:

$$ \boxed{94.55\%} $$

while still reducing the number of configurations that need to be examined.

Then comes the real discovery stage

Once these tables are working, the next major step is no longer benchmarking.

We will take the ML Top-5 candidates for each parent, and perform the actual:

$$ \boxed{ \text{magnetic compensation} + P/T/PT + \text{magnetic spin-space symmetry}} $$

screening on them.

Workflow summary:

All magnetic configurations →
Spin-aware ALIGNN →
Rank by predicted ΔE →
Top-5 per parent →
DFT / magnetic-symmetry screening →
AM candidates


Then using Top-10 as a validation/rescue comparison, not the primary protocol.

#### **Important distinction:**
The 72.73% is not saying that 72.73% of your Top-5 candidates are altermagnets.

It means:

Of the 55 AM ground states that we already know from the complete DFT/symmetry analysis, 40 would have been captured by the Top-5 ML screening.

## Phase - 9 - Real AM screening

For the Top-5 candidates of all 259 parents, we now need to run the magnetic-symmetry procedure and determine which ones actually satisfy your AM criteria.

That means we should generate a table like:

parent_id

formula

task_id

ML_rank

DFT_energy

magnetization

P_preserved

T_preserved

PT_preserved

MSG/BNS

AM_type

AM_candidate



The final AM_candidate=True rows will be your actual ML-screened altermagnet candidates.

There will be two parts:

* Building the Top-5 candidate set for all 259 parents.
* Applying the magnetic symmetry screen to those candidates.

### Step - 9.1 - Freezing the Top-5 candidate set

In [ ]:
# ============================================================
# ACTUAL AM DISCOVERY SCREEN — TOP-5 CANDIDATES
# ============================================================

# ranked_test already exists from the previous cells:
# sorted by parent_structure_id and pred_energy
# ML_rank = 1,2,3,...

top5_candidates = (
    ranked_test[ranked_test["ML_rank"] <= 5]
    .copy()
    .reset_index(drop=True)
)

print("Number of parent structures:",
      top5_candidates["parent_structure_id"].nunique())

print("Total Top-5 candidate configurations:",
      len(top5_candidates))

print("\nColumns available:")
print(top5_candidates.columns.tolist())

Number of parent structures: 259
Total Top-5 candidate configurations: 1198

Columns available:
['task_id', 'parent_structure_id', 'formula', 'input_structure', 'initial_magmoms', 'delta_E', 'energy_per_atom', 'ordering', 'ordering_changed', 'n_dft_records', 'input_ordering', 'origin', 'input_index', 'index', 'split', 'pred_energy', 'ML_rank']

Saving

In [ ]:
# top5_candidates_path = (
#     "/content/drive/MyDrive/Proj_2_Alt_Mags_Grnd_E/"
#     "magnetic-topological-materials/"
#     "AM_Top5_all_candidates.csv"
# )

# top5_candidates.to_csv(top5_candidates_path, index=False)

# print("Saved:", top5_candidates_path)

### Step - 9.2 - Need for the actual DFT magnetic information

The ML ranking alone cannot establish altermagnetism.

For each Top-5 candidate we need the DFT-derived quantities:

$$ M_{\rm total}, \quad P, \quad T, \quad PT $$

and ultimately the magnetic-space/spin-space symmetry.

In [ ]:
# ============================================================
# FIND THE DFT / MAGNETIC DATA COLUMNS
# ============================================================

print("test_df columns:")
for i, c in enumerate(test_df.columns):
    print(i, repr(c))

test_df columns:
0 'task_id'
1 'parent_structure_id'
2 'formula'
3 'input_structure'
4 'initial_magmoms'
5 'delta_E'
6 'energy_per_atom'
7 'ordering'
8 'ordering_changed'
9 'n_dft_records'
10 'input_ordering'
11 'origin'
12 'input_index'
13 'index'
14 'split'
15 'pred_energy'

In [ ]:
# Inspecting the first candidate
print("\nFirst Top-5 candidate:")
display(top5_candidates.iloc[0])

First Top-5 candidate:

task_id                                                            28096
parent_structure_id    03184e0f328eb3520417711ec3daa327f40c3aedc29a71...
formula                                                      Li2Fe(WO4)2
input_structure        {'@module': 'pymatgen.core.structure', '@class...
initial_magmoms        [0.6, 0.6, 0.6, 0.6, -5.0, 5.0, -5.0, -5.0, 5....
delta_E                                                          0.00111
energy_per_atom                                                -6.902637
ordering                                                             AFM
ordering_changed                                                    True
n_dft_records                                                          1
input_ordering                                                       FiM
origin                                                               afm
input_index                                                          0.0
index                                                                  3
split                                                               test
pred_energy                                                    -0.002875
ML_rank                                                                1
Name: 0, dtype: object

In [ ]:
print("graph_df columns:")
print(graph_df.columns.tolist())

graph_df columns:
['task_id', 'parent_structure_id', 'formula', 'input_structure', 'initial_magmoms', 'delta_E', 'energy_per_atom', 'ordering', 'ordering_changed', 'n_dft_records', 'input_ordering', 'origin', 'input_index', 'index', 'split']

In [ ]:
# ============================================================
# MERGE TOP-5 WITH THE DFT-DERIVED INFORMATION
# ============================================================

top5_dft = top5_candidates.merge(
    graph_df.drop_duplicates("task_id"),
    on="task_id",
    how="left",
    suffixes=("", "_graph")
)

print("Top-5 rows:", len(top5_dft))

print("\nColumns after merge:")
print(top5_dft.columns.tolist())

Top-5 rows: 1198

Columns after merge:
['task_id', 'parent_structure_id', 'formula', 'input_structure', 'initial_magmoms', 'delta_E', 'energy_per_atom', 'ordering', 'ordering_changed', 'n_dft_records', 'input_ordering', 'origin', 'input_index', 'index', 'split', 'pred_energy', 'ML_rank', 'parent_structure_id_graph', 'formula_graph', 'input_structure_graph', 'initial_magmoms_graph', 'delta_E_graph', 'energy_per_atom_graph', 'ordering_graph', 'ordering_changed_graph', 'n_dft_records_graph', 'input_ordering_graph', 'origin_graph', 'input_index_graph', 'index_graph', 'split_graph']

In [ ]:
# ============================================================
# FIND THE DFT MAGNETIC DATA SOURCE
# ============================================================

# Show variables in the current notebook that may contain
# DFT / magnetic information.
for name in [
    "df", "master_df", "raw_df", "dft_df",
    "results_df", "records_df", "magnetic_df",
    "all_dft", "dft_records", "master_data"
]:
    if name in globals():
        obj = globals()[name]
        print(f"\n{name}:")
        print(type(obj))
        if isinstance(obj, pd.DataFrame):
            print("shape:", obj.shape)
            print("columns:", obj.columns.tolist())

df:
<class 'pandas.core.frame.DataFrame'>
shape: (2203, 16)
columns: ['task_id', 'parent_structure_id', 'formula', 'input_structure', 'initial_magmoms', 'delta_E', 'energy_per_atom', 'ordering', 'ordering_changed', 'n_dft_records', 'input_ordering', 'origin', 'input_index', 'index', 'split', 'pred_delta_E']

Searching the notebook namespace for anything specifically containing magnetic/DFT names:

In [ ]:
# Search variable names for useful objects
keywords = [
    "mag", "dft", "vasp", "record",
    "spin", "sym", "structure"
]

print("\nPossible relevant variables:")
for name in sorted(globals()):
    low = name.lower()
    if any(k in low for k in keywords):
        print(name)

Possible relevant variables:
CollinearMagneticStructureAnalyzer
MagneticSpaceGroup
SpinAwareDataset
Structure
actual_dft
all_spin_predictions
all_spin_targets
check_PT_symmetry
collate_spin_alignn
collate_spin_rank
df_mag
dft_per_parent
dft_saving
duplicate_records
extract_final_magmoms
extract_initial_magmoms
final_magmoms
final_mags
final_structure
full_dft
get_PTR_symmetry
get_magnetic_spacegroup_info
initial_magmoms
input_magnetic_signature
input_spin_structure_signature
mag_analyzer
mag_sym
mag_tol
maggroups
magmom
magmoms
magnetic_operation_preserves
mags
make_alignn_record
matching_records
pmg_structure
record
record_by_task
record_lookup
records
records_by_task
records_target
screen_altermagnet_corrected
spin_accuracy
spin_checkpoint_path
spin_comparison
spin_config
spin_loader
spin_model
spin_model_path
spin_preds
spin_sign_pattern
spin_structure
spin_test_loader
spin_test_mae
spin_test_rmse
structure
structure_signature
structure_summary
symm_ops
symprecs
test_records
test_spin_dataset
test_spin_df
top5_dft
train_records
train_spin_dataset
train_spin_df
val_records
val_spin_dataset
val_spin_df
vasp_magmoms

Identifying which one contains the final DFT magnetic moments and structures keyed by task_id

In [ ]:
# ============================================================
# INSPECT THE ACTUAL DFT DATA SOURCES
# ============================================================

for name in [
    "actual_dft",
    "full_dft",
    "df_mag",
    "test_records",
    "records",
    "records_by_task",
    "record_by_task",
    "final_magmoms",
    "final_mags",
    "vasp_magmoms",
]:
    if name not in globals():
        continue

    obj = globals()[name]

    print("\n" + "="*70)
    print(name)
    print("="*70)
    print("Type:", type(obj))

    if isinstance(obj, pd.DataFrame):
        print("Shape:", obj.shape)
        print("Columns:", obj.columns.tolist())
        print("\nFirst row:")
        display(obj.head(1))

    elif isinstance(obj, dict):
        print("Number of entries:", len(obj))
        if len(obj) > 0:
            first_key = next(iter(obj))
            print("First key:", first_key)
            print("First value type:", type(obj[first_key]))
            print("First value:")
            print(obj[first_key])

    elif isinstance(obj, (list, tuple)):
        print("Length:", len(obj))
        if len(obj) > 0:
            print("First element type:", type(obj[0]))
            print("First element:")
            print(obj[0])

======================================================================
actual_dft
======================================================================
Type: <class 'numpy.float64'>

======================================================================
full_dft
======================================================================
Type: <class 'numpy.float64'>

======================================================================
df_mag
======================================================================
Type: <class 'pandas.core.frame.DataFrame'>
Shape: (23155, 17)
Columns: ['task_id', 'formula', 'parent_structure_id', 'ordering', 'ordering_changed', 'energy_per_atom', 'energy_above_ground', 'initial_magmoms', 'n_sites', 'total_initial_moment', 'n_magnetic_sites', 'n_positive', 'n_negative', 'n_zero', 'spin_pattern', 'input_spin_signature', 'input_magnetic_signature']

First row:

,task_id,formula,parent_structure_id,ordering,ordering_changed,energy_per_atom,energy_above_ground,initial_magmoms,n_sites,total_initial_moment,n_magnetic_sites,n_positive,n_negative,n_zero,spin_pattern,input_spin_signature,input_magnetic_signature
0,27,LaFeO3,efbd17b56f24b8829276ef912ddb2f718ccd826da286ab...,FM,False,-7.599371,0.040136,"[0.0, 0.0, 4.373, 4.373, 0.177, 0.176, 0.172, ...",10,9.796,8,8,0,2,"(0, 0, 1, 1, 1, 1, 1, 1, 1, 1)",95087a9186cd6537f39baa1292ff7934b151c6384ed552...,3dfb98bb407f163b915fb2cc028f0ccd104bb38dde2d8e...

======================================================================
test_records
======================================================================
Type: <class 'list'>
Length: 2203
First element type: <class 'dict'>
First element:
{'jid': '27890', 'atoms': {'lattice_mat': [[-2.546122, 4.813236, -1.856976], [-5.150747, 0.15068, 6.040222], [2.438487, 4.885431, 4.042048]], 'coords': [[0.311847, 0.144398, 0.605292], [0.811847, 0.644398, 0.105292], [0.688153, 0.855602, 0.394708], [0.188153, 0.355602, 0.894708], [0.25, 0.75, 0.75], [0.75, 0.25, 0.25], [0.273225, 0.958291, 0.201201], [0.226775, 0.541709, 0.298799], [0.773225, 0.458291, 0.701201], [0.726775, 0.041709, 0.798799], [0.028542, 0.790601, 0.254795], [0.528542, 0.290601, 0.754795], [0.971458, 0.209399, 0.745205], [0.471458, 0.709399, 0.245205], [0.718411, 0.054852, 0.524295], [0.218411, 0.554852, 0.024295], [0.281589, 0.945148, 0.475705], [0.781589, 0.445148, 0.975705], [0.610791, 0.054976, 0.108913], [0.110791, 0.554976, 0.608913], [0.389209, 0.945024, 0.891087], [0.889209, 0.445024, 0.391087], [0.600129, 0.654764, 0.64671], [0.100129, 0.154764, 0.14671], [0.399871, 0.345236, 0.35329], [0.899871, 0.845236, 0.85329]], 'elements': ['Li', 'Li', 'Li', 'Li', 'Fe', 'Fe', 'W', 'W', 'W', 'W', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O'], 'props': [[''], [''], [''], [''], [''], [''], [''], [''], [''], [''], [''], [''], [''], [''], [''], [''], [''], [''], [''], [''], [''], [''], [''], [''], [''], ['']], 'cartesian': False}, 'target': 0.0004899592307685552}

======================================================================
records
======================================================================
Type: <class 'list'>
Length: 22459
First element type: <class 'dict'>
First element:
{'task_id': 53864, 'parent_structure_id': '000aa4ac0b5d42d6a9fadefdb79f1b4bd881c1afec542567b0827805c8be4199', 'formula': 'Li2V4CrCuO12', 'input_structure': {'@module': 'pymatgen.core.structure', '@class': 'Structure', 'charge': None, 'lattice': {'matrix': [[6.90922468, -0.44309351, -0.07031606], [-1.17654922, 6.82295497, 0.07031853], [-1.58396863, 1.42337006, 5.23374934]], 'a': 6.9237751180710045, 'b': 6.924010924701929, 'c': 5.650404507863036, 'alpha': 72.22556532230291, 'beta': 107.77423185512325, 'gamma': 103.45791285523455, 'volume': 242.71307292838904}, 'sites': [{'species': [{'element': 'Li', 'occu': 1}], 'abc': [0.26512875, 0.26514678, 0.24999616], 'xyz': [1.1238897906225778, 2.0474447612000537, 1.3084191601136428], 'label': 'Li', 'properties': {'magmom': 0.0}}, {'species': [{'element': 'Li', 'occu': 1}], 'abc': [0.71806091, 0.71809134, 0.74999885], 'xyz': [2.9283997042134295, 5.648862656285695, 3.9253098995915745], 'label': 'Li', 'properties': {'magmom': 0.0}}, {'species': [{'element': 'V', 'occu': 1}], 'abc': [0.16547101, 0.61401579, 0.70808284], 'xyz': [-0.700724418676966, 5.1239468698706006, 3.737469514797494], 'label': 'V', 'properties': {'magmom': 5.0}}, {'species': [{'element': 'V', 'occu': 1}], 'abc': [0.37774068, 0.81695026, 0.2329562], 'xyz': [1.2797177247501792, 5.738223273310178, 1.250119863045905], 'label': 'V', 'properties': {'magmom': 5.0}}, {'species': [{'element': 'V', 'occu': 1}], 'abc': [0.61392567, 0.16541096, 0.79198624], 'xyz': [2.7926548953304335, 1.9838545535730439, 4.11352008219491], 'label': 'V', 'properties': {'magmom': 5.0}}, {'species': [{'element': 'V', 'occu': 1}], 'abc': [0.81691964, 0.37776898, 0.26700801], 'xyz': [4.776885227706793, 2.595580156141475, 1.3665745850439945], 'label': 'V', 'properties': {'magmom': 5.0}}, {'species': [{'element': 'Cr', 'occu': 1}], 'abc': [0.07315656, 0.07320373, 0.74987809], 'xyz': [-0.7684560524610067, 1.534404578432098, 3.924677456239724], 'label': 'Cr', 'properties': {'magmom': 5.0}}, {'species': [{'element': 'Cu', 'occu': 1}], 'abc': [0.89255349, 0.89236242, 0.25025124], 'xyz': [4.72055417834122, 6.049264072327252, 1.3097410310297748], 'label': 'Cu', 'properties': {'magmom': 1.73}}, {'species': [{'element': 'O', 'occu': 1}], 'abc': [0.99994017, 0.79794563, 0.66909135], 'xyz': [4.910169283504137, 5.953644697277964, 3.4876549221936024], 'label': 'O', 'properties': {'magmom': 0.0}}, {'species': [{'element': 'O', 'occu': 1}], 'abc': [0.11621086, 0.3480932, 0.81503319], 'xyz': [-0.8976088463201088, 3.4836257916579765, 4.281985332563179], 'label': 'O', 'properties': {'magmom': 0.0}}, {'species': [{'element': 'O', 'occu': 1}], 'abc': [0.1942794, 0.9815303, 0.13178776], 'xyz': [-0.02124636123374274, 6.798435849182361, 0.7451029078193734], 'label': 'O', 'properties': {'magmom': 0.0}}, {'species': [{'element': 'O', 'occu': 1}], 'abc': [0.40867443, 0.70950675, 0.56973937], 'xyz': [1.0864045551877344, 5.47080157978636, 3.003028147654247], 'label': 'O', 'properties': {'magmom': 0.0}}, {'species': [{'element': 'O', 'occu': 1}], 'abc': [0.3480059, 0.11611437, 0.68481962], 'xyz': [1.1831038863228, 1.612795705756787, 3.5678688222595727], 'label': 'O', 'properties': {'magmom': 0.0}}, {'species': [{'element': 'O', 'occu': 1}], 'abc': [0.31600016, 0.62931208, 0.06407537], 'xyz': [1.341406091459728, 4.244953327103499, 0.3573868396140287], 'label': 'O', 'properties': {'magmom': 0.0}}, {'species': [{'element': 'O', 'occu': 1}], 'abc': [0.70942347, 0.40864194, 0.93023152], 'xyz': [2.9473212454117355, 3.797868314511053, 4.847449841082416], 'label': 'O', 'properties': {'magmom': 0.0}}, {'species': [{'element': 'O', 'occu': 1}], 'abc': [0.60335414, 0.97232235, 0.17105714], 'xyz': [2.7537750686895897, 6.610246918334176, 0.9212169860059447], 'label': 'O', 'properties': {'magmom': 0.0}}, {'species': [{'element': 'O', 'occu': 1}], 'abc': [0.62935275, 0.31604246, 0.43598117], 'xyz': [3.2859195463752924, 2.498043898264144, 2.2597861962145465], 'label': 'O', 'properties': {'magmom': 0.0}}, {'species': [{'element': 'O', 'occu': 1}], 'abc': [0.79792789, 0.99998591, 0.83096045], 'xyz': [3.020315142456152, 7.652066390631606, 4.363249100576601], 'label': 'O', 'properties': {'magmom': 0.0}}, {'species': [{'element': 'O', 'occu': 1}], 'abc': [0.97240679, 0.60331133, 0.32893378], 'xyz': [5.487730728871592, 4.1536933939265035, 1.6956051056466028], 'label': 'O', 'properties': {'magmom': 0.0}}, {'species': [{'element': 'O', 'occu': 1}], 'abc': [0.98147132, 0.19424741, 0.36813164], 'xyz': [5.969555258663204, 1.4144453138406927, 1.8713547239852257], 'label': 'O', 'properties': {'magmom': 0.0}}], '@version': '2020.10.20'}, 'initial_magmoms': [0.0, 0.0, 5.0, 5.0, 5.0, 5.0, 5.0, 1.73, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], 'delta_E': 0.0, 'energy_per_atom': -7.066531543000001, 'ordering': 'FM', 'ordering_changed': True, 'n_dft_records': 1, 'input_ordering': 'FM', 'origin': 'fm', 'input_index': 12, 'index': 0}

======================================================================
records_by_task
======================================================================
Type: <class 'dict'>
Number of entries: 22459
First key: 53864
First value type: <class 'dict'>
First value:
{'task_id': 53864, 'parent_structure_id': '000aa4ac0b5d42d6a9fadefdb79f1b4bd881c1afec542567b0827805c8be4199', 'formula': 'Li2V4CrCuO12', 'input_structure': {'@module': 'pymatgen.core.structure', '@class': 'Structure', 'charge': None, 'lattice': {'matrix': [[6.90922468, -0.44309351, -0.07031606], [-1.17654922, 6.82295497, 0.07031853], [-1.58396863, 1.42337006, 5.23374934]], 'a': 6.9237751180710045, 'b': 6.924010924701929, 'c': 5.650404507863036, 'alpha': 72.22556532230291, 'beta': 107.77423185512325, 'gamma': 103.45791285523455, 'volume': 242.71307292838904}, 'sites': [{'species': [{'element': 'Li', 'occu': 1}], 'abc': [0.26512875, 0.26514678, 0.24999616], 'xyz': [1.1238897906225778, 2.0474447612000537, 1.3084191601136428], 'label': 'Li', 'properties': {'magmom': 0.0}}, {'species': [{'element': 'Li', 'occu': 1}], 'abc': [0.71806091, 0.71809134, 0.74999885], 'xyz': [2.9283997042134295, 5.648862656285695, 3.9253098995915745], 'label': 'Li', 'properties': {'magmom': 0.0}}, {'species': [{'element': 'V', 'occu': 1}], 'abc': [0.16547101, 0.61401579, 0.70808284], 'xyz': [-0.700724418676966, 5.1239468698706006, 3.737469514797494], 'label': 'V', 'properties': {'magmom': 5.0}}, {'species': [{'element': 'V', 'occu': 1}], 'abc': [0.37774068, 0.81695026, 0.2329562], 'xyz': [1.2797177247501792, 5.738223273310178, 1.250119863045905], 'label': 'V', 'properties': {'magmom': 5.0}}, {'species': [{'element': 'V', 'occu': 1}], 'abc': [0.61392567, 0.16541096, 0.79198624], 'xyz': [2.7926548953304335, 1.9838545535730439, 4.11352008219491], 'label': 'V', 'properties': {'magmom': 5.0}}, {'species': [{'element': 'V', 'occu': 1}], 'abc': [0.81691964, 0.37776898, 0.26700801], 'xyz': [4.776885227706793, 2.595580156141475, 1.3665745850439945], 'label': 'V', 'properties': {'magmom': 5.0}}, {'species': [{'element': 'Cr', 'occu': 1}], 'abc': [0.07315656, 0.07320373, 0.74987809], 'xyz': [-0.7684560524610067, 1.534404578432098, 3.924677456239724], 'label': 'Cr', 'properties': {'magmom': 5.0}}, {'species': [{'element': 'Cu', 'occu': 1}], 'abc': [0.89255349, 0.89236242, 0.25025124], 'xyz': [4.72055417834122, 6.049264072327252, 1.3097410310297748], 'label': 'Cu', 'properties': {'magmom': 1.73}}, {'species': [{'element': 'O', 'occu': 1}], 'abc': [0.99994017, 0.79794563, 0.66909135], 'xyz': [4.910169283504137, 5.953644697277964, 3.4876549221936024], 'label': 'O', 'properties': {'magmom': 0.0}}, {'species': [{'element': 'O', 'occu': 1}], 'abc': [0.11621086, 0.3480932, 0.81503319], 'xyz': [-0.8976088463201088, 3.4836257916579765, 4.281985332563179], 'label': 'O', 'properties': {'magmom': 0.0}}, {'species': [{'element': 'O', 'occu': 1}], 'abc': [0.1942794, 0.9815303, 0.13178776], 'xyz': [-0.02124636123374274, 6.798435849182361, 0.7451029078193734], 'label': 'O', 'properties': {'magmom': 0.0}}, {'species': [{'element': 'O', 'occu': 1}], 'abc': [0.40867443, 0.70950675, 0.56973937], 'xyz': [1.0864045551877344, 5.47080157978636, 3.003028147654247], 'label': 'O', 'properties': {'magmom': 0.0}}, {'species': [{'element': 'O', 'occu': 1}], 'abc': [0.3480059, 0.11611437, 0.68481962], 'xyz': [1.1831038863228, 1.612795705756787, 3.5678688222595727], 'label': 'O', 'properties': {'magmom': 0.0}}, {'species': [{'element': 'O', 'occu': 1}], 'abc': [0.31600016, 0.62931208, 0.06407537], 'xyz': [1.341406091459728, 4.244953327103499, 0.3573868396140287], 'label': 'O', 'properties': {'magmom': 0.0}}, {'species': [{'element': 'O', 'occu': 1}], 'abc': [0.70942347, 0.40864194, 0.93023152], 'xyz': [2.9473212454117355, 3.797868314511053, 4.847449841082416], 'label': 'O', 'properties': {'magmom': 0.0}}, {'species': [{'element': 'O', 'occu': 1}], 'abc': [0.60335414, 0.97232235, 0.17105714], 'xyz': [2.7537750686895897, 6.610246918334176, 0.9212169860059447], 'label': 'O', 'properties': {'magmom': 0.0}}, {'species': [{'element': 'O', 'occu': 1}], 'abc': [0.62935275, 0.31604246, 0.43598117], 'xyz': [3.2859195463752924, 2.498043898264144, 2.2597861962145465], 'label': 'O', 'properties': {'magmom': 0.0}}, {'species': [{'element': 'O', 'occu': 1}], 'abc': [0.79792789, 0.99998591, 0.83096045], 'xyz': [3.020315142456152, 7.652066390631606, 4.363249100576601], 'label': 'O', 'properties': {'magmom': 0.0}}, {'species': [{'element': 'O', 'occu': 1}], 'abc': [0.97240679, 0.60331133, 0.32893378], 'xyz': [5.487730728871592, 4.1536933939265035, 1.6956051056466028], 'label': 'O', 'properties': {'magmom': 0.0}}, {'species': [{'element': 'O', 'occu': 1}], 'abc': [0.98147132, 0.19424741, 0.36813164], 'xyz': [5.969555258663204, 1.4144453138406927, 1.8713547239852257], 'label': 'O', 'properties': {'magmom': 0.0}}], '@version': '2020.10.20'}, 'initial_magmoms': [0.0, 0.0, 5.0, 5.0, 5.0, 5.0, 5.0, 1.73, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], 'delta_E': 0.0, 'energy_per_atom': -7.066531543000001, 'ordering': 'FM', 'ordering_changed': True, 'n_dft_records': 1, 'input_ordering': 'FM', 'origin': 'fm', 'input_index': 12, 'index': 0}

======================================================================
record_by_task
======================================================================
Type: <class 'dict'>
Number of entries: 23155
First key: 27
First value type: <class 'dict'>
First value:

Checking the known AM material

In [ ]:
# ============================================================
# CHECK KNOWN AM: Li2Fe(WO4)2, task 28294
# ============================================================

known_task = 28294

print("record_by_task:")
if isinstance(record_by_task, dict):
    rec = record_by_task.get(known_task)
    print(rec)

print("\nrecords_by_task:")
if isinstance(records_by_task, dict):
    rec = records_by_task.get(known_task)
    print(rec)

record_by_task:
None

records_by_task:
{'task_id': 28294, 'parent_structure_id': '03184e0f328eb3520417711ec3daa327f40c3aedc29a710f7b7ac5c6ce7d08c9', 'formula': 'Li2Fe(WO4)2', 'input_structure': {'@module': 'pymatgen.core.structure', '@class': 'Structure', 'charge': None, 'lattice': {'matrix': [[-2.52672338, 4.79779338, -1.88186254], [-5.12147962, 0.10889061, 6.0275799], [2.47335523, 4.87668291, 4.04154379]], 'a': 5.7397350962971885, 'b': 7.910317952769378, 'c': 6.799529285541904, 'alpha': 76.86308668795567, 'beta': 75.84774359897716, 'gamma': 87.3238265087798, 'volume': 291.5031273429439}, 'sites': [{'species': [{'element': 'Li', 'occu': 1}], 'abc': [0.31137766, 0.14605565, 0.60412622], 'xyz': [-0.040567502575413084, 4.4559617772072375, 2.735994718891753], 'label': 'Li', 'properties': {'magmom': 0.6}}, {'species': [{'element': 'Li', 'occu': 1}], 'abc': [0.81168287, 0.64642609, 0.10374043], 'xyz': [-5.104969195442837, 4.470585613662466, 2.788180810145331], 'label': 'Li', 'properties': {'magmom': 0.6}}, {'species': [{'element': 'Li', 'occu': 1}], 'abc': [0.68832856, 0.85357271, 0.3962729], 'xyz': [-5.130647454404635, 5.327901540630325, 5.451192255848678], 'label': 'Li', 'properties': {'magmom': 0.6}}, {'species': [{'element': 'Li', 'occu': 1}], 'abc': [0.18862644, 0.35393184, 0.89589587], 'xyz': [-0.07339280586336727, 5.312530617449572, 5.3991858031496065], 'label': 'Li', 'properties': {'magmom': 0.6}}, {'species': [{'element': 'Fe', 'occu': 1}], 'abc': [0.25002496, 0.74997302, 0.74984692], 'xyz': [-2.618077648214025, 4.937998777434244, 7.080548857581926], 'label': 'Fe', 'properties': {'magmom': -5.0}}, {'species': [{'element': 'Fe', 'occu': 1}], 'abc': [0.74990812, 0.25009825, 0.24997034], 'xyz': [-2.557418022244632, 4.844163649831567, 1.106529260566539], 'label': 'Fe', 'properties': {'magmom': 5.0}}, {'species': [{'element': 'W', 'occu': 1}], 'abc': [0.77459281, 0.45894652, 0.702018], 'xyz': [-2.57132712000268, 7.1898304056461555, 4.145896114602832], 'label': 'W', 'properties': {'magmom': -5.0}}, {'species': [{'element': 'W', 'occu': 1}], 'abc': [0.7254097, 0.04102921, 0.79799747], 'xyz': [-0.06930869595721822, 7.376414176324742, 2.1073272202404523], 'label': 'W', 'properties': {'magmom': -5.0}}, {'species': [{'element': 'W', 'occu': 1}], 'abc': [0.27393197, 0.95888953, 0.20157284], 'xyz': [-5.104522260814884, 2.4016898820288364, 6.078946404231706], 'label': 'W', 'properties': {'magmom': 5.0}}, {'species': [{'element': 'W', 'occu': 1}], 'abc': [0.22606463, 0.54112007, 0.29841797], 'xyz': [-2.604444549664539, 2.598824094107585, 4.042291192080539], 'label': 'W', 'properties': {'magmom': 5.0}}, {'species': [{'element': 'O', 'occu': 1}], 'abc': [0.02828544, 0.78896781, 0.25358195], 'xyz': [-3.4849538000465214, 1.458257644733126, 5.727199758618193], 'label': 'O', 'properties': {'magmom': 0.6}}, {'species': [{'element': 'O', 'occu': 1}], 'abc': [0.52879761, 0.28958426, 0.75374094], 'xyz': [-0.9549560743237868, 6.244350240000957, 3.7966448667576076], 'label': 'O', 'properties': {'magmom': 0.6}}, {'species': [{'element': 'O', 'occu': 1}], 'abc': [0.97120899, 0.21041968, 0.74627465], 'xyz': [-1.6858342560721882, 8.321917621950924, 2.4567412942821214], 'label': 'O', 'properties': {'magmom': 0.6}}, {'species': [{'element': 'O', 'occu': 1}], 'abc': [0.47172273, 0.71101844, 0.24644502], 'xyz': [-4.2238332215481655, 3.542485640130984, 4.394021462777248], 'label': 'O', 'properties': {'magmom': 0.6}}, {'species': [{'element': 'O', 'occu': 1}], 'abc': [0.71787265, 0.05402667, 0.52376659], 'xyz': [-0.7951012632832566, 6.004331223187603, 1.0915380308543787], 'label': 'O', 'properties': {'magmom': 0.6}}, {'species': [{'element': 'O', 'occu': 1}], 'abc': [0.2183985, 0.55264163, 0.02583627], 'xyz': [-3.3182731677873183, 1.2340036580711702, 3.0245140415243106], 'label': 'O', 'properties': {'magmom': 0.6}}, {'species': [{'element': 'O', 'occu': 1}], 'abc': [0.28161018, 0.94735393, 0.47417717], 'xyz': [-4.390596287907815, 3.76667710591937, 7.096707654802625], 'label': 'O', 'properties': {'magmom': 0.6}}, {'species': [{'element': 'O', 'occu': 1}], 'abc': [0.78213053, 0.44597906, 0.97624366], 'xyz': [-1.8457028008842062, 8.56189438373837, 5.161843773679419], 'label': 'O', 'properties': {'magmom': 0.6}}, {'species': [{'element': 'O', 'occu': 1}], 'abc': [0.61166819, 0.05629027, 0.10712087], 'xyz': [-1.5688578230279293, 3.4631815906092784, -0.37884766672513204], 'label': 'O', 'properties': {'magmom': 0.6}}, {'species': [{'element': 'O', 'occu': 1}], 'abc': [0.11297761, 0.55775225, 0.60954639], 'xyz': [-1.6343551983535467, 3.5753416750427895, 5.612796346383464], 'label': 'O', 'properties': {'magmom': 0.6}}, {'species': [{'element': 'O', 'occu': 1}], 'abc': [0.38703411, 0.94223605, 0.89046852], 'xyz': [-3.6011258908064323, 6.302042962417676, 8.549925599920646], 'label': 'O', 'properties': {'magmom': 0.6}}, {'species': [{'element': 'O', 'occu': 1}], 'abc': [0.88833386, 0.44370711, 0.39290236], 'xyz': [-3.545223747436402, 6.226418074917752, 2.590689936709829], 'label': 'O', 'properties': {'magmom': 0.6}}, {'species': [{'element': 'O', 'occu': 1}], 'abc': [0.60092324, 0.65409063, 0.64760013], 'xyz': [-3.2665334627871307, 6.112470356940914, 5.429032883199601], 'label': 'O', 'properties': {'magmom': 0.6}}, {'species': [{'element': 'O', 'occu': 1}], 'abc': [0.10100725, 0.15468436, 0.14760008], 'xyz': [-0.6823627475808296, 1.2212543773504976, 1.3388227658644523], 'label': 'O', 'properties': {'magmom': 0.6}}, {'species': [{'element': 'O', 'occu': 1}], 'abc': [0.39898495, 0.34530868, 0.35242725], 'xyz': [-1.904938186680215, 3.6705241717264236, 2.7548909910990362], 'label': 'O', 'properties': {'magmom': 0.6}}, {'species': [{'element': 'O', 'occu': 1}], 'abc': [0.89909645, 0.84589625, 0.85240921], 'xyz': [-4.495697648445757, 8.562718581184315, 6.851780454097698], 'label': 'O', 'properties': {'magmom': 0.6}}], '@version': '2020.10.20'}, 'initial_magmoms': [0.6, 0.6, 0.6, 0.6, -5.0, 5.0, -5.0, -5.0, 5.0, 5.0, 0.6, 0.6, 0.6, 0.6, 0.6, 0.6, 0.6, 0.6, 0.6, 0.6, 0.6, 0.6, 0.6, 0.6, 0.6, 0.6], 'delta_E': 0.0, 'energy_per_atom': -6.903747734615385, 'ordering': 'AFM', 'ordering_changed': True, 'n_dft_records': 1, 'input_ordering': 'FiM', 'origin': 'afm', 'input_index': 0, 'index': 10}

In [ ]:
# Check the final magnetic moments variables for task 28294
for name in ["final_magmoms", "final_mags", "vasp_magmoms"]:
    if name in globals():
        obj = globals()[name]
        print("\n", name, "type =", type(obj))

        if isinstance(obj, dict):
            print("28294 =", obj.get(28294))
        else:
            print(obj)

 final_magmoms type = <class 'numpy.ndarray'>
[-0.000e+00  0.000e+00  0.000e+00 -0.000e+00 -3.766e+00  3.766e+00
 -2.000e-03 -2.000e-03  2.000e-03  2.000e-03 -1.000e-03  1.000e-03
  1.000e-03 -1.000e-03  1.100e-02 -1.100e-02 -1.100e-02  1.100e-02
  1.000e-02 -1.000e-02 -1.000e-02  1.000e-02 -6.000e-03  6.000e-03
  6.000e-03 -6.000e-03]

 final_mags type = <class 'list'>
[0.001, -0.001, -0.001, 0.001, 0.001, -0.001, 0.001, -0.001, -1.769, -1.769, 1.769, 1.769, 0.004, -0.004, 0.0, -0.0, -0.005, 0.005, 0.001, -0.001, -0.033, 0.033, -0.032, 0.032, 0.018, -0.018, 0.027, -0.027, 0.04, -0.04, 0.037, -0.037, 0.033, -0.033, 0.031, -0.031, 0.026, -0.026, -0.018, 0.018, 0.04, -0.04, 0.037, -0.037]

 vasp_magmoms type = <class 'numpy.ndarray'>
[-5.000e-03  0.000e+00 -4.265e+00 -4.265e+00  4.216e+00  4.216e+00
  4.163e+00  4.163e+00  4.216e+00  4.216e+00  2.000e-03  2.000e-03
  6.000e-03  6.000e-03  1.700e-02 -2.000e-03  1.000e-02  8.300e-02
  8.300e-02  1.000e-02  1.000e-02  8.300e-02  8.300e-02  1.000e-02
  6.500e-02  2.500e-02  2.500e-02  6.500e-02  2.500e-02  6.500e-02
  6.500e-02  2.500e-02  6.900e-02 -1.190e-01 -1.190e-01  6.900e-02
  1.050e-01  1.050e-01  1.050e-01  1.050e-01]

### Step - 9.3 - Attaching the final DFT information

In [ ]:
# ============================================================
# STEP 9 — CORRECT DFT LOOKUP USING STRING TASK IDs
# ============================================================

dft_rows = []
missing_tasks = []

for _, row in top5_candidates.iterrows():

    task_id = int(row["task_id"])

    # record_by_task uses STRING keys
    rec = record_by_task.get(str(task_id))

    if rec is None:
        missing_tasks.append(task_id)
        continue

    mag_data = rec.get("magmoms", {})

    dft_rows.append({
        "task_id": task_id,

        # Final relaxed DFT structure
        "dft_structure": rec.get("structure"),

        # Final VASP magnetic moments
        "final_magmoms": mag_data.get("vasp"),

        # Total magnetic moment
        "total_magnetization": rec.get(
            "total_magnetization"
        ),

        # DFT information
        "dft_ordering": rec.get("ordering"),
        "dft_energy_per_atom": rec.get(
            "energy_per_atom"
        ),
        "dft_energy_above_ground": rec.get(
            "energy_above_ground_state_per_atom"
        ),
        "symmetry": rec.get("symmetry"),
        "symmetry_changed": rec.get(
            "symmetry_changed"
        ),
    })

dft_info = pd.DataFrame(dft_rows)

print("Top-5 candidates:", len(top5_candidates))
print("DFT records found:", len(dft_info))
print("Missing DFT records:", len(missing_tasks))

if missing_tasks:
    print("Missing:", missing_tasks[:20])

Top-5 candidates: 1198
DFT records found: 1198
Missing DFT records: 0

Verifying our known AM state

In [ ]:
# ============================================================
# VALIDATE Li2Fe(WO4)2 TASK 28294
# ============================================================

rec = record_by_task["28294"]

print("Formula:", rec["formula"])
print("Task ID:", rec["task_id"])
print("Ordering:", rec["ordering"])
print("Total magnetization:", rec["total_magnetization"])
print("Symmetry:", rec["symmetry"])

print("\nFinal VASP magnetic moments:")
print(rec["magmoms"]["vasp"])

Formula: Li2 Fe1 W2 O8
Task ID: 28294
Ordering: AFM
Total magnetization: 1e-06
Symmetry: P-1

Final VASP magnetic moments:
[-0.0, 0.0, 0.0, -0.0, -3.766, 3.766, -0.002, -0.002, 0.002, 0.002, -0.001, 0.001, 0.001, -0.001, 0.011, -0.011, -0.011, 0.011, 0.01, -0.01, -0.01, 0.01, -0.006, 0.006, 0.006, -0.006]

Merging

In [ ]:
# ============================================================
# MERGE ML + FINAL DFT INFORMATION
# ============================================================

top5_full = top5_candidates.merge(
    dft_info,
    on="task_id",
    how="left"
)

print("Rows:", len(top5_full))

display(
    top5_full[
        [
            "task_id",
            "formula",
            "ML_rank",
            "pred_energy",
            "delta_E",
            "dft_energy_per_atom",
            "total_magnetization",
            "dft_ordering",
        ]
    ].head(10)
)

Rows: 1198

,task_id,formula,ML_rank,pred_energy,delta_E,dft_energy_per_atom,total_magnetization,dft_ordering
0,28096,Li2Fe(WO4)2,1,-0.002875,0.001110,-6.902637,1.400000e-06,AFM
1,28032,Li2Fe(WO4)2,2,-0.002809,0.001433,-6.902315,7.000000e-07,AFM
2,28294,Li2Fe(WO4)2,3,-0.002588,0.000000,-6.903748,1.000000e-06,AFM
3,28216,Li2Fe(WO4)2,4,-0.002550,0.001194,-6.902554,4.300000e-06,AFM
4,27988,Li2Fe(WO4)2,5,-0.002530,0.002164,-6.901583,0.000000e+00,AFM
5,32534,LiCrSnO4,1,-0.000016,0.000321,-6.653044,3.126000e-04,FiM
6,32991,LiCrSnO4,2,-0.000001,0.000183,-6.653181,1.373000e-04,AFM
7,32425,LiCrSnO4,3,0.000002,0.000270,-6.653094,7.650000e-05,AFM
8,32678,LiCrSnO4,4,0.000433,0.000096,-6.653268,5.420000e-05,AFM
9,32834,LiCrSnO4,5,0.000442,0.000113,-6.653252,3.655000e-04,AFM

In [ ]:
# ============================================================
# CHECK TASK 28294 INSIDE THE TOP-5 TABLE
# ============================================================

display(
    top5_full[
        top5_full["task_id"] == 28294
    ][
        [
            "task_id",
            "formula",
            "ML_rank",
            "pred_energy",
            "delta_E",
            "dft_energy_per_atom",
            "total_magnetization",
            "dft_ordering",
            "symmetry",
        ]
    ]
)

,task_id,formula,ML_rank,pred_energy,delta_E,dft_energy_per_atom,total_magnetization,dft_ordering,symmetry
2,28294,Li2Fe(WO4)2,3,-0.002588,0.0,-6.903748,0.000001,AFM,P-1

### Step - 9.4 - Validating the symmetry function on task 28294 again using the actual final DFT structure and final VASP moments.

In [ ]:
# ============================================================
# DEFINE MAGNETIC P / T / PT SYMMETRY TEST
# ============================================================

import spglib
import numpy as np


def magnetic_PT_classification(
    structure,
    magmoms,
    symprec=1e-2,
    mag_symprec=1e-2,
):

    lattice = np.array(
        structure.lattice.matrix,
        dtype=float
    )

    positions = np.array(
        structure.frac_coords,
        dtype=float
    )

    numbers = np.array(
        structure.atomic_numbers,
        dtype=int
    )

    magmoms = np.array(
        magmoms,
        dtype=float
    )

    # spglib magnetic cell
    cell = (
        lattice,
        positions,
        numbers,
        magmoms
    )

    mag_sym = spglib.get_magnetic_symmetry(
        cell,
        symprec=symprec,
        mag_symprec=mag_symprec
    )

    if mag_sym is None:
        return {
            "P_preserved": np.nan,
            "T_preserved": np.nan,
            "PT_preserved": np.nan,
            "n_operations": 0,
            "n_time_reversal_ops": 0,
            "symmetry_status": "failed",
        }

    rotations = np.asarray(
        mag_sym["rotations"],
        dtype=int
    )

    time_reversals = np.asarray(
        mag_sym["time_reversals"],
        dtype=bool
    )

    I = np.eye(3, dtype=int)
    minus_I = -I

    # P = spatial inversion only
    P_preserved = np.any(
        np.all(rotations == minus_I, axis=(1, 2))
        & (~time_reversals)
    )

    # T = time reversal only
    T_preserved = np.any(
        np.all(rotations == I, axis=(1, 2))
        & time_reversals
    )

    # PT = inversion + time reversal
    PT_preserved = np.any(
        np.all(rotations == minus_I, axis=(1, 2))
        & time_reversals
    )

    return {
        "P_preserved": bool(P_preserved),
        "T_preserved": bool(T_preserved),
        "PT_preserved": bool(PT_preserved),
        "n_operations": len(rotations),
        "n_time_reversal_ops": int(time_reversals.sum()),
        "symmetry_status": "ok",
    }

print("magnetic_PT_classification() is ready.")

magnetic_PT_classification() is ready.

In [ ]:
# ============================================================
# VALIDATE KNOWN AM STATE
# ============================================================

from pymatgen.core import Structure

known_rec = record_by_task["28294"]

# Convert serialized dictionary -> pymatgen Structure object
known_structure = Structure.from_dict(
    known_rec["structure"]
)

known_magmoms = np.array(
    known_rec["magmoms"]["vasp"],
    dtype=float
)

known_sym = magnetic_PT_classification(
    known_structure,
    known_magmoms,
    symprec=1e-2,
    mag_symprec=1e-2
)

print("Li2Fe(WO4)2 — task 28294")
print("--------------------------------")
print("P preserved :", known_sym["P_preserved"])
print("T preserved :", known_sym["T_preserved"])
print("PT preserved:", known_sym["PT_preserved"])
print("Operations   :", known_sym["n_operations"])
print("T operations:", known_sym["n_time_reversal_ops"])
print("Status       :", known_sym["symmetry_status"])

Li2Fe(WO4)2 — task 28294
--------------------------------
P preserved : True
T preserved : False
PT preserved: False
Operations   : 2
T operations: 0
Status       : ok

### Step - 9.5 - Magnetic symmetry screening

Creating the 259 DFT-selected states

In [ ]:
# ============================================================
# SELECT LOWEST-DFT-ENERGY STATE WITHIN EACH PARENT'S TOP-5
# ============================================================

top5_dft_selected = (
    top5_full
    .sort_values(
        ["parent_structure_id", "dft_energy_per_atom"]
    )
    .groupby("parent_structure_id", as_index=False)
    .first()
)

print("Number of parent materials:", len(top5_dft_selected))

display(
    top5_dft_selected[
        [
            "task_id",
            "formula",
            "ML_rank",
            "pred_energy",
            "delta_E",
            "dft_energy_per_atom",
            "total_magnetization",
            "dft_ordering",
            "symmetry",
        ]
    ].head(20)
)

Number of parent materials: 259

,task_id,formula,ML_rank,pred_energy,delta_E,dft_energy_per_atom,total_magnetization,dft_ordering,symmetry
0,28294,Li2Fe(WO4)2,3,-0.002588,0.000000,-6.903748,1.000000e-06,AFM,P-1
1,32678,LiCrSnO4,4,0.000433,0.000096,-6.653268,5.420000e-05,AFM,Imma
2,29656,V2CoO4,1,0.013108,0.000000,-7.553429,2.009580e+00,FiM,C2/m
3,33877,CoH5CN(ClO)2,1,0.000096,0.000264,-5.232197,1.000000e-07,AFM,C2/c
4,45309,NaCo2H3(SO5)2,4,0.001961,0.000000,-5.785045,1.900000e-06,AFM,Cm
5,17608,LiCr(CO3)2,1,-0.005627,0.000063,-7.452183,3.000003e+00,FM,R-3
6,52617,CaLaMnSnO6,1,0.001078,0.000000,-7.202124,8.002934e+00,FM,Pc
7,53621,LiVSiO4,5,0.006333,0.000451,-7.294286,2.700000e-06,FiM,P6_422
8,53553,ZnCr4(CuO4)3,5,0.005746,0.001552,-6.394592,2.222625e+01,FM,Im-3
9,38840,Li4Cr3FeO8,1,-0.000122,0.000000,-6.724375,2.000002e+00,FiM,P-1
10,23995,ScMnO3,1,-0.002973,0.000000,-8.263226,1.599979e+01,FM,P2_1/c
11,7605,Ba3Mn2O8,1,0.004961,0.000000,-6.645346,0.000000e+00,AFM,R-3m
12,53935,SrMn(GeO3)2,3,-0.002309,0.000000,-6.845358,1.000000e-07,AFM,P-1
13,33225,LiFePO4,1,-0.000904,0.000000,-6.798103,1.000000e-06,FiM,P1
14,52096,Mn3TeO6,1,-0.003429,0.000159,-7.001651,2.600000e-06,AFM,P2_1/c
15,51786,Sr3LaMn4O12,1,0.004499,0.000000,-7.178450,1.300011e+01,FM,P2
16,26698,Li2FeO3,2,0.000653,0.000000,-5.679626,4.910000e-05,AFM,P-1
17,38368,Li2SiNiO4,5,0.001223,0.001030,-6.123783,7.000000e-06,FiM,P1
18,50826,Li6V2OF11,5,-0.001093,0.000033,-5.442667,2.038198e-01,FiM,P1
19,48339,ZnCr(SiO3)2,1,-0.002844,0.000000,-7.216485,8.000000e-07,AFM,C2/c

Symmetry screen

In [ ]:
# ============================================================
# FULL TOP-5 -> DFT -> MAGNETIC SYMMETRY SCREEN
# ============================================================

from pymatgen.core import Structure
import numpy as np
import pandas as pd

symmetry_results = []

for _, row in top5_dft_selected.iterrows():

    task_id = int(row["task_id"])

    try:
        structure = Structure.from_dict(
            row["dft_structure"]
        )

        magmoms = np.asarray(
            row["final_magmoms"],
            dtype=float
        )

        result = magnetic_PT_classification(
            structure,
            magmoms,
            symprec=1e-2,
            mag_symprec=1e-2
        )

    except Exception as e:

        result = {
            "P_preserved": np.nan,
            "T_preserved": np.nan,
            "PT_preserved": np.nan,
            "n_operations": np.nan,
            "n_time_reversal_ops": np.nan,
            "symmetry_status": f"ERROR: {e}",
        }

    result["task_id"] = task_id
    symmetry_results.append(result)


symmetry_df = pd.DataFrame(symmetry_results)

top5_final = top5_dft_selected.merge(
    symmetry_df,
    on="task_id",
    how="left"
)

print("Parent materials:", len(top5_final))
print(
    "Successful symmetry analyses:",
    (top5_final["symmetry_status"] == "ok").sum()
)
print(
    "Failures:",
    (top5_final["symmetry_status"] != "ok").sum()
)

print("\nStatus:")
print(top5_final["symmetry_status"].value_counts(dropna=False))

Parent materials: 259
Successful symmetry analyses: 259
Failures: 0

Status:
symmetry_status
ok    259
Name: count, dtype: int64

In [ ]:
# ============================================================
# COMPENSATION + P/T/PT SCREEN
# ============================================================

MAG_TOL = 1e-2

top5_final["compensated"] = (
    top5_final["total_magnetization"].abs() < MAG_TOL
)

print("Compensated:", top5_final["compensated"].sum())
print("Non-compensated:", (~top5_final["compensated"]).sum())

print("\nT preserved:")
print(top5_final["T_preserved"].value_counts(dropna=False))

print("\nPT preserved:")
print(top5_final["PT_preserved"].value_counts(dropna=False))

print("\nP preserved:")
print(top5_final["P_preserved"].value_counts(dropna=False))

Compensated: 170
Non-compensated: 89

T preserved:
T_preserved
False    168
True      91
Name: count, dtype: int64

PT preserved:
PT_preserved
False    187
True      72
Name: count, dtype: int64

P preserved:
P_preserved
False    130
True     129
Name: count, dtype: int64

Preliminary AM screening

In [ ]:
# ============================================================
# PRELIMINARY AM CLASSIFICATION
# ============================================================

top5_final["AM_candidate"] = (
    top5_final["compensated"]
    & (top5_final["T_preserved"] == False)
    & (top5_final["PT_preserved"] == False)
)

# Use a string default instead of np.nan
top5_final["AM_type"] = np.select(
    [
        top5_final["AM_candidate"]
        & (top5_final["P_preserved"] == True),

        top5_final["AM_candidate"]
        & (top5_final["P_preserved"] == False),
    ],
    [
        "S-type",
        "S/A-type",
    ],
    default="Not AM"
)

am_candidates = (
    top5_final[
        top5_final["AM_candidate"]
    ]
    .sort_values(["AM_type", "ML_rank"])
    .reset_index(drop=True)
)

print("\n================================================")
print("PRELIMINARY AM DISCOVERY")
print("================================================")

print("Total AM candidates:", len(am_candidates))

print("\nAM type:")
print(
    am_candidates["AM_type"]
    .value_counts(dropna=False)
)

================================================
PRELIMINARY AM DISCOVERY
================================================
Total AM candidates: 58

AM type:
AM_type
S-type      29
S/A-type    29
Name: count, dtype: int64

In [ ]:
display(
    am_candidates[
        [
            "task_id",
            "formula",
            "ML_rank",
            "dft_ordering",
            "total_magnetization",
            "symmetry",
            "P_preserved",
            "T_preserved",
            "PT_preserved",
            "AM_type",
        ]
    ]
)

,task_id,formula,ML_rank,dft_ordering,total_magnetization,symmetry,P_preserved,T_preserved,PT_preserved,AM_type
0,33877,CoH5CN(ClO)2,1,AFM,1.000000e-07,C2/c,True,False,False,S-type
1,52096,Mn3TeO6,1,AFM,2.600000e-06,P2_1/c,True,False,False,S-type
2,8096,Mn2CdO4,1,AFM,0.000000e+00,I4_1/amd,True,False,False,S-type
3,37955,Li4Ni3TeO8,1,FiM,5.635000e-04,R-3m,True,False,False,S-type
4,37876,Li3TiMn3O8,1,FiM,1.600000e-05,P-1,True,False,False,S-type
5,2136,Sr2MnWO6,1,AFM,0.000000e+00,P2_1/c,True,False,False,S-type
6,5140,NiSeO3,1,AFM,0.000000e+00,Pnma,True,False,False,S-type
7,40225,BaCo2(PO4)2,1,AFM,5.380000e-05,P2_1/c,True,False,False,S-type
8,30779,LiMnSnO4,1,AFM,2.600000e-06,Imma,True,False,False,S-type
9,4286,Zn(FeO2)2,1,AFM,0.000000e+00,Fd-3m,True,False,False,S-type
10,2797,MgMn2O4,1,AFM,0.000000e+00,I4_1/amd,True,False,False,S-type
11,309,Fe2SiO4,1,FiM,0.000000e+00,Fd-3m,True,False,False,S-type
12,41088,MgMnO2,1,AFM,7.400000e-06,Fd-3m,True,False,False,S-type
13,4189,Ca2MnO4,2,AFM,1.200000e-06,I4_1/acd,True,False,False,S-type
14,4981,LaCrO3,2,AFM,4.200000e-06,Pnma,True,False,False,S-type
15,28294,Li2Fe(WO4)2,3,AFM,1.000000e-06,P-1,True,False,False,S-type
16,38193,LiVO2,3,AFM,3.926000e-04,P-1,True,False,False,S-type
17,7162,Co(ClO4)2,3,FiM,2.000000e-06,P-1,True,False,False,S-type
18,7367,CrCoO4,3,FiM,2.687400e-03,C2/m,True,False,False,S-type
19,30169,LiTiNiO4,3,AFM,1.560000e-05,C2/c,True,False,False,S-type
20,41393,Li2MnCoO4,3,FiM,6.897400e-03,P-1,True,False,False,S-type
21,29916,Zn(FeO2)2,3,FiM,2.100000e-06,Imma,True,False,False,S-type
22,14465,LiCoAsO4,3,AFM,1.979000e-04,Pnma,True,False,False,S-type
23,10560,CaV2O5,3,AFM,1.700000e-06,Pmmn,True,False,False,S-type
24,477,MnO2,4,FiM,1.900000e-06,Pnma,True,False,False,S-type
25,9540,NaMnO2,4,FiM,6.000000e-07,C2/c,True,False,False,S-type
26,769,LaVO3,4,AFM,9.976000e-04,Pnma,True,False,False,S-type
27,1908,Sr2CoTeO6,4,FiM,2.493000e-04,P-1,True,False,False,S-type
28,14352,LiMn3O4,4,FiM,2.000000e-07,P-1,True,False,False,S-type
29,33225,LiFePO4,1,FiM,1.000000e-06,P1,False,False,False,S/A-type
30,30688,LiCo2OF3,1,AFM,2.700000e-06,C2,False,False,False,S/A-type
31,49391,Li2TiFe2O5,1,AFM,3.840000e-05,Cc,False,False,False,S/A-type
32,2950,SrFe2S2O,1,AFM,1.140000e-05,Pmn2_1,False,False,False,S/A-type
33,29064,LiMn2OF3,1,FiM,1.000000e-06,Cm,False,False,False,S/A-type
34,15141,KCoO2,1,FiM,2.188600e-03,I-4,False,False,False,S/A-type
35,40636,Li2TiFeO4,2,AFM,4.000000e-07,P1,False,False,False,S/A-type
36,52258,Li5Co3(SbO5)2,2,FiM,8.251200e-03,P1,False,False,False,S/A-type
37,47306,LiFeBO3,2,FiM,8.080000e-05,P1,False,False,False,S/A-type
38,53849,Li3MnV4O12,2,FiM,3.264800e-03,C2,False,False,False,S/A-type
39,12578,SrLaCoO4,2,FiM,6.000000e-07,Aea2,False,False,False,S/A-type
40,49844,SrLaTiMnO6,2,AFM,0.000000e+00,Pc,False,False,False,S/A-type
41,53056,LaMgFeAgO6,2,FiM,5.121000e-04,Pc,False,False,False,S/A-type
42,36830,Ni3(AsO4)2,2,FiM,0.000000e+00,Cmce,False,False,False,S/A-type
43,1791,K3NiO2,2,AFM,1.380900e-03,P2_1,False,False,False,S/A-type
44,41465,Li2Fe2P2O9F,2,FiM,2.300000e-06,P1,False,False,False,S/A-type
45,27974,Ba2CoSi2O7,2,AFM,8.000000e-07,P-42_1m,False,False,False,S/A-type
46,55367,Mn3(P2O7)2,3,FiM,1.860000e-05,P1,False,False,False,S/A-type
47,53979,VCr(P2O7)2,3,AFM,2.525000e-04,P1,False,False,False,S/A-type
48,45309,NaCo2H3(SO5)2,4,AFM,1.900000e-06,Cm,False,False,False,S/A-type
49,40381,Li2VOF4,4,AFM,5.500000e-06,P1,False,False,False,S/A-type
50,55156,Li2Si2NiO6,4,FiM,4.220000e-05,P1,False,False,False,S/A-type
51,52663,Li4VCr(TeO6)2,4,FiM,3.020000e-05,P1,False,False,False,S/A-type
52,38368,Li2SiNiO4,5,FiM,7.000000e-06,P1,False,False,False,S/A-type
53,44990,Li2VPO5,5,AFM,0.000000e+00,Pna2_1,False,False,False,S/A-type
54,51836,SrCo(GeO3)2,5,AFM,1.600000e-06,P1,False,False,False,S/A-type
55,10652,NbVO4,5,FiM,4.576000e-04,Cm,False,False,False,S/A-type
56,45855,V2CoO6,5,FiM,8.690000e-05,P1,False,False,False,S/A-type
57,6170,Ba2CoReO6,5,FiM,1.920000e-05,R-3m,False,False,False,S/A-type

### Step - 9.6 - Separating the 58 into ground-state AMs and excited-state AM-like states

In [ ]:
# ============================================================
# STEP 17: CHECK WHETHER THE 58 AM CANDIDATES ARE
#          ACTUAL GLOBAL DFT GROUND STATES
# ============================================================

# Find the true DFT ground-state energy for every parent
global_ground_energy = (
    test_df
    .groupby("parent_structure_id")["delta_E"]
    .min()
    .rename("global_ground_delta_E")
)

# Find one task corresponding to the minimum-energy state
idx_ground = (
    test_df
    .groupby("parent_structure_id")["delta_E"]
    .idxmin()
)

global_ground_tasks = (
    test_df.loc[
        idx_ground,
        ["parent_structure_id", "task_id", "formula", "delta_E"]
    ]
    .rename(columns={
        "task_id": "global_ground_task_id",
        "formula": "global_ground_formula",
        "delta_E": "global_ground_delta_E_check",
    })
)

# Merge global-ground information into the 58 candidates
am_candidates_checked = (
    am_candidates
    .merge(
        global_ground_tasks,
        on="parent_structure_id",
        how="left"
    )
)

# A tiny numerical tolerance for DFT degeneracy
GROUND_TOL = 1e-8

am_candidates_checked["is_global_DFT_ground"] = (
    am_candidates_checked["delta_E"]
    <= am_candidates_checked["global_ground_delta_E_check"]
    + GROUND_TOL
)

print("Total preliminary AM candidates:",
      len(am_candidates_checked))

print(
    "Candidates that are global DFT ground states:",
    am_candidates_checked["is_global_DFT_ground"].sum()
)

print(
    "Candidates that are NOT global DFT ground states:",
    (~am_candidates_checked["is_global_DFT_ground"]).sum()
)

Total preliminary AM candidates: 58
Candidates that are global DFT ground states: 48
Candidates that are NOT global DFT ground states: 10

### Step - 9.7 - Comparing them with the original 55 known AM ground states

In [ ]:
# ============================================================
# STEP 18: COMPARE WITH THE 55 KNOWN AM GROUND STATES
# ============================================================

known_am_ids = set(
    master_am["task_id"].astype(int)
)

am_candidates_checked["known_AM_ground"] = (
    am_candidates_checked["task_id"]
    .astype(int)
    .isin(known_am_ids)
)

print("Known AM ground states recovered:",
      am_candidates_checked["known_AM_ground"].sum())

print(
    "\nKnown AM ground states recovered AND global ground:",
    (
        am_candidates_checked["known_AM_ground"]
        & am_candidates_checked["is_global_DFT_ground"]
    ).sum()
)

print(
    "\nPreliminary candidates that are global ground states "
    "but are NOT in the original 55:",
    (
        ~am_candidates_checked["known_AM_ground"]
        & am_candidates_checked["is_global_DFT_ground"]
    ).sum()
)

Known AM ground states recovered: 27

Known AM ground states recovered AND global ground: 27

Preliminary candidates that are global ground states but are NOT in the original 55: 21

### Step - 9.8 - Classifying The 58 candidates

In [ ]:
# ============================================================
# STEP 19: CLASSIFY THE 58 CANDIDATES
# ============================================================

am_candidates_checked["candidate_category"] = np.select(
    [
        (
            am_candidates_checked["known_AM_ground"]
            & am_candidates_checked["is_global_DFT_ground"]
        ),

        (
            ~am_candidates_checked["known_AM_ground"]
            & am_candidates_checked["is_global_DFT_ground"]
        ),

        (
            am_candidates_checked["known_AM_ground"]
            & ~am_candidates_checked["is_global_DFT_ground"]
        ),
    ],
    [
        "Known AM ground state",
        "New preliminary AM ground candidate",
        "Known AM symmetry, but not ground state",
    ],
    default="Other preliminary candidate"
)

print(
    am_candidates_checked[
        "candidate_category"
    ].value_counts()
)

candidate_category
Known AM ground state                  27
New preliminary AM ground candidate    21
Other preliminary candidate            10
Name: count, dtype: int64

Displaying

In [ ]:
display(
    am_candidates_checked[
        [
            "task_id",
            "formula",
            "ML_rank",
            "delta_E",
            "global_ground_task_id",
            "global_ground_delta_E_check",
            "is_global_DFT_ground",
            "AM_type",
            "candidate_category",
        ]
    ]
    .sort_values(
        ["candidate_category", "formula"]
    )
    .reset_index(drop=True)
)

,task_id,formula,ML_rank,delta_E,global_ground_task_id,global_ground_delta_E_check,is_global_DFT_ground,AM_type,candidate_category
0,27974,Ba2CoSi2O7,2,0.000000,27974,0.0,True,S/A-type,Known AM ground state
1,40225,BaCo2(PO4)2,1,0.000000,40225,0.0,True,S-type,Known AM ground state
2,4189,Ca2MnO4,2,0.000000,4189,0.0,True,S-type,Known AM ground state
3,10560,CaV2O5,3,0.000000,10560,0.0,True,S-type,Known AM ground state
4,7162,Co(ClO4)2,3,0.000000,7162,0.0,True,S-type,Known AM ground state
5,1791,K3NiO2,2,0.000000,1791,0.0,True,S/A-type,Known AM ground state
6,4981,LaCrO3,2,0.000000,4981,0.0,True,S-type,Known AM ground state
7,28294,Li2Fe(WO4)2,3,0.000000,28294,0.0,True,S-type,Known AM ground state
8,49391,Li2TiFe2O5,1,0.000000,49391,0.0,True,S/A-type,Known AM ground state
9,52663,Li4VCr(TeO6)2,4,0.000000,52663,0.0,True,S/A-type,Known AM ground state
10,30688,LiCo2OF3,1,0.000000,30688,0.0,True,S/A-type,Known AM ground state
11,14465,LiCoAsO4,3,0.000000,14465,0.0,True,S-type,Known AM ground state
12,30779,LiMnSnO4,1,0.000000,30779,0.0,True,S-type,Known AM ground state
13,30169,LiTiNiO4,3,0.000000,30169,0.0,True,S-type,Known AM ground state
14,2797,MgMn2O4,1,0.000000,2797,0.0,True,S-type,Known AM ground state
15,41088,MgMnO2,1,0.000000,41088,0.0,True,S-type,Known AM ground state
16,8096,Mn2CdO4,1,0.000000,8096,0.0,True,S-type,Known AM ground state
17,55367,Mn3(P2O7)2,3,0.000000,55367,0.0,True,S/A-type,Known AM ground state
18,477,MnO2,4,0.000000,477,0.0,True,S-type,Known AM ground state
19,45309,NaCo2H3(SO5)2,4,0.000000,45309,0.0,True,S/A-type,Known AM ground state
20,10652,NbVO4,5,0.000000,10652,0.0,True,S/A-type,Known AM ground state
21,5140,NiSeO3,1,0.000000,5140,0.0,True,S-type,Known AM ground state
22,1908,Sr2CoTeO6,4,0.000000,1908,0.0,True,S-type,Known AM ground state
23,2136,Sr2MnWO6,1,0.000000,2136,0.0,True,S-type,Known AM ground state
24,2950,SrFe2S2O,1,0.000000,2950,0.0,True,S/A-type,Known AM ground state
25,49844,SrLaTiMnO6,2,0.000000,49844,0.0,True,S/A-type,Known AM ground state
26,4286,Zn(FeO2)2,1,0.000000,4286,0.0,True,S-type,Known AM ground state
27,6170,Ba2CoReO6,5,0.000000,6170,0.0,True,S/A-type,New preliminary AM ground candidate
28,7367,CrCoO4,3,0.000000,7367,0.0,True,S-type,New preliminary AM ground candidate
29,309,Fe2SiO4,1,0.000000,309,0.0,True,S-type,New preliminary AM ground candidate
30,15141,KCoO2,1,0.000000,15141,0.0,True,S/A-type,New preliminary AM ground candidate
31,769,LaVO3,4,0.000000,769,0.0,True,S-type,New preliminary AM ground candidate
32,41393,Li2MnCoO4,3,0.000000,41393,0.0,True,S-type,New preliminary AM ground candidate
33,55156,Li2Si2NiO6,4,0.000000,55156,0.0,True,S/A-type,New preliminary AM ground candidate
34,40636,Li2TiFeO4,2,0.000000,40636,0.0,True,S/A-type,New preliminary AM ground candidate
35,40381,Li2VOF4,4,0.000000,40381,0.0,True,S/A-type,New preliminary AM ground candidate
36,44990,Li2VPO5,5,0.000000,44990,0.0,True,S/A-type,New preliminary AM ground candidate
37,53849,Li3MnV4O12,2,0.000000,53849,0.0,True,S/A-type,New preliminary AM ground candidate
38,37876,Li3TiMn3O8,1,0.000000,37876,0.0,True,S-type,New preliminary AM ground candidate
39,47306,LiFeBO3,2,0.000000,47306,0.0,True,S/A-type,New preliminary AM ground candidate
40,33225,LiFePO4,1,0.000000,33225,0.0,True,S/A-type,New preliminary AM ground candidate
41,29064,LiMn2OF3,1,0.000000,29064,0.0,True,S/A-type,New preliminary AM ground candidate
42,38193,LiVO2,3,0.000000,38193,0.0,True,S-type,New preliminary AM ground candidate
43,9540,NaMnO2,4,0.000000,9540,0.0,True,S-type,New preliminary AM ground candidate
44,36830,Ni3(AsO4)2,2,0.000000,36830,0.0,True,S/A-type,New preliminary AM ground candidate
45,12578,SrLaCoO4,2,0.000000,12578,0.0,True,S/A-type,New preliminary AM ground candidate
46,53979,VCr(P2O7)2,3,0.000000,53979,0.0,True,S/A-type,New preliminary AM ground candidate
47,29916,Zn(FeO2)2,3,0.000000,29916,0.0,True,S-type,New preliminary AM ground candidate
48,33877,CoH5CN(ClO)2,1,0.000264,34225,0.0,False,S-type,Other preliminary candidate
49,53056,LaMgFeAgO6,2,0.000237,53853,0.0,False,S/A-type,Other preliminary candidate
50,41465,Li2Fe2P2O9F,2,0.000658,40398,0.0,False,S/A-type,Other preliminary candidate
51,38368,Li2SiNiO4,5,0.001030,42065,0.0,False,S/A-type,Other preliminary candidate
52,37955,Li4Ni3TeO8,1,0.000790,41904,0.0,False,S-type,Other preliminary candidate
53,52258,Li5Co3(SbO5)2,2,0.001428,52083,0.0,False,S/A-type,Other preliminary candidate
54,14352,LiMn3O4,4,0.002791,14150,0.0,False,S-type,Other preliminary candidate
55,52096,Mn3TeO6,1,0.000159,52889,0.0,False,S-type,Other preliminary candidate
56,51836,SrCo(GeO3)2,5,0.000401,51857,0.0,False,S/A-type,Other preliminary candidate
57,45855,V2CoO6,5,0.000323,45774,0.0,False,S/A-type,Other preliminary candidate

Diagnosing 13-state discrepancy

In [ ]:
# ============================================================
# CHECK: KNOWN AM STATES THAT ARE IN TOP-5
#       BUT WERE NOT SELECTED AS THE LOWEST DFT STATE
# ============================================================

known_am_ids = set(
    master_am["task_id"].astype(int)
)

# All known AM states appearing anywhere in Top-5
known_am_in_top5 = (
    top5_candidates[
        top5_candidates["task_id"].astype(int).isin(known_am_ids)
    ]
    .copy()
)

print(
    "Known AM states appearing in Top-5:",
    len(known_am_in_top5)
)

# Which of those survived as the selected DFT state?
selected_ids = set(
    top5_dft_selected["task_id"].astype(int)
)

known_am_in_top5["selected_as_parent_state"] = (
    known_am_in_top5["task_id"].astype(int).isin(selected_ids)
)

problem_cases = known_am_in_top5[
    ~known_am_in_top5["selected_as_parent_state"]
].copy()

print(
    "Known AM states in Top-5 but NOT selected:",
    len(problem_cases)
)

Known AM states appearing in Top-5: 40
Known AM states in Top-5 but NOT selected: 0

In [ ]:
# ============================================================
# INSPECT THE DISCREPANCY
# ============================================================

problem_ids = problem_cases["task_id"].astype(int).tolist()

for task_id in problem_ids:

    am_row = top5_candidates[
        top5_candidates["task_id"].astype(int) == task_id
    ].iloc[0]

    parent = am_row["parent_structure_id"]

    group = (
        top5_full[
            top5_full["parent_structure_id"] == parent
        ]
        .sort_values("dft_energy_per_atom")
        .copy()
    )

    print("\n" + "="*80)
    print(
        "Known AM:",
        task_id,
        am_row["formula"]
    )

    print(
        group[
            [
                "task_id",
                "ML_rank",
                "delta_E",
                "dft_energy_per_atom",
                "dft_ordering"
            ]
        ].to_string(index=False)
    )

In [ ]:
# ============================================================
# COMPARE THE 40 KNOWN AM STATES WITH CURRENT SYMMETRY TEST
# ============================================================

known_am_ids = set(
    master_am["task_id"].astype(int)
)

# Known AM states that are among the DFT-selected Top-5 states
selected_known_am = top5_final[
    top5_final["task_id"].astype(int).isin(known_am_ids)
].copy()

print("Known AM states selected from Top-5:",
      len(selected_known_am))

# Add the original classification from master_am
original_am_info = master_am[
    ["task_id",
     "AM_type_preliminary",
     "P_preserved",
     "T_preserved",
     "PT_preserved"]
].copy()

original_am_info["task_id"] = (
    original_am_info["task_id"].astype(int)
)

comparison = selected_known_am.merge(
    original_am_info,
    on="task_id",
    how="left",
    suffixes=("_current", "_original")
)

print("\nCurrent vs original symmetry classification:")
display(
    comparison[
        [
            "task_id",
            "formula",
            "P_preserved_current",
            "T_preserved_current",
            "PT_preserved_current",
            "P_preserved_original",
            "T_preserved_original",
            "PT_preserved_original",
            "AM_type_preliminary",
            "AM_type",
        ]
    ].sort_values("task_id")
)

Known AM states selected from Top-5: 40

Current vs original symmetry classification:

,task_id,formula,P_preserved_current,T_preserved_current,PT_preserved_current,P_preserved_original,T_preserved_original,PT_preserved_original,AM_type_preliminary,AM_type
3,477,MnO2,True,False,False,True,False,False,S-type,S-type
30,1791,K3NiO2,False,False,False,False,False,False,S/A-type,S/A-type
19,1908,Sr2CoTeO6,True,False,False,True,False,False,S-type,S-type
17,2136,Sr2MnWO6,True,False,False,True,False,False,S-type,S-type
25,2552,CoO,False,True,False,False,False,False,S/A-type,Not AM
29,2797,MgMn2O4,True,False,False,True,False,False,S-type,S-type
20,2950,SrFe2S2O,False,False,False,False,False,False,S/A-type,S/A-type
12,4189,Ca2MnO4,True,False,False,True,False,False,S-type,S-type
28,4286,Zn(FeO2)2,True,False,False,True,False,False,S-type,S-type
31,4981,LaCrO3,True,False,False,True,False,False,S-type,S-type
18,5140,NiSeO3,True,False,False,True,False,False,S-type,S-type
4,7162,Co(ClO4)2,True,False,False,True,False,False,S-type,S-type
10,8096,Mn2CdO4,True,False,False,True,False,False,S-type,S-type
2,8924,LiFeOF,False,True,False,False,False,False,S/A-type,Not AM
26,10560,CaV2O5,True,False,False,True,False,False,S-type,S-type
14,10652,NbVO4,False,False,False,False,False,False,S/A-type,S/A-type
39,14450,NaNiO2,True,True,False,True,False,False,S-type,Not AM
21,14465,LiCoAsO4,True,False,False,True,False,False,S-type,S-type
36,17885,BaLaTiFeO6,False,True,False,False,False,False,S/A-type,Not AM
38,25497,CoTeO4,False,True,False,False,False,False,S/A-type,Not AM
35,26498,NaCoBO3,False,True,False,False,False,False,S/A-type,Not AM
34,27974,Ba2CoSi2O7,False,False,False,False,False,False,S/A-type,S/A-type
11,28203,CsCr(SO4)2,False,True,False,False,False,False,S/A-type,Not AM
0,28294,Li2Fe(WO4)2,True,False,False,True,False,False,S-type,S-type
8,30169,LiTiNiO4,True,False,False,True,False,False,S-type,S-type
5,30688,LiCo2OF3,False,False,False,False,False,False,S/A-type,S/A-type
27,30779,LiMnSnO4,True,False,False,True,False,False,S-type,S-type
15,38352,Li2NiBO4,False,True,False,False,False,False,S/A-type,Not AM
24,40214,Li4CrGa3O8,False,True,False,False,False,False,S/A-type,Not AM
22,40225,BaCo2(PO4)2,True,False,False,True,False,False,S-type,S-type
32,40753,Li2MnGeO4,False,True,False,False,False,False,S/A-type,Not AM
33,41088,MgMnO2,True,False,False,True,False,False,S-type,S-type
6,43985,Li4FeO3F,False,True,False,False,False,False,S/A-type,Not AM
1,45309,NaCo2H3(SO5)2,False,False,False,False,False,False,S/A-type,S/A-type
23,46201,NaCo2H3(SeO5)2,False,True,False,False,False,False,S/A-type,Not AM
16,49391,Li2TiFe2O5,False,False,False,False,False,False,S/A-type,S/A-type
7,49603,Li3Ni(SbO3)4,False,True,False,False,False,False,S/A-type,Not AM
13,49844,SrLaTiMnO6,False,False,False,False,False,False,S/A-type,S/A-type
37,52663,Li4VCr(TeO6)2,False,False,False,False,False,False,S/A-type,S/A-type
9,55367,Mn3(P2O7)2,False,False,False,False,False,False,S/A-type,S/A-type

In [ ]:
# ============================================================
# FIND SYMMETRY DISAGREEMENTS
# ============================================================

comparison["P_match"] = (
    comparison["P_preserved_current"]
    == comparison["P_preserved_original"]
)

comparison["T_match"] = (
    comparison["T_preserved_current"]
    == comparison["T_preserved_original"]
)

comparison["PT_match"] = (
    comparison["PT_preserved_current"]
    == comparison["PT_preserved_original"]
)

print("P disagreements:",
      (~comparison["P_match"]).sum())

print("T disagreements:",
      (~comparison["T_match"]).sum())

print("PT disagreements:",
      (~comparison["PT_match"]).sum())

print("\nRows with ANY disagreement:")

display(
    comparison[
        ~(comparison["P_match"]
          & comparison["T_match"]
          & comparison["PT_match"])
    ][
        [
            "task_id",
            "formula",
            "P_preserved_current",
            "T_preserved_current",
            "PT_preserved_current",
            "P_preserved_original",
            "T_preserved_original",
            "PT_preserved_original",
        ]
    ]
)

P disagreements: 0
T disagreements: 13
PT disagreements: 0

Rows with ANY disagreement:

,task_id,formula,P_preserved_current,T_preserved_current,PT_preserved_current,P_preserved_original,T_preserved_original,PT_preserved_original
2,8924,LiFeOF,False,True,False,False,False,False
6,43985,Li4FeO3F,False,True,False,False,False,False
7,49603,Li3Ni(SbO3)4,False,True,False,False,False,False
11,28203,CsCr(SO4)2,False,True,False,False,False,False
15,38352,Li2NiBO4,False,True,False,False,False,False
23,46201,NaCo2H3(SeO5)2,False,True,False,False,False,False
24,40214,Li4CrGa3O8,False,True,False,False,False,False
25,2552,CoO,False,True,False,False,False,False
32,40753,Li2MnGeO4,False,True,False,False,False,False
35,26498,NaCoBO3,False,True,False,False,False,False
36,17885,BaLaTiFeO6,False,True,False,False,False,False
38,25497,CoTeO4,False,True,False,False,False,False
39,14450,NaNiO2,True,True,False,True,False,False

In [ ]:
# ============================================================
# THE 13 KNOWN AM STATES NOT CURRENTLY CLASSIFIED AS AM
# ============================================================

rejected_known_am = comparison[
    ~(
        (comparison["T_preserved_current"] == False)
        &
        (comparison["PT_preserved_current"] == False)
    )
].copy()

print(
    "Known AM states rejected by current P/T/PT test:",
    len(rejected_known_am)
)

display(
    rejected_known_am[
        [
            "task_id",
            "formula",
            "ML_rank",
            "total_magnetization",
            "P_preserved_current",
            "T_preserved_current",
            "PT_preserved_current",
            "P_preserved_original",
            "T_preserved_original",
            "PT_preserved_original",
        ]
    ]
)

Known AM states rejected by current P/T/PT test: 13

,task_id,formula,ML_rank,total_magnetization,P_preserved_current,T_preserved_current,PT_preserved_current,P_preserved_original,T_preserved_original,PT_preserved_original
2,8924,LiFeOF,5,1.600000e-06,False,True,False,False,False,False
6,43985,Li4FeO3F,3,0.000000e+00,False,True,False,False,False,False
7,49603,Li3Ni(SbO3)4,5,0.000000e+00,False,True,False,False,False,False
11,28203,CsCr(SO4)2,3,0.000000e+00,False,True,False,False,False,False
15,38352,Li2NiBO4,2,6.600000e-06,False,True,False,False,False,False
23,46201,NaCo2H3(SeO5)2,4,0.000000e+00,False,True,False,False,False,False
24,40214,Li4CrGa3O8,2,3.970000e-05,False,True,False,False,False,False
25,2552,CoO,3,5.000000e-07,False,True,False,False,False,False
32,40753,Li2MnGeO4,4,1.500000e-06,False,True,False,False,False,False
35,26498,NaCoBO3,4,1.500000e-06,False,True,False,False,False,False
36,17885,BaLaTiFeO6,4,0.000000e+00,False,True,False,False,False,False
38,25497,CoTeO4,2,5.000000e-07,False,True,False,False,False,False
39,14450,NaNiO2,1,1.480000e-05,True,True,False,True,False,False

In [ ]:
# ============================================================
# INSPECT THE ORIGINAL VALIDATED SYMMETRY FUNCTIONS
# ============================================================

import inspect

for name in [
    "check_PT_symmetry",
    "get_PTR_symmetry",
    "magnetic_operation_preserves",
    "screen_altermagnet_corrected",
]:

    if name in globals():
        print("\n" + "="*80)
        print(name)
        print("="*80)

        try:
            print(inspect.signature(globals()[name]))
            print()
            print(inspect.getsource(globals()[name]))
        except Exception as e:
            print("Could not inspect:", e)

================================================================================
check_PT_symmetry
================================================================================
(structure, magmoms, op, coord_tol=0.01, mag_tol=0.05)

def check_PT_symmetry(
    structure,
    magmoms,
    op,
    coord_tol=0.01,
    mag_tol=0.05,
):
    """
    Test whether inversion + time reversal preserves
    the collinear magnetic structure.

    For PT:
        position -> inversion(position)
        moment  -> -moment
    """

    for i, site in enumerate(structure):

        transformed = (
            op.operate(site.frac_coords) % 1.0
        )

        best_j = None
        best_dist = np.inf

        for j, target in enumerate(structure):

            diff = (
                transformed
                - target.frac_coords
            )

            # minimum-image fractional distance
            diff -= np.round(diff)

            dist = np.linalg.norm(diff)

            if dist < best_dist:
                best_dist = dist
                best_j = j

        if best_dist > coord_tol:
            return False

        # Under PT the magnetic moment changes sign
        if abs(
            magmoms[best_j] + magmoms[i]
        ) > mag_tol:
            return False

    return True


================================================================================
get_PTR_symmetry
================================================================================
(record, symprec=0.01)

def get_PTR_symmetry(record, symprec=0.01):

    structure = Structure.from_dict(
        record["structure"]
    )

    magmoms = np.asarray(
        record["magmoms"]["vasp"],
        dtype=float
    )

    sga = SpacegroupAnalyzer(
        structure,
        symprec=symprec,
        angle_tolerance=5,
    )

    ops = sga.get_symmetry_operations(
        cartesian=False
    )

    P_found = False
    PT_found = False
    T_found = False
    identity = None

    for op in ops:

        R = np.asarray(
            op.rotation_matrix,
            dtype=float
        )

        ordinary = magnetic_operation_preserves(
            structure,
            magmoms,
            op,
            time_reversal=+1,
        )

        with_T = magnetic_operation_preserves(
            structure,
            magmoms,
            op,
            time_reversal=-1,
        )

        if (
            np.allclose(R, np.eye(3), atol=1e-5)
            and np.allclose(
                op.translation_vector,
                [0, 0, 0],
                atol=1e-5,
            )
        ):
            identity = op

        if np.allclose(
            R,
            -np.eye(3),
            atol=1e-5
        ):
            if ordinary:
                P_found = True

            if with_T:
                PT_found = True

    if identity is not None:

        T_found = magnetic_operation_preserves(
            structure,
            magmoms,
            identity,
            time_reversal=-1,
        )

    return {
        "spacegroup": sga.get_space_group_symbol(),
        "P_preserved": P_found,
        "T_preserved": T_found,
        "PT_preserved": PT_found,
    }


================================================================================
magnetic_operation_preserves
================================================================================
(structure, magmoms, op, time_reversal=1, coord_tol=0.01, mag_tol=0.05)

def magnetic_operation_preserves(
    structure,
    magmoms,
    op,
    time_reversal=+1,
    coord_tol=0.01,
    mag_tol=0.05,
):
    for i, site in enumerate(structure):

        transformed = (
            op.operate(site.frac_coords) % 1.0
        )

        best_j = None
        best_dist = np.inf

        for j, target in enumerate(structure):

            diff = transformed - target.frac_coords
            diff -= np.round(diff)

            dist = np.linalg.norm(diff)

            if dist < best_dist:
                best_dist = dist
                best_j = j

        if best_dist > coord_tol:
            return False

        expected = time_reversal * magmoms[i]

        if abs(
            magmoms[best_j] - expected
        ) > mag_tol:
            return False

    return True


================================================================================
screen_altermagnet_corrected
================================================================================
(record, symprec=0.01, angle_tolerance=5, net_tol=0.0001, coord_tol=0.01, mag_tol=0.05)

def screen_altermagnet_corrected(
    record,
    symprec=1e-2,
    angle_tolerance=5,
    net_tol=1e-4,
    coord_tol=0.01,
    mag_tol=0.05,
):
    """
    Preliminary altermagnet screen.

    Criterion:
        1. Fully compensated magnetic ground state
        2. Broken PT symmetry

    If inversion P is absent, PT is automatically absent
    because PT requires P.
    """

    structure = Structure.from_dict(
        record["structure"]
    )

    magmoms = np.asarray(
        record["magmoms"]["vasp"],
        dtype=float
    )

    net_moment = abs(magmoms.sum())

    compensated = net_moment <= net_tol

    if not compensated:
        return {
            "task_id": str(record["task_id"]),
            "formula": record["formula_pretty"],
            "ordering": record["ordering"],
            "net_moment": net_moment,
            "compensated": False,
            "spacegroup": None,
            "inversion_found": False,
            "PT_preserved": None,
            "AM_candidate": False,
        }

    sga = SpacegroupAnalyzer(
        structure,
        symprec=symprec,
        angle_tolerance=angle_tolerance,
    )

    ops = sga.get_symmetry_operations(
        cartesian=False
    )

    inversion_found = False
    pt_preserved = False

    # Search for an inversion operation.
    for op in ops:

        R = np.asarray(
            op.rotation_matrix,
            dtype=float
        )

        if np.allclose(
            R,
            -np.eye(3),
            atol=1e-5
        ):

            inversion_found = True

            if check_PT_symmetry(
                structure,
                magmoms,
                op,
                coord_tol=coord_tol,
                mag_tol=mag_tol,
            ):
                pt_preserved = True

            break

    # If P does not exist, PT cannot exist.
    if not inversion_found:
        pt_preserved = False

    # Correct AM screening criterion
    am_candidate = (
        compensated
        and not pt_preserved
    )

    return {
        "task_id": str(record["task_id"]),
        "formula": record["formula_pretty"],
        "ordering": record["ordering"],
        "net_moment": net_moment,
        "compensated": compensated,
        "spacegroup": sga.get_space_group_symbol(),
        "inversion_found": inversion_found,
        "PT_preserved": pt_preserved,
        "AM_candidate": am_candidate,
    }

### Step - 9.9 - Redoing the 259-state screen

In [ ]:
# ============================================================
# FINAL CONSISTENT AM SCREEN
# Use the ORIGINAL validated criterion:
#
#   compensated AND PT broken
#
# No T-preserved filter.
# ============================================================

am_screen_results = []

for _, row in top5_dft_selected.iterrows():

    task_id = int(row["task_id"])

    # Get the original DFT record
    record = record_by_task[str(task_id)]

    try:
        result = screen_altermagnet_corrected(
            record,
            symprec=1e-2,
            angle_tolerance=5,
            net_tol=1e-4,
            coord_tol=0.01,
            mag_tol=0.05,
        )

    except Exception as e:

        result = {
            "task_id": str(task_id),
            "formula": row["formula"],
            "ordering": row["dft_ordering"],
            "net_moment": np.nan,
            "compensated": False,
            "spacegroup": None,
            "inversion_found": None,
            "PT_preserved": None,
            "AM_candidate": False,
            "error": str(e),
        }

    am_screen_results.append(result)


am_screen_df = pd.DataFrame(am_screen_results)

# Convert task_id back to integer for merging
am_screen_df["task_id"] = (
    am_screen_df["task_id"].astype(int)
)

# Merge onto our Top-5 selected states
top5_consistent = top5_dft_selected.merge(
    am_screen_df,
    on="task_id",
    how="left",
    suffixes=("", "_screen")
)

print("================================================")
print("CONSISTENT TOP-5 AM SCREEN")
print("================================================")

print(
    "Parent materials:",
    len(top5_consistent)
)

print(
    "AM candidates:",
    top5_consistent["AM_candidate"].sum()
)

print(
    "Non-AM:",
    (~top5_consistent["AM_candidate"]).sum()
)

================================================
CONSISTENT TOP-5 AM SCREEN
================================================
Parent materials: 259
AM candidates: 70
Non-AM: 189

Checking the known-AM recovery

In [ ]:
# ============================================================
# CHECK RECOVERY OF THE ORIGINAL 55 AM GROUND STATES
# ============================================================

known_am_ids = set(
    master_am["task_id"].astype(int)
)

top5_consistent["known_AM_ground"] = (
    top5_consistent["task_id"].astype(int)
    .isin(known_am_ids)
)

recovered_known_am = top5_consistent[
    top5_consistent["known_AM_ground"]
    & top5_consistent["AM_candidate"]
]

print(
    "Known AM ground states recovered:",
    len(recovered_known_am)
)

print(
    "Expected from Top-5 benchmark:",
    40
)

Known AM ground states recovered: 40
Expected from Top-5 benchmark: 40

Classifying S vs S/A using P

In [ ]:
# ============================================================
# PRELIMINARY AM SUBTYPE
# ============================================================

top5_consistent["P_preserved"] = (
    top5_consistent["inversion_found"]
)

top5_consistent["AM_type"] = np.select(
    [
        top5_consistent["AM_candidate"]
        & top5_consistent["P_preserved"],

        top5_consistent["AM_candidate"]
        & (~top5_consistent["P_preserved"]),
    ],
    [
        "S-type",
        "S/A-type",
    ],
    default="Not AM"
)

am_candidates_consistent = (
    top5_consistent[
        top5_consistent["AM_candidate"]
    ]
    .sort_values(
        ["AM_type", "ML_rank"]
    )
    .reset_index(drop=True)
)

print(
    "Total preliminary AM candidates:",
    len(am_candidates_consistent)
)

print("\nAM subtype:")
print(
    am_candidates_consistent["AM_type"]
    .value_counts()
)

Total preliminary AM candidates: 70

AM subtype:
AM_type
S-type      35
S/A-type    35
Name: count, dtype: int64

Finally separating known vs genuinely new

In [ ]:
# ============================================================
# KNOWN vs NEW PRELIMINARY AM GROUND CANDIDATES
# ============================================================

am_candidates_consistent["known_AM_ground"] = (
    am_candidates_consistent["task_id"].astype(int)
    .isin(known_am_ids)
)

known_recovered = am_candidates_consistent[
    am_candidates_consistent["known_AM_ground"]
]

new_preliminary = am_candidates_consistent[
    ~am_candidates_consistent["known_AM_ground"]
]

print(
    "Known AM ground states recovered:",
    len(known_recovered)
)

print(
    "Preliminary AM ground candidates not in original 55:",
    len(new_preliminary)
)

print("\nNEW PRELIMINARY CANDIDATES:")
display(
    new_preliminary[
        [
            "task_id",
            "formula",
            "ML_rank",
            "dft_ordering",
            "net_moment",
            "spacegroup",
            "P_preserved",
            "PT_preserved",
            "AM_type",
        ]
    ]
)

Known AM ground states recovered: 40
Preliminary AM ground candidates not in original 55: 30

NEW PRELIMINARY CANDIDATES:

,task_id,formula,ML_rank,dft_ordering,net_moment,spacegroup,P_preserved,PT_preserved,AM_type
0,33877,CoH5CN(ClO)2,1,AFM,0.000000e+00,C2/c,True,False,S-type
1,7605,Ba3Mn2O8,1,AFM,0.000000e+00,R-3m,True,False,S-type
2,52096,Mn3TeO6,1,AFM,0.000000e+00,P2_1/c,True,False,S-type
4,14652,Ca3MnO4,1,AFM,0.000000e+00,C2/m,True,False,S-type
13,39392,SrZnNi(PO4)2,1,AFM,0.000000e+00,P-1,True,False,S-type
14,5585,Ba2FeWO6,2,AFM,0.000000e+00,I4/mmm,True,False,S-type
15,6112,Ni2P2O7,2,AFM,0.000000e+00,C2/m,True,False,S-type
16,33213,LiNiAsO4,2,AFM,0.000000e+00,Imma,True,False,S-type
18,31341,VZn2O4,2,AFM,0.000000e+00,Imma,True,False,S-type
19,47297,Li4Ti2Mn3O10,2,AFM,8.881784e-16,P-1,True,False,S-type
20,4924,FeCuO2,2,AFM,0.000000e+00,R-3m,True,False,S-type
22,40222,Li2VOF4,2,AFM,0.000000e+00,C2/c,True,False,S-type
24,53935,SrMn(GeO3)2,3,AFM,0.000000e+00,P-1,True,False,S-type
27,56534,Na6FeO4,3,FiM,0.000000e+00,P4_2/nmc,True,False,S-type
28,5659,Sr2NiTeO6,3,AFM,0.000000e+00,C2/m,True,False,S-type
29,11073,Ca2MnO3,3,AFM,0.000000e+00,I4/mmm,True,False,S-type
33,38658,Li3VP2HO8,4,AFM,0.000000e+00,P-1,True,False,S-type
38,12320,V2HO4,1,AFM,0.000000e+00,Pm,False,False,S/A-type
44,18076,BaLaMnSbO6,2,AFM,0.000000e+00,I-4,False,False,S/A-type
50,10424,Cs2LiMnO4,3,AFM,0.000000e+00,Cmc2_1,False,False,S/A-type
51,44933,Ta2MnO6,3,AFM,0.000000e+00,P4_2/mnm,False,False,S/A-type
52,32678,LiCrSnO4,4,AFM,0.000000e+00,Imma,False,False,S/A-type
54,11804,LiVSiO4,4,FiM,0.000000e+00,I-4,False,False,S/A-type
55,20037,Ca2MnWO6,4,AFM,0.000000e+00,P1,False,False,S/A-type
61,13251,Co(IO3)2,4,AFM,0.000000e+00,P2_1,False,False,S/A-type
62,53621,LiVSiO4,5,FiM,0.000000e+00,P6_422,False,False,S/A-type
66,13679,Mn(IO3)2,5,AFM,0.000000e+00,P2_1,False,False,S/A-type
67,17963,BaSrNiWO6,5,AFM,0.000000e+00,F-43m,False,False,S/A-type
68,34911,Li3SiNi3O8,5,FiM,0.000000e+00,P2/m,False,False,S/A-type
69,37634,Li4Y3FeO8,5,AFM,0.000000e+00,C222,False,False,S/A-type

The current screen only establishes:

$$ M_{\rm total}\approx0 $$

and

$$ PT\text{ broken}. $$

That is a preliminary screening criterion. It does not yet establish the required spin-space symmetry responsible for altermagnetic spin splitting.

So freezing these 30 as your:

ML-guided preliminary AM ground-state candidate set

and move to the final symmetry stage.

**Now,**

For each of these 30 candidates we should determine the magnetic spin-space symmetry, rather than relying only on ordinary spatial \(P/T/PT\) symmetry.

We should also retain the 40 recovered known AM states as a validation set. A good final check will be:

$$ \text{55 known AM} \rightarrow \text{40 captured by Top-5} \rightarrow \text{spin-space validation}. $$

That lets us measure whether the final symmetry classifier correctly recognizes the known AM states before trusting the 30 new candidates.

Next task is:

$$\text{70 preliminary candidates → spin-space symmetry → confirmed AM / rejected}$$

## Phase - 10 - Spin-space symmetry operations

Using 'spinspg' specifically designed to find spin-space symmetry operations from a magnetic spin arrangement.

### Step - 10.1 - Installing spinspg

In [ ]:
!pip install -q spinspg

In [ ]:
import spinspg
from spinspg import get_spin_symmetry

print("spinspg version:", getattr(spinspg, "__version__", "unknown"))

spinspg version: 0.3.2

### Step - 10.2 - Testing it on our known AM: Li₂Fe(WO₄)₂

In [ ]:
# ============================================================
# TEST SPIN-SPACE SYMMETRY ON KNOWN AM
# Li2Fe(WO4)2, task 28294
# ============================================================

from pymatgen.core import Structure
import numpy as np

rec = record_by_task["28294"]

structure = Structure.from_dict(rec["structure"])

# spinspg expects magnetic moments as Cartesian vectors.
# Our DFT moments are collinear scalar moments along one common axis,
# so represent them along +z / -z.
scalar_magmoms = np.asarray(
    rec["magmoms"]["vasp"],
    dtype=float
)

magmoms_3d = np.zeros((len(scalar_magmoms), 3))
magmoms_3d[:, 2] = scalar_magmoms

lattice = np.asarray(
    structure.lattice.matrix,
    dtype=float
)

positions = np.asarray(
    structure.frac_coords,
    dtype=float
)

numbers = np.asarray(
    structure.atomic_numbers,
    dtype=int
)

sog, rotations, translations, spin_rotations = get_spin_symmetry(
    lattice,
    positions,
    numbers,
    magmoms_3d
)

print("Spin-only group:")
print(sog)

print("\nNumber of spin-space operations:")
print(len(rotations))

print("\nShapes:")
print("rotations:", np.asarray(rotations).shape)
print("translations:", np.asarray(translations).shape)
print("spin_rotations:", np.asarray(spin_rotations).shape)

Spin-only group:
COLLINEAR(axis=[0. 0. 1.])

Number of spin-space operations:
1

Shapes:
rotations: (1, 3, 3)
translations: (1, 3)
spin_rotations: (1, 3, 3)

### Step - 10.3 - Inspecting the spin rotations

In [ ]:
# ============================================================
# INSPECT SPIN ROTATIONS
# ============================================================

for i, (R, t, W) in enumerate(
    zip(rotations, translations, spin_rotations)
):
    print("\nOperation", i)
    print("Spatial rotation R:")
    print(np.asarray(R))

    print("Translation:")
    print(np.asarray(t))

    print("Spin rotation W:")
    print(np.asarray(W))

Operation 0
Spatial rotation R:
[[1 0 0]
 [0 1 0]
 [0 0 1]]
Translation:
[0. 0. 0.]
Spin rotation W:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Diagnose the known AM systematically

In [ ]:
# ============================================================
# DIAGNOSTIC: Li2Fe(WO4)2
# ============================================================

import spglib
import numpy as np
from pymatgen.core import Structure
from pymatgen.symmetry.analyzer import SpacegroupAnalyzer

rec = record_by_task["28294"]

structure = Structure.from_dict(rec["structure"])
magmoms = np.asarray(rec["magmoms"]["vasp"], dtype=float)

print("Pymatgen structure:")
sga = SpacegroupAnalyzer(
    structure,
    symprec=1e-2,
    angle_tolerance=5,
)

print("Space group:", sga.get_space_group_symbol())
print("Number of operations:", len(
    sga.get_symmetry_operations(cartesian=False)
))

print("\nFinal magnetic moments:")
print(magmoms)

print("\nNet moment:")
print(abs(magmoms.sum()))

Pymatgen structure:
Space group: P-1
Number of operations: 2

Final magnetic moments:
[-0.000e+00  0.000e+00  0.000e+00 -0.000e+00 -3.766e+00  3.766e+00
 -2.000e-03 -2.000e-03  2.000e-03  2.000e-03 -1.000e-03  1.000e-03
  1.000e-03 -1.000e-03  1.100e-02 -1.100e-02 -1.100e-02  1.100e-02
  1.000e-02 -1.000e-02 -1.000e-02  1.000e-02 -6.000e-03  6.000e-03
  6.000e-03 -6.000e-03]

Net moment:
0.0

Checking the raw Spglib magnetic symmetry

In [ ]:
# ============================================================
# RAW SPGLIB MAGNETIC SYMMETRY
# ============================================================

lattice = np.asarray(structure.lattice.matrix, dtype=float)
positions = np.asarray(structure.frac_coords, dtype=float)
numbers = np.asarray(structure.atomic_numbers, dtype=int)

cell = (
    lattice,
    positions,
    numbers,
    magmoms,
)

for mag_symprec in [1e-2, 5e-2, 1e-1]:

    msym = spglib.get_magnetic_symmetry(
        cell,
        symprec=1e-2,
        mag_symprec=mag_symprec,
    )

    print("\nmag_symprec =", mag_symprec)

    if msym is None:
        print("None")
        continue

    print("Operations:", len(msym["rotations"]))
    print(
        "Time-reversal operations:",
        int(np.asarray(msym["time_reversals"]).sum())
    )

mag_symprec = 0.01
Operations: 2
Time-reversal operations: 0

mag_symprec = 0.05
Operations: 2
Time-reversal operations: 0

mag_symprec = 0.1
Operations: 2
Time-reversal operations: 0

In [ ]:
# ============================================================
# DIRECT SPIN-SPACE INVERSION TEST
# Li2Fe(WO4)2, task 28294
# ============================================================

from pymatgen.core import Structure
from pymatgen.symmetry.analyzer import SpacegroupAnalyzer
import numpy as np

rec = record_by_task["28294"]

structure = Structure.from_dict(rec["structure"])
m = np.asarray(rec["magmoms"]["vasp"], dtype=float)

sga = SpacegroupAnalyzer(
    structure,
    symprec=1e-2,
    angle_tolerance=5
)

ops = sga.get_symmetry_operations(cartesian=False)

inv_ops = []

for op in ops:
    R = np.asarray(op.rotation_matrix, dtype=float)

    if np.allclose(
        R,
        -np.eye(3),
        atol=1e-5
    ):
        inv_ops.append(op)

print("Number of inversion operations:", len(inv_ops))

for op in inv_ops:

    print("\nInversion rotation:")
    print(op.rotation_matrix)

    print("Translation:")
    print(op.translation_vector)

    max_no_flip = 0.0
    max_flip = 0.0

    failed_no_flip = 0
    failed_flip = 0

    for i, site in enumerate(structure):

        transformed = (
            op.operate(site.frac_coords) % 1.0
        )

        distances = []

        for j, target in enumerate(structure):

            diff = (
                transformed
                - target.frac_coords
            )

            diff -= np.round(diff)

            distances.append(
                np.linalg.norm(diff)
            )

        best_j = int(np.argmin(distances))
        best_dist = distances[best_j]

        if best_dist > 0.01:
            continue

        # Ordinary inversion: m -> m
        err_no_flip = abs(
            m[best_j] - m[i]
        )

        # Inversion + spin reversal:
        # m -> -m
        err_flip = abs(
            m[best_j] + m[i]
        )

        max_no_flip = max(
            max_no_flip,
            err_no_flip
        )

        max_flip = max(
            max_flip,
            err_flip
        )

        if err_no_flip > 0.05:
            failed_no_flip += 1

        if err_flip > 0.05:
            failed_flip += 1

    print("\nMaximum moment mismatch:")
    print("P  (no spin flip):", max_no_flip)
    print("PT (spin flip):   ", max_flip)

    print("\nNumber of mismatches > 0.05 μB:")
    print("P :", failed_no_flip)
    print("PT:", failed_flip)

Number of inversion operations: 1

Inversion rotation:
[[-1.  0.  0.]
 [ 0. -1.  0.]
 [ 0.  0. -1.]]
Translation:
[0.5 0.5 0.5]

Maximum moment mismatch:
P  (no spin flip): 0.0
PT (spin flip):    7.532

Number of mismatches > 0.05 μB:
P : 0
PT: 2

Saving 30 candidates

In [ ]:
# ============================================================
# SAVE THE 30 NEW PRELIMINARY AM CANDIDATES
# ============================================================

new_preliminary = am_candidates_consistent[
    ~am_candidates_consistent["task_id"].astype(int).isin(
        known_am_ids
    )
].copy()

new_preliminary = new_preliminary.sort_values(
    ["AM_type", "formula"]
).reset_index(drop=True)

print("New preliminary AM candidates:", len(new_preliminary))

display(
    new_preliminary[
        [
            "task_id",
            "formula",
            "ML_rank",
            "dft_ordering",
            "net_moment",
            "spacegroup",
            "P_preserved",
            "PT_preserved",
            "AM_type",
        ]
    ]
)

New preliminary AM candidates: 30

,task_id,formula,ML_rank,dft_ordering,net_moment,spacegroup,P_preserved,PT_preserved,AM_type
0,5585,Ba2FeWO6,2,AFM,0.000000e+00,I4/mmm,True,False,S-type
1,7605,Ba3Mn2O8,1,AFM,0.000000e+00,R-3m,True,False,S-type
2,11073,Ca2MnO3,3,AFM,0.000000e+00,I4/mmm,True,False,S-type
3,14652,Ca3MnO4,1,AFM,0.000000e+00,C2/m,True,False,S-type
4,33877,CoH5CN(ClO)2,1,AFM,0.000000e+00,C2/c,True,False,S-type
5,4924,FeCuO2,2,AFM,0.000000e+00,R-3m,True,False,S-type
6,40222,Li2VOF4,2,AFM,0.000000e+00,C2/c,True,False,S-type
7,38658,Li3VP2HO8,4,AFM,0.000000e+00,P-1,True,False,S-type
8,47297,Li4Ti2Mn3O10,2,AFM,8.881784e-16,P-1,True,False,S-type
9,33213,LiNiAsO4,2,AFM,0.000000e+00,Imma,True,False,S-type
10,52096,Mn3TeO6,1,AFM,0.000000e+00,P2_1/c,True,False,S-type
11,56534,Na6FeO4,3,FiM,0.000000e+00,P4_2/nmc,True,False,S-type
12,6112,Ni2P2O7,2,AFM,0.000000e+00,C2/m,True,False,S-type
13,5659,Sr2NiTeO6,3,AFM,0.000000e+00,C2/m,True,False,S-type
14,53935,SrMn(GeO3)2,3,AFM,0.000000e+00,P-1,True,False,S-type
15,39392,SrZnNi(PO4)2,1,AFM,0.000000e+00,P-1,True,False,S-type
16,31341,VZn2O4,2,AFM,0.000000e+00,Imma,True,False,S-type
17,18076,BaLaMnSbO6,2,AFM,0.000000e+00,I-4,False,False,S/A-type
18,17963,BaSrNiWO6,5,AFM,0.000000e+00,F-43m,False,False,S/A-type
19,20037,Ca2MnWO6,4,AFM,0.000000e+00,P1,False,False,S/A-type
20,13251,Co(IO3)2,4,AFM,0.000000e+00,P2_1,False,False,S/A-type
21,10424,Cs2LiMnO4,3,AFM,0.000000e+00,Cmc2_1,False,False,S/A-type
22,34911,Li3SiNi3O8,5,FiM,0.000000e+00,P2/m,False,False,S/A-type
23,37634,Li4Y3FeO8,5,AFM,0.000000e+00,C222,False,False,S/A-type
24,32678,LiCrSnO4,4,AFM,0.000000e+00,Imma,False,False,S/A-type
25,11804,LiVSiO4,4,FiM,0.000000e+00,I-4,False,False,S/A-type
26,53621,LiVSiO4,5,FiM,0.000000e+00,P6_422,False,False,S/A-type
27,13679,Mn(IO3)2,5,AFM,0.000000e+00,P2_1,False,False,S/A-type
28,44933,Ta2MnO6,3,AFM,0.000000e+00,P4_2/mnm,False,False,S/A-type
29,12320,V2HO4,1,AFM,0.000000e+00,Pm,False,False,S/A-type

In [ ]:
new_preliminary_path = (
    "/content/drive/MyDrive/Proj_2_Alt_Mags_Grnd_E/"
    "magnetic-topological-materials/"
    "AM_new_preliminary_Top5_candidates.csv"
)

new_preliminary.to_csv(
    new_preliminary_path,
    index=False
)

print("Saved:", new_preliminary_path)

Saved: /content/drive/MyDrive/Proj_2_Alt_Mags_Grnd_E/magnetic-topological-materials/AM_new_preliminary_Top5_candidates.csv

### Step - 10.4 - Classifying the known 40 first

This is the validation set.

In [ ]:
# ============================================================
# STEP 20: SPIN-SPACE ALTERMAGNET TEST
# ============================================================

import numpy as np
import pandas as pd
from pymatgen.core import Structure
from spinspg import get_spin_symmetry


SPIN_TOL = 0.05


def spin_space_am_test(
    record,
    symprec=1e-2,
    mag_symprec=5e-2,
    spin_tol=0.05,
):
    """
    Preliminary spin-space test for collinear altermagnetism.

    We look for a spin-space operation where:
        spatial operation maps one magnetic sublattice
        to the opposite-spin sublattice,

    i.e. the spin rotation sends the collinear axis
    n -> -n.

    Pure translation (R = I) and pure inversion (R = -I)
    are excluded from the AM-generating operation.
    """

    structure = Structure.from_dict(record["structure"])

    raw_m = np.asarray(
        record["magmoms"]["vasp"],
        dtype=float
    )

    # Remove tiny induced moments so that weak polarization
    # on ligand / nonmagnetic atoms does not artificially
    # destroy the collinear symmetry.
    m = raw_m.copy()
    m[np.abs(m) < spin_tol] = 0.0

    # Collinear moments along a common axis.
    magmoms_3d = np.zeros((len(m), 3))
    magmoms_3d[:, 2] = m

    lattice = np.asarray(
        structure.lattice.matrix,
        dtype=float
    )

    positions = np.asarray(
        structure.frac_coords,
        dtype=float
    )

    numbers = np.asarray(
        structure.atomic_numbers,
        dtype=int
    )

    sog, rotations, translations, spin_rotations = (
        get_spin_symmetry(
            lattice,
            positions,
            numbers,
            magmoms_3d,
            symprec=symprec,
            mag_symprec=mag_symprec,
            angle_tolerance=5,
        )
    )

    axis = np.array([0.0, 0.0, 1.0])

    spin_flip_ops = []

    for i, (R, t, W) in enumerate(
        zip(
            np.asarray(rotations),
            np.asarray(translations),
            np.asarray(spin_rotations),
        )
    ):

        R = np.asarray(R, dtype=float)
        t = np.asarray(t, dtype=float)
        W = np.asarray(W, dtype=float)

        # What does the spin rotation do to the collinear axis?
        transformed_axis = W @ axis

        flips_spin = np.allclose(
            transformed_axis,
            -axis,
            atol=1e-5
        )

        if not flips_spin:
            continue

        # Exclude pure translation
        pure_translation = np.allclose(
            R,
            np.eye(3),
            atol=1e-5
        )

        # Exclude pure inversion / inversion + translation
        pure_inversion = np.allclose(
            R,
            -np.eye(3),
            atol=1e-5
        )

        if pure_translation or pure_inversion:
            continue

        spin_flip_ops.append({
            "operation_index": i,
            "R": R,
            "translation": t,
            "W": W,
            "det_R": np.linalg.det(R),
        })

    return {
        "spin_group": str(sog),
        "n_spin_space_operations": len(rotations),
        "n_spin_flip_rotation_ops": len(spin_flip_ops),
        "spin_flip_ops": spin_flip_ops,
        "spin_space_AM_candidate": (
            len(spin_flip_ops) > 0
        ),
        "cleaned_magmoms": m,
    }

Testing it on Li₂Fe(WO₄)₂

In [ ]:
# ============================================================
# TEST: Li2Fe(WO4)2
# ============================================================

rec = record_by_task["28294"]

result_28294 = spin_space_am_test(rec)

print("Task:", 28294)
print("Formula:", rec["formula"])
print("Spin-only group:", result_28294["spin_group"])
print(
    "Total spin-space operations:",
    result_28294["n_spin_space_operations"]
)
print(
    "Spin-flip rotation/mirror operations:",
    result_28294["n_spin_flip_rotation_ops"]
)
print(
    "Preliminary spin-space AM:",
    result_28294["spin_space_AM_candidate"]
)

for op in result_28294["spin_flip_ops"]:
    print("\nOperation:", op["operation_index"])
    print("R =\n", op["R"])
    print("translation =", op["translation"])
    print("W =\n", op["W"])
    print("det(R) =", op["det_R"])

Task: 28294
Formula: Li2 Fe1 W2 O8
Spin-only group: COLLINEAR(axis=[0. 0. 1.])
Total spin-space operations: 2
Spin-flip rotation/mirror operations: 0
Preliminary spin-space AM: False

Validating against the 40 known recovered AM states

In [ ]:
# ============================================================
# STEP 21: VALIDATE ON THE 40 KNOWN AM STATES
# ============================================================

known_recovered_ids = (
    set(
        recovered_known_am["task_id"]
        .astype(int)
    )
)

known_validation = []

for task_id in sorted(known_recovered_ids):

    rec = record_by_task[str(task_id)]

    try:
        result = spin_space_am_test(rec)

        known_validation.append({
            "task_id": task_id,
            "formula": rec["formula"],
            "spin_group": result["spin_group"],
            "n_spin_ops": result["n_spin_space_operations"],
            "n_spin_flip_ops":
                result["n_spin_flip_rotation_ops"],
            "spin_space_AM":
                result["spin_space_AM_candidate"],
        })

    except Exception as e:

        known_validation.append({
            "task_id": task_id,
            "formula": rec["formula"],
            "spin_group": None,
            "n_spin_ops": np.nan,
            "n_spin_flip_ops": np.nan,
            "spin_space_AM": False,
            "error": str(e),
        })

known_spin_validation = pd.DataFrame(
    known_validation
)

print(
    "Known recovered AM states:",
    len(known_spin_validation)
)

print(
    "\nSpin-space candidates:",
    known_spin_validation["spin_space_AM"].sum()
)

print(
    "\nNon-candidates:",
    (~known_spin_validation["spin_space_AM"]).sum()
)

display(known_spin_validation)

Known recovered AM states: 40

Spin-space candidates: 30

Non-candidates: 10

,task_id,formula,spin_group,n_spin_ops,n_spin_flip_ops,spin_space_AM
0,477,Mn4 O8,COLLINEAR(axis=[0. 0. 1.]),8,4,True
1,1791,K12 Ni4 O8,COLLINEAR(axis=[0. 0. 1.]),2,0,False
2,1908,Sr4 Co2 Te2 O12,COLLINEAR(axis=[0. 0. 1.]),2,0,False
3,2136,Sr4 Mn2 W2 O12,COLLINEAR(axis=[0. 0. 1.]),4,2,True
4,2552,Co1 O1,COLLINEAR(axis=[0. 0. 1.]),16,7,True
5,2797,Mg2 Mn4 O8,COLLINEAR(axis=[0. 0. 1.]),8,4,True
6,2950,Sr2 Fe4 S4 O2,COLLINEAR(axis=[0. 0. 1.]),4,0,False
7,4189,Ca8 Mn4 O16,COLLINEAR(axis=[0. 0. 1.]),16,8,True
8,4286,Zn2 Fe4 O8,COLLINEAR(axis=[0. 0. 1.]),16,8,True
9,4981,La4 Cr4 O12,COLLINEAR(axis=[0. 0. 1.]),8,4,True
10,5140,Ni4 Se4 O12,COLLINEAR(axis=[0. 0. 1.]),8,4,True
11,7162,Co1 Cl2 O8,COLLINEAR(axis=[0. 0. 1.]),2,0,False
12,8096,Mn4 Cd2 O8,COLLINEAR(axis=[0. 0. 1.]),8,4,True
13,8924,Li1 Fe1 O1 F1,COLLINEAR(axis=[0. 0. 1.]),4,1,True
14,10560,Ca2 V4 O10,COLLINEAR(axis=[0. 0. 1.]),8,4,True
15,10652,Nb1 V1 O4,COLLINEAR(axis=[0. 0. 1.]),2,0,False
16,14450,Na2 Ni2 O4,COLLINEAR(axis=[0. 0. 1.]),4,1,True
17,14465,Li4 Co4 As4 O16,COLLINEAR(axis=[0. 0. 1.]),8,4,True
18,17885,Ba1 La1 Ti1 Fe1 O6,COLLINEAR(axis=[0. 0. 1.]),12,5,True
19,25497,Co2 Te2 O8,COLLINEAR(axis=[0. 0. 1.]),4,1,True
20,26498,Na2 Co2 B2 O6,COLLINEAR(axis=[0. 0. 1.]),4,1,True
21,27974,Ba4 Co2 Si4 O14,COLLINEAR(axis=[0. 0. 1.]),8,4,True
22,28203,Cs1 Cr1 S2 O8,COLLINEAR(axis=[0. 0. 1.]),12,5,True
23,28294,Li2 Fe1 W2 O8,COLLINEAR(axis=[0. 0. 1.]),2,0,False
24,30169,Li2 Ti2 Ni2 O8,COLLINEAR(axis=[0. 0. 1.]),4,2,True
25,30688,Li2 Co4 O2 F6,COLLINEAR(axis=[0. 0. 1.]),2,1,True
26,30779,Li2 Mn2 Sn2 O8,COLLINEAR(axis=[0. 0. 1.]),8,4,True
27,38352,Li4 Ni2 B2 O8,COLLINEAR(axis=[0. 0. 1.]),8,3,True
28,40214,Li4 Cr1 Ga3 O8,COLLINEAR(axis=[0. 0. 1.]),2,0,False
29,40225,Ba2 Co4 P4 O16,COLLINEAR(axis=[0. 0. 1.]),4,2,True
30,40753,Li4 Mn2 Ge2 O8,COLLINEAR(axis=[0. 0. 1.]),4,1,True
31,41088,Mg4 Mn4 O8,COLLINEAR(axis=[0. 0. 1.]),16,8,True
32,43985,Li8 Fe2 O6 F2,COLLINEAR(axis=[0. 0. 1.]),8,3,True
33,45309,Na1 Co2 H3 S2 O10,COLLINEAR(axis=[0. 0. 1.]),2,1,True
34,46201,Na1 Co2 H3 Se2 O10,COLLINEAR(axis=[0. 0. 1.]),4,1,True
35,49391,Li4 Ti2 Fe4 O10,COLLINEAR(axis=[0. 0. 1.]),2,1,True
36,49603,Li3 Ni1 Sb4 O12,COLLINEAR(axis=[0. 0. 1.]),2,0,False
37,49844,Sr2 La2 Ti2 Mn2 O12,COLLINEAR(axis=[0. 0. 1.]),2,1,True
38,52663,Li4 V1 Cr1 Te2 O12,COLLINEAR(axis=[0. 0. 1.]),2,0,False
39,55367,Mn3 P4 O14,COLLINEAR(axis=[0. 0. 1.]),1,0,False

### Step - 10.5 - Applying exactly the same test to the 30 new candidates

In [ ]:
# ============================================================
# STEP 22: SPIN-SPACE TEST ON THE 30 NEW CANDIDATES
# ============================================================

new_spin_results = []

for _, row in new_preliminary.iterrows():

    task_id = int(row["task_id"])

    rec = record_by_task[str(task_id)]

    try:

        result = spin_space_am_test(
            rec,
            symprec=1e-2,
            mag_symprec=5e-2,
            spin_tol=0.05,
        )

        new_spin_results.append({
            "task_id": task_id,
            "formula": row["formula"],
            "ML_rank": row["ML_rank"],
            "AM_type_preliminary": row["AM_type"],
            "dft_ordering": row["dft_ordering"],
            "spacegroup": row["spacegroup"],
            "n_spin_ops":
                result["n_spin_space_operations"],
            "n_spin_flip_ops":
                result["n_spin_flip_rotation_ops"],
            "spin_space_AM":
                result["spin_space_AM_candidate"],
        })

    except Exception as e:

        new_spin_results.append({
            "task_id": task_id,
            "formula": row["formula"],
            "ML_rank": row["ML_rank"],
            "AM_type_preliminary": row["AM_type"],
            "dft_ordering": row["dft_ordering"],
            "spacegroup": row["spacegroup"],
            "n_spin_ops": np.nan,
            "n_spin_flip_ops": np.nan,
            "spin_space_AM": False,
            "error": str(e),
        })


new_spin_df = pd.DataFrame(new_spin_results)

print("New preliminary candidates:", len(new_spin_df))

print(
    "\nSpin-space AM candidates:",
    new_spin_df["spin_space_AM"].sum()
)

print(
    "Rejected by spin-space test:",
    (~new_spin_df["spin_space_AM"]).sum()
)

New preliminary candidates: 30

Spin-space AM candidates: 22
Rejected by spin-space test: 8

Candidates that pass

In [ ]:
# ============================================================
# STEP 23: STRONGER AM CANDIDATES
# ============================================================

stronger_AM_candidates = (
    new_spin_df[
        new_spin_df["spin_space_AM"]
    ]
    .sort_values(
        ["AM_type_preliminary", "ML_rank"]
    )
    .reset_index(drop=True)
)

print(
    "Candidates passing spin-space test:",
    len(stronger_AM_candidates)
)

display(
    stronger_AM_candidates[
        [
            "task_id",
            "formula",
            "ML_rank",
            "dft_ordering",
            "spacegroup",
            "AM_type_preliminary",
            "n_spin_ops",
            "n_spin_flip_ops",
        ]
    ]
)

Candidates passing spin-space test: 22

,task_id,formula,ML_rank,dft_ordering,spacegroup,AM_type_preliminary,n_spin_ops,n_spin_flip_ops
0,7605,Ba3Mn2O8,1,AFM,R-3m,S-type,8,2
1,33877,CoH5CN(ClO)2,1,AFM,C2/c,S-type,4,2
2,52096,Mn3TeO6,1,AFM,P2_1/c,S-type,4,2
3,5585,Ba2FeWO6,2,AFM,I4/mmm,S-type,16,6
4,4924,FeCuO2,2,AFM,R-3m,S-type,8,2
5,33213,LiNiAsO4,2,AFM,Imma,S-type,16,6
6,6112,Ni2P2O7,2,AFM,C2/m,S-type,8,2
7,31341,VZn2O4,2,AFM,Imma,S-type,8,2
8,11073,Ca2MnO3,3,AFM,I4/mmm,S-type,16,6
9,56534,Na6FeO4,3,FiM,P4_2/nmc,S-type,16,6
10,5659,Sr2NiTeO6,3,AFM,C2/m,S-type,8,2
11,12320,V2HO4,1,AFM,Pm,S/A-type,4,1
12,18076,BaLaMnSbO6,2,AFM,I-4,S/A-type,4,1
13,10424,Cs2LiMnO4,3,AFM,Cmc2_1,S/A-type,8,3
14,44933,Ta2MnO6,3,AFM,P4_2/mnm,S/A-type,8,3
15,13251,Co(IO3)2,4,AFM,P2_1,S/A-type,4,1
16,32678,LiCrSnO4,4,AFM,Imma,S/A-type,4,1
17,17963,BaSrNiWO6,5,AFM,F-43m,S/A-type,12,5
18,34911,Li3SiNi3O8,5,FiM,P2/m,S/A-type,4,1
19,37634,Li4Y3FeO8,5,AFM,C222,S/A-type,4,1
20,53621,LiVSiO4,5,FiM,P6_422,S/A-type,4,1
21,13679,Mn(IO3)2,5,AFM,P2_1,S/A-type,4,1

Rejected ones

In [ ]:
# ============================================================
# STEP 24: PRELIMINARY AM CANDIDATES REJECTED
# BY THE STRONGER SPIN-SPACE TEST
# ============================================================

rejected_spin = (
    new_spin_df[
        ~new_spin_df["spin_space_AM"]
    ]
    .sort_values("ML_rank")
    .reset_index(drop=True)
)

print(
    "Rejected by spin-space test:",
    len(rejected_spin)
)

display(
    rejected_spin[
        [
            "task_id",
            "formula",
            "ML_rank",
            "dft_ordering",
            "spacegroup",
            "AM_type_preliminary",
            "n_spin_ops",
            "n_spin_flip_ops",
        ]
    ]
)

Rejected by spin-space test: 8

,task_id,formula,ML_rank,dft_ordering,spacegroup,AM_type_preliminary,n_spin_ops,n_spin_flip_ops
0,14652,Ca3MnO4,1,AFM,C2/m,S-type,4,0
1,39392,SrZnNi(PO4)2,1,AFM,P-1,S-type,4,0
2,47297,Li4Ti2Mn3O10,2,AFM,P-1,S-type,4,0
3,40222,Li2VOF4,2,AFM,C2/c,S-type,4,0
4,53935,SrMn(GeO3)2,3,AFM,P-1,S-type,4,0
5,38658,Li3VP2HO8,4,AFM,P-1,S-type,4,0
6,20037,Ca2MnWO6,4,AFM,P1,S/A-type,2,0
7,11804,LiVSiO4,4,FiM,I-4,S/A-type,2,0

Our hierarchy will now be:

$$ 259\ \text{parents} $$ $$ \downarrow\quad\text{ALIGNN Top-5} $$ $$ 70\ \text{preliminary AM states} $$ $$ \downarrow\quad M\approx0,\ PT\text{-broken} $$ $$ 30\ \text{new preliminary candidates} $$ $$ \downarrow\quad\text{spin-space rotation/mirror test} $$
$$\boxed{\text{final stronger AM candidate pool}}$$
	​

From the 30 new preliminary AM candidates:

$$ \boxed{22/30 = 73.3\%} $$

pass the stronger spin-space operation test, while 8/30 are rejected.

So our current funnel is:

$$\boxed{\text{259 parents → ALIGNN Top-5 → 70 preliminary AM → 30 new preliminary AM → 22 spin-space AM candidates}}$$
	​

Saving 22 candidates

In [ ]:
# ============================================================
# SAVE 22 SPIN-SPACE-SUPPORTED NEW CANDIDATES
# ============================================================

spin_space_new_candidates = stronger_AM_candidates.copy()

spin_space_new_path = (
    "/content/drive/MyDrive/Proj_2_Alt_Mags_Grnd_E/"
    "magnetic-topological-materials/"
    "AM_new_spin_space_candidates.csv"
)

spin_space_new_candidates.to_csv(
    spin_space_new_path,
    index=False
)

print(
    "Saved:",
    spin_space_new_path
)

Saved: /content/drive/MyDrive/Proj_2_Alt_Mags_Grnd_E/magnetic-topological-materials/AM_new_spin_space_candidates.csv

Inspecting the actual spin-flip operations

The number of spin-flip operations alone is not enough. We should know what spatial operation is doing the spin exchange.

For each of the 22 candidates, extract the spatial rotation matrix \(R\), translation, and spin rotation W

In [ ]:
# ============================================================
# INSPECT THE SPIN-FLIP OPERATIONS OF THE 22 CANDIDATES
# ============================================================

spin_operation_rows = []

for _, row in spin_space_new_candidates.iterrows():

    task_id = int(row["task_id"])
    rec = record_by_task[str(task_id)]

    result = spin_space_am_test(
        rec,
        symprec=1e-2,
        mag_symprec=5e-2,
        spin_tol=0.05,
    )

    for op in result["spin_flip_ops"]:

        R = np.asarray(op["R"], dtype=float)

        spin_operation_rows.append({
            "task_id": task_id,
            "formula": row["formula"],
            "AM_type": row["AM_type_preliminary"],
            "operation_index": op["operation_index"],
            "R": R,
            "translation": op["translation"],
            "W": op["W"],
            "det_R": op["det_R"],
        })

spin_ops_df = pd.DataFrame(spin_operation_rows)

print(
    "Total spin-flip operations across 22 candidates:",
    len(spin_ops_df)
)

display(
    spin_ops_df[
        [
            "task_id",
            "formula",
            "AM_type",
            "operation_index",
            "det_R",
            "translation",
            "R",
            "W",
        ]
    ]
)

Total spin-flip operations across 22 candidates: 57

,task_id,formula,AM_type,operation_index,det_R,translation,R,W
0,7605,Ba3Mn2O8,S-type,5,1.0,"[0.5, 0.5, 0.0]","[[1.0, 0.0, 1.0], [0.0, -1.0, 0.0], [0.0, 0.0,...","[[1.0, 0.0, 0.0], [0.0, 1.0, 0.0], [0.0, 0.0, ..."
1,7605,Ba3Mn2O8,S-type,7,-1.0,"[0.5, 0.5, 0.0]","[[-1.0, 0.0, -1.0], [0.0, 1.0, 0.0], [0.0, 0.0...","[[1.0, 0.0, 0.0], [0.0, 1.0, 0.0], [0.0, 0.0, ..."
2,33877,CoH5CN(ClO)2,S-type,2,1.0,"[0.5, 1.0000000000285759e-06, 1.00000000003053...","[[-1.0, 0.0, 0.0], [0.0, 0.0, -1.0], [0.0, -1....","[[1.0, 0.0, 0.0], [0.0, 1.0, 0.0], [0.0, 0.0, ..."
3,33877,CoH5CN(ClO)2,S-type,3,-1.0,"[0.49999999999999983, 1.0000000002231673e-06, ...","[[1.0, 0.0, 0.0], [0.0, 0.0, 1.0], [0.0, 1.0, ...","[[1.0, 0.0, 0.0], [0.0, 1.0, 0.0], [0.0, 0.0, ..."
4,52096,Mn3TeO6,S-type,2,1.0,"[0.49999899999999986, 0.49999999999999994, 0.5...","[[-1.0, 0.0, 0.0], [0.0, 1.0, 0.0], [0.0, 0.0,...","[[1.0, 0.0, 0.0], [0.0, 1.0, 0.0], [0.0, 0.0, ..."
5,52096,Mn3TeO6,S-type,3,-1.0,"[0.4999999999999998, 0.49999999999999994, 0.49...","[[1.0, 0.0, 0.0], [0.0, -1.0, 0.0], [0.0, 0.0,...","[[1.0, 0.0, 0.0], [0.0, 1.0, 0.0], [0.0, 0.0, ..."
6,5585,Ba2FeWO6,S-type,5,1.0,"[0.4999979999999997, 0.4999939999999998, 0.500...","[[0.0, 0.0, 1.0], [0.0, -1.0, 0.0], [1.0, 0.0,...","[[1.0, 0.0, 0.0], [0.0, 1.0, 0.0], [0.0, 0.0, ..."
7,5585,Ba2FeWO6,S-type,7,-1.0,"[0.49999199999999977, 0.5000000000000001, 0.49...","[[0.0, 0.0, -1.0], [0.0, 1.0, 0.0], [-1.0, 0.0...","[[1.0, 0.0, 0.0], [0.0, 1.0, 0.0], [0.0, 0.0, ..."
8,5585,Ba2FeWO6,S-type,9,1.0,"[0.49998999999999927, 0.5, 0.49999400000000005]","[[-1.0, 0.0, 0.0], [0.0, 1.0, 0.0], [0.0, 0.0,...","[[1.0, 0.0, 0.0], [0.0, 1.0, 0.0], [0.0, 0.0, ..."
9,5585,Ba2FeWO6,S-type,11,-1.0,"[0.5000000000000001, 0.49999400000000005, 0.50...","[[1.0, 0.0, 0.0], [0.0, -1.0, 0.0], [0.0, 0.0,...","[[1.0, 0.0, 0.0], [0.0, 1.0, 0.0], [0.0, 0.0, ..."
10,5585,Ba2FeWO6,S-type,13,1.0,"[0.49999199999999955, 0.49999400000000005, 0.4...","[[0.0, 0.0, -1.0], [0.0, -1.0, 0.0], [-1.0, 0....","[[1.0, 0.0, 0.0], [0.0, 1.0, 0.0], [0.0, 0.0, ..."
11,5585,Ba2FeWO6,S-type,15,-1.0,"[0.4999979999999997, 0.4999999999999999, 0.500...","[[0.0, 0.0, 1.0], [0.0, 1.0, 0.0], [1.0, 0.0, ...","[[1.0, 0.0, 0.0], [0.0, 1.0, 0.0], [0.0, 0.0, ..."
12,4924,FeCuO2,S-type,5,1.0,"[0.5, 0.0, 0.5]","[[1.0, 0.0, 0.0], [0.0, -1.0, 0.0], [0.0, 0.0,...","[[1.0, 0.0, 0.0], [0.0, 1.0, 0.0], [0.0, 0.0, ..."
13,4924,FeCuO2,S-type,7,-1.0,"[0.5, 0.0, 0.5]","[[-1.0, 0.0, 0.0], [0.0, 1.0, 0.0], [0.0, 0.0,...","[[1.0, 0.0, 0.0], [0.0, 1.0, 0.0], [0.0, 0.0, ..."
14,33213,LiNiAsO4,S-type,4,1.0,"[0.9999955000000005, 0.4999990000000004, 1.942...","[[-1.0, 0.0, 0.0], [0.0, -1.0, 0.0], [0.0, 0.0...","[[1.0, 0.0, 0.0], [0.0, 1.0, 0.0], [0.0, 0.0, ..."
15,33213,LiNiAsO4,S-type,6,-1.0,"[1.0, 0.5000000000000001, 1.9999999999742446e-06]","[[1.0, 0.0, 0.0], [0.0, 1.0, 0.0], [0.0, 0.0, ...","[[1.0, 0.0, 0.0], [0.0, 1.0, 0.0], [0.0, 0.0, ..."
16,33213,LiNiAsO4,S-type,9,1.0,"[0.5000000000000007, 0.49999900000000075, 0.50...","[[1.0, 0.0, 0.0], [0.0, -1.0, 0.0], [0.0, 0.0,...","[[1.0, 0.0, 0.0], [0.0, 1.0, 0.0], [0.0, 0.0, ..."
17,33213,LiNiAsO4,S-type,11,-1.0,"[0.49999550000000004, 0.4999999999999999, 0.50...","[[-1.0, 0.0, 0.0], [0.0, 1.0, 0.0], [0.0, 0.0,...","[[1.0, 0.0, 0.0], [0.0, 1.0, 0.0], [0.0, 0.0, ..."
18,33213,LiNiAsO4,S-type,12,1.0,"[0.9999955, 0.5000000000000001, 2.000000000029...","[[-1.0, 0.0, 0.0], [0.0, 1.0, 0.0], [0.0, 0.0,...","[[1.0, 0.0, 0.0], [0.0, 1.0, 0.0], [0.0, 0.0, ..."
19,33213,LiNiAsO4,S-type,14,-1.0,"[4.364167859376456e-16, 0.4999990000000004, 1....","[[1.0, 0.0, 0.0], [0.0, -1.0, 0.0], [0.0, 0.0,...","[[1.0, 0.0, 0.0], [0.0, 1.0, 0.0], [0.0, 0.0, ..."
20,6112,Ni2P2O7,S-type,4,1.0,"[0.999999, 0.9999989999999999, 1.0]","[[0.0, -1.0, 0.0], [-1.0, 0.0, 0.0], [0.0, 0.0...","[[1.0, 0.0, 0.0], [0.0, 1.0, 0.0], [0.0, 0.0, ..."
21,6112,Ni2P2O7,S-type,6,-1.0,"[1.0000000002516124e-06, 0.9999989999999999, 1.0]","[[0.0, 1.0, 0.0], [1.0, 0.0, 0.0], [0.0, 0.0, ...","[[1.0, 0.0, 0.0], [0.0, 1.0, 0.0], [0.0, 0.0, ..."
22,31341,VZn2O4,S-type,4,1.0,"[0.12500199999999995, 0.625007, 0.249990999999...","[[0.0, 1.0, 1.0], [0.0, -1.0, 0.0], [1.0, 1.0,...","[[1.0, 0.0, 0.0], [0.0, 1.0, 0.0], [0.0, 0.0, ..."
23,31341,VZn2O4,S-type,6,-1.0,"[1.300000000015178e-05, 0.0, 1.300000000015178...","[[0.0, -1.0, -1.0], [0.0, 1.0, 0.0], [-1.0, -1...","[[1.0, 0.0, 0.0], [0.0, 1.0, 0.0], [0.0, 0.0, ..."
24,11073,Ca2MnO3,S-type,5,1.0,"[0.5, 0.5, 0.25]","[[-1.0, 0.0, 0.0], [0.0, 1.0, 0.0], [0.0, 0.0,...","[[1.0, 0.0, 0.0], [0.0, 1.0, 0.0], [0.0, 0.0, ..."
25,11073,Ca2MnO3,S-type,7,-1.0,"[0.0, 0.0, 0.5]","[[1.0, 0.0, 0.0], [0.0, -1.0, 0.0], [0.0, 0.0,...","[[1.0, 0.0, 0.0], [0.0, 1.0, 0.0], [0.0, 0.0, ..."
26,11073,Ca2MnO3,S-type,9,1.0,"[0.0, 0.0, 0.5]","[[-1.0, 0.0, 0.0], [0.0, -1.0, 0.0], [0.0, 0.0...","[[1.0, 0.0, 0.0], [0.0, 1.0, 0.0], [0.0, 0.0, ..."
27,11073,Ca2MnO3,S-type,11,-1.0,"[0.5, 0.5, 0.25]","[[1.0, 0.0, 0.0], [0.0, 1.0, 0.0], [0.0, 0.0, ...","[[1.0, 0.0, 0.0], [0.0, 1.0, 0.0], [0.0, 0.0, ..."
28,11073,Ca2MnO3,S-type,13,1.0,"[0.5, 0.5, 0.25]","[[1.0, 0.0, 0.0], [0.0, -1.0, 0.0], [0.0, 0.0,...","[[1.0, 0.0, 0.0], [0.0, 1.0, 0.0], [0.0, 0.0, ..."
29,11073,Ca2MnO3,S-type,15,-1.0,"[0.0, 0.0, 0.5]","[[-1.0, 0.0, 0.0], [0.0, 1.0, 0.0], [0.0, 0.0,...","[[1.0, 0.0, 0.0], [0.0, 1.0, 0.0], [0.0, 0.0, ..."
30,56534,Na6FeO4,S-type,3,1.0,"[0.5000137500000001, 7.100000000016446e-05, 0....","[[0.0, 0.0, 1.0], [1.0, 0.0, -1.0], [0.0, 1.0,...","[[1.0, 0.0, 0.0], [0.0, 1.0, 0.0], [0.0, 0.0, ..."
31,56534,Na6FeO4,S-type,5,1.0,"[0.9999290000000003, 0.5001695000000002, 0.499...","[[0.0, 1.0, 1.0], [0.0, -1.0, 0.0], [1.0, 1.0,...","[[1.0, 0.0, 0.0], [0.0, 1.0, 0.0], [0.0, 0.0, ..."
32,56534,Na6FeO4,S-type,7,1.0,"[0.4999152499999999, 0.5000985000000002, 0.499...","[[1.0, 1.0, 0.0], [-1.0, 0.0, 1.0], [1.0, 0.0,...","[[1.0, 0.0, 0.0], [0.0, 1.0, 0.0], [0.0, 0.0, ..."
33,56534,Na6FeO4,S-type,11,-1.0,"[0.9999090000000004, 9.849999999985048e-05, 0....","[[0.0, 0.0, -1.0], [-1.0, 0.0, 1.0], [0.0, -1....","[[1.0, 0.0, 0.0], [0.0, 1.0, 0.0], [0.0, 0.0, ..."
34,56534,Na6FeO4,S-type,13,-1.0,"[0.49999375, 0.5000000000000004, 0.99999375]","[[0.0, -1.0, -1.0], [0.0, 1.0, 0.0], [-1.0, -1...","[[1.0, 0.0, 0.0], [0.0, 1.0, 0.0], [0.0, 0.0, ..."
35,56534,Na6FeO4,S-type,15,-1.0,"[7.499999999938112e-06, 0.5000710000000003, 0....","[[-1.0, -1.0, 0.0], [1.0, 0.0, -1.0], [-1.0, 0...","[[1.0, 0.0, 0.0], [0.0, 1.0, 0.0], [0.0, 0.0, ..."
36,5659,Sr2NiTeO6,S-type,5,1.0,"[0.9999997499999997, 2.500000002569891e-07, 0....","[[0.0, 1.0, 0.0], [1.0, 0.0, 0.0], [0.0, 0.0, ...","[[1.0, 0.0, 0.0], [0.0, 1.0, 0.0], [0.0, 0.0, ..."
37,5659,Sr2NiTeO6,S-type,7,-1.0,"[0.24999899999999986, 0.24999899999999986, 0.5]","[[0.0, -1.0, 0.0], [-1.0, 0.0, 0.0], [0.0, 0.0...","[[1.0, 0.0, 0.0], [0.0, 1.0, 0.0], [0.0, 0.0, ..."
38,12320,V2HO4,S/A-type,3,-1.0,"[0.0, 0.5, 0.5]","[[-1.0, 0.0, 0.0], [0.0, 1.0, 0.0], [0.0, 0.0,...","[[1.0, 0.0, 0.0], [0.0, 1.0, 0.0], [0.0, 0.0, ..."
39,18076,BaLaMnSbO6,S/A-type,3,1.0,"[0.2500024999999997, 0.7500022500000009, 0.499...","[[-1.0, 0.0, 0.0], [0.0, 1.0, 1.0], [0.0, 0.0,...","[[1.0, 0.0, 0.0], [0.0, 1.0, 0.0], [0.0, 0.0, ..."
40,10424,Cs2LiMnO4,S/A-type,3,1.0,"[0.5000000000000002, 0.5000000000000002, 0.499...","[[-1.0, 0.0, 0.0], [0.0, -1.0, 0.0], [0.0, 0.0...","[[1.0, 0.0, 0.0], [0.0, 1.0, 0.0], [0.0, 0.0, ..."
41,10424,Cs2LiMnO4,S/A-type,5,-1.0,"[0.5000000000000002, 0.5, 0.0]","[[-1.0, 0.0, 0.0], [0.0, 1.0, 0.0], [0.0, 0.0,...","[[1.0, 0.0, 0.0], [0.0, 1.0, 0.0], [0.0, 0.0, ..."
42,10424,Cs2LiMnO4,S/A-type,7,-1.0,"[0.5, 0.5000000000000002, 0.49999999999999994]","[[1.0, 0.0, 0.0], [0.0, -1.0, 0.0], [0.0, 0.0,...","[[1.0, 0.0, 0.0], [0.0, 1.0, 0.0], [0.0, 0.0, ..."
43,44933,Ta2MnO6,S/A-type,3,-1.0,"[1.9535847478732803e-22, 0.5, 0.6666175000000001]","[[1.0, 0.0, 0.0], [0.0, 1.0, 0.0], [0.0, 0.0, ...","[[1.0, 0.0, 0.0], [0.0, 1.0, 0.0], [0.0, 0.0, ..."
44,44933,Ta2MnO6,S/A-type,5,1.0,"[0.5000000000000001, 0.750036, 0.1666175000000...","[[1.0, 0.0, 0.0], [0.0, -1.0, 0.0], [0.0, 0.0,...","[[1.0, 0.0, 0.0], [0.0, 1.0, 0.0], [0.0, 0.0, ..."
45,44933,Ta2MnO6,S/A-type,7,-1.0,"[0.5000000000000001, 0.750036, 0.5000000000000...","[[1.0, 0.0, 0.0], [0.0, -1.0, 0.0], [0.0, 0.0,...","[[1.0, 0.0, 0.0], [0.0, 1.0, 0.0], [0.0, 0.0, ..."
46,13251,Co(IO3)2,S/A-type,2,1.0,"[0.49999999999999994, 0.5000005000000001, 0.49...","[[1.0, 0.0, 0.0], [0.0, -1.0, 0.0], [0.0, 0.0,...","[[1.0, 0.0, 0.0], [0.0, 1.0, 0.0], [0.0, 0.0, ..."
47,32678,LiCrSnO4,S/A-type,3,1.0,"[0.2500009999999999, 0.7499990000000001, 0.249...","[[0.0, 1.0, 0.0], [1.0, 0.0, 0.0], [0.0, 0.0, ...","[[1.0, 0.0, 0.0], [0.0, 1.0, 0.0], [0.0, 0.0, ..."
48,17963,BaSrNiWO6,S/A-type,3,-1.0,"[0.5, 0.0, 0.5]","[[-1.0, -1.0, 0.0], [0.0, 1.0, 0.0], [0.0, 0.0...","[[1.0, 0.0, 0.0], [0.0, 1.0, 0.0], [0.0, 0.0, ..."
49,17963,BaSrNiWO6,S/A-type,5,1.0,"[0.5, 0.0, 0.5]","[[0.0, 1.0, 1.0], [-1.0, -1.0, -1.0], [0.0, 0....","[[1.0, 0.0, 0.0], [0.0, 1.0, 0.0], [0.0, 0.0, ..."
50,17963,BaSrNiWO6,S/A-type,7,-1.0,"[0.5, 0.0, 0.5]","[[0.0, 1.0, 1.0], [1.0, 0.0, -1.0], [0.0, 0.0,...","[[1.0, 0.0, 0.0], [0.0, 1.0, 0.0], [0.0, 0.0, ..."
51,17963,BaSrNiWO6,S/A-type,9,-1.0,"[0.5, 0.0, 0.5]","[[1.0, 0.0, 0.0], [-1.0, -1.0, -1.0], [0.0, 0....","[[1.0, 0.0, 0.0], [0.0, 1.0, 0.0], [0.0, 0.0, ..."
52,17963,BaSrNiWO6,S/A-type,11,1.0,"[0.5, 0.0, 0.5]","[[-1.0, -1.0, 0.0], [1.0, 0.0, -1.0], [0.0, 0....","[[1.0, 0.0, 0.0], [0.0, 1.0, 0.0], [0.0, 0.0, ..."
53,34911,Li3SiNi3O8,S/A-type,2,-1.0,"[0.0, 0.0, 0.0]","[[1.0, 0.0, 0.0], [0.0, 0.0, 1.0], [0.0, 1.0, ...","[[1.0, 0.0, 0.0], [0.0, 1.0, 0.0], [0.0, 0.0, ..."
54,37634,Li4Y3FeO8,S/A-type,2,1.0,"[0.4999680000000002, 0.7500199999999999, 0.249...","[[-1.0, 0.0, 0.0], [0.0, 0.0, 1.0], [0.0, 1.0,...","[[1.0, 0.0, 0.0], [0.0, 1.0, 0.0], [0.0, 0.0, ..."
55,53621,LiVSiO4,S/A-type,2,1.0,"[1.0, 0.0, 9.499999999995621e-06]","[[1.0, 1.0, 0.0], [0.0, -1.0, 0.0], [0.0, 0.0,...","[[1.0, 0.0, 0.0], [0.0, 1.0, 0.0], [0.0, 0.0, ..."
56,13679,Mn(IO3)2,S/A-type,2,1.0,"[0.5, 0.0, 0.0]","[[1.0, 0.0, 0.0], [0.0, -1.0, 0.0], [0.0, 0.0,...","[[1.0, 0.0, 0.0], [0.0, 1.0, 0.0], [0.0, 0.0, ..."

Classifying the spatial operation

For each \(R\), we want to distinguish:

* proper rotation: \(\det R=+1\)
* improper rotation/mirror: \(\det R=-1\)
* identity
* inversion

In [ ]:
# ============================================================
# CLASSIFY SPATIAL OPERATIONS
# ============================================================

def classify_rotation_matrix(R, tol=1e-5):

    R = np.asarray(R, dtype=float)

    I = np.eye(3)
    inv = -I

    if np.allclose(R, I, atol=tol):
        return "identity"

    if np.allclose(R, inv, atol=tol):
        return "inversion"

    det = np.linalg.det(R)

    if det > 0:
        return "proper rotation"

    return "improper rotation / mirror"


spin_ops_df["spatial_operation_type"] = (
    spin_ops_df["R"]
    .apply(classify_rotation_matrix)
)

print(
    spin_ops_df[
        "spatial_operation_type"
    ].value_counts()
)

spatial_operation_type
proper rotation               29
improper rotation / mirror    28
Name: count, dtype: int64

Confidence of the 22

In [ ]:
# ============================================================
# ADD ENERGY-ROBUSTNESS INFORMATION
# ============================================================

candidate_energy_info = (
    top5_full[
        top5_full["task_id"].isin(
            spin_space_new_candidates["task_id"]
        )
    ]
    [
        [
            "task_id",
            "parent_structure_id",
            "formula",
            "ML_rank",
            "pred_energy",
            "delta_E",
            "dft_energy_per_atom",
            "total_magnetization",
            "dft_ordering",
        ]
    ]
    .copy()
)

candidate_energy_info["true_gap_meV"] = (
    candidate_energy_info["delta_E"] * 1000
)

final_candidate_table = (
    spin_space_new_candidates[
        [
            "task_id",
            "formula",
            "ML_rank",
            "AM_type_preliminary",
            "spacegroup",
            "n_spin_ops",
            "n_spin_flip_ops",
        ]
    ]
    .merge(
        candidate_energy_info,
        on=[
            "task_id",
            "formula",
            "ML_rank",
        ],
        how="left"
    )
    .sort_values(
        ["AM_type_preliminary", "ML_rank"]
    )
    .reset_index(drop=True)
)

display(final_candidate_table)

,task_id,formula,ML_rank,AM_type_preliminary,spacegroup,n_spin_ops,n_spin_flip_ops,parent_structure_id,pred_energy,delta_E,dft_energy_per_atom,total_magnetization,dft_ordering,true_gap_meV
0,7605,Ba3Mn2O8,1,S-type,R-3m,8,2,0c2d52183c38df88fee8ae11f97c4ed7a98349063c3b54...,0.004961,0.000000,-6.645346,0.000000e+00,AFM,0.000000
1,33877,CoH5CN(ClO)2,1,S-type,C2/c,4,2,04cc4f9f56be07e7246735311948061e37779c4b9a8f2c...,0.000096,0.000264,-5.232197,1.000000e-07,AFM,0.264211
2,52096,Mn3TeO6,1,S-type,P2_1/c,4,2,1038d9d2669e5a3effc9d793059a22e841361444e02f96...,-0.003429,0.000159,-7.001651,2.600000e-06,AFM,0.159475
3,5585,Ba2FeWO6,2,S-type,I4/mmm,16,6,1f14fd73fee38e689e79bc251edd3e629007fb159670d4...,0.016076,0.000000,-7.053958,7.820000e-05,AFM,0.000000
4,4924,FeCuO2,2,S-type,R-3m,8,2,ab9bce210c52aa26bab4d805a88dae0e6a044df5171ca5...,0.010748,0.000000,-6.029899,1.000000e-07,AFM,0.000000
5,33213,LiNiAsO4,2,S-type,Imma,16,6,4a5d049498693a0be19f93facaa657a93e71d2f69a1326...,-0.000637,0.000000,-5.633101,2.500000e-06,AFM,0.000000
6,6112,Ni2P2O7,2,S-type,C2/m,8,2,3dd018ce066394470e995a3218e3dad2c0e37227e5fffd...,0.001600,0.000000,-6.502522,0.000000e+00,AFM,0.000000
7,31341,VZn2O4,2,S-type,Imma,8,2,6bd858f396b22c6b26d15d57cdfd9396675ba9f6fac10f...,0.009675,0.000000,-5.916865,2.910000e-05,AFM,0.000000
8,11073,Ca2MnO3,3,S-type,I4/mmm,16,6,73f4bd37278a6a38b593e717339a0a86afd47520c56919...,0.004522,0.000000,-6.888079,3.000000e-07,AFM,0.000000
9,56534,Na6FeO4,3,S-type,P4_2/nmc,16,6,3e6de35153e09542a954e9ca329cf11ff6411d1e57536a...,0.008597,0.000045,-4.297959,1.000000e-07,FiM,0.045268
10,5659,Sr2NiTeO6,3,S-type,C2/m,8,2,5497dbf8cd951bb7d91511d8a460a1f144c03db7328433...,0.012778,0.000000,-5.833346,1.030000e-05,AFM,0.000000
11,12320,V2HO4,1,S/A-type,Pm,4,1,9d55b73476b87b62e5017d61813db0028a19d0b3ac333f...,0.016886,0.006605,-7.250552,7.319000e-04,AFM,6.605424
12,18076,BaLaMnSbO6,2,S/A-type,I-4,4,1,d22c9cb3cd0f21e2920aa778f93bdfedde05c669ed7241...,0.007145,0.000076,-7.169242,0.000000e+00,AFM,0.075741
13,10424,Cs2LiMnO4,3,S/A-type,Cmc2_1,8,3,c09704c5a3cbebf823f642b7e035b2862c8a7c5eb7035c...,-0.006036,0.000021,-5.414654,1.250000e-05,AFM,0.021183
14,44933,Ta2MnO6,3,S/A-type,P4_2/mnm,8,3,e56f8da9db2fc40f44b74fb9dbcba2ca5a24806d3c01d4...,0.001325,0.000041,-9.400009,0.000000e+00,AFM,0.041349
15,13251,Co(IO3)2,4,S/A-type,P2_1,4,1,da34197fc6027979dc4ab3106a3c324c7105618b346a01...,0.004034,0.000161,-4.758716,1.000000e-07,AFM,0.161260
16,32678,LiCrSnO4,4,S/A-type,Imma,4,1,0448b1eaa7be7933adf68fe3e072fc226a55d6c89fc79d...,0.000433,0.000096,-6.653268,5.420000e-05,AFM,0.096326
17,17963,BaSrNiWO6,5,S/A-type,F-43m,12,5,8c8af08376deab5d84bebd54de9ef0c741ca5676765b44...,0.013386,0.000007,-6.662155,0.000000e+00,AFM,0.007273
18,34911,Li3SiNi3O8,5,S/A-type,P2/m,4,1,a8ff7985f2d477f1b39e8930201616e64dcde19e55c84c...,-0.003092,0.000810,-5.492732,1.440000e-05,FiM,0.809639
19,37634,Li4Y3FeO8,5,S/A-type,C222,4,1,c5b942af1855dfa4270c38478d769e94938b918b2580f8...,0.005864,0.000123,-7.095216,0.000000e+00,AFM,0.123420
20,53621,LiVSiO4,5,S/A-type,P6_422,4,1,0775dee4594fc6fa3e403dc67f91fd95720ce3a6e0d2ee...,0.006333,0.000451,-7.294286,2.700000e-06,FiM,0.450752
21,13679,Mn(IO3)2,5,S/A-type,P2_1,4,1,7e6f6611eec92036dc036610212e90f8ce34638de9fed8...,0.004848,0.000038,-5.176944,0.000000e+00,AFM,0.037968

Calculating the actual DFT ground-state gap for the 22

In [ ]:
# ============================================================
# STEP 25 — ACTUAL DFT GROUND-STATE GAP FOR THE 22 CANDIDATES
# ============================================================

# For every parent, sort all configurations by delta_E.
# The difference between the two lowest values is the
# true DFT ground-state gap.

sorted_energy = (
    test_df[
        [
            "parent_structure_id",
            "task_id",
            "formula",
            "delta_E",
        ]
    ]
    .sort_values(
        ["parent_structure_id", "delta_E"]
    )
    .copy()
)

# First and second lowest states for every parent
gap_info = (
    sorted_energy
    .groupby("parent_structure_id", sort=False)
    .head(2)
    .groupby("parent_structure_id")["delta_E"]
    .agg(["min", "count"])
    .reset_index()
)

# Get the two lowest energies explicitly
gap_values = (
    sorted_energy
    .groupby("parent_structure_id")["delta_E"]
    .apply(lambda x: x.iloc[1] - x.iloc[0]
           if len(x) >= 2 else np.nan)
    .rename("ground_gap_eV_atom")
    .reset_index()
)

gap_values["ground_gap_meV_atom"] = (
    gap_values["ground_gap_eV_atom"] * 1000
)

# ------------------------------------------------------------
# Add parent_structure_id to the 22 candidates
# ------------------------------------------------------------

candidate_parent_map = (
    top5_candidates[
        [
            "task_id",
            "parent_structure_id"
        ]
    ]
    .drop_duplicates("task_id")
)

stronger_AM_candidates_with_parent = (
    stronger_AM_candidates
    .merge(
        candidate_parent_map,
        on="task_id",
        how="left"
    )
)

# ------------------------------------------------------------
# Merge actual DFT gap
# ------------------------------------------------------------

final_candidate_table = (
    stronger_AM_candidates_with_parent
    .merge(
        gap_values,
        on="parent_structure_id",
        how="left"
    )
    .sort_values(
        "ground_gap_meV_atom",
        ascending=False
    )
    .reset_index(drop=True)
)

print(
    "Number of candidates:",
    len(final_candidate_table)
)

display(
    final_candidate_table[
        [
            "task_id",
            "formula",
            "AM_type_preliminary",
            "ML_rank",
            "spacegroup",
            "n_spin_ops",
            "n_spin_flip_ops",
            "ground_gap_meV_atom",
        ]
    ]
)

Number of candidates: 22

,task_id,formula,AM_type_preliminary,ML_rank,spacegroup,n_spin_ops,n_spin_flip_ops,ground_gap_meV_atom
0,34911,Li3SiNi3O8,S/A-type,5,P2/m,4,1,0.349178
1,53621,LiVSiO4,S/A-type,5,P6_422,4,1,0.311660
2,33877,CoH5CN(ClO)2,S-type,1,C2/c,4,2,0.198972
3,5585,Ba2FeWO6,S-type,2,I4/mmm,16,6,0.188812
4,13251,Co(IO3)2,S/A-type,4,P2_1,4,1,0.161260
5,52096,Mn3TeO6,S-type,1,P2_1/c,4,2,0.159475
6,33213,LiNiAsO4,S-type,2,Imma,16,6,0.125226
7,32678,LiCrSnO4,S/A-type,4,Imma,4,1,0.096326
8,31341,VZn2O4,S-type,2,Imma,8,2,0.078027
9,18076,BaLaMnSbO6,S/A-type,2,I-4,4,1,0.075741
10,5659,Sr2NiTeO6,S-type,3,C2/m,8,2,0.049990
11,4924,FeCuO2,S-type,2,R-3m,8,2,0.045802
12,6112,Ni2P2O7,S-type,2,C2/m,8,2,0.041679
13,44933,Ta2MnO6,S/A-type,3,P4_2/mnm,8,3,0.041349
14,13679,Mn(IO3)2,S/A-type,5,P2_1,4,1,0.037968
15,37634,Li4Y3FeO8,S/A-type,5,C222,4,1,0.026285
16,7605,Ba3Mn2O8,S-type,1,R-3m,8,2,0.024890
17,56534,Na6FeO4,S-type,3,P4_2/nmc,16,6,0.022829
18,10424,Cs2LiMnO4,S/A-type,3,Cmc2_1,8,3,0.021183
19,11073,Ca2MnO3,S-type,3,I4/mmm,16,6,0.019353
20,17963,BaSrNiWO6,S/A-type,5,F-43m,12,5,0.007273
21,12320,V2HO4,S/A-type,1,Pm,4,1,0.000011

In [ ]:
# ============================================================
# CLEAN GROUND-STATE GAP CALCULATION
# ============================================================

energy_ranked = (
    test_df[
        [
            "parent_structure_id",
            "delta_E"
        ]
    ]
    .sort_values(
        ["parent_structure_id", "delta_E"]
    )
    .copy()
)

energy_ranked["energy_rank"] = (
    energy_ranked
    .groupby("parent_structure_id")
    .cumcount()
    + 1
)

lowest_two = energy_ranked[
    energy_ranked["energy_rank"] <= 2
]

gap_values = (
    lowest_two
    .pivot(
        index="parent_structure_id",
        columns="energy_rank",
        values="delta_E"
    )
    .reset_index()
)

gap_values["ground_gap_eV_atom"] = (
    gap_values[2] - gap_values[1]
)

gap_values["ground_gap_meV_atom"] = (
    gap_values["ground_gap_eV_atom"] * 1000
)

gap_values = gap_values[
    [
        "parent_structure_id",
        "ground_gap_eV_atom",
        "ground_gap_meV_atom"
    ]
]

print("Gap values calculated for:",
      len(gap_values),
      "parents")

Gap values calculated for: 259 parents

Merge

In [ ]:
# ============================================================
# MERGE GAP INTO THE 22 CANDIDATES
# ============================================================

final_candidate_table = (
    stronger_AM_candidates
    .merge(
        candidate_parent_map,
        on="task_id",
        how="left"
    )
    .merge(
        gap_values,
        on="parent_structure_id",
        how="left"
    )
    .sort_values(
        "ground_gap_meV_atom",
        ascending=False
    )
    .reset_index(drop=True)
)

display(
    final_candidate_table[
        [
            "task_id",
            "formula",
            "AM_type_preliminary",
            "ML_rank",
            "spacegroup",
            "n_spin_ops",
            "n_spin_flip_ops",
            "ground_gap_meV_atom",
        ]
    ]
)

,task_id,formula,AM_type_preliminary,ML_rank,spacegroup,n_spin_ops,n_spin_flip_ops,ground_gap_meV_atom
0,34911,Li3SiNi3O8,S/A-type,5,P2/m,4,1,0.349178
1,53621,LiVSiO4,S/A-type,5,P6_422,4,1,0.311660
2,33877,CoH5CN(ClO)2,S-type,1,C2/c,4,2,0.198972
3,5585,Ba2FeWO6,S-type,2,I4/mmm,16,6,0.188812
4,13251,Co(IO3)2,S/A-type,4,P2_1,4,1,0.161260
5,52096,Mn3TeO6,S-type,1,P2_1/c,4,2,0.159475
6,33213,LiNiAsO4,S-type,2,Imma,16,6,0.125226
7,32678,LiCrSnO4,S/A-type,4,Imma,4,1,0.096326
8,31341,VZn2O4,S-type,2,Imma,8,2,0.078027
9,18076,BaLaMnSbO6,S/A-type,2,I-4,4,1,0.075741
10,5659,Sr2NiTeO6,S-type,3,C2/m,8,2,0.049990
11,4924,FeCuO2,S-type,2,R-3m,8,2,0.045802
12,6112,Ni2P2O7,S-type,2,C2/m,8,2,0.041679
13,44933,Ta2MnO6,S/A-type,3,P4_2/mnm,8,3,0.041349
14,13679,Mn(IO3)2,S/A-type,5,P2_1,4,1,0.037968
15,37634,Li4Y3FeO8,S/A-type,5,C222,4,1,0.026285
16,7605,Ba3Mn2O8,S-type,1,R-3m,8,2,0.024890
17,56534,Na6FeO4,S-type,3,P4_2/nmc,16,6,0.022829
18,10424,Cs2LiMnO4,S/A-type,3,Cmc2_1,8,3,0.021183
19,11073,Ca2MnO3,S-type,3,I4/mmm,16,6,0.019353
20,17963,BaSrNiWO6,S/A-type,5,F-43m,12,5,0.007273
21,12320,V2HO4,S/A-type,1,Pm,4,1,0.000011

Freezing the project

$$\boxed{\text{259 parents}}$$
	​

$$ \downarrow\ {\rm ALIGNN\ Top\!-\!5} $$ $$ \boxed{70\ \text{preliminary AM}} $$ $$ \downarrow\ {\rm exclude\ known\ 55} $$ $$ \boxed{30\ \text{new preliminary}} $$ $$ \downarrow\ {\rm spin\!-\!space\ test} $$
$$\boxed{\text{22 spin-space-supported new candidates}}$$
	​

### Step - 10.6 - Making the 22-candidate master table

One clean table containing the symmetry evidence and energetic robustness

In [ ]:
# # ============================================================
# # STEP 28: MASTER TABLE FOR THE 22 CANDIDATES
# # ============================================================

# master_22 = final_candidate_table.copy()

# master_22["priority_gap"] = pd.cut(
#     master_22["ground_gap_meV_atom"],
#     bins=[-np.inf, 0.01, 0.1, 0.2, np.inf],
#     labels=[
#         "ultra-near-degenerate",
#         "near-degenerate",
#         "moderate",
#         "larger gap",
#     ]
# )

# master_22 = master_22.sort_values(
#     [
#         "ground_gap_meV_atom",
#         "n_spin_flip_ops",
#     ],
#     ascending=[False, False]
# ).reset_index(drop=True)

# display(
#     master_22[
#         [
#             "task_id",
#             "formula",
#             "AM_type_preliminary",
#             "ML_rank",
#             "spacegroup",
#             "n_spin_ops",
#             "n_spin_flip_ops",
#             "ground_gap_meV_atom",
#             "priority_gap",
#         ]
#     ]
# )

Inspecting the pure spin rotations

In [ ]:
# # ============================================================
# # STEP 29: PURE SPIN-ROTATION SYMMETRIES
# # ============================================================

# pure_spin_rows = []

# for _, row in stronger_AM_candidates.iterrows():

#     task_id = int(row["task_id"])
#     rec = record_by_task[str(task_id)]

#     result = spin_space_am_test(
#         rec,
#         symprec=1e-2,
#         mag_symprec=5e-2,
#         spin_tol=0.05,
#     )

#     # Recalculate full spin-space symmetry
#     structure = Structure.from_dict(rec["structure"])
#     raw_m = np.asarray(rec["magmoms"]["vasp"], dtype=float)

#     m = raw_m.copy()
#     m[np.abs(m) < 0.05] = 0.0

#     mag3 = np.zeros((len(m), 3))
#     mag3[:, 2] = m

#     lattice = np.asarray(structure.lattice.matrix, dtype=float)
#     positions = np.asarray(structure.frac_coords, dtype=float)
#     numbers = np.asarray(structure.atomic_numbers, dtype=int)

#     sog, rotations, translations, spin_rotations = get_spin_symmetry(
#         lattice,
#         positions,
#         numbers,
#         mag3,
#         symprec=1e-2,
#         mag_symprec=5e-2,
#         angle_tolerance=5,
#     )

#     R_all = np.asarray(rotations, dtype=float)
#     W_all = np.asarray(spin_rotations, dtype=float)

#     pure_spin_count = 0
#     pure_spin_flip_count = 0

#     for R, W in zip(R_all, W_all):

#         spatial_identity = np.allclose(
#             R, np.eye(3), atol=1e-5
#         )

#         if not spatial_identity:
#             continue

#         pure_spin_count += 1

#         axis = np.array([0.0, 0.0, 1.0])
#         transformed_axis = W @ axis

#         if np.allclose(
#             transformed_axis,
#             -axis,
#             atol=1e-5
#         ):
#             pure_spin_flip_count += 1

#     pure_spin_rows.append({
#         "task_id": task_id,
#         "formula": row["formula"],
#         "pure_spin_ops": pure_spin_count,
#         "pure_spin_flip_ops": pure_spin_flip_count,
#         "total_spin_ops": len(R_all),
#     })

# pure_spin_df = pd.DataFrame(pure_spin_rows)

# master_22 = master_22.merge(
#     pure_spin_df,
#     on=["task_id", "formula"],
#     how="left"
# )

# display(
#     master_22[
#         [
#             "task_id",
#             "formula",
#             "AM_type_preliminary",
#             "n_spin_flip_ops",
#             "pure_spin_ops",
#             "pure_spin_flip_ops",
#             "ground_gap_meV_atom",
#         ]
#     ]
# )

Identifying the nontrivial AM-generating operation

In [ ]:
# # ============================================================
# # STEP 30: IDENTIFY NONTRIVIAL SPIN-FLIP SPATIAL OPERATIONS
# # ============================================================

# operation_summary = []

# for _, row in stronger_AM_candidates.iterrows():

#     task_id = int(row["task_id"])
#     rec = record_by_task[str(task_id)]

#     result = spin_space_am_test(
#         rec,
#         symprec=1e-2,
#         mag_symprec=5e-2,
#         spin_tol=0.05,
#     )

#     nontrivial_ops = []

#     for op in result["spin_flip_ops"]:

#         R = np.asarray(op["R"], dtype=float)
#         t = np.asarray(op["translation"], dtype=float)

#         is_identity = np.allclose(
#             R, np.eye(3), atol=1e-5
#         )

#         is_inversion = np.allclose(
#             R, -np.eye(3), atol=1e-5
#         )

#         if (not is_identity) and (not is_inversion):
#             nontrivial_ops.append(op)

#     operation_summary.append({
#         "task_id": task_id,
#         "formula": row["formula"],
#         "AM_type": row["AM_type_preliminary"],
#         "n_total_spin_flip": len(
#             result["spin_flip_ops"]
#         ),
#         "n_nontrivial_spin_flip": len(
#             nontrivial_ops
#         ),
#         "has_nontrivial_spin_flip": (
#             len(nontrivial_ops) > 0
#         ),
#     })

# operation_summary_df = pd.DataFrame(
#     operation_summary
# )

# print(
#     "Candidates with a nontrivial spatial "
#     "spin-flipping operation:",
#     operation_summary_df[
#         "has_nontrivial_spin_flip"
#     ].sum()
# )

# print(
#     "Candidates without one:",
#     (
#         ~operation_summary_df[
#             "has_nontrivial_spin_flip"
#         ]
#     ).sum()
# )

# display(operation_summary_df)

Merging this into your final 22 table

In [ ]:
# ============================================================
# STEP 31 — MERGE ALL 22-CANDIDATE SYMMETRY INFORMATION
# ============================================================

# pure_spin_df was created in Step 29
# operation_summary_df was created in Step 30

final_22_summary = (
    master_22
    .merge(
        pure_spin_df[
            [
                "task_id",
                "formula",
                "pure_spin_ops",
                "pure_spin_flip_ops",
            ]
        ],
        on=["task_id", "formula"],
        how="left"
    )
    .merge(
        operation_summary_df[
            [
                "task_id",
                "formula",
                "n_total_spin_flip",
                "n_nontrivial_spin_flip",
                "has_nontrivial_spin_flip",
            ]
        ],
        on=["task_id", "formula"],
        how="left"
    )
)

print("Rows:", len(final_22_summary))
print("Columns:", final_22_summary.columns.tolist())

display(
    final_22_summary[
        [
            "task_id",
            "formula",
            "AM_type_preliminary",
            "ML_rank",
            "spacegroup",
            "n_spin_ops",
            "n_spin_flip_ops",
            "n_nontrivial_spin_flip",
            "has_nontrivial_spin_flip",
            "pure_spin_ops",
            "pure_spin_flip_ops",
            "ground_gap_meV_atom",
        ]
    ]
)

NameError: name 'master_22' is not defined

Key count

In [ ]:
# # ============================================================
# # NONTRIVIAL SPIN-FLIP SUMMARY
# # ============================================================

# print(
#     "Candidates with nontrivial spatial spin-flip:",
#     final_22_summary[
#         "has_nontrivial_spin_flip"
#     ].sum()
# )

# print(
#     "Candidates without nontrivial spatial spin-flip:",
#     (
#         ~final_22_summary[
#             "has_nontrivial_spin_flip"
#         ]
#     ).sum()
# )

### Summary so far

1. What are the 55 AM candidates?

The 55 came from the complete DFT test set, before using the ML Top-5 screening.

We had 259 parent materials and all of their magnetic configurations. For each parent, we identified the true DFT ground-state configuration and then applied your original preliminary AM screen:

$$ M_{\rm total}\approx0 $$

and

$$ PT\text{ broken}. $$

That produced:

$$ \boxed{55\text{ preliminary AM ground states}} $$

They were divided into:

19 S-type
36 S/A-type

These 55 are therefore our reference/benchmark AM set.


2. Where did the 70 preliminary AM ground states come from?

The 70 were generated by the new ML-guided workflow.

For every one of the 259 parents:

$$ \text{ALIGNN prediction} \rightarrow \text{choose Top-5 predicted configurations} $$

giving 1198 candidate configurations.

We then looked at the DFT results of those Top-5 configurations and selected the lowest DFT-energy state for each parent.

So:

$$ 1198\text{ Top-5 configurations} \rightarrow 259\text{ DFT-selected states}. $$

We then applied the same preliminary AM criterion:

$$ M\approx0,\qquad PT\text{ broken}. $$

That produced:

$$ \boxed{70\text{ preliminary AM ground states}}. $$

So these 70 are the ML-discovered preliminary AM states.


3. How do the 55 and 70 relate?

They are not two pieces of the same set.

The 55 were obtained from the complete DFT ground-state screening.

The 70 were obtained from the ML Top-5 screening workflow.

When we compared them:

$$ \boxed{40} $$

of the 70 were already known in the original 55.

The remaining:

$$ 70-40=\boxed{30} $$

were new preliminary AM candidates that were not present in our original 55.


55 reference AM states
        ↑
        │ 40 recovered by Top-5
        │
70 ML-guided preliminary AM states
        │
        └── 30 new candidates


And our independent benchmark had already shown:

$$ 40/55=72.73\% $$

Top-5 recovery.

So the ML screen correctly recovered 40 of the 55 known AM ground states, while also producing 30 additional preliminary candidates.

4. What does "spin-space" mean?

This is the extra symmetry analysis we introduced after the 70.

Ordinary magnetic-space symmetry looks mainly at:

$$ \text{position/space} + \text{time reversal}. $$

A spin-space symmetry goes one step further and considers a symmetry operation acting in real space and spin space together.

Very roughly:

$$ \text{spatial operation }R + \text{spin rotation }W. $$

For a collinear magnetic structure, a useful example is:

$$ \boxed{ R:\text{ maps one magnetic sublattice to another} } $$

while

$$ \boxed{ W:\uparrow\rightarrow\downarrow. } $$

So instead of merely asking:

"Is \(PT\) broken?"

we ask:

"Is there a nontrivial spatial operation that connects opposite-spin sublattices?"

That is much closer to the symmetry mechanism associated with altermagnetism.

5. What are the 22 spin-space-supported AM candidates?

We took the 30 new preliminary candidates and applied our stricter spin-space test.

Of those:

$$ 30\rightarrow22 $$

passed.

So:

$$ \boxed{22\text{ spin-space-supported new AM candidates}} $$

means:

These 22 are not only compensated and \(PT\)-broken; they also possess at least one nontrivial spatial symmetry operation that flips the collinear spin direction.

All 22 passed your has_nontrivial_spin_flip=True test.

The other 8 failed that stronger test.

6. Difference between 70 and 22

This is the simplest way to remember it:

70

Preliminary AM

Criteria:

$$ M\approx0 $$

and

$$ PT\text{ broken}. $$

This is a broad symmetry screen.

22

Spin-space-supported AM candidates

Criteria:

$$ M\approx0 $$ $$ PT\text{ broken} $$

plus

$$ \text{nontrivial spatial operation} + \text{spin reversal}. $$

This is a more specific symmetry screen.

And these 22 are only candidates, not yet experimentally/theoretically confirmed altermagnets.

The complete workflow is now:

$$ \boxed{2203\text{ test configurations}} $$ $$ \downarrow $$ $$ \boxed{259\text{ parent materials}} $$
ML stage
$$ \text{Spin-aware ALIGNN} \rightarrow \text{rank configurations} $$ $$ \downarrow $$ $$ \boxed{\text{Top-5}} $$

This gives:

$$ 1198\text{ candidate configurations} $$

instead of evaluating all 2203.

DFT selection
$$ 1198 \rightarrow 259 $$

by selecting the lowest DFT-energy state among each parent's Top-5.

Preliminary AM screen
$$ 259 \rightarrow \boxed{70} $$

using:

$$ M\approx0,\quad PT\text{ broken}. $$
Remove already-known benchmark states
$$ 70-40 = \boxed{30\text{ new preliminary candidates}} $$
Spin-space screen
$$ 30 \rightarrow \boxed{22} $$

So our current final candidate pool is:

$$ \boxed{22\text{ new spin-space-supported AM candidates}}. $$

That are,

* $Li_3SiNi_3O_8$
* $LiVSiO_4$
* $CoH_5CN(ClO)_2$
* $Ba_2FeWO_6$
* $Co(IO_3)_2$
* $Mn_3TeO_6$
* $LiNiAsO_4$
* $LiCrSnO_4$
* $VZn_2O_4$
* $BaLaMnSbO_6$
* $Sr_2NiTeO_6$
* $FeCuO_2$
* $Ni_2P_2O_7$
* $Ta_2MnO_6$
* $Mn(IO_3)_2$
* $Li_4Y_3FeO_8$
* $Ba_3Mn_2O_8$
* $Na_6FeO_4$
* $Cs_2LiMnO_4$
* $Ca_2MnO_3$
* $BaSrNiWO_6$
* $V_2HO_4$

## Phase - 11 - DFT electronic-structure validation

For the 22 candidates, we need to test whether the electronic structure actually shows the characteristic altermagnetic spin splitting.

The workflow becomes:

$$\boxed{\text{22 candidates → DFT electronic structure → SOC OFF → spin-resolved bands →}ΔE_{↑↓}(k)}$$
	​

We have 22 candidates. We don't need to do the most expensive calculation for all 22 immediately.

Lets follow this order:

$$ \boxed{\text{22}} \rightarrow \text{select 5–6 strongest candidates} \rightarrow \text{SOC-off band structures} $$

and then, depending on the results, expand to the remaining candidates.

The strongest starting candidates from your current list are:

* Li₃SiNi₃O₈
* LiVSiO₄
* CoH₅CN(ClO)₂
* Ba₂FeWO₆
* Co(IO₃)₂
* Mn₃TeO₆

These have the largest ground-to-first-excited magnetic energy gaps within the 22.

The important point is that symmetry has given us 22 candidates, but the decisive physical signature is non-relativistic spin splitting (NRSS): spin-up/down bands can be split even with SOC turned off. Strong altermagnets have this zero-SOC splitting; weak ones require SOC.

**What the DFT validation must show**

For each candidate we want:

$$ M\simeq0 $$ $$ PT\text{ broken} $$ $$ \text{nontrivial spin-space symmetry} $$

and finally

$$ \boxed{\Delta E_{\uparrow\downarrow}(\mathbf k)\neq0 \quad\text{with SOC OFF}} $$

at least over appropriate regions of the Brillouin zone.

The splitting does not have to occur everywhere: altermagnetic symmetry can enforce degeneracies on certain symmetry planes/lines while allowing splitting elsewhere. Recent calculations demonstrate exactly this behavior.

$$\boxed{\text{DFT ground state → SOC OFF → spin splitting? → YES → strong-AM candidate → SOC ON → check how SOC modifies splitting}}$$

For candidates that do not split without SOC, an SOC calculation can tell us whether they are potentially weak altermagnets.

We need to use the actual converged DFT magnetic structures already stored in the record_by_task, not the ALIGNN input moments. The record contains the final structure and final VASP moments, so that is the correct starting point.

For each candidate we should therefore extract,

* task_id
* final relaxed structure
* final VASP magmoms
* DFT ground-state configuration

### Step - 11.1 - First calculation: $Li_3SiNi_3O_8$

Starting with task 34911, before generating an INCAR/POSCAR/KPOINTS set, inspecting its DFT record.

In [ ]:
# ============================================================
# INSPECT FIRST ELECTRONIC-STRUCTURE CANDIDATE
# ============================================================

task_id = 34911
rec = record_by_task[str(task_id)]

print("Task:", task_id)
print("Formula:", rec["formula"])
print("Ordering:", rec["ordering"])
print("Symmetry:", rec["symmetry"])
print("Total magnetization:", rec["total_magnetization"])
print("Energy/atom:", rec["energy_per_atom"])

print("\nFinal VASP magnetic moments:")
print(np.asarray(rec["magmoms"]["vasp"]))

print("\nFinal structure:")
structure_34911 = Structure.from_dict(rec["structure"])
print(structure_34911)

Task: 34911
Formula: Li3 Si1 Ni3 O8
Ordering: FiM
Symmetry: P2/m
Total magnetization: 1.44e-05
Energy/atom: -5.492732297333333

Final VASP magnetic moments:
[ 0.    -0.    -0.     0.    -0.     0.     0.    -0.    -1.14  -1.183
 -1.183  1.14   1.183  1.183  0.     0.    -0.    -0.    -0.073  0.073
  0.195 -0.195 -0.007  0.007 -0.098  0.098 -0.007  0.007 -0.098  0.098]

Final structure:
Full Formula (Li6 Si2 Ni6 O16)
Reduced Formula: Li3SiNi3O8
abc   :   5.183802   7.516145   7.516142
angles:  94.955037  75.611663  75.611673
pbc   :       True       True       True
Sites (30)
  #  SP           a         b         c    magmom
---  ----  --------  --------  --------  --------
  0  Li    0.999944  0.250095  0.750095     0
  1  Li    0.999932  0.750098  0.250098    -0
  2  Li    7.5e-05   0.371941  0.127881    -0
  3  Li    6.6e-05   0.871941  0.627881     0
  4  Li    7.5e-05   0.627881  0.871941    -0
  5  Li    6.6e-05   0.127881  0.371941     0
  6  Si    0.500193  0.249843  0.249845     0
  7  Si    0.500193  0.749845  0.749843    -0
  8  Ni    0.500113  0.000255  0.500255    -1.14
  9  Ni    0.499861  0.623986  0.37587     -1.183
 10  Ni    0.499861  0.875869  0.123985    -1.183
 11  Ni    0.500127  0.500257  0.000256     1.14
 12  Ni    0.499888  0.123968  0.875884     1.183
 13  Ni    0.499887  0.375885  0.623969     1.183
 14  O     0.302992  0.131967  0.131966     0
 15  O     0.302993  0.631966  0.631967     0
 16  O     0.696993  0.368014  0.368019    -0
 17  O     0.696993  0.868019  0.868014    -0
 18  O     0.275552  0.362279  0.862278    -0.073
 19  O     0.275512  0.86227   0.36227      0.073
 20  O     0.724953  0.637664  0.137664     0.195
 21  O     0.724958  0.137649  0.637649    -0.195
 22  O     0.714918  0.263104  0.025479    -0.007
 23  O     0.714894  0.763107  0.525471     0.007
 24  O     0.284795  0.474568  0.23706     -0.098
 25  O     0.284781  0.974576  0.737062     0.098
 26  O     0.714918  0.525478  0.763104    -0.007
 27  O     0.714893  0.025471  0.263107     0.007
 28  O     0.284794  0.73706   0.974568    -0.098
 29  O     0.28478   0.237062  0.474576     0.098

The workflow will be now,

$$\boxed{\text{final relaxed structure → SCF without SOC → verify magnetic state → non-SOC bands → spin splitting}}$$

### Step - 11.2 - Generating the exact inputs from the actual structure

This will produce the POSCAR and a first-pass INCAR/MAGMOM

In [ ]:
# ============================================================
# PREPARE Li3SiNi3O8 (task 34911) FOR NON-SOC DFT
# ============================================================

from pymatgen.core import Structure
from pathlib import Path

task_id = 34911
rec = record_by_task[str(task_id)]

structure = Structure.from_dict(rec["structure"])

# Final moments from the previous DFT calculation
final_m = np.asarray(
    rec["magmoms"]["vasp"],
    dtype=float
)

print("Number of sites:", len(structure))
print("Elements:", [str(site.specie) for site in structure])
print("Final magnetic moments:")
print(final_m)

# Write POSCAR
outdir = Path("/content/Li3SiNi3O8_task34911")
outdir.mkdir(exist_ok=True)

structure.to(
    fmt="poscar",
    filename=str(outdir / "POSCAR")
)

# Construct a simple initial MAGMOM:
# use the sign of the converged moments, with ~1.2 μB
# on the Ni sites and zero on nominally nonmagnetic sites.
initial_magmom = []

for site, m in zip(structure, final_m):

    element = str(site.specie)

    if element == "Ni" and abs(m) > 0.05:
        initial_magmom.append(
            1.2 if m > 0 else -1.2
        )
    else:
        initial_magmom.append(0.0)

print("\nInitial MAGMOM:")
print(initial_magmom)

print("\nVASP MAGMOM line:")
print(
    "MAGMOM = "
    + " ".join(f"{x:.1f}" for x in initial_magmom)
)

print("\nFiles written to:")
print(outdir)

Number of sites: 30
Elements: ['Li', 'Li', 'Li', 'Li', 'Li', 'Li', 'Si', 'Si', 'Ni', 'Ni', 'Ni', 'Ni', 'Ni', 'Ni', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O']
Final magnetic moments:
[ 0.    -0.    -0.     0.    -0.     0.     0.    -0.    -1.14  -1.183
 -1.183  1.14   1.183  1.183  0.     0.    -0.    -0.    -0.073  0.073
  0.195 -0.195 -0.007  0.007 -0.098  0.098 -0.007  0.007 -0.098  0.098]

Initial MAGMOM:
[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -1.2, -1.2, -1.2, 1.2, 1.2, 1.2, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

VASP MAGMOM line:
MAGMOM = 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 -1.2 -1.2 -1.2 1.2 1.2 1.2 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0

Files written to:
/content/Li3SiNi3O8_task34911

### Step - 11.3 - INCAR — non-SOC SCF

* SYSTEM = Li3SiNi3O8_task34911
* ENCUT = 520
* PREC = Accurate

* ISPIN = 2
* LSORBIT = .FALSE.
* LORBIT = 11

* EDIFF = 1E-6
* EDIFFG = -1E-3
* NELM = 150

* ISMEAR = 0
* SIGMA = 0.05

* IBRION = -1
* NSW = 0

* ISYM = 0

* LWAVE = .TRUE.
* LCHARG = .TRUE.

* MAGMOM = 0 0 0 0 0 0 0 0 -1.2 -1.2 -1.2 1.2 1.2 1.2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0

### Step - 11.4 - KPOINTS — SCF

Using a reasonably dense Monkhorst-Pack mesh

Automatic mesh

0

Gamma

6 6 6

0 0 0

### Step - 11.5 - POTCAR

Using the same PAW/POTCAR set and exchange-correlation functional as the original DFT calculations. Without changing that between the reference calculation and this validation calculation.

### Step - 11.6 - Runing the SCF

The directory should contain at least,

* POSCAR
* INCAR
* KPOINTS
* POTCAR

### Step - 11.7 - Understanding the workflow

POSCAR: we can generate it ourselves from the stored final structure.

INCAR: we create it ourselves with the desired calculation settings.

KPOINTS: we create it ourselves.

POTCAR: we need the appropriate VASP PAW potentials, preferably the same versions you used in the original DFT calculation.

OUTCAR: VASP creates this after you run the calculation.


$$\text{Your existing ML/DFT records → generate POSCAR → create INCAR → create KPOINTS}$$

$$\text{→ obtain correct POTCAR → run VASP yourself → OUTCAR / WAVECAR / CHGCAR → analyze spin-resolved bands}$$

In [ ]:
from pymatgen.core import Structure

task_id = 34911
rec = record_by_task[str(task_id)]

structure = Structure.from_dict(rec["structure"])

structure.to(
    fmt="poscar",
    filename="/content/Li3SiNi3O8_task34911/upd_POSCAR"
)

'Li6 Si2 Ni6 O16\n1.0\n   1.5623700000000000    0.9020350000000000    4.8597460000000003\n   7.1681879999999998   -2.2578969999999998    0.1068280000000000\n   1.6286970000000001    7.3367789999999999    0.1068290000000000\nLi Si Ni O\n6 2 6 16\ndirect\n   0.9999440000000001    0.2500950000000000    0.7500950000000000 Li\n   0.9999320000000000    0.7500980000000000    0.2500980000000000 Li\n   0.0000750000000000    0.3719410000000000    0.1278810000000000 Li\n   0.0000660000000000    0.8719410000000000    0.6278810000000000 Li\n   0.0000750000000000    0.6278810000000000    0.8719410000000000 Li\n   0.0000660000000000    0.1278810000000000    0.3719410000000000 Li\n   0.5001930000000000    0.2498430000000000    0.2498450000000000 Si\n   0.5001930000000000    0.7498450000000000    0.7498430000000000 Si\n   0.5001130000000000    0.0002550000000000    0.5002550000000000 Ni\n   0.4998610000000000    0.6239860000000000    0.3758700000000000 Ni\n   0.4998610000000000    0.8758690000000000    0.1239850000000000 Ni\n   0.5001270000000000    0.5002570000000000    0.0002560000000000 Ni\n   0.4998880000000000    0.1239680000000000    0.8758840000000000 Ni\n   0.4998870000000000    0.3758850000000000    0.6239690000000000 Ni\n   0.3029920000000000    0.1319670000000000    0.1319660000000000 O\n   0.3029930000000000    0.6319660000000000    0.6319669999999999 O\n   0.6969930000000000    0.3680140000000000    0.3680190000000000 O\n   0.6969930000000000    0.8680190000000000    0.8680140000000000 O\n   0.2755520000000000    0.3622790000000000    0.8622780000000000 O\n   0.2755120000000000    0.8622700000000000    0.3622700000000000 O\n   0.7249530000000000    0.6376640000000000    0.1376640000000000 O\n   0.7249580000000000    0.1376490000000000    0.6376490000000000 O\n   0.7149180000000001    0.2631040000000000    0.0254790000000000 O\n   0.7148940000000000    0.7631070000000000    0.5254710000000000 O\n   0.2847950000000000    0.4745680000000000    0.2370600000000000 O\n   0.2847810000000000    0.9745760000000000    0.7370620000000000 O\n   0.7149180000000001    0.5254780000000000    0.7631040000000000 O\n   0.7148930000000000    0.0254710000000000    0.2631070000000000 O\n   0.2847940000000000    0.7370600000000000    0.9745680000000000 O\n   0.2847800000000000    0.2370620000000000    0.4745760000000000 O\n'